### ISSUE TITLE
dayjs localization 

### ISSUE THREAD

**Issue by Toub** [mui-org/material-ui-pickers#1006]
**Is your feature request related to a problem? Please describe.**

`material-ui-pickers` documentation mentions [date-fns](https://material-ui-pickers.dev/localization/date-fns) & [moment](https://material-ui-pickers.dev/localization/moment), but nothing about **dayjs**.

Is it supported, and how to use it?

Configuring `dayjs` locale globaly before initialization partially works, but formats and `weekStart` *(Sunday or Monday are still default one: english)*.

```ts
  dayjs.extend(utc, {});
  dayjs.locale('fr'); // default locale
```
```tsx
  <MuiPickersUtilsProvider utils={DayjsUtils} locale="fr">
```

![image](https://user-images.githubusercontent.com/367762/56721140-f0677c00-674c-11e9-9f74-9a4abefe5dc3.png)

**Describe the solution you'd like**

Official support & documentation for **dayjs localization**  would be a must!

**Additional context**

Not sure if it is related but **last `date-io` version mention support for dayjs localization**: 
https://github.com/dmtrKovalenko/date-io/pull/39

**Comment by iakovosvo** [comment]
Any updates on this?

**Comment by Studio384** [comment]
I'd like an update on this as well. Setting the local shifts the numbers for the days correctly, but the labels keep starting with Sunday instead of Monday.

**Comment by dmtrKovalenko** [comment]
I am not really sure it is possible with dayjs

**Comment by testarossaaaaa** [comment]
There are any ideas? We have roll out "material ui pickers: with dayjs in production and realised that weekdays shift do not work properly 😅

**Comment by dmtrKovalenko** [comment]
It is possible with custom override. You will need to override

**Comment by stunaz** [comment]
Snippet?

**Comment by vmajsuk** [comment]
@dmtrKovalenko I investigated this a little and I think this is a bug in date-io wrapper around dayjs
1. `DatePicker` uses `getWeekdays()` from `date-io`
2. `getWeekdays` for dayjs something like this: 
```js
const getWeekdays = () => [0, 1, 2, ...].map(n => dayjs.set('day', n).format('dd))
```
You can see it here:
https://github.com/dmtrKovalenko/date-io/blob/master/packages/dayjs/src/dayjs-utils.ts#L209

While dayjs docs states that this way you will always get ['su', 'mo', 'tu', ...]:
![Screenshot from 2019-08-11 19-08-24](https://user-images.githubusercontent.com/11076829/62836439-790e1780-bc6b-11e9-8033-e8a3a5cddc16.png)


_____

The solution I see is to use `dayjs.startOf('week')` in the `date-io` in the `getWeekdays` function.
In dayjs `startOf('week')` respects locale

**Comment by Toub** [comment]
related issue here https://github.com/dmtrKovalenko/date-io/issues/111

**Comment by Toub** [comment]
> It is possible with custom override. You will need to override

@dmtrKovalenko thanks for your answer. So does it mean a "won't fix"?

**Comment by testarossaaaaa** [comment]
@Toub it's works in this patched fork: https://github.com/vmajsuk/date-io
```json
"date-io": "https://github.com/vmajsuk/date-io"
```
```js
import DayJsUtils from 'date-io/packages/dayjs/build
```

**Comment by dmtrKovalenko** [comment]
@testarossaaaaa can you please make a PR to the original date-io?

**Comment by vmajsuk** [comment]
@dmtrKovalenko https://github.com/dmtrKovalenko/date-io/pull/113

**Comment by hug0b** [comment]
Could someone provide an example on how to achieve dayjs localization currently ?

**Comment by HartmannVolker** [comment]
In case someone is finding this issue because of the missing documentation:

just import the local from dayjs and set the local globally on dayjs:

``` 
import "dayjs/locale/de"

dayjs.locale("de")
```
[dayjs docs](https://day.js.org/docs/en/i18n/changing-locale)
