### ISSUE TITLE
KeyboardDatePicker onAccept doesn't trigger on enter.

### ISSUE THREAD

**Issue by dominictwlee** [mui-org/material-ui-pickers#1013]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  ^3.0.0-alpha.3       |
| material-ui         |    ^4.0.0-alpha.8     |
| React               |   ^16.8.0      |
| Browser             |     Firefox 67.0b14    |
| Peer library        |   date-fns ^2.0.0-alpha.27, @date-io/date-fns ^1.3.5      | 

## Steps to reproduce
1. Input date by keyboard
2. Press enter once a valid date has been inputted.

## Expected behavior

onAccept should trigger on enter, similar to previous 2.x versions.

## Actual behavior

Nothing happens. So if I decide to make a fetch request in onAccept, it cannot be triggered by keyboard if i pressed enter.

## Live example
https://codesandbox.io/s/mowmjy93z9

**Comment by dmtrKovalenko** [comment]
I suppose from the perspective of v3 architecture using `onEnter` is not really best variant. 
From now `onAccept` is triggered by the actual click on the accept button. But in keyboard mode, we are not relying on "enter" key down anymore. 

You can make it works by yourself using `onKeyDown` prop, that will be spreaded to text field.

**Comment by dominictwlee** [comment]
Cool, I'll do that, thanks.
