### ISSUE TITLE
animateYearScrolling not working in v3.0.0-beta.1

### ISSUE THREAD

**Issue by hill84** [mui-org/material-ui-pickers#1024]
**animateYearScrolling** is broken in v3.0.0-beta.1. You can verify for yourself in the [documentation example](https://material-ui-pickers.dev/demo/datepicker#different-views) (first on left).

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.0.0-beta.1 |
| material-ui          | 4.0.0-beta.0 |
| React                | 16.8.6 |
| Browser              | Chrome 74.0 |
| Peer library         | Moment 2.24.0 |

**Comment by dmtrKovalenko** [comment]
Please mention your browser

**Comment by hill84** [comment]
It seams to happen on Chrome (74), Opera (58) and Edge (44), but not in Firefox (66).

**Comment by dmtrKovalenko** [comment]
Here is strange behavior :) 
You can see that on the very first example of datepicker everything works fine. 

Reason: when you open a modal from the year view browser 
1) Render the modal
2) Runs the modal animation
3) React rendering year list
4) Runs the hooks with actual scrolling logic  <- Here scrolling element didn't painted, so browser skipping animation
5) Finishing animation and painting dome elements

So when you are opening from year selection - it just didn't painted :)
Only 1 option here to use `setTimeout` - but I don't want to. That seems smelling to me 💩 . So I suppose we will just remove `animateYearScrolling` from example

**Comment by dmtrKovalenko** [comment]
Here effect is calling
![image](https://user-images.githubusercontent.com/16926049/57197944-b16bce80-6f75-11e9-8feb-460be49fec9d.png)
And here renders animation
![image](https://user-images.githubusercontent.com/16926049/57197949-c5afcb80-6f75-11e9-9424-736901873ec0.png)
