### ISSUE TITLE
Theming guidelines

### ISSUE THREAD

**Issue by Fiontan** [mui-org/material-ui-pickers#1040]
![Capture](https://user-images.githubusercontent.com/1700120/57572181-c9789d80-740e-11e9-97d9-004e060a6d7b.JPG)

![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   ^3.0.0-beta.1      |
| material-ui          |    ^3.6.1     |
| React                |        ^16.2.0 |
| Browser              |         chrome|
| Peer library         |        moment": "^2.24.0" |

## Steps to reproduce
I'm using a custom Hoc to apply themes from an api call e.g:
function withRoot(Component) {
  function WithRoot(props) {
    let theme = utils.getTheme(props.bundle);
    // MuiThemeProvider makes the theme available down the React tree thanks to React context.
    return (
      <MuiThemeProvider theme={theme}>
        <CssBaseline />
        <Component {...props} />
      </MuiThemeProvider>
    );
  }
  WithRoot.propTypes = {
    classes: PropTypes.object,
    bundle: PropTypes.object.isRequired
  };
  return WithRoot;
}

export default withRoot;

This is then used in my Root component:
export default withRoot(withWidth()(withStyles(styles)(Root)));

1. A solution that loads theming info from an api, then appies the theme (SEE ABOVE)

## Expected behavior
Some guidance is required for the timing in this type of scenario.
Some dev/compile time analysis and outout would be good as the project compiles without issue then fails catastrophically
The application should not break, theming and date picker utils should co-exist in harmony.

## Actual behavior

The project compiles no isses, however, loading is a different story:
TypeError: Object(...) is not a function
./node_modules/@material-ui/pickers/dist/material-ui-pickers.esm.js
...blablablar/node_modules/@material-ui/pickers/dist/material-ui-pickers.esm.js:26
  23 | import Tabs from '@material-ui/core/Tabs';
  24 | import Paper from '@material-ui/core/Paper';
  25 | 
> 26 | var useStyles = makeStyles(function (theme) {
  27 |   var textColor = theme.palette.type === 'light' ? theme.palette.primary.contrastText : theme.palette.getContrastText(theme.palette.background.default);
  28 |   return {
  29 |     toolbarTxt: { et etc
 
At this point a breakpoint shows that the theme param is not defined.

So my question is more an issue surrounding guidance for this type of scenario using a custom (built from config rturned from api) theming solution.

**Comment by dmtrKovalenko** [comment]
You need material-ui v4
