### ISSUE TITLE
TypeError: _styles.makeStyles is not a function[詳細] ToolbarText.tsx:14:25

### ISSUE THREAD

**Issue by ncaq** [mui-org/material-ui-pickers#1042]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.0.0-beta.1 |
| material-ui          | 3.9.3   |
| React                | 16.0.0  |
| Browser              | Firefox 66 |
| Peer library         |         |  |

It's impotant, material ui use 3.0.0.

## Steps to reproduce

1. `import * as MP from "@material-ui/pickers";`

## Expected behavior

import pickers.

## Actual behavior

~~~
13:33:08.056 TypeError: _styles.makeStyles is not a function[詳細] ToolbarText.tsx:14:25
    parcelRequire<["../node_modules/@material-ui/pickers/dist/material-ui-pickers.esm.js"]< ToolbarText.tsx:14
    newRequire frontend.f69400ca.js:47
    localRequire frontend.f69400ca.js:53
    parcelRequire<["index.tsx"]< index.tsx:8
    newRequire frontend.f69400ca.js:47
    parcelRequire frontend.f69400ca.js:81
    <匿名> frontend.f69400ca.js:8
~~~

## Live example

https://codesandbox.io/s/j3xo56k0oy

## proposal

I think to write material ui use 4 to README.

~~~console
yarn add @material-ui/core
~~~

is install is 3 default.

**Comment by dmtrKovalenko** [comment]
Definitely 🥺

**Comment by llafitte007** [comment]
Not exactly same problem but i feel same cause :

## Environment

Tech | Version
-- | --
@material-ui/pickers | 3.0.0-beta.1
material-ui | 3.9.3
React | 16.8.6
Browser | Chromium 73.0.3683.86
Peer library|moment 2.24.0

## Code

```
<MuiPickersUtilsProvider utils={MomentUtils}>
     <DatePicker
        value={vdate}
        onChange={(d: any) => console.log(d)}
    />
</MuiPickersUtilsProvider>
```

## Actual behavior

```
TypeScript error: Type '{ value: Date; onChange: (date: any) => void; }' 
is missing the following properties from type 'Pick<DatePickerProps, "label" 
| "select" | "style" | "title" | "children" | "open" | "onAccept" | "okLabel" | "cancelLabel" 
| "clearLabel" | "todayLabel" | "showTodayButton" | ... 305 more ... | "invalidDateMessage">': 
onAuxClick, onAuxClickCapture, key  TS2739
```

**Comment by RinatRezyapov** [comment]
same here

**Comment by RinatRezyapov** [comment]
> Not exactly same problem but i feel same cause :
> 
> ## Environment
> Tech	Version
> @material-ui/pickers	3.0.0-beta.1
> material-ui	3.9.3
> React	16.8.6
> Browser	Chromium 73.0.3683.86
> Peer library	moment 2.24.0
> ## Code
> ```
> <MuiPickersUtilsProvider utils={MomentUtils}>
>      <DatePicker
>         value={vdate}
>         onChange={(d: any) => console.log(d)}
>     />
> </MuiPickersUtilsProvider>
> ```
> 
> ## Actual behavior
> ```
> TypeScript error: Type '{ value: Date; onChange: (date: any) => void; }' 
> is missing the following properties from type 'Pick<DatePickerProps, "label" 
> | "select" | "style" | "title" | "children" | "open" | "onAccept" | "okLabel" | "cancelLabel" 
> | "clearLabel" | "todayLabel" | "showTodayButton" | ... 305 more ... | "invalidDateMessage">': 
> onAuxClick, onAuxClickCapture, key  TS2739
> ```

I have same issue

**Comment by dmtrKovalenko** [comment]
!!! Use material-ui v4 with a new `@material-ui/pickers` package

**Comment by llafitte007** [comment]
I'll tried with this environment and give a feedback :

Tech | Version
-- | --
@material-ui/pickers | 3.0.0-beta.1
material-ui | 4.0.0-beta.2
React | 16.8.6
Browser | Chromium 73.0.3683.86
Peer library | moment 2.24.0

**Comment by llafitte007** [comment]
same problem as previous with given environment ! :(

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/o7oojxx1pq?from-embed
Here everything works please make a reproduction

**Comment by llafitte007** [comment]
hmmmm ... it's ok on your codesandbox, and I imported all my package.json conf and it's ok too ...
I don't explain what append but I'll come back if I found a solution.

**Comment by neeschit** [comment]
if you're running yarn, maybe you need to run `yarn upgrade`?

**Comment by ncaq** [comment]
If need update, it is maybe `yarn upgrade-interactive --latest`.

**Comment by llafitte007** [comment]
Thanks both for your interest, I'm using npm
