### ISSUE TITLE
[<KeyboardDateTimePicker>] doesn't trigger onChange on clear

### ISSUE THREAD

**Issue by DJanoskova** [mui-org/material-ui-pickers#1047]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.0.0-beta.1 |
| material-ui          | 4.0.0-beta.1 |
| React                | 16.8.6 |
| Browser              | Chrome |
| Peer library         | "@date-io/moment": "^1.1.0" |  |

## Steps to reproduce

1. Create a component
```
 <KeyboardDateTimePicker
            placeholder={`${today} 12:00`}
            value={convertedValue}
            onChange={handleChange}
            format="DD/MM/YYYY HH:mm"
            clearable
          />
```

## Expected behavior

The `onChange` function triggers when I click the "CLEAR" button.

## Actual behavior

The `onChange` function doesn't trigger when I click the "CLEAR" button. I get an error in the console.

## Live example

<img width="448" alt="Screenshot 2019-05-20 at 09 59 14" src="https://user-images.githubusercontent.com/35444313/58006597-b6d62680-7ae8-11e9-92bd-3ae6f18c0660.png">

**Comment by njetsy** [comment]
FYI this should be fixed by #1036

**Comment by DJanoskova** [comment]
@njetsy Thanks a lot, gonna check it out

**Comment by dmtrKovalenko** [comment]
Fixed in rev.0
