### ISSUE TITLE
Loss Of Ability to Specify TextField Variant

### ISSUE THREAD

**Issue by foresttoney** [mui-org/material-ui-pickers#1050]
![](https://media.giphy.com/media/EfdrZTT4sSGY0/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.0.0-beta.1     |
| material-ui          |   next      |
| React                |    16.8.5     |
| Browser              |    Chrome 74.0.3729.157     |
| Peer library         |   date-fns 2.0.0-alpha.27      |  |

## Steps to reproduce
 
```
<DatePicker
  variant="outlined"
  label="Date"
  value={selectedDate}
  onChange={handleDateChange}
  InputLabelProps={{
    shrink: true,
    variant: "outlined"
  }}
/>
```

## Expected behavior

The `variant` prop should be passed to the `TextField` component.

## Actual behavior

As of 3.x, it looks like the `variant` prop is no longer passed.

## Live example

https://codesandbox.io/s/cocky-bohr-vp86w [2.x]
https://codesandbox.io/s/materialuipickersusagedemo-11wfs [3.x]

**Comment by dmtrKovalenko** [comment]
`inpurtVariant` prop
https://material-ui-pickers.dev/demo/datetime-picker#basic-usage

It is also listed in component API

**Comment by foresttoney** [comment]
My b - I didn't pour over all the new documentation. The breaking change wasn't documented in the migration guide. I can submit a PR if interested.

**Comment by dmtrKovalenko** [comment]
Yep, it will be cool to mention that in migration guide
