### ISSUE TITLE
IE Broken: SCRIPT438: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by SpearThruster** [mui-org/material-ui-pickers#1054]
Also all the demos (both v2 and v3 of @material-ui/pickers) are broken in IE11.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.0.0-rc.0        |
| material-ui          |  4.0.0-rc.0       |
| React                |     16.8.0    |
| Browser              |      IE11   |

## Steps to reproduce

1. 2. 3.

**Comment by dmtrKovalenko** [comment]
PR is appreciated
