### ISSUE TITLE
A not published package as a peer dependency

### ISSUE THREAD

**Issue by artemnesterenko** [mui-org/material-ui-pickers#1057]
When I install the library, I get the message:
`@material-ui/pickers@3.0.0-rc.0" has incorrect peer dependency "@date-io/core@^1.3.0"`
There are no versions above 1.3.0 of [@date-io/core](https://www.npmjs.com/package/@date-io/core) on npm

**Comment by dmtrKovalenko** [comment]
Fixed in 3.0

**Comment by cjmyles** [comment]
When I install the library, I get the message:
`@material-ui/pickers@3.2.10" has unmet peer dependency "@date-io/core@^1.3.6"`
I am using the latest version of @material-ui/pickers

**Comment by oliviertassinari** [comment]
@cjmyles You need to install it. We have hidden this aspect to users in the next major (v4.0.0-alpha.4 as we are speaking).
