### ISSUE TITLE
Where did the 2.2.4 docs go?

### ISSUE THREAD

**Issue by Vigrond** [mui-org/material-ui-pickers#1060]
Some of us haven't / can't upgrade to Material UI 4.0.0 . It would be nice to still be able to view the 2.2.4 docs site the same way the material-ui site allows you to select different versions.

**Comment by dmtrKovalenko** [comment]
Thanks we will implement this feature. But right now you can use https://material-ui-pickers-v2.dmtr-kovalenko.now.sh/

**Comment by dmtrKovalenko** [comment]
BTW this is actually 2.2.4 release. I don’t know why it says 2.2.2 version
