### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by fenyagg** [mui-org/material-ui-pickers#1064]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |      3.0.0   |
| material-ui          |     4.0.0    |
| React                |     16.8.6    |
| Browser              |      any   |
| Peer library         |   moment      |  |

## Steps to reproduce

1. place component in app
2. open calendar (click on text field)

## Expected behavior

no warnings

## Actual behavior

warnings in console:
```
index.js:1437 Warning: Failed prop type: Invalid prop `TextFieldComponent` supplied to `DateTextField`.
...
index.js:1437 Warning: Material-UI: theme.spacing.unit usage has been deprecated.
....
index.js:1437 Warning: Material-UI: the key `action` provided to the classes property is not implemented in ForwardRef(DialogActions).
You can only override one of the following: root,spacing.
```
![15899246af](https://user-images.githubusercontent.com/2457209/58419617-cbd82a00-8093-11e9-80be-93e7b0110bb3.jpg)

## Live example

https://codesandbox.io/s/silent-architecture-ni7wv

**Comment by dmtrKovalenko** [comment]
You must update to **@material-ui/core** https://codesandbox.io/s/loving-night-ciyfr

**Comment by pavles6** [comment]
@dmtrKovalenko @material-ui/pickers do not support variant prop, so i cannot match date picker with my variant="filled" text fields in a form..

**Comment by dmtrKovalenko** [comment]
@pavles6 please read documentation carefully. For input variant use `inputVariant` prop
