### ISSUE TITLE
[question] Multiple formats in DatePicker

### ISSUE THREAD

**Issue by jromx** [mui-org/material-ui-pickers#1066]
Hi!
Is it possible currently to provide multiple date formats for DatePicker?
If it's not, would it be something that you consider implementing?

**Comment by dmtrKovalenko** [comment]
What do you mean under multiple formats?

**Comment by jromx** [comment]
Thanks for your reply.
Now it is possible to pass `format` property to DatePicker, which is a string.
Let's say we have an user using keyboard to enter value. In this case it is straight forward that this certain format should be used. But this user is also often using copy/paste to enter date value. Then, if this value has different format, it has to be corrected.
I was wondering if it would be possible to provide for example an array of formats that would be accepted by picker.

**Comment by dmtrKovalenko** [comment]
Right now it is not possible. I will left this issue as feature request. But it will be low-priority

**Comment by Jkitche** [comment]
This could be implemented by overriding the TextFieldComponent and extend TextField to parse the value for a valid date time then convert it to the format that you use in the DatePicker itself. This seems like an implementation detail for your use-case @jromx, and can already be implemented with the current state of the DatePicker

**Comment by oliviertassinari** [comment]
@Jkitche Great, thanks for sharing a solution.
