### ISSUE TITLE
"X" and "x" Date Format Mask and Validation

### ISSUE THREAD

**Issue by sidpagariya** [mui-org/material-ui-pickers#1068]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.0.0     |
| material-ui          |   4.0.0  |
| React                |    16.8.6     |
| Browser              | Chrome 74.0.3729.169    |
| Peer library         |  moment       |  |

## Steps to reproduce

1. Set the format to "X" or "x"
2. Clear the date from the input in the KeyboardDateTimePicker.
3. Start typing an epoch time in the field.

## Expected behavior

The expected behavior is a 10-digit mask for format "X" and 13-digit mask for format "x"

## Actual behavior

You can't type the entire epoch time, only one digit fits in the mask.

## Live example
[Demo](https://codesandbox.io/s/materialuipickersusagedemo-ln98y)

**Comment by dmtrKovalenko** [comment]
Yeep, it is actually the case when you need to specify mask manually.
Working demo -> https://codesandbox.io/s/materialuipickersusagedemo-9tx5i
