### ISSUE TITLE
ToolbarButton button variant not changeable

### ISSUE THREAD

**Issue by DrewBe121212** [mui-org/material-ui-pickers#1076]
Issue here is that I have specified a default button variant in MUI Theme ('outlined'). This then changes the button type in the calendar picker which makes them look more like buttons and not text. 

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |3.0.0|
| material-ui          |4.0.1|
| React                |16.8.6|
| Browser              |Chrome|
| Peer library         |moment|  |

## Steps to reproduce
1. Set default props in material-ui theme
`const theme = createMuiTheme({
    props: {
      MuiButton: {
        variant: 'outlined'
      }
    };`
2. View calendar. 

## Expected behavior
I expect either the button to pass `variant="text"` (always) as a prop, or allow us to pass `toolbarButtonProps={ { variant: 'text' } }` to override the default mui theme, showing the text version of a button. Although, the second option here could become cumbersome if we were to pass props for each individual button in the toolbar. IE showTodayButtonProps, clearButtonProps.

## Actual behavior
Button gets the 'outlined' variant, and looks silly. This affects the toolbar buttons at the top of the calendar (year/date/month), as well as the buttons on the bottom of the calendar (show today, clear, OK etc.).

Thank you very much for your consideration, this project is amazing!

**Comment by DrewBe121212** [comment]
Thank you!

**Comment by pontusdevelopment** [comment]
This is still an issue in MUI v.5. Should I create a separate issue for this?
