### ISSUE TITLE
Cancel & Ok buttons no longer right-justified with material-ui 4

### ISSUE THREAD

**Issue by aboe026** [mui-org/material-ui-pickers#1078]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    2.2.4     |
| material-ui          |    4.0.1     |
| React                |     16.8.6    |
| Browser              |     Google Chrome 74.0.3729.169     |
| Peer library         |    @date-io/moment     |  |

## Steps to reproduce

1. On the `DatePicker` component with the `clearable` attribute, click the calendar icon

## Expected behavior

The 3 buttons at the bottom of the picker dialog should be separated, with `CLEAR` justified to the left, and `CANCEL` and `OK` justified to the right:

![material-ui-date-picker-original-behavior](https://user-images.githubusercontent.com/11340779/58755855-6da7ae80-84ba-11e9-82a0-fa78e8e405cd.JPG)

## Actual behavior

The 3 the buttons at the bottom of the picker dialog (`CLEAR`, `CANCEL`, `OK`) are justified to the left:

![material-ui-date-picker-bad-bottom-button-justification](https://user-images.githubusercontent.com/11340779/58755839-2ae5d680-84ba-11e9-8382-296c4f0b9349.JPG)

**Comment by dmtrKovalenko** [comment]
Provide a way to reproduce it. For me it is working like on the first screen
