### ISSUE TITLE
Cancel button shouldn't update with the current date

### ISSUE THREAD

**Issue by chriswardo** [mui-org/material-ui-pickers#1088]
Currently if no date is set in DatePicker (and therefore the emptyLabel is displayed) and the user opens the picker and presses the 'cancel' button, the onChange function is called with today's date for some reason.

Thanks!

**Comment by bogdansoare** [comment]
also having this issue

**Comment by stopak** [comment]
I'm also having this issue

**Comment by pankaz** [comment]
This behaviour is observed for the "clear" button too.

**Comment by dmtrKovalenko** [comment]
Fixed in 3.3.1
