### ISSUE TITLE
emptyLabel warning

### ISSUE THREAD

**Issue by DrewBe121212** [mui-org/material-ui-pickers#1093]
## Environment
| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |3.1.0|
| material-ui          |4.0.2|
| React                |16.8.6|
| Browser              |Chrome|
| Peer library         |moment|  |

## Steps to reproduce
1. use emptyLabel prop

## Expected behavior
1. No warning is produced

## Actual behavior
1. React throws a warning, `react-dom.development.js:507 Warning: React does not recognize the `emptyLabel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `emptylabel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`.

**Comment by bbourn** [comment]
Same with invalidLabel
