### ISSUE TITLE
ESLint warning  'styles' was used before it was defined

### ISSUE THREAD

**Issue by Philipp91** [mui-org/material-ui-pickers#1100]
Example warning:

```
material-ui-pickers/lib/src/_shared/ToolbarButton.tsx
  12:23  warning  'styles' was used before it was defined  @typescript-eslint/no-use-before-define
```

Possible resolutions are to disable the `no-use-before-define` rule (there's no per-variable-name disabling option), or to move the `styles` closer to the top in the 6 affected files. I can send a PR for either.

**Comment by dmtrKovalenko** [comment]
Just fix at when are a warn

**Comment by Philipp91** [comment]
I don't understand what you mean. It would be nice if `npm run lint` produced empty output for code at `next`.

**Comment by dmtrKovalenko** [comment]
Yeah, need to fix it. 
When we migrate to eslint from tslint -> some rules was left as warnings to fix in future

**Comment by dmtrKovalenko** [comment]
To fix it when you are working on particular component

**Comment by Philipp91** [comment]
Alright. TSLint is deprecated btw: https://github.com/palantir/tslint/issues/4534
