### ISSUE TITLE
Ability to disable auto-formatting in the input mask

### ISSUE THREAD

**Issue by ghost** [mui-org/material-ui-pickers#1102]
**Is your feature request related to a problem? Please describe.**
Having the `rifm` mask is very useful, as it communicates the expected date format to the user. However, the auto-formatting in the input mask is a bit intrusive and not always correct. I am referring to the auto-calculating behavior of the date picker, when you enter an invalid date. 

For instance (and here's a [playground](https://codesandbox.io/s/gifted-zhukovsky-4to35) to try it out),
- user mistypes `12-32-2020` and it gets auto-formatted to `01-01-2021`
- if you enter `99-99-9999`, it gets auto-formatted to `06-07-10007` (if you type any character, it changes to `06-07-1000`)

Looking at [`KeyboardDateInput`](https://github.com/mui-org/material-ui-pickers/blob/d2974fe09e609e8a2b94d49df5bd2a0aad7e1e0b/lib/src/_shared/KeyboardDateInput.tsx#L74), there doesn't seem to be a way to customize the `format` prop on `Rifm`, nor opt out of the formatting entirely.

**Describe the solution you'd like**
It would be great to expose a boolean prop, e.g. `maskFormatting` or `maskAutoCorrect` defaulting to `true` (for backwards compat). When `false`, simply don't auto-format or auto-correct the input date. Ideally, I'd like to make it behave just as the "Date format with mask" example under "Date format" section in [`rifm` docs](https://istarkov.github.io/rifm/).

**Describe alternatives you've considered**
Alternatively, expose the `rifm` API through props, but this would involve more complexity.

Thank you.

**Comment by dmtrKovalenko** [comment]
Yeah, I see your point. We cannot disable autoformatting, because it is coming from the date library, which actually parsing the date. 

So we will add ability to change rifm's formatter
