### ISSUE TITLE
difference between DatePicker and KeyboardDatePicker

### ISSUE THREAD

**Issue by mg901** [mui-org/material-ui-pickers#1103]
Yo! Thank you for this awesome package.
What is the difference between date picker and keyboard date picker? I did not understand from the documentation.

**Comment by dmtrKovalenko** [comment]
Possibility to enter date via keyboard with mask

**Comment by mg901** [comment]
@dmtrKovalenko, please add this information to the documentation.

**Comment by dmtrKovalenko** [comment]
It is recommended to use keyboard input with mask for better desktop experience. Make sure that mask will be automatically generated from passed format. It's recommended to use only robust formats for keyboard input.

From the docs

**Comment by mateja176** [comment]
Correct me if I'm wrong, but from what I understood, the `KeyboardDatePicker` is the same as `DatePicker` with the addition of keyboard UX enhancements.
