### ISSUE TITLE
Ability to completely remove input component

### ISSUE THREAD

**Issue by curtisupshall** [mui-org/material-ui-pickers#1104]
I'm using a Button to control the `open` state of the `<DatePicker>`, which I use to fetch data from an API. Since the Button and fetched data already displays the date, having the input TextField is not wanted. I'm not sure if there's a way to achieve this currently, but couldn't manage to get the TextField to go away.

Perhaps something like `variant='dialog-only'`?

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/material-ui-pickers-usage-demo-u9tl6
