### ISSUE TITLE
getYearRange return wrong years after 19670

### ISSUE THREAD

**Issue by MatteoGioioso** [mui-org/material-ui-pickers#1105]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    2.2.4     |
| material-ui          |    4.1.0     |
| React                |     16.8    |
| Browser              |         |
| Peer library         |    moment 2.24     |  |

## Steps to reproduce
I would like to display a custom array of years, starting from the current year till 1900 in reverse order.
I have override the provided interface `class LocalizedUtils extends MomentUtils`

## Expected behavior
It should display years normally

## Actual behavior
after `1969` it displays `2068`

## Live example

https://codesandbox.io/s/momentutils-year-range-bq7lq

**Comment by dmtrKovalenko** [comment]
Make a proper reproduction and fill the issue with new *v3* version

**Comment by MatteoGioioso** [comment]
@dmtrKovalenko there is a link to a the codesandbox ...

**Comment by dmtrKovalenko** [comment]
for v2

**Comment by MatteoGioioso** [comment]
Sorry, what do you mean?

**Comment by dmtrKovalenko** [comment]
You have used `material-ui-pickers` package that is not supported anymore

**Comment by MatteoGioioso** [comment]
I have tried with version 3.0.0 same result. No problem I can re-open
