### ISSUE TITLE
Document when a date is considered accepted

### ISSUE THREAD

**Issue by charlax** [mui-org/material-ui-pickers#1107]
It would be nice to document when a value is considered "accepted" with v3. I was expecting `onAccept` to fire when the field is blurred for a `KeyboardDatePicker`. Happy to jot down some notes if you agree.

Also, in the API page, the argument to `onChange` could be clarified.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.1.0       |
| material-ui          |    4.1.0     |

**Comment by dmtrKovalenko** [comment]
Fixed in 3.3.1
