### ISSUE TITLE
Make onChange and value optional

### ISSUE THREAD

**Issue by charlax** [mui-org/material-ui-pickers#1108]
**Is your feature request related to a problem? Please describe.**

I have a mapping of `{[name: string]: FormComponent}`. TypeScript is not happy because, contrary to other components (such as MUI's `TextField`), `DatePicker` requires `onChange` and `value`.

**Describe the solution you'd like**

Make `onChange` and `value` optional.

**Describe alternatives you've considered**

I have a custom component that accepts optional `onChange` and `value`, replacing then with noop when creating the `DatePicker`component.

**Additional context**

This would be consistent with almost all of MUI's components, including https://material-ui.com/api/text-field/

**Comment by dmtrKovalenko** [comment]
No, the components must be controlled.

**Comment by charlax** [comment]
Can you explain the rationale here?

Another example: downshift makes them optional too.

https://github.com/downshift-js/downshift/blob/master/typings/index.d.ts
