### ISSUE TITLE
DatePicker auto assign today Date when select date without OK

### ISSUE THREAD

**Issue by quocvan1311** [mui-org/material-ui-pickers#1110]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.1.0 |
| material-ui          | 4.0.2 |
| React                | 16.8.6 |

## Steps to reproduce
When I select date from picker (without autoOk option and the initial value is empty), the current date immediately assign to the pickers' textfield.
## Expected behavior
The value is only assigned when I click OK with the date I've selected.
## Actual behavior
When select date without click OK, the current date is unexpected assigned to the textfield. With material-ui-pickers package (old version), this work as expected behaviour
## Live example
![image](https://user-images.githubusercontent.com/43029562/59319161-dc271080-8cf3-11e9-9e80-4c0f5f4b4bfe.png)

**Comment by dmtrKovalenko** [comment]
Fixed in 3.3.1
