### ISSUE TITLE
Feature request: Add ability to reverse/sort the order of years in DatePicker component.

### ISSUE THREAD

**Issue by eliranamar** [mui-org/material-ui-pickers#1112]
**Is your feature request related to a problem? Please describe.**
There is no option to sort the years ascending or descending by choice.
only order is ascending.
this would be very helpful when asking the user to enter dates related to his past details,
right now they need to scroll up.

**Describe the solution you'd like**
Ability to send a boolean prop like `yearsDescend` or `reverseYears` to the component
that would have the ability to control the desired order of years.

**Additional context**
So instead of the years looking like this:
![image](https://user-images.githubusercontent.com/27783006/59341148-04bd0380-8d10-11e9-9562-b9ab462d07e4.png)
they will be sorted like this:
2019
2018
2017
...

**Comment by Nusnus** [comment]
Upvote +1

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/momentutils-year-range-13emx

**Comment by eliranamar** [comment]
hey @dmtrKovalenko cool, but doesn't that mean that it will always be reversed ? 
what if i want to have 2 pickers with different order?

**Comment by dmtrKovalenko** [comment]
You can have several providers. I will think about moving it to the core via props. 
But it will need some time

**Comment by advance512** [comment]
Agreed, makes sense. +1 for this feature

**Comment by XiRoSe** [comment]
Makes sense, but i saw at several places that it's a common thing to show dates only by descending, it means to scroll down for past dates and up for future ones.
So do we really need both options?, shouldn't we go for more unified ux?

**Comment by dmtrKovalenko** [comment]
@XiRoSe who knows...

**Comment by XiRoSe** [comment]
@dmtrKovalenko thanks for your response,  but idk, i think you add a feature you really need not to have the option, because if you'll need it after you can always still add it..

**Comment by advance512** [comment]
@dmtrKovalenko so is this something you're interested in supporting?

**Comment by dmtrKovalenko** [comment]
I don’t think it is a rare case. If somebody needs it — please use this solution

**Comment by dmtrKovalenko** [comment]
Published better example in documentation for overriding date logic https://material-ui-pickers-5v8lfdtv4.now.sh/guides/date-io-customization#override-date-logic
