### ISSUE TITLE
TimePicker not updating when using luxon

### ISSUE THREAD

**Issue by WilsonCWong** [mui-org/material-ui-pickers#1114]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.1.0        |
| material-ui          |  4.1.0       |
| React                |  16.8.6       |
| Browser              | Chrome        |
| Peer library         | luxon 1.16.0   |

## Expected behavior

When you open the TimePicker and change the time, then press Ok, the input field should be updated.

## Actual behavior

The input remains the same.

## Live example

See the example here: https://codesandbox.io/s/material-ui-pickers-usage-demo-wqqfz.

Try changing the time and pressing OK, and you'll see it doesn't update until you click it again and try to assign another new value.

The TimePicker field updates fine when using @date-io/date-fns, so I'm beginning to think this is an issue with LuxonUtils or the way luxon works with material-ui-pickers. I'm also thinking it could be that the luxon object that's passed by onChange isn't a new object, but the same object with its ```ts``` property updated, so it doesn't trigger a re-render. Help would be appreciated.

**Comment by andokai** [comment]
Same issue when using moment.

**Comment by dmtrKovalenko** [comment]
Fixed in 3.3.1
