### ISSUE TITLE
How to center horizontally an inline Datepicker right under the textfield  ?

### ISSUE THREAD

**Issue by QuentinChevance** [mui-org/material-ui-pickers#1115]
Hello,

I would like to know if there is a way to center horizontally an inline Datepicker right under the input ?
In the previous version of material-ui-pickers (2.2.4) the datepicker was centered under the input by default. With the current version, the datepicker is placed at the right extremity of the input.
How it is :
![Screenshot_2019-06-13 Phileas](https://user-images.githubusercontent.com/19190545/59437716-5ccc3680-8df2-11e9-9e3b-7f9f56576d60.png)
How I would like it to be :
![Screenshot_2019-06-13 Phileas(1)](https://user-images.githubusercontent.com/19190545/59437698-58078280-8df2-11e9-8efa-e4e0f09f80b4.png)

Environment
--
| Tech           | Version |
|----------------|---------|
| Material-UI    | 3.9.3   |
| @material-ui/pickers | 3.1.0  |
| React          | 16.8.6  |

**Comment by dmtrKovalenko** [comment]
You can use `PopoverProps`

**Comment by QuentinChevance** [comment]
I already tried to use `PopoverProps` to change the position of the Datepicker by doing :
```javascript
<MUIDatePicker
    value={parseDate(defaultValue)}
    onChange={onChange}
    format="DD/MM/YYYY"
    label={labelValue}
    variant="inline"
    ...
    PopoverProps={{style: {...{left: '-400px'}}}}
/>
```
But I can't find a way to find the exact center depending on the input width.

**Comment by dmtrKovalenko** [comment]
You can pass `anchorEl` and positions relative to `anchorEl`

**Comment by QuentinChevance** [comment]
I've never used `anchorEl`, do you have and implementation I could take as example ?

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/material-ui-pickers-usage-demo-4yqe9

**Comment by QuentinChevance** [comment]
Thanks ! :+1:
