### ISSUE TITLE
shouldDisableDate crashes calendar picker

### ISSUE THREAD

**Issue by DrewBe121212** [mui-org/material-ui-pickers#1120]
## Environment
| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |3.1.1|
| material-ui          |4.1.1|
| React                |16.8.6|
| Browser              |Chrome|
| Peer library         |moment|  |

## Steps to reproduce
1. Set the shouldDisableDate prop
```
<DatePicker
  name="effectiveDate"
  label="Effective Date"
  value={effectiveDate}
  onChange={handleEffectiveDateChange)
  format="YYYY-MM-DD"
  shouldDisableDate={() => true}
  autoOk
  fullWidth
  required
  />
```
## Expected behavior
1. Date picker renders days with all days disabled

## Actual behavior
1. Entire component crashes
index.esm.js:77 Uncaught TypeError: Cannot read property 'clone' of null
    at MomentUtils.setHours (index.esm.js:77)
    at MomentUtils.mergeDateAndTime (index.esm.js:131)
    at Calendar._this.handleDaySelect (material-ui-pickers.esm.js:774)
    at Calendar.componentDidMount (material-ui-pickers.esm.js:897)
    at Calendar.<anonymous> (react-hot-loader.development.js:655)
    at commitLifeCycles (react-dom.development.js:17335)
    at commitAllLifeCycles (react-dom.development.js:18737)
    at HTMLUnknownElement.callCallback (react-dom.development.js:150)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:257)

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/material-ui-pickers-usage-demo-0u8vm

You must not disable all days. Becuase of calendars try to find the closest enabled date to select

**Comment by DrewBe121212** [comment]
OMG! It's been a long week my friend. Sorry for the derp. I was just checking out the function to make sure it was all kosher...

It never even dawned on me to actually try having some dates active... 🤣 

All is well, using something akin to this...
```
shouldDisableDate={(date) => {
    return date.isSameOrAfter(moment('2019-06-07')) && date.isSameOrBefore(moment('2019-06-15'));
}}
```

Sorry again! And thank you for a fantastic project!

**Comment by omkarrevankarthinkitive** [comment]
i have list of dates and then how I can pass them Into the calender so from that only they can be selected

**Comment by LukasTy** [comment]
@omkarrevankarthinkitive A friendly reminder that this package has not been maintained for quite some time.
Please consider migrating to `@mui/x-date-pickers` to get the latest features and fixes. 😉 
As for the implementation, I'm pretty sure that your best bet is using `shouldDisableDate` callback prop.
We also have [an interesting example of using Autocomplete](https://mui.com/x/react-date-pickers/custom-field/#using-an-autocomplete) on the latest package version that might be relevant in your use case. 🤔

**Comment by omkarrevankarthinkitive** [comment]
@LukasTy thanks for the suggessions i'm using dateCalender from material UI inside that i get prop shouldDisableDate 

      <LocalizationProvider dateAdapter={AdapterDayjs}>
                        <DateCalendar
                          sx={{
                            margin: "0px",
                            width: "420px",
                            boxShadow: "0px 0px 8px #00000029",
                          }}
                          onChange={handleDateChange}
                          shouldDisableDate={shouldDisableDate}
                        />
                      </LocalizationProvider>
                      
                        const availableDates = [
    new Date('2023-10-18'), // Add available dates here in the Date format
    new Date('2023-10-20'),
    // Add more available dates as needed
  ];

  function shouldDisableDate(date) {
    // Convert the date to a string for comparison
    const dateString = date.toISOString().split('T')[0];
  
    // Check if the date is in the availableDates array
    return !availableDates.includes(new Date(dateString));
  }

**Comment by LukasTy** [comment]
I see that you are using `AdadpterDayjs`, but managing the `availableDates` as JS `Date` objects.
Consider aligning the API to either use `AdapterDateFns` or create `dayjs` objects instead of `Date` for `availableDates`.
It's not a problem on the package version you are using, but it might simply cause confusion or unknown issues and will also no longer work if and when you upgrade to `@mui/x-date-pickers@6.x`.
It should allow you to go with 
```ts
const shouldDisableDate(date) {
  return !availableDates.some(d => d.isSame(date));
}
```

**Comment by omkarrevankarthinkitive** [comment]
Thanks @LukasTy worked well enough
