### ISSUE TITLE
Keyboard picker return bad value

### ISSUE THREAD

**Issue by kellhellia** [mui-org/material-ui-pickers#1124]
First of all, thanx for great library!

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.1.1    |
| material-ui          |    4.1.0     |
| React                |    16.8.6     |
| Browser              |    Google Chrome 74.0.3729.169     |
| Peer library         |    moment |

## Steps to reproduce

1. Use KeyboardTimePicker (or KeyboardDateTimePicker) 

2. Pass to the value date with utc offset (for example: moment().utc() )

3. Edit the value in keyboard picker

## Expected behavior

Value will be edited

## Actual behavior

Keyboard picker return a value with difference in hours for my timezone, instead of utc time

Picker in modal return right value.

## Live example

First of all, try to edit minutes in textfield - you will see, that keyboard picker value is not right.
Then try to set value via modal picker - everything will be fine :)

https://codesandbox.io/embed/material-ui-pickers-usage-demo-hfslq

**Comment by dmtrKovalenko** [comment]
Ok, after diving deeper I understand that this is not a bug. 
The problem here - when we are parsing date we don't know what you have passed to value. So you must set default timezone to utc in order to parse in particular timezone. 
https://codesandbox.io/s/material-ui-pickers-usage-demo-nv6tr

**Comment by dmtrKovalenko** [comment]
And if you don't want to install and use moment-timezone you can change parsing behavior like so 
https://codesandbox.io/s/material-ui-pickers-usage-demo-bmuq

**Comment by kellhellia** [comment]
> And if you don't want to install and use moment-timezone you can change parsing behavior like so
> https://codesandbox.io/s/material-ui-pickers-usage-demo-bmuq

Sorry, can you fix link for this example? Thanks

**Comment by dmtrKovalenko** [comment]
This works? https://codesandbox.io/s/material-ui-pickers-usage-demo-bmuqx?from-embed

**Comment by kellhellia** [comment]
> This works? https://codesandbox.io/s/material-ui-pickers-usage-demo-bmuqx?from-embed

Yeah, thanx a lot!

**Comment by kellhellia** [comment]
> This works? https://codesandbox.io/s/material-ui-pickers-usage-demo-bmuqx?from-embed

Dmitriy, sorry I have, last question:

If I use this mehod, onChange doesn't return time value (it's undefined), onChange returns only text, by second argument. You can open your example and console.log(time) in onChange prop for testing.

If I add return to parse func, then I have same bug with hours :(

Example with return:
https://codesandbox.io/embed/material-ui-pickers-usage-demo-5o7r7

**Comment by dmtrKovalenko** [comment]
:D My fault 
this works https://codesandbox.io/s/material-ui-pickers-usage-demo-8vemy

**Comment by kellhellia** [comment]
Yeap, it works!
Thanx a lot!
