### ISSUE TITLE
Feature request: Pass props to Dialog Buttons

### ISSUE THREAD

**Issue by ffjanhoeck** [mui-org/material-ui-pickers#1127]
**Is your feature request related to a problem? Please describe.**
No really. I just would like to make my action buttons not primary :).
![image](https://user-images.githubusercontent.com/9037364/59608996-d1ff7a80-9116-11e9-88a5-91e39f607318.png)

**Describe the solution you'd like**
I would like it if the action buttons has their own classes to overwrite them and to pass props to the buttons.

![image](https://user-images.githubusercontent.com/9037364/59608963-c4e28b80-9116-11e9-9de2-6d1dbd87b60c.png)

I havn't found a solution in the docs. Maybe there is one. If not, here is my feature request :)
Big thanks !!

**Comment by dmtrKovalenko** [comment]
Only this way https://codesandbox.io/s/material-ui-pickers-usage-demo-zoxvm
