### ISSUE TITLE
React does not recognize the `invalidLabel` prop on a DOM element.

### ISSUE THREAD

**Issue by lifeiscontent** [mui-org/material-ui-pickers#1130]
![A GIF or MEME to give some spice of the internet](https://media1.tenor.com/images/0d1329f5ff7d31712e3d12ce160df6ec/tenor.gif?itemid=5263684)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |         |
| material-ui          |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

https://codesandbox.io/s/xenodochial-mirzakhani-tdhwd

## Expected behavior

not to throw an error

## Actual behavior

throws a react error (look at console)

## Live example

https://codesandbox.io/s/xenodochial-mirzakhani-tdhwd

**Comment by ekameleoon** [comment]
Hello, I have the same problem +1
