### ISSUE TITLE
Mixed translations used (locales)

### ISSUE THREAD

**Issue by qlecler** [mui-org/material-ui-pickers#1131]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  2.2.1       |
| material-ui          |     3.9.2    |
| React                |   16.8.3      |
| Browser              |    Google Chrome 75     |
| Peer library         |     moment 1.1.0    |  |

## Steps to reproduce

/

## Expected behavior

Translations to be in one language

## Actual behavior

Translations are in multiple languages

## Live example

https://i.imgur.com/i6n4s4j.png

**Comment by dmtrKovalenko** [comment]
PLease update to `@date-io/moment` v1.3.7

**Comment by qlecler** [comment]
I just tried it, it seems to work just fine.

Thanks 👍
