### ISSUE TITLE
Where is the v2 doc ?

### ISSUE THREAD

**Issue by qlecler** [mui-org/material-ui-pickers#1133]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |         |
| material-ui          |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. 2. 3.

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers-v2.dmtr-kovalenko.now.sh/
