### ISSUE TITLE
OnBackdropClick shouldn't update with the current date

### ISSUE THREAD

**Issue by Tareltos** [mui-org/material-ui-pickers#1134]
If no date is set in DatePicker (KeyboardDatePicker,  variant="inline", autoOk={true}) and the user opens the picker and click on backdrop, the onChange function is called with today's date.

Thanks!

**Comment by Tareltos** [comment]
The same behavior as https://github.com/mui-org/material-ui-pickers/issues/1030

**Comment by kg-currenxie** [comment]
Also have this issue. I think a lot of users would expect clicking the backdrop behave like a 'cancel', and not set any date.

**Comment by marc-mrt** [comment]
Yes it was said that my issue was fixed in v3, turned out I redid the whole codesandbox with the updated deps, same thing is still happening: https://codesandbox.io/s/wonderful-wood-fnznc

**Comment by kg-currenxie** [comment]
Yay 🎉
