### ISSUE TITLE
Issue when passing views prop

### ISSUE THREAD

**Issue by emmettcv** [mui-org/material-ui-pickers#1135]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |         |
| material-ui          |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. 2. 3.
I was passing the views prop to DatePicker react component as
views={["years", "month", "date"}

I fixed it by passing

views={["years", "month", "day"}

I think your documentation is wrong

## Expected behavior

I wanted to be asked enter year, month, then day

## Actual behavior

it was asking year, month, then closing on day, and setting the day to the 1st of the month

**Comment by dmtrKovalenko** [comment]
It is invalid. Provide a way to reproduce if you still think that it is an issue
