### ISSUE TITLE
Can't set an id on Calendar

### ISSUE THREAD

**Issue by sachadvt** [mui-org/material-ui-pickers#1136]
First of all, thank you for the amazing work you do! It's the first issue I fill on Github so I apologize if I do it wrong and don't hesitate to tell me if this is the case. I'm not sure if this is a bug or a feature request, sorry in advance if I chose the wrong one.

## Environment

| Tech                           | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.1.1 |
| material-ui                 | 4.1.1 |
| React                         | 16.8.6 |
| Browser                     | Google Chrome 75.0.3770.100 |
| Peer library               | moment 2.2.4.0 |

## Steps to reproduce

1. Use Calendar
2. Set an id prop

`<Calendar date={moment.tz(date, timeZone)} id="myId" onChange={onChange} renderDay={renderDay} />`

## Expected behavior

It compiles with TypeScript.

## Actual behavior

It doesn't compile:

```Type '{ date: Moment; id: string; onChange: (d: any) => void; renderDay: (day: any, selectedDate: any, isDayInCurrentMonth: boolean) => Element; }' is not assignable to type 'IntrinsicAttributes & Pick<PropsWithChildren<Pick<CalendarProps, "date" | "classes" | "onChange" | "theme" | "onMonthChange" | "leftArrowIcon" | "rightArrowIcon" | "leftArrowButtonProps" | ... 8 more ... | "loadingIndicator">>, "children" | ... 14 more ... | "loadingIndicator"> & StyledComponentProps<...> & { ...; }'.
  Property 'id' does not exist on type 'IntrinsicAttributes & Pick<PropsWithChildren<Pick<CalendarProps, "date" | "classes" | "onChange" | "theme" | "onMonthChange" | "leftArrowIcon" | "rightArrowIcon" | "leftArrowButtonProps" | ... 8 more ... | "loadingIndicator">>, "children" | ... 14 more ... | "loadingIndicator"> & StyledComponentProps<...> & { ...; }'.  TS2322

**Comment by dmtrKovalenko** [comment]
Yeah, but we are not spreading anything down for calendar component

**Comment by sachadvt** [comment]
Would it be possible to do so?

**Comment by dmtrKovalenko** [comment]
I think no
