### ISSUE TITLE
Allow to change the rendering of the name of a day in the calendar

### ISSUE THREAD

**Issue by sachadvt** [mui-org/material-ui-pickers#1137]
First of all, thank you for the amazing work you do!   

**Is your feature request related to a problem? Please describe.**

I wanted to use your Calendar outside of a picker so I took your Calendar component and implemented renderDay to add a Badge and some margin to the display of a day. But now, the names of the days are not aligned with the numbers and there is no way to modify them.

![what_i_have](https://user-images.githubusercontent.com/5445471/59931977-713dae00-9446-11e9-8691-c13f14d78998.png)

**Describe the solution you'd like**

Would it be possible to add a method like renderDay to personalize the render of the name of the days in the CalendarHeader?

**Describe alternatives you've considered**

I used some global css to do the trick but the code is kind of ugly.

![what_i_want](https://user-images.githubusercontent.com/5445471/59932461-7e0ed180-9447-11e9-9217-fb27f7c8082b.png)

**Comment by dmtrKovalenko** [comment]
You can override them with a help of `overrides` or using global css. https://material-ui-pickers.dev/guides/css-overrides

**Comment by sachadvt** [comment]
Sorry I didn't see this page, this is exactly what I needed, thank you!

**Comment by ehcaneontheweb** [comment]
> You can override them with a help of `overrides` or using global css. https://material-ui-pickers.dev/guides/css-overrides

not sure what's the reason, but that url redirects me to a different page outside material-ui.
