### ISSUE TITLE
Can no longer access `keepCharPositions` parameter in version 3.1.0

### ISSUE THREAD

**Issue by nikolayg** [mui-org/material-ui-pickers#1144]
Hi there,

Thanks for your work on this great library!

I've been trying to set the `keepCharPositions` flag for the underlying text field. I followed the solution in [this issues](https://github.com/mui-org/material-ui-pickers/issues/505), but it doesn't seem to be working for `@material-ui/pickers` version `3.1.0`.

For example, in the following code keepCharPositions does not take effect:

```
    <KeyboardDatePicker
      autoOk={true}
      variant="inline"
      label={"Test"}
      format={"dd/MM/yyyy"}
      inputValue={"12/12/1900"}
      value={null}
      InputAdornmentProps={{ position: "end" }}
      placeholder={"__/__/____"}
      onChange={(_date, value) => {
        console.log(value);
      }}
      InputProps={{
        inputProps: {
          keepCharPositions: true
        }
      }}
    />
```

Any ideas how to use `keepCharPositions` with the latest version?

**Comment by dmtrKovalenko** [comment]
Hey @TrySound do you know is it possible to make smth simmilar to [keepCharPositions](keepCharPositions) from react-text-mask with rifm?

**Comment by TrySound** [comment]
We have `mask` flag in the new version for this. In the version you use it's `replace: string => boolean`.

**Comment by dmtrKovalenko** [comment]
Hmm, but can we update to the latest rifm without major release? We exposing only `refuse` api prop

**Comment by TrySound** [comment]
Refuse is replaced with inverted accept. I'm not sure it is possible to convert this regexp. Upgrade will be a breaking change. You may add `keepCharPositions` option for now which will wrap `replace` and after upgrade `mask`.
