### ISSUE TITLE
Cannot pick a date on small screen

### ISSUE THREAD

**Issue by rbuetzer** [mui-org/material-ui-pickers#1147]
## Description

When I open the date picker on a small device in landscape mode, I cannot select a date.

## Environment

I had this issue on a Redmi Note 3, but I am quite sure it is not the only device affected.

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.1.2 |
| material-ui          | 4.0.2 |
| React                | 16.8.6 |
| Browser              | Chrome mobile |
| Peer library         |  moment.js 22.2.2 |

## Steps to reproduce

Without knowing what device you have available, the easiest way to reproduce this behaviour is probably in a desktop browser.

1. Go to https://material-ui-pickers.dev/demo/datepicker
2. Simulate a device viewport ([Firefox](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode#Using_Responsive_Design_Mode), [Chrome](https://developers.google.com/web/tools/chrome-devtools/device-mode/#viewport))
3. Select a small viewport, e.g. _iPhone 6/7/8_, _landscape_
4. Click on the first example ("Basic Example")

## Expected behavior

I can select the last day of the current month.

## Actual behavior

The month is cropped and I cannot scroll to the last day of the current month.

![datepicker-small-screen](https://user-images.githubusercontent.com/2462187/60074893-5019dd80-9724-11e9-8088-6870b5d71874.png)

## Live example

See _Steps to reproduce_

**Comment by dmtrKovalenko** [comment]
Ohh yeah, that is related to #766. 
We need to implement that :)

**Comment by aguilera51284** [comment]
+1

**Comment by rbuetzer** [comment]
@dmtrKovalenko Thanks for your response. As this issue is a duplicate of #766, feel free to close it.

**Comment by dmtrKovalenko** [comment]
I will leave it for myself as a reminder that this is hight priority

**Comment by dmtrKovalenko** [comment]
Closed by #1177
