### ISSUE TITLE
moment localization problem in picker ver 2.2

### ISSUE THREAD

**Issue by daniel-pietryga** [mui-org/material-ui-pickers#1149]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  2.2.4       |
| material-ui          |   3.8.1      |
| React                |    16.6     |
| Browser              |     chrome    |
| Peer library         |    moment 2.24.0     |  |

## Steps to reproduce

1. 
import moment, and 'pl' locale
2.
set moment.locale('pl') globally - just after imports
 3.
pass MomentUtils, locale and moment to MuiPickersUtilsProvider, as in exaple attached below

## Expected behavior

picker translated to 'pl' locale

## Actual behavior

picker still in 'en' locale

## Live example

I try to recreate example from this: 
[https://material-ui-pickers-v2.dmtr-kovalenko.now.sh/localization/moment](url)

I have a dateTimePicker and try to localize it with locale ='pl'. I call moment.locale=('pl') but console.log still shows it as 'en' and nothing changes on template

**Comment by dmtrKovalenko** [comment]
Please fill the issue. Or it will be closed

**Comment by daniel-pietryga** [comment]
@ Why is this topic closed without any answer?

**Comment by daniel-pietryga** [comment]
@dmtrKovalenko why is this topic closed without any answer?

**Comment by dmtrKovalenko** [comment]
1) Nothing was updated when I closed the ticket
2) Right now can say that we are no longer support v2 -- please update

**Comment by dmtrKovalenko** [comment]
This problem was already fixed
