### ISSUE TITLE
Configure Timezone with date-fns

### ISSUE THREAD

**Issue by zsid** [mui-org/material-ui-pickers#1150]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.1.2      |
| material-ui-core          |    4.1.3     |
| React                |    Yes     |
| Browser              |    Chrome     |
| Peer library         |  date-fns     | 

## Steps to reproduce
Keep up the goods work! The use case we are running into is:

We have a movie release that is specified in Europe/London timezone on 29/10/2019 at 10:00 o'clock.
* When a user in another time zone opens it, we want to ignore their timezone and show exactly the same entry - `Europe/London` time zone and `10:00` o'clock. The user can change the scheduled release time to `13:00` and save it back to the db. That `13:00` is the time in `Europe/London` time zone.

There is another issue raised for timezone using [`moment`](https://github.com/mui-org/material-ui-pickers/issues/971) where you can pass a moment instance with that timezone. I couldn't find anything for `date-fns`

## Expected behavior
* We can specify the `DateTimePicker` to ignore the browser time zone and always display it in that particular timezone - i.e. Europe/London at `10:00`.

## Actual behavior
* `DateTimePicker` is using browser time to show the time.

**Comment by dmtrKovalenko** [comment]
What lib do you use to support time zone? Native datefns doesn’t support timezone management

**Comment by zsid** [comment]
We are using [`date-fns-tz`](https://github.com/marnusw/date-fns-tz#readme)

**Comment by dmtrKovalenko** [comment]
I think it will be possible only with some sort of custom utils 
```js
class DateFnsTzUtils {
  format(date, formatString) {
    return formatTz(date, formatString, {
      timeZone: "America/New_York",
      locale: this.locale
    });
  }
}
```

But it will not work due to [issue](https://github.com/dmtrKovalenko/date-io/issues/55) in date-io. Right now you will be needed to override a lot of methods to be sure it works. I will fix this issue and it should be easy.

**Comment by zsid** [comment]
Great, thanks. I will wait for that the be addressed in `date-io`. Cheers.

**Comment by zsid** [comment]
My bad 😄

**Comment by zsid** [comment]
I have posted about `disablePast` in the other [issue](https://github.com/dmtrKovalenko/date-io/issues/55). Not sure whether it can be addressed there or here.

**Comment by dmtrKovalenko** [comment]
Fixed by https://github.com/dmtrKovalenko/date-io/issues/55

**Comment by jbojcic1** [comment]
hey @zsid did you manage to do this? If yes which properties of the DateFnsUtils did you need to override?

If I override just format as shown above, I have other issues like today's date not highlighted correctly etc

**Comment by zsid** [comment]
@jbojcic1 we saved the date in UTC format in the database. The timezone requirement changed and we used whatever the browser timezone was when initiating.
