### ISSUE TITLE
Static DatePicker

### ISSUE THREAD

**Issue by shtelzerartem** [mui-org/material-ui-pickers#1154]
Firstly, wanna pay you gratitude for what you`re doing! Very useful. Much thanks!

**In previous versions you could staticly place datepicker on the page without (or with) textfiled.**
The problem is that you cannot do this in current verion (3.1.2) 
I`ve read some previous issues on this theme and the code attached there is not working now. Much code has changed since, that is not surprisingly.

I think, these feature will be useful, cause now you can only use calendar.

**Comment by hinsxd** [comment]
Glad to have someone dealing with the same problem too!
I tried today, figured out that the behavior of  `onChange` is a bit strange.
You need to defined `onChange` prop again in the component.
```js
<Calendar
    {...pickerProps}
    onChange={date => setDate(date)} // or your custom logic
/>
```

**Comment by crazytyper** [comment]
Same issue here: We want to place a `<Picker/>` inline alongside other components.

I am ware that there is some way of control over how the `<Picker/>` is rendered using property `variant="dialog|line"`.

It would be great to have a 3rd value for `variant` that would prevent wrapping the `<Picker/>` in a popover. 

Note: In previous versions we have solved this by importing internal components, but that is no longer possible unless you solely use [named imports](https://material-ui-pickers.dev/guides/static-components).
