### ISSUE TITLE
Hours only view in TimePicker does not hide separator

### ISSUE THREAD

**Issue by netaelk** [mui-org/material-ui-pickers#1155]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.1.2      |
| material-ui          |         |
| React                |    16.8.6     |
| Browser              |     chrome    |
| Peer library         |     moment 2.24.0   |

## Steps to reproduce

1.set views={["hours"]}
2. open TimePicker

## Expected behavior

tool bar contains hours figures only

## Actual behavior

tool bar displays separator too. e.g "08:" instead of "08"
## Live example

https://codesandbox.io/embed/material-ui-pickers-usage-demo-um132

**Comment by dmtrKovalenko** [comment]
Closed by #1161
