### ISSUE TITLE
Opening DatePicker on specific date even if value is not null

### ISSUE THREAD

**Issue by me21** [mui-org/material-ui-pickers#1158]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to open DatePicker on specific date even if `value` is not null. Currently, `initialFocusedDate` is considered only if `value` is null (date not set yet). If the date is already set, DatePicker opens on the set date.

**Describe the solution you'd like**
I'd like a way to specify that `initialFocusedDate` should be applied even if some date is already set.

**Describe alternatives you've considered**
I'm not very familiar with DatePicker component yet to try any undocumented solutions.

**Comment by dmtrKovalenko** [comment]
That is weird. Why you need to open another day if some already set

**Comment by me21** [comment]
I need to set start and end dates for records in the database.
I have a specific date, 31.12.2100, meaning "end date is not set". I'd like to open datepicker on today in that case.
I could use NULL for that case, but checking if some date is between start and end is simpler if they cannot be NULL.

**Comment by me21** [comment]
I have solved it by passing `value` prop as null when needed.

**Comment by olaj** [comment]
I actually would like this as well.

For me it is that "in 90% of the cases" the user is picking "today" as the value but i do not want to automatically change the value. I could of course add some kind of custom button or whatnot but that feels a bit overkill.

I tried with                 

`onOpen={() => (values.dateChecked = moment())}`

But it just changed the value and not the value in the picker itself.
