### ISSUE TITLE
TextFieldComponent Documentation Example

### ISSUE THREAD

**Issue by joshkay** [mui-org/material-ui-pickers#1165]
![A GIF or MEME to give some spice of the internet](https://www.rover.com/blog/wp-content/uploads/2014/10/bailey-computer1.png)

**Is your feature request related to a problem? Please describe.**
I've been trying to provide the `DatePicker` with a custom `TextFieldComponent`, but I can't for the life of me figure out what I am doing wrong.  I have tried to find examples, but I found nothing in the current documentation.  Is this something that is only supported by Typescript?

**Describe the solution you'd like**
Is it possible to get some examples on how to use a custom `TextFieldComponent`?

**Additional context**
I am currently passing the component like so
```TextFieldComponent={TextField}``` where `TextField` is the existing component provided by @material-ui.  I was originally trying to pass `InputBase`, but am trying this step to see if that was the issue.  I get the following error: ```Warning: React does not recognize the `TextFieldComponent` prop on a DOM element.```

I can't help but feel like I am doing something incredibly stupid.

Thanks!

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/o7oojxx1pq
This must help

**Comment by AcidRaZor** [comment]
> https://codesandbox.io/s/o7oojxx1pq
> This must help

I have the same issue it appears, wondering what you mean by "this must help" when it doesn't address the confusion? Sorry my English is bad.

**Comment by denis-zenkovich** [comment]
This is really a problem, I had to digest the sources to figure out how to use this `TextFieldComponent` so it finally works! And trust me with all this wrappers wrapped around wrapper ;) this is not a simple task.

So this is not desciptive but this is what I finally came for and what is working with `ReduxForm` tuned `TextField`.

`
import React from 'react'
import { DateTimePicker } from '@material-ui/pickers'
import TextFieldWrap from './TextFieldWrap'
import { DATE_FORMAT_TIME } from '../../constants'

const DateTimePickerWrap = ({
                              input: { onChange, value },
                              ...props
                            }) =>
  <DateTimePicker variant="inline"
                  value={value}
                  onChange={value => {
                    onChange(value && value.format(DATE_FORMAT_TIME))
                  }}
                  TextFieldComponent={
                    ({ inputProps, onClick, inputRef }) =>
                      <TextFieldWrap {...props}
                                     input={{ value }}
                                     inputProps={inputProps}
                                     onClick={onClick}
                                     inputRef={inputRef}/>
                  }
                  format={DATE_FORMAT_TIME}

  />

export default DateTimePickerWrap
`

The key problem I was having is missing `inputRef` down the props pipe. So as you can see, the statement that lib passes all unrecognised props down to TextField doesn't seem true, so I'm grabbing all the ReduxForm things except for `onChange` and passing them down to my TextFieldWrapper (that's the material UI FormControl thing updated to work with ReduxForm). I'm using `onChange` to update the ReduxForm on changes in calendar. I'm formatting the date down to string right away (FYI this will keep buggin you with console warning of non-ISO format, but I don't care) and I've also hardcoded it to be "inline" mode. Hope this helps.

**Comment by adamtaylor13** [comment]
@denis-zenkovich Please share your full example! 🙌

**Comment by ianccy** [comment]
I use inputRef as component reference, datePicker popup will find target render view.

source code
```
// inputRef, onClick    get from dataPicker component props
function TextFieldWrap({ placeholder, value, inputRef, onClick }) {
    return (
        <input
            ref={inputRef}
            css={css(fieldInputTextStyle, dateWidthStyle)}
            type="text"
            placeholder={placeholder}
            value={value}
            onClick={onClick}
        />
    );
}```

**Comment by denis-zenkovich** [comment]
@adamtaylor13 
Here you go:
[`DateTimePickerWrap.jsx `](https://gist.github.com/denis-zenkovich/635d64352c493a8e1c15ce024bcafdb0)
I've applied couple fixes, and changed it to work with date object but pass down formatted date string into `TextField`

[`TextFieldWrap.jsx`](https://gist.github.com/denis-zenkovich/38c9318cad5314991be6debc9d10d0d4)
This is wrapped `InputBase` to make it look similar to Bootstrap and make it work with `redux-form`

**Comment by barbalex** [comment]
Why is this closed? It is not documented or have I missed the documentation?

**Comment by monteiz** [comment]
Here is a simple example, if you want to display a Button instead of a TextField:

```
import React from "react";
import Button from "@material-ui/core/Button";

const DatePickerTextField = function(props) {
  return (
    <Button
      color="primary"
      onClick={props.onClick} // do not override
      id={props.id} // do not override
      disabled={props.disabled} // do not override
      {...props.inputProps} // do not override
    >
      {props.value}
    </Button>
  );
};

export default DatePickerTextField;
```

**Comment by aemc** [comment]
The onChange function doesn't seem to work inside the TextFieldComponent props

**Comment by oliviertassinari** [comment]
@aemc Do you have a reproduction with the latest version (v4.0.0-alpha?)

**Comment by erin-doyle** [comment]
This is still an issue.  I'm not finding anything in the docs showing how to use this prop.  It shouldn't require digging through the source and trial and error.  If it works then a simple example added to the docs would be massively useful.

**Comment by dmtrKovalenko** [comment]
@erin-doyle https://next.material-ui-pickers.dev/demo/datepicker#custom-input-component

**Comment by erin-doyle** [comment]
Ok, so it's in the alpha docs but not yet the current "latest" version which is what I was looking at.  Thanks.

**Comment by pipech** [comment]
For those who still need an answer.

You'll then change MUI TextField to your custom components.

```js
import React from 'react';

import { KeyboardDatePicker } from '@material-ui/pickers';
import { TextField } from '@material-ui/core';

const TextFieldComp = ({
  InputProps,
  disabled,
  error,
  helperText,
  onChange,
  value,
}) => (
  <TextField
    InputProps={InputProps}
    disabled={disabled}
    error={error}
    helperText={helperText}
    onChange={onChange}
    value={value}
  />
);

const DateInput = () => {
  const [selectedDate, setSelectedDate] = React.useState(
    new Date('2014-08-18T21:11:54'),
  );

  const handleDateChange = (date) => {
    setSelectedDate(date);
  };

  return (
    <KeyboardDatePicker
      value={selectedDate}
      onChange={handleDateChange}
      TextFieldComponent={TextFieldComp}
      format="MM/dd/yyyy"
    />
  );
};
export default DateInput;
```
