### ISSUE TITLE
Wrong picker placement when using Keyboard* components

### ISSUE THREAD

**Issue by tonai** [mui-org/material-ui-pickers#1166]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.1.1        |
| material-ui          |  4.1.3       |
| React                |  16.8.6       |
| Browser              | chrome 72        |
| Peer library         | moment 2.24        |  |

## Steps to reproduce

Just use the `KeyboardDatePicker` or `KeyboardTimePicker`.

## Expected behavior

I expect the picker to be aligned with the field.

## Actual behavior

The picker is aligned with the inner `input` element, but not the whole `Textfield` which contains an icon to open the picker.

## Live example

Go to https://material-ui-pickers.dev/api/TimePicker and on the `Inline mode` part, open the picker which label is `With keyboard`.

The position of the picker is shifted to the left:
![Capture d’écran de 2019-07-08 11-38-25](https://user-images.githubusercontent.com/5246045/60801666-ac92e900-a177-11e9-9b33-ba9339075b44.png)

This can be quicly fixed by changing the `anchorOrigin` and `transformOrigin` properties of the `Popover` in this file https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/wrappers/InlineWrapper.tsx#L61-L68 by using `left` instead of `right`.

Or maybe using another element as the `anchorEl` property.

Also the ternary `true ? 'right' : 'center'` is useless...

**Comment by dmtrKovalenko** [comment]
yeah 💃  it is side effect of v3 refactoring :D

**Comment by manoharreddyporeddy** [comment]
Below does not work for my case:

```
        PopoverProps={{
          anchorOrigin: { horizontal: 'center', vertical: 'bottom' },
          transformOrigin: { horizontal: 'center', vertical: 'bottom' },
        }}
```

Need to use `anchorEl`, but no good example for when there are many dynamic elements
