### ISSUE TITLE
Display time on iOS device wrongly using Material-UI-Picker

### ISSUE THREAD

**Issue by dovanquynh** [mui-org/material-ui-pickers#1168]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui-pickers |  2.0.4       |
| material-ui          |     3.5.1    |
| React                |     16.6.0    |
| Browser              |     chrome, safari iPhone    |
| Peer library         |     @date-io/date-fns, moment 2.23.0    |  |

## Steps to reproduce

1. I have an example on codesandbox. I think there are some problems about timezone momentjs

## Expected behavior

Display 01:00

## Actual behavior

Display 08:00

## Live example
https://codesandbox.io/s/test-time-picker-4l6l1

**Comment by dmtrKovalenko** [comment]
1) why you are using date fns with moment 
2) pass configured library instance. Like date for date-fan and moment instance for moment utils. 
That’s a problem with iso strings in safari

**Comment by dovanquynh** [comment]
> 1. why you are using date fns with moment
> 2. pass configured library instance. Like date for date-fan and moment instance for moment utils.
>    That’s a problem with iso strings in safari

Thank you, It is not bug
