### ISSUE TITLE
when providing shouldDisableDate function, the validation shouldn't validate against every date in the past

### ISSUE THREAD

**Issue by natehardy** [mui-org/material-ui-pickers#1169]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.0.0       |
| material-ui          |  4.0.2       |
| React                |  16.8.6       |
| Browser              |  Chrome       |
| Peer library         |  date-fns       |  |

## Steps to reproduce

Provide a shouldDisableDate function

## Expected behavior

The function shouldn't run against all possible dates when it first mounts. Either the developer should provide a range to check within or the function should only run against visible dates.
The performance hit would be much less on startup

**Comment by dmtrKovalenko** [comment]
It will be run on all the date only if current date is disabled, isn’t it?
