### ISSUE TITLE
inputComponent prop only accepts string

### ISSUE THREAD

**Issue by AcidRaZor** [mui-org/material-ui-pickers#1173]
When trying to override the input component that is used with TextField (so I can get normal styling on my input element for the calendar), propTypes appear to only accept string:

> React.createElement: type is invalid -- expected a string

However, from the documentation on the API:

> inputComponent - The component used for the native input. Either a string to use a DOM element **or a component**.

**Comment by dmtrKovalenko** [comment]
You must use TextFieldComponent prop

**Comment by AcidRaZor** [comment]
@dmtrKovalenko Apologies, I was using TextFieldComponent property. Same behavior.
