### ISSUE TITLE
Impossible to specify custom zIndex with classes (using DialogProps)

### ISSUE THREAD

**Issue by volodalexey** [mui-org/material-ui-pickers#1174]
**Is your feature request related to a problem? Please describe.**
I have `DatePicker` in different cases.
1)
`Simple page` -> `DatePicker`
2)
`Simple page` -> `DetailViewDrawer` -> `FiltersModal` -> `DatePicker`

And for 1 - it works.
For 2 - doesn't work. I can not see `Dialog` because my `FiltersModal` has higher `zIndex` than regular `MuiModal` that is used by `DatePicker`

**Describe the solution you'd like**
I investigated suggested proposals [552](https://github.com/mui-org/material-ui-pickers/issues/552) and [955](https://github.com/mui-org/material-ui-pickers/issues/955).
And I used `DialogProps`:
```
const styles = () => ({
  modalRoot: {
    zIndex: 5000,
  },
});

function Calendar({
  classes,
} = {}) {
  return (
    <DatePicker
      DialogProps={{
        classes: {
          dialogRoot: classes.modalRoot,
        },
      }}
    />
  );
}
```
With this settings following layout is generated (when `DatePicker` is opened):
```
<div role="dialog" class="jss-MuiModal-root-102 jss-MuiDialog-root-443">
  <div class="jss-MuiBackdrop-root-341" aria-hidden="true"></div>
  <div class="jss-MuiDialog-container-446 jss-MuiDialog-scrollPaper-444" role="document">
    <div class="... jss-Calendar-modalRoot-411 ..."></div>
  </div>
</div>
```
As you can see, the top most element that I can reach with `DialogProps` is `<div class="... jss-Calendar-modalRoot-411 ..."></div>`
However I need to change `zIndex` of `MuiModal-root` for particular DatePicker.

Can you help me?
Can I reach some how low level `ModalProps`?

**Comment by nikhilaggala** [comment]
@volodalexey Is this issue resolved?

**Comment by volodalexey** [comment]
@nikhilaggala unfortunately no.

**Comment by nikhilaggala** [comment]
@volodalexey So, is there any workaround?

**Comment by volodalexey** [comment]
@nikhilaggala I do not know (

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case with the latest version (v4.0.0-alpha.5 as we are writing). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/cool-cherry-v3cbt) _may_ be a good starting point. Thank you!
