### ISSUE TITLE
[KeyboardDatePicker] After the update to 3.1.2, we can't display helperText 

### ISSUE THREAD

**Issue by Amraneze** [mui-org/material-ui-pickers#1175]
Hi,

I have an issue, before updating material-UI to 4 and material-ui-pickers to latest version, I got an issue with displaying helperText. Before, I was using it in DatePicker and it was displaying everytime I have an error, but now the props 'helperText' was removed in KeyboardDatePicker and even I added the props **validationError** I don't see anything displayed. 
Then I added in inputProps the following props
`InputProps={{
         error: !!error,
         helperText: error,
}}`

for the last solution I have the input in red state which mean sthe error props works but there is no helperText below it.

What I found that **ModalWrapper** doesn't pass the **validationError** to **KeyboardDateInput**. If you added the a text in **validationError** of **KeyboardDateInput** then the error will be displayed.

![image](https://user-images.githubusercontent.com/28459763/61185108-96909700-a655-11e9-8112-d198551e2657.png)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.1.2 |
| material-ui                 | 4.0.0 |
| React                          | 16.8.6 |
| Browser                      | Chrome 75.0.3770.100 |
| date-fns                     | 2.0.0-alpha.27 |

## Steps to reproduce

1. Adding errors in KeyboardDatePicker to display errors

## Expected behavior

The error needs to be displayed in helperText of the input

## Actual behavior

Nothing displayed

## Live example

Here is a live example 
https://codesandbox.io/s/material-ui-pickers-usage-demo-ecbp0

Thank you.

**Comment by dmtrKovalenko** [comment]
Here is working example https://codesandbox.io/s/material-ui-pickers-usage-demo-o4uqs 
You need to pass props directly to the component
