### ISSUE TITLE
Webpack issue - ver 2.2.4

### ISSUE THREAD

**Issue by avagarwal** [mui-org/material-ui-pickers#1176]
Hi,

When running webpack to build a dev version - receiving the following issue -

material-ui-pickers/_shared/DateTextField.d.ts(101,74):
    TS2344: Type '"hidden" | "color" | "style" | "disabled" | "label" | "select" | "title" | "mask" | "children" | "error" | "dir" | "slot" | "type" | "component" | "margin" | "name" | "defaultChecked" | ... 283 more ... | "onInputChange"' does not satisfy the constraint '"hidden" | "color" | "style" | "disabled" | "label" | "select" | "title" | "mask" | "key" | "ref" | "children" | "error" | "dir" | "slot" | "type" | "margin" | "name" | "defaultChecked" | ... 286 more ... | "onInputChange"'.
      Type '"component"' is not assignable to type '"hidden" | "color" | "style" | "disabled" | "label" | "select" | "title" | "mask" | "key" | "ref" | "children" | "error" | "dir" | "slot" | "type" | "margin" | "name" | "defaultChecked" | ... 286 more ... | "onInputChange"'.

What is the cause of the same?

**Comment by dmtrKovalenko** [comment]
We are not supporting the v2 version. But looks like mismatch of material ui and pickers version
