### ISSUE TITLE
adding local in calendar

### ISSUE THREAD

**Issue by atifaziz2** [mui-org/material-ui-pickers#1178]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   ^2.1.2      |
| material-ui          |  ^0.20.2       |
| React                |   16.6.0      |
| Browser              |  Chrome       |

## Steps to reproduce

1. Add MuiPickersUtilsProvider
2. local props is not working

## Expected behavior

Calendar should be changed by local.

## Actual behavior

Nothing happens change, calendar is showing with default local.

**Comment by dmtrKovalenko** [comment]
Provide reproduction and note that we are no longer support v2 versions
