### ISSUE TITLE
focus loses after each keyboard input for custom TextFieldComponent

### ISSUE THREAD

**Issue by fedchenko273** [mui-org/material-ui-pickers#1179]
Overriding TextFieldComponent forces losing focus after each keyboard input
 
```TextFieldComponent={props => {
     return (
            <TextField
              {...props}
              value={formattedValue}
              onChange={event => setFormattedValue(event.target.value)}
            />
          );
    }}
```

## Live example

Sandbox example https://codesandbox.io/embed/datepicker-y0dn7

**Comment by dmtrKovalenko** [comment]
You must call `props.onChange` on textfield change. But the issue is that you are changing the datepicker value on each keystroke. It forces to reapply value 
https://codesandbox.io/embed/datepicker-y0dn7

**Comment by fedchenko273** [comment]
So there is no way to pass a value to custom TextFieldComponent?

**Comment by dmtrKovalenko** [comment]
Ohh god you are using v2. We are not supporting it
In v3 you can use `inputValue` and pass any string from the root of `<KeyboardDatePicker />`

**Comment by bjutkoski** [comment]
I still can't understand how to make it work

https://codesandbox.io/embed/clever-brattain-5bujt

**Comment by De-Santa** [comment]
Having same issue as @bjutkoski .
@dmtrKovalenko can you provide more details or example please?

**Comment by dmtrKovalenko** [comment]
Solution https://github.com/mui-org/material-ui-pickers/issues/1388

**Comment by bjutkoski** [comment]
So simple. Thank you @dmtrKovalenko 
@De-Santa it works for me
