### ISSUE TITLE
Custom Toolbar component

### ISSUE THREAD

**Issue by wscourge** [mui-org/material-ui-pickers#1180]
![image](https://user-images.githubusercontent.com/16985871/61212151-aebdf000-a701-11e9-99c0-df3ccc0e4e66.png)

Reference: [Rethinking the date picker UI](https://uxdesign.cc/rethinking-the-date-picker-ui-99b9dcb303ad)

**Is your feature request related to a problem? Please describe.**

It is not, as far as I've searched for the "toolbar" in all the Issues.

**Describe the solution you'd like**

In order to create the DatePicker described in the referenced article, I'd like to be able to pass my own `<Toolbar />` component in place of the default one, ideally with the currently selected date as a prop.

```
<DatePicker 
  ToolbarComponent={({ year, month, date }) => (<div>{year}</div><div>{month}</div>))
/>
```

**Describe alternatives you've considered**

I looked through [`Dialog`](https://material-ui.com/api/dialog/) and [`Popover`](https://material-ui.com/api/popover/) documentations for more specific `prop` name instead of proposed `ToolbarComponent`, but this one seems self-descriptive enough, I guess.

**Comment by dmtrKovalenko** [comment]
Yeah it should be easy

**Comment by simromm** [comment]
How do you overload the ToolbarComponent with additionnal compoment?

Something like but I don't know how to call the default toolbar:
```
<DatePicker 
  ToolbarComponent={(props) => (<div><ToolbarComponentDefault {...props /><OtherComponent /></div>))
/>
```

**Comment by monteiz** [comment]
This is a basic implementation of a CustomToolbar that mimics the default behaviour. It can be further customised.

It may help someone.

```
import React, { useState } from 'react';
import PickerToolbar from "@material-ui/pickers/_shared/PickerToolbar";
import ToolbarButton from "@material-ui/pickers/_shared/ToolbarButton";
import { makeStyles } from '@material-ui/core';

export const useStyles = makeStyles({
	toolbar: {
		display: "flex",
		flexDirection: "column",
		alignItems: "flex-start"
	}
});

const CustomToolbar = function (props) {

	const { date,
		isLandscape,
		openView,
		setOpenView,
		title} = props;

	const handleChangeViewClick = (view) => (e) => {

		setOpenView(view);

	}

	const classes = useStyles();

	return (
		<PickerToolbar className={classes.toolbar} title={title} isLandscape={isLandscape}>
			<ToolbarButton
				onClick={handleChangeViewClick("year")}
				variant="h6"
				label={date.format("YYYY")}
				selected={openView === "year"}
			/>
			<ToolbarButton
				onClick={handleChangeViewClick("date")}
				variant="h4"
				selected={openView === "date"}
				label={date.format("LL")}
			/>
		</PickerToolbar>
	);

}

export default CustomToolbar;
```

**Comment by Github3143** [comment]
@monteiz how to use CustomToolbar component
in the DatePicker component

**Comment by jaynsuthar** [comment]
@monteiz Thank you for the custom toolbar component implementation. 
@Github3143  you can pass in "ToolbarComponent" props

<KeyboardDatePicker
                label="DOB"
                autoOk="true"
                variant="inline"
                value={search.dob}
                onChange={date => setDate(date)}
                views={["year", "month", "date"]}
                name="dob"
                format="MM/dd/yyyy"
                KeyboardButtonProps={{ className: classes.dateIcon }}
                **ToolbarComponent={CustomToolbar}**
              />

**Comment by tae-at-speer** [comment]
@monteiz Can you also provide default toolbar for Keyboard Time picker?

**Comment by monteiz** [comment]
@tae-at-speer Sorry, I do not have it.

**Comment by tae-at-speer** [comment]
I've found out that you can use Keyboard Time picker Toolbar separately using this.
`import { T as TimePickerToolbar } from '@material-ui/pickers/esm/TimePickerToolbar-81100fab.js';
`
