### ISSUE TITLE
Orientation property doesn't seem to exist

### ISSUE THREAD

**Issue by goosecoid** [mui-org/material-ui-pickers#1185]
From the DatePicker API:

[API url](https://material-ui-pickers.dev/api/DatePicker)

`orientation       "portrait" \| "landscape" | "portrait" | Force rendering in particular orientation`

`<DatePicker orientation={'landscape'}/>`

Gives me this: ` Property 'orientataion' does not exist on type 'IntrinsicAttributes & DateValidationProps & BasePickerProps...`

**Comment by dmtrKovalenko** [comment]
Which version are you using?

**Comment by goosecoid** [comment]
"@material-ui/pickers": "^3.1.2"

**Comment by dmtrKovalenko** [comment]
It landed in 3.2.0
