### ISSUE TITLE
TextField props missing from TS types

### ISSUE THREAD

**Issue by mAAdhaTTah** [mui-org/material-ui-pickers#1186]
# Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.0       |
| material-ui          |   3.2.0      |
| React                |    16.8.6     |
| Browser              |    Chrome     |
| Peer library         | date-fns        |  |

## Steps to reproduce

1. Build a component like this:

```ts
<KeyboardDatePicker inputProps={{ 'data-testid': 'job-expire-date-input' }} />
```
2. Check it with TypeScript.

## Expected behavior

`inputProps` should be recognized as one of the TextField props that gets forwarded.

## Actual behavior

> Property 'inputProps' does not exist on type

If you're extending or inheriting the props from TextField, it should just work. I haven't dove into the code yet, but if you're not currently doing that, it may be easier than explicitly whitelisted which props are passed down.

**Comment by dmtrKovalenko** [comment]
You can pass props directly to the picker

**Comment by mAAdhaTTah** [comment]
I did–I need to use `inputProps` so the testid ends up on the input. This is a prop supported by the TextField component: https://material-ui.com/api/text-field/#props
