### ISSUE TITLE
Import error: 'makeStyles' is not exported from '@material-ui/core' (imported as 'makeStyles$1')

### ISSUE THREAD

**Issue by meghna-saxena** [mui-org/material-ui-pickers#1190]
I did the following steps in my project repo:
-  `npm i @material-ui/pickers`

And expected the library to be installed successfully without breaking my build. But I'm getting the following error on terminal. 

<img width="866" alt="Screenshot 2019-07-18 at 15 06 49" src="https://user-images.githubusercontent.com/18181755/61460403-f8f7d900-a96e-11e9-96e3-9455c4668ad0.png">

I tried to stop my docker container, and build it again, but it complains of the following issue `./node_modules/@material-ui/pickers/dist/material-ui-pickers.esm.js  | Attempted import error: 'makeStyles' is not exported from '@material-ui/core' (imported as 'makeStyles$1').`

**Comment by dmtrKovalenko** [comment]
Make sure that it's required to use @mateiral-ui/core v4

**Comment by ruthwe** [comment]
same issue
