### ISSUE TITLE
Height of transitionContainer not set dynamically?

### ISSUE THREAD

**Issue by katy6514** [mui-org/material-ui-pickers#1192]
![dont-touch-my-garbage-when-a-coworker-wants-to-do-36085809](https://user-images.githubusercontent.com/5386309/61498415-ffd71980-a977-11e9-99dc-778fa640af85.png)

I've been looking for a while for a solution to this but I'm not sure if it's been encountered yet. Looking at all the examples of the Mui DatePickers online (and even one that I use in one part of the app I'm working on) the transitionContainer is set high enough that all weeks are visible. 

However, a Mui DatePicker used elsewhere in the app (built originally by someone else no longer at the company) works wonderfully except for when the dates of the month span 6 weeks. The sixth week is always hidden. I have a suspicion that it's being hard coded somewhere in the app but it's got to be someplace I haven't looked yet.

**what this currently looks like:**
july looks great
![goodJuly](https://user-images.githubusercontent.com/5386309/61498618-d4a0fa00-a978-11e9-9267-95fb932ef88a.png)
june's last month is hidden
![badJune](https://user-images.githubusercontent.com/5386309/61498627-d965ae00-a978-11e9-9c58-d7ace2b352ab.png)

I've tried all the combinations of CSS settings that I can think of to try to dynamically set the height of the transitionContainer to be big enough vertically to show all weeks but so far have had no luck. Currently my solution is to use CSS overrides to hardcode the height big enough to display all weeks regardless of number of weeks needed to display. The problem is this leaves a big blank row of white at the bottom of the calendar that my design team isn't going to like.

**what my hardcoded solution looks like:**
june looks great
![goodJune](https://user-images.githubusercontent.com/5386309/61498639-eda9ab00-a978-11e9-9ddd-6590ec90ccb3.png)
july has so much white space
![badJuly](https://user-images.githubusercontent.com/5386309/61498643-f13d3200-a978-11e9-8579-1009be2ff29f.png)

**A solution I'm hoping for is:**
all weeks visible
![goodJune](https://user-images.githubusercontent.com/5386309/61498679-129e1e00-a979-11e9-88bf-b1655b779ea5.png)
no extra white space
![goodJuly](https://user-images.githubusercontent.com/5386309/61498684-15990e80-a979-11e9-91d3-e32688e91ac7.png)

Versions:
    "react": "16.4.1",
    "@material-ui/core": "^3.9.2",
    "material-ui-pickers": "^2.2.0",

any suggestions greatly appreciated!

**Comment by dmtrKovalenko** [comment]
It can be done only in overrides section of mui theme. Originally we always showing the white space for 6th week

**Comment by katy6514** [comment]
i've tried all the combinations of override rules that I can think of to set this height dynamically, haven't been able to find a solution yet, I'm grateful for any suggestions.

**Comment by katy6514** [comment]
I've tried all combinations of CSS overrides in the mui theme that was created and can't find a solution. Also, if the height of the transition container is being overridden somewhere already to show only 5 weeks, I cannot find where.

This is the entirety of the existing MUI theme that was in place when I got to it, excluding my transitionContainr override attempts:

`const materialTheme = createMuiTheme({
  overrides: {
    MuiPickersCalendarHeader: {
      daysHeader: {
        display: 'flex',
        justifyContent: 'space-around',
        padding: 3,
      },
    },
    MuiPickersCalendar: {
      week: {
        display: 'flex',
        justifyContent: 'space-around',
        padding: 3,
      },
    },
  },
})
`
I don't think anything in there is setting the height to only allow 5 weeks to be displayed. Where else might I look to change the setting? Thanks for any suggestions.

**Comment by katy6514** [comment]
I found a solution involving jss-nested syntax in my muiTheme! Had to target the first child div in the transition container for the MuiPickersSlideTransition like so: ` '&& > div': {...styles...},`

**Comment by alexdao3** [comment]
@katy6514 I came across this same issue. If I'm understanding you correctly, are you flipping the `div`'s position from `absolute` to `static`? When I attempt this, the transitionContainer grows to roughly 2x the size on month change, due to the static positioning of the 2 divs storing the 2 months. How did you address that?
