### ISSUE TITLE
Landscape time picker: Time not centered in 24h mode

### ISSUE THREAD

**Issue by rbuetzer** [mui-org/material-ui-pickers#1197]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.1.2 |
| material-ui          | 4.0.2 |
| React                | 16.8.6 |
| Browser              | Chrome mobile |
| Peer library         |  moment.js 22.2.2 |

## Steps to reproduce

1. Go to https://material-ui-pickers.dev/demo/timepicker
2. Simulate a device viewport ([Firefox](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode#Using_Responsive_Design_Mode), [Chrome](https://developers.google.com/web/tools/chrome-devtools/device-mode/#viewport))
3. Select a small viewport with orientation _landscape_
4. Click on the first example ("Basic Example")

## Expected behavior

The time is displayed vertically centered

## Actual behavior

The time is displayed at the bottom

![timepicker-24h-issue](https://user-images.githubusercontent.com/2462187/61693336-b26bfb00-ad2f-11e9-87d6-67c7151e5f9b.png)

## Live example

See *steps to reproduce*

**Comment by dmtrKovalenko** [comment]
Ohh god I missed this issue. Sorry 😐
