### ISSUE TITLE
pickers doesn't work with @material-ui/styles/stylesProvider

### ISSUE THREAD

**Issue by yairzahavi** [mui-org/material-ui-pickers#1198]
hi there,
i'm using @material-ui/pickers and @material-ui/core and trying to support rtl for my application but it doesn't seem to work.
whenever i wrap my app with stylesProvider the rtl is fixed but when i try to open any material-ui/pickers component the app crashes.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.1.1     |
| material-ui          |     4.1.3    |
| React                |      16.8.6   |
| Browser              |     chrome  70.0.3538.67    |
| Peer library         |        date-io/moment 1.1.0  |
| moment             |        2.24.0  |

## Expected behavior
    rtl without crashing

## Actual behavior
    crashing

## Live example
https://codesandbox.io/embed/material-ui-pickers-usage-demo-prpj9

**Comment by dmtrKovalenko** [comment]
And they will not work. Our package doesn't know anything about `@material-ui/styles`. So it cannot use context consumer from there

**Comment by yairzahavi** [comment]
the problem was with on of the npm packages version.
i had jss version 9.8.7.
if you have that problem use jss version 10.0.0-alpha.12
