### ISSUE TITLE
DatePicker onChange event is fired twice!

### ISSUE THREAD

**Issue by mtermoul** [mui-org/material-ui-pickers#1202]
Hello, 
I am having an issue with DatePicker component. The onChange event is fired twice, causing the setState to be called twice. I was trying to find a way to use event.preventDefault to fix it, however the onChange event only expose one parameter which the date.
Is there a way to prevent this?

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |^3.2.0|
| material-ui          |^4.2.0|
| React                |^16.8.6|
| Browser              |Crome 75|
| Peer library         |momentjs ^2.24.0

## Steps to reproduce

1- Click on the date picker input field
2- The inline calendar will popup
3- Click on a day
4- The date field will be updated
5- The onChange event will be fired twice

## Expected behavior
I am expecting the the onChange event to fire one time only.

## Actual behavior
The onChange event is fired twice

## Live example

https://codesandbox.io/s/material-ui-pickers-usage-demo-woym3

See in the console that the onChange event fire twice!

```
import React, { useState } from "react";
import MomentUtils from "@date-io/moment";
import moment from "moment";
import { DatePicker, MuiPickersUtilsProvider } from "@material-ui/pickers";

function App() {
  const [selectedDate, setDate] = useState(moment());

  const onDateChange = val => {
    console.log("--- date changed: ", val.toString());
    setDate(val);
  };
  return (
    <MuiPickersUtilsProvider utils={MomentUtils}>
      <DatePicker
        disableToolbar
        autoOk
        variant="inline"
        label="Select new date"
        format="MM/DD/YYYY"
        value={selectedDate}
        onChange={onDateChange}
      />
    </MuiPickersUtilsProvider>
  );
}

export default App;
```

**Comment by dmtrKovalenko** [comment]
Haha it's because of `autoOk`. It is included automatically in case of `variant="inline"`
So missing return somewhere -- will fix it
https://codesandbox.io/s/material-ui-pickers-usage-demo-woym3
