### ISSUE TITLE
Changing formats triggers some strange behaviours  

### ISSUE THREAD

**Issue by felipepastor** [mui-org/material-ui-pickers#1203]
Hi everyone,

I'm opening this ticket just to understand a bit about the pickers, I'm using the keyboard date component and I'm trying to change the format of the date when the user change the country. But when this happen the component cannot understand the new format and reject the new date and change it back to the old format.

I already took a look in how the moment object and even with the new format it's not updating this object. I tried to do it by hand but without success. I created an example to make it more clear. 

https://codesandbox.io/s/eloquent-glitter-b9419

Thanks!

**Comment by dmtrKovalenko** [comment]
Hmm, looks like lack of react hook dependency somewhere. I'll take a look

**Comment by felipepastor** [comment]
Thank you very much, Dimitri. Let me know if I can help in any way.

**Comment by felipepastor** [comment]
@dmtrKovalenko Hey, any thoughts on this or anything that I can take a look?

**Comment by felipepastor** [comment]
One more thing that I noticed and I would like your thought, when I have an invalid date and change the mask, it's doesn't change then when I type valid date it changes to the new format. Is it the correct behaviour for this case?

Thanks!

**Comment by felipepastor** [comment]
@dmtrKovalenko
