### ISSUE TITLE
Allow to override header component

### ISSUE THREAD

**Issue by yevheniiminin** [mui-org/material-ui-pickers#1215]
**Is your feature request related to a problem? Please describe.**
Can we have a feature to override the component for calendar header?
I need to create a complex layout where a popup with month/year picker appears if you click on header  (see screenshot)
![image](https://user-images.githubusercontent.com/15870873/62157218-f43b0980-b30c-11e9-8a51-8ffec7155c08.png)

**Describe the solution you'd like**
Allow to override header component, something like
`<DatePicker HeaderComponent={MyHeaderComponent} .../>`

**Describe alternatives you've considered**
Tried to put in an absolute positioned div on top of the header to capture click on it but that didn't work out quite well because the calendar can move/resize when screen size is changed.

P.S. awesome library, keep up the great work ;)

**Comment by dmtrKovalenko** [comment]
`ToolbarComponent` is what you are looking for

**Comment by dmtrKovalenko** [comment]
Add this to docs in the commit https://github.com/mui-org/material-ui-pickers/pull/1206/commits/0b942583f40dc9b17c99fa0f7a9b66696d1abe21
