### ISSUE TITLE
Add excludeDates property

### ISSUE THREAD

**Issue by benmccann** [mui-org/material-ui-pickers#1226]
**If you don't mind add a fun gif or meme, but no pressure**
![A GIF or MEME to give some spice of the internet](http://www.quickmeme.com/img/dc/dc42e7dd31c3a31a038b8854fc375fb7ec07034501e2470448b35fd9921a5da9.jpg)

**Is your feature request related to a problem? Please describe.**
We would like customers to select the date for their electric utility service to start. However, there are certain days that our providers will not be able to accommodate and so we'd like to disable those dates as selectable options.

**Describe the solution you'd like**
I would like a new property such as `excludeDates` which would accept an array of dates. The dates in the given array would be grayed out on the calendar such that they're not selectable.

**Describe alternatives you've considered**
This is a feature offered by the alternative library `react-date-picker`: https://reactdatepicker.com/#example-20

**Additional context**
You can see [this feature implemented on our site currently](https://getgex.com/customers/new/account/details) with `react-date-picker` by clicking "Choose Service Date"

**Comment by dmtrKovalenko** [comment]
Actually that is possible right now with function `shouldDisableDate`. I always thought that function is more flexible way to accomplish that.

**Comment by benmccann** [comment]
Oh, perfect! Thanks. Yes, that's all I need

The docs for `shouldDisableDate` are slightly confusing though. It says the type is `(day: any) => boolean`. How can I know how to handle `day` without knowing what type it is? I'd expect it to be a `Date` or maybe a `number` representing millis since epoch or something

**Comment by dmtrKovalenko** [comment]
That’s a luck of our docs. There passing the date l moment l luxon l dayjs. But we cannot infer it as a type. I’ll try to figure that out.

**Comment by dmtrKovalenko** [comment]
Fixed on the docs

**Comment by benmccann** [comment]
Thanks! That's helpful!
