### ISSUE TITLE
Adding a div below.

### ISSUE THREAD

**Issue by supritsethi** [mui-org/material-ui-pickers#1230]
![image](https://user-images.githubusercontent.com/49560168/62460139-cf2c1800-b79e-11e9-9983-1f7ea4ab356b.png)

I want to add some css to particular dates and show the details of the respective classes below such as cheaper and expensive as shown in the above image,

Maybe we can add a prop that takes a component as calendar footer and display the footer accordingly.
Or we can find out if the same data can be places at some other place in the component.

We need to highlight the dates on which the rate are cheap or expensive and also let the user know what color means what.

**Comment by dmtrKovalenko** [comment]
You can only use our `Calendar` component and build everything you wish outside of it.
