### ISSUE TITLE
Using tab if i focus on input the calendar should open or on the press of enter.

### ISSUE THREAD

**Issue by supritsethi** [mui-org/material-ui-pickers#1231]
I'm using the input in a form and it'd be great to be able to tab through the fields and auto open the pickers or atleast when i hit enter key. 
I attempted to set open property on focus and on close i use to set open as false but it seems that the on focus event triggered again.
An onFocus prop for the pickers that only is called when the input is first entered OR when the user focused using tab and hit enter the picker should appear.

Apologies if I missed an existing setting.

**Comment by TrySound** [comment]
Enter usually is used to submit form. Mixing behaviours will be confusing.
