### ISSUE TITLE
Documentation website is broken

### ISSUE THREAD

**Issue by amirmohsen** [mui-org/material-ui-pickers#1233]
Your website is down.
https://material-ui-pickers.dev/
I am getting a connection refused error.

**Comment by dmtrKovalenko** [comment]
I don’t think so. Possibly your company vpn or firewall blocking .dev domain

**Comment by pixelwhip** [comment]
I'm also unable to reach the .dev domain from my laptop without logging into a VPN. I can reach it from my phone without a VPN on the same wifi connection as my laptop. I recently upgraded MacOS to Mojave which may be related but my Firewall is disabled.

**Comment by amirmohsen** [comment]
I figured out what it was. A few years ago, I setup my computer with its own DNS proxy that routed all `.dev` and `.local` traffic to `127.0.0.1`. Since `.dev` was only recently made available to the public, this was the first time I had come across a website actually using it. Anyway, I've fixed my problem by editing my proxy settings.

**Comment by pixelwhip** [comment]
My issue was an old dev domain resolver pointing to an old IP. Just had to delete `/etc/resolver/dev`

Sorry for the false alarm.
