### ISSUE TITLE
material-ui imports treeshakeable

### ISSUE THREAD

**Issue by badbyte7** [mui-org/material-ui-pickers#1235]
![](https://media.giphy.com/media/l0NwNrl4BtDD7JCx2/giphy.gif)

There are some material-ui imports, which prevent webpack from tree shaking. So the whole material-ui is in the bundle, which leads to a bigger bundle size, and a longer compile time.

One example is:
`src/_shared/KeyboardDateInput.tsx:5:import { IconButton } from '@material-ui/core'`

Is it possible to change the imports?

**Comment by dmtrKovalenko** [comment]
Which version do you use? It should not be an issue with 3.2.

**Comment by badbyte7** [comment]
I was using 3.1.3, but I tried it now with 3.2.2 with the same result.
The code snippet of my ticket is from the current [file](https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/_shared/KeyboardDateInput.tsx)

**Comment by bjartebore** [comment]
This issue also affects style imports for material-ui [#15610](https://github.com/mui-org/material-ui/issues/15610)
