### ISSUE TITLE
Not showing "Invalid Date Format" when the value is empty

### ISSUE THREAD

**Issue by serg-kan** [mui-org/material-ui-pickers#1237]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   ^3.1.2      |
| material-ui          |     ^4.0.1    |
| React                |     ^16.8.6    |
| Browser              |     Chrome 69    |
| Peer library         |   moment: "^2.24.0"      |  |

## Steps to reproduce

When default value is an empty string, shows "Invalid Date Format"

## Expected behavior
Not showing an error.

I saw https://github.com/mui-org/material-ui-pickers/pull/199 solution, but it doesn't work for me. I want the default value to be an empty string, because the pickers are part of filters.

![image](https://user-images.githubusercontent.com/52253662/62626317-c6b71700-b92f-11e9-90f7-c6524c03b0c8.png)

**Comment by dmtrKovalenko** [comment]
Consider using null. Because empty string is really flaky thing in JavaScript. We will not add any special cases for that.

**Comment by serg-kan** [comment]
@dmtrKovalenko 
Null also doesn't work for me.
I set date: null in the state, but picker displays today's date with "Invalid Date Format" message.

**Comment by rodrigo-rrp** [comment]
Any luck with this?
