### ISSUE TITLE
KeyboardDatePicker renders incorrect date

### ISSUE THREAD

**Issue by lifeiscontent** [mui-org/material-ui-pickers#1238]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |         |
| material-ui          |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. 2. 3.

## Expected behavior

date value is parsed as ISO 8601

## Actual behavior

date value is parsed as something else

## Live example

https://codesandbox.io/s/blue-pond-1qll6

**Comment by dmtrKovalenko** [comment]
We are using date-fns as provider to create a date. So please follow their docs. 
Actually just pass new Date object
