### ISSUE TITLE
Typo on https://www.patreon.com/dmtrKovalenko

### ISSUE THREAD

**Issue by benmccann** [mui-org/material-ui-pickers#1241]
It says "baker" and "bakers list", but I'm assuming "backers" was meant

![bakers](http://www.quickmeme.com/img/f0/f067ba70b131aaf1d07aef0ba5586ad4caecebc5ba9d6f289dcc9c2bd28e5a6d.jpg)

**Comment by dmtrKovalenko** [comment]
>D Ohh those typos

**Comment by dmtrKovalenko** [comment]
Fixed

**Comment by benmccann** [comment]
Just FYI, it still says "bakers" under "Unicorns"
