### ISSUE TITLE
Datepicker allows you to enter lyrics you should not allow in case it is formatted to "YYYY-DD-MM", or some other type of format as before

### ISSUE THREAD

**Issue by CarlosOrozc** [mui-org/material-ui-pickers#1242]
<img width="1145" alt="Screen Shot 2019-08-08 at 3 15 13 PM" src="https://user-images.githubusercontent.com/8071575/62738544-cbdb9b00-b9ef-11e9-8543-af8c83c7453b.png">

**Comment by oliviertassinari** [comment]
@CarlosOrozc Why not? Take https://uxsolutions.github.io/bootstrap-datepicker/ as an example, you can write anything you want.

**Comment by CarlosOrozc** [comment]
http://pushtell.github.io/react-bootstrap-date-picker/

**Comment by oliviertassinari** [comment]
And yet, the *uxsolutions* version has ~x10 more users.

**Comment by CarlosOrozc** [comment]
several but none meets the needs

I have not currently found one that meets all my needs
:(

**Comment by dmtrKovalenko** [comment]
Actually it should not be allowed. Please procide the steps to reproduce

**Comment by CarlosOrozc** [comment]
https://material-ui-pickers.dev/demo/datepicker
In the "Inline mode #" section
