### ISSUE TITLE
You guys deleted Deleted "material-ui-pickers": "^2.2.4" it's breaking production app please restore so we can migrate

### ISSUE THREAD

**Issue by ebredy** [mui-org/material-ui-pickers#1244]
Date picker from "material-ui-pickers": "^2.2.4" was being used and the tag has been deleted from GitHub and as an outcome, our application's date-UI picker is broken.  Why did you delete the tag?  What is the process by which you delete tags and etc? Is there a way to restore this tag?
This is preventing our application form properly building.

| Tech        | Version |
| ----------- | ------- |
| Material-UI | v2.2.4  |
| React       |         |
| Browser     |         |
| TypeScript  |         |
| etc.        |         |

**Comment by dmtrKovalenko** [comment]
Here is a tag https://github.com/mui-org/material-ui-pickers/tree/v2.2.4

**Comment by ebredy** [comment]
@dmtrKovalenko actually it's from the npm not github it has been removed: https://www.npmjs.com/package/@material-ui/pickers

**Comment by dmtrKovalenko** [comment]
No, it is still hosted and avaialable as [material-ui-pickers](https://www.npmjs.com/package/material-ui-pickers)

**Comment by ebredy** [comment]
@dmtrKovalenko  the issue is that the 2.2.4 tag is not there and we are calling the package via the tag name in npm: https://www.npmjs.com/package/material-ui-pickers. Check out the history and the tag is no longer there.
