### ISSUE TITLE
2.2.4 doesn't exists in npm package https://www.npmjs.com/package/material-ui-pickers

### ISSUE THREAD

**Issue by ebredy** [mui-org/material-ui-pickers#1245]
we are currently pulling in the branch by tag name yet the tag 2.2.4 is missing from this npm package: https://www.npmjs.com/package/material-ui-pickers.  Please fix if possible.  This is breaking our production app

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/cocky-greider-38fmi 
Check it out. Everything works with **material-ui-pickers** v2.2.4. **NOT** @material-ui/pickers

**Comment by ebredy** [comment]
@dmtrKovalenko  there is no tag it can't be pulled in.  you closed this too quickly....it's the fact that it's working, it's the fact that it can't be pulled in in the first place.
