### ISSUE TITLE
tag 2.2.4 is no longer in npm package https://www.npmjs.com/package/material-ui-pickers

### ISSUE THREAD

**Issue by ebredy** [mui-org/material-ui-pickers#1246]
1) the branch 2.2.4 works perfectly.
2) the issue is that we can't pull in the branch by tag 2.2.4 because it's no longer in the npm package: https://www.npmjs.com/package/material-ui-pickers.  Please look at the history as there is no tag 2.2.4.

**Comment by dmtrKovalenko** [comment]
There is. :D I don’t know how to explain you. Tick the show deprecated versions
