### ISSUE TITLE
`onChange` Event is not fired in variant "dialog"

### ISSUE THREAD

**Issue by lukas-alliado** [mui-org/material-ui-pickers#1247]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.2     |
| material-ui          |    4.1.1     |
| React                |    16.8.6     |
| Browser              |     Chrome 75    |
| Peer library         |         moment v2.24.0  |

## Steps to reproduce

1. Add DatePicker in dialog variant
2. Open DatePicker modal and click any date
3. `onChange` event should fire on each date change by click but does not

## Expected behavior
II would expect the `onChange` event to fire on each date clicked as in the other variants and the `onAccepted` only once the *Ok* button is clicked

## Actual behavior

n `inline` and `static` variants the `onChange` event is fired whenever a date is clicked in in the date picker.
In `dialog` variant (withou `autoOk`) the `onChange` event is only fired once you click *Ok*. Then it is fired but at the same time the `onAccepted` event is fired as well.

This behaviour change with *v3.1.1* as on *v3.1.0* the event was fired as expected

## Live example
Check this example with *v3.1.0* where the behaviour is correct. Change to any higher version and the `onChange` is not fired correctly any more.

https://codesandbox.io/s/material-ui-pickers-usage-demo-ljwzd

**Comment by lukas-alliado** [comment]
https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/_shared/hooks/usePickerState.ts#L84

This line makes sure the `onChange` event is never fired until the date is accepted.
Is this on purpose?

The customization example relies exactly on the behaviour prior v3.1.1
https://material-ui-pickers.dev/demo/datepicker#customization

With what version are the examples deployed? 
I cannot make it work with any version higher than 3.1.0

**Comment by dmtrKovalenko** [comment]
Yeah, we started exposing `onChange` for each date click, but it causes a lot more problems. So `onChange` right now works exactly as `onAccept`. Why do you need to have `onChange` fired for each date change
