### ISSUE TITLE
time picker

### ISSUE THREAD

**Issue by brandonpc** [mui-org/material-ui-pickers#1249]
## Environment

| Tech                 | Version 3.2.2 |
| -------------------- | ------- |
| @material-ui/pickers |         |
| material-ui          |         |
| React                |         |
| Browser              |   all      |
| Peer library         |    all     |  |

## Steps to reproduce

1. go to https://material-ui-pickers.dev/demo/timepicker || https://material-ui-pickers.dev/demo/datetime-picker || use time picker with the icon in any way.
 

## Expected behavior

a clock icon, not a calendar.

## Actual behavior

a calendar icon, with no (obvious) way to fix it while using it

## Live example

Can't get more live than the actual documentation!

**Comment by dmtrKovalenko** [comment]
You can change it with `keyboardIcon` prop

**Comment by dmtrKovalenko** [comment]
Like in [this](https://material-ui-pickers.dev/demo/datetime-picker#customization) example
![image](https://user-images.githubusercontent.com/16926049/62847861-469f0180-bce1-11e9-97fe-7c9b42e0c9f0.png)
