### ISSUE TITLE
KeyboardDateTimePicker focus and Inline Picker Open

### ISSUE THREAD

**Issue by hernanif1** [mui-org/material-ui-pickers#1250]
Is it possible to keep the menu inline open and the input typing feature at the same time?
When the menu inline it's open is not possible to type the datetime so the user needs to close it to type and if it's close, the user needs to click at the icon to open it.
Some dates and times are easier to type and others to pick, but only the user can decide this.

This feature would be a great UX improvement for the user.

**Comment by dmtrKovalenko** [comment]
I think it is not possible. Right now to render material-ui popup is using hidden overlay. So any interactions outside the popover is not possible 
![image](https://user-images.githubusercontent.com/16926049/63209229-cc0e2180-c0e6-11e9-9235-632fdb2755ba.png)
