### ISSUE TITLE
TypeScript error 'Property 'hiddenLabel' missing' in KeyboardDatePicker

### ISSUE THREAD

**Issue by sofiset** [mui-org/material-ui-pickers#1251]
![typescript](https://user-images.githubusercontent.com/16353702/62877268-a81c9b80-bcf4-11e9-99f2-d94dc0fb13f6.jpeg)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   ^3.2.2    |
| material-ui          |   ^4.2.1      |
| React                |    ^16.8.6     |
| Browser              |     Version 76.0.3809.100    |
| Peer library         |      date-fns ^2.0.0-beta.4   |  |

## Steps to reproduce

1. Including `hiddenLabel` prop

```    <KeyboardDatePicker
      margin="normal"
      id="mui-pickers-date"
      label={label}
      value={selectedDate}
      onChange={onDateChange}
      KeyboardButtonProps={{
        'aria-label': 'change date'
      }}
      hiddenLabel="change date"
    />
```

leads to React console warning:

```
Warning: React does not recognize the `hiddenLabel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `hiddenlabel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

2. Removing `hiddenLabel` prop leads to TypeScript compilation error:

```
TypeScript error in /Users/sophie.fiset/magnet-fe/magnet-dashboard/src/components/shared/DatePicker.tsx(14,6):
Property 'hiddenLabel' is missing in type '{ margin: "normal"; id: string; label: string | undefined; value: Date | null; onChange: (date: Date | null) => void; KeyboardButtonProps: { 'aria-label': string; }; }' but required in type 'Pick<KeyboardDateInputProps, "label" | "children" | "ref" | "select" | "style" | "title" | "mask" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | ... 273 more ... | "rifmFormatter">'.  TS2741
```

## Expected behavior

If passing the prop `hiddenLabel` that is expected by TS, there should be no React warning. If omitting the prop, app should still compile.

## Actual behavior

I can't include or exclude :( Seems like a "me" problem with my version of Typescript perhaps?

**Comment by dmtrKovalenko** [comment]
I am not seeing `hiddenLabel` in allowed text-field [props](https://material-ui.com/api/text-field/#textfield-api)

**Comment by alex-scown-checkit** [comment]
Having the same issue. Looks like `hiddenLabel` was introduced in Material UI 4.3.0 (if I upgrade Material UI, the warning goes away). `hiddenLabel` is in the Props of `FormControl`: https://material-ui.com/api/form-control/#props

**Comment by AdamBeddoe** [comment]
Upgrading @material-ui/core fixed this for me too

**Comment by dmtrKovalenko** [comment]
So closing this issue

**Comment by sofiset** [comment]
Awesome - thanks a lot @dmtrKovalenko @alex-scown-checkit @AdamBeddoe!

**Comment by Pablohack** [comment]
> Upgrading @material-ui/core fixed this for me too

it is necessary to update material-ui / pickers
