### ISSUE TITLE
Mask Function

### ISSUE THREAD

**Issue by Felix-N** [mui-org/material-ui-pickers#1254]
Hi,

I'm just updating to version 3 from 2 and have some trouble with the keyboard masks.

On v2 i passed in a function, which generated the mask dependent on the user input, autocompleting date parts.

However it seems that on v3 only a string is allowed. Any chance to keep using a function instead, to continue generating a dynamic mask?

**Comment by dmtrKovalenko** [comment]
You can use `rifmFormatter` property. This is a function used to generate input values. It is much more flexible than old masks. More info here https://github.com/istarkov/rifm

**Comment by Felix-N** [comment]
thanks for pointing me into that direction.

however without access to the replace and ideally mask I do not understand how to replicate the functionality
