### ISSUE TITLE
Two issues: onChange event is getting fired after onClose event and is getting triggered on each year change

### ISSUE THREAD

**Issue by rsverma91** [mui-org/material-ui-pickers#1260]
1. onChange event is getting fired after onClose event. (onClose is just to handle what will happen after close, why onChange event is there after this).
2. On each year or date change onChange event is getting triggered, how am i suppose to fetch data on onChange event (or on final date selection, i am not getting any date on onClose also), it will trigger each time when i will change year or date. so on final date change it will trigger twice and there is no other way i can stop it.

Previously this issue was not there in "material-ui-pickers", now everything is messed up after upgrade to "@material-ui/pickers".

**Comment by dmtrKovalenko** [comment]
Which `variant` you are using?

**Comment by rsverma91** [comment]
inline variant

**Comment by dmtrKovalenko** [comment]
inline is using `autoOk` by default. So anytime you are closing dialog you are actually submitting a date. If you want to make a request you can use `onClose` and query with your date in state

```javascript
const [date, setDate] = useState(null)

const makeApiCall = () => {
   console.log(date) // use saved date
}

<DatePicker
  value={date}
  onChange={setDate}
  onClose={makeApiCall}
/>
```

**Comment by rsverma91** [comment]
autoOk is not false by default, so if i will select any date it will no close the picker.
please check this https://material-ui-pickers.dev/demo/datepicker 
check for inline picker.
if i will set autoOk to true it will close.

and please console the  date and check , it is giving previous date.
please try to run that code.

**Comment by rsverma91** [comment]
please check this example, i have not added autoOk, and it is not closing the picket on date select, and if you will add autoOk then it will close
select any date it will show the previous date.

https://codesandbox.io/s/material-demo-ffesp

**Comment by rsverma91** [comment]
Thanks for fixing the 1st issue but 2nd issue is still there after fixing 1st issue.
or will you please tell me how will i handle the above scenario.
https://codesandbox.io/s/material-demo-ffesp.
I tried your changes in my local node_module  and 1st issue got fixed but still I am getting the previous value.
If you will suggest I will open an another thread since this thread is already closed

**Comment by rsverma91** [comment]
I dig in the node_module and I added isFinish in the code with one condition which was already there.
I modified onChange function
`if (!autoOk && (variant === 'inline' || variant === 'static')) {
    _onChange(newDate);
    onAccept && onAccept(newDate);
}`

I understand the usecase of inline and static picker (it will show all the updates onChange) but for autoOk case I think you can add this and it will serve the purpose.

Please think about this
