### ISSUE TITLE
on setting open={isDateOpen}, Inline datepicker does not open on click 

### ISSUE THREAD

**Issue by rsverma91** [mui-org/material-ui-pickers#1262]
I tried setting open props for Inline DatePicker, it is working fine on on state change, but when i am trying to click on the DatePicker box it is not opening. I think It is hard bounded to the open props.
will you please look into this.

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.dev/guides/controlling-programmatically

Please read documentation first

**Comment by rsverma91** [comment]
yes I checked the docs. but for fixing this I need to set onOpen event on date picker. i already bound onChange onClose now i need to add onOpen also Why?

**Comment by dmtrKovalenko** [comment]
Because you have choosen manual control of the open/close state

**Comment by rsverma91** [comment]
Ok no issue
