### ISSUE TITLE
Dialog pickers do not respect material-ui theme (atleast typogaphy.fontSIze)

### ISSUE THREAD

**Issue by NoHomey** [mui-org/material-ui-pickers#1269]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.2.2    |
| material-ui          |     4.3.2    |
| React                |     16.9.0    |
| Browser              |   Google  Chrome     |
| Peer library         |   dayjs@1.8.15 |

## Steps to reproduce

Increase `typography.fontSize` of material-ui's theme.

## Expected behavior

It should respect theme e.g. sizes should be some how related to theme (atleast fontSize)

## Actual behavior

The component looks buggy, some parts are partially displayed ( views and current month )  ...

![mui-date-picker](https://user-images.githubusercontent.com/8791438/63227438-41fdb000-c1ef-11e9-8cc2-4d0bcea533f5.png)

## Live example
https://codesandbox.io/embed/material-ui-pickers-usage-demo-ikmcx

**Comment by dmtrKovalenko** [comment]
I have no idea how to change the sizes depends on fontSize. You can try to increase theme.spacing. But it looks like you need to left the same style for material-ui-pickers.
