### ISSUE TITLE
KeyboardDatePicker opens on the wrong month when using dayjs and UTC

### ISSUE THREAD

**Issue by dominictobias** [mui-org/material-ui-pickers#1272]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |      3.2.2   |
| material-ui          |    4.3.2     |
| React                |    16.8.6     |
| Browser              |    Chrome     |
| Peer library         |   dayjs 1.8.15     |  |

## Steps to reproduce

https://codesandbox.io/s/vigilant-violet-hs851

## Expected behavior

Should open the calendar on the correct month. Should be able to change a date.

## Actual behavior

Opens calendar on month before date. Changing the date (clicking on one) just scrolls to another month.

## Live example

https://codesandbox.io/s/vigilant-violet-hs851

**Comment by dominictobias** [comment]
Same thing works in moment but didn't want to use such a bloated library:

```js
class UTCMomentUtils extends MomentJSUtils {
  format(value, formatString) {
    return moment(value)
      .utc()
      .format(formatString);
  }
}
```

Fortunately it works in luxon though:

```js
class UTCLuxonUtils extends LuxonJSUtils {
  format(value, formatString) {
    return DateTime.fromISO(value).toFormat(formatString)
  }
}
```

**Comment by dmtrKovalenko** [comment]
I belive you need to override all usages of dayjs. Like here https://codesandbox.io/s/material-ui-pickers-usage-demo-fex8q

**Comment by dominictobias** [comment]
Thanks that helps a lot. However those pickers work but KeyboardPicker is wrong: https://codesandbox.io/s/material-ui-pickers-usage-demo-461q7

It opens on September 29 instead of Oct 1st like the others:

```js
<KeyboardDatePicker
        disableToolbar
        variant="inline"
        format="YYYY-MM-DD"
        value={selectedDate}
        onChange={handleDateChange}
        KeyboardButtonProps={{
          "aria-label": "change date"
        }}
      />
```

P.S. Same thing happened using `moment` too
P.S.S Your demo also has the same issue

**Comment by dominictobias** [comment]
Actually DatePicker doesn't work either, note it's on the wrong month:

![wrong-month](https://user-images.githubusercontent.com/760314/65950322-bd30c380-e435-11e9-88b4-830f54ab7c83.png)

**Comment by dominictobias** [comment]
I think this should be re-opened as the calendar has a bug where it doesn't open on the right month even on your demo?
