### ISSUE TITLE
Timepicker's value automatically becomes the current time on initial load and after component loses focus.

### ISSUE THREAD

**Issue by snsheth55** [mui-org/material-ui-pickers#1275]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.2.3    |
| material-ui          |   0.20.2      |
| React                |     16.9.0    |
| Browser              |    Chrome     |
| Peer library         |  moment: 2.24.0  ,     @date-io/momen: 1.3.9,  redux-form: 8.2.3    |  |

## Steps to reproduce

This is how I am calling Timepicker

```
MuiPickersUtilsProvider utils={MomentUtils}>
                              <Field name='login_constrained_by_end_time' type='time' label="End Time" component={renderMUITimePicker} className={classes.datepicker} disabled={this.state.disabled} />
                          </MuiPickersUtilsProvider>
```

This is my component that syncs timepicker with redux form

```
const renderMUITimePicker = ({
  label,
  input,
  meta: { touched, invalid, error },
  ...custom
}) => {
  console.log("Timepick", label, input, custom)
  return (
  <TimePicker
    clearable
    ampm={false}
    label={label}
    value={null}
    placeholder={label}
    error={touched && invalid}
    helperText={touched && error}
    {...input}
    {...custom}
  />
)}
```

These are my props,

input 

```
name: "login_constrained_by_end_time"
onBlur: ƒ (event)
onChange: ƒ (event)
onDragStart: ƒ (event)
onDrop: ƒ (event)
onFocus: ƒ (event)
value: "21:45"
```

custom 

```
className: "EditUser-datepicker-279"
disabled: false
type: "time"
```

## Expected behavior

I expect the the initial data to be presented in the timepicker and the updated time to be represented in the timepicker

## Actual behavior

The timepicker always defaults to the the current time during the initial load and during the updates, the updated value is put in the pay load but my form value becomes this:

```
login_constrained_by_end_time: Moment
_d: Wed Aug 21 2019 09:45:49 GMT-0400 (Eastern Daylight Time) {}
_isAMomentObject: true
_isUTC: false
_isValid: true
_locale: Locale {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", ordinal: ƒ, _dayOfMonthOrdinalParse: /\d{1,2}(th|st|nd|rd)/, …}
_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -2, charsLeftOver: 0, …}
__proto__: Object
```

then after the timepicker loses focus it becomes the current time

`login_constrained_by_end_time: "13:34"`

**Comment by dmtrKovalenko** [comment]
Provide a live example
