### ISSUE TITLE
[TypeScript] 'KeyboardDateInput' refers to a value, but is being used as a type here.

### ISSUE THREAD

**Issue by damir-sirola** [mui-org/material-ui-pickers#1276]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.3        |
| material-ui          | 4.3.3        |
| React                | 16.9.0        |
| Browser              | N/A        |
| Peer library         | moment 2.24.0        |  |
| TypeScript          | 3.5.3                       |
## Steps to reproduce

1. Import `KeyboardDatePicker`
2. Use it in a component

## Expected behavior

No compilation errors

## Actual behavior

TypeScript compilation error
Error message:
```
node_modules/@material-ui/pickers/Picker/makePickerWithState.d.ts:13:12 - error TS2749: 'KeyboardDateInput' refers to a value, but is being used as a type here.
       Input: KeyboardDateInput | PureDateInputProps;
```

## Live example

I have created a repo where you can see the issue here [https://github.com/damir-sirola/ts-compilation-error-repro](https://github.com/damir-sirola/ts-compilation-error-repro)

**Comment by kpala** [comment]
Same issue here. Downgrading @material-ui/pickers to 3.2.2 seems to work for now.

**Comment by maelle-le-bon** [comment]
My guess is that in the file 'Picker/makePickerWithState.tsx' the interface should be:
```typescript
export interface MakePickerOptions<T extends any> {
    Input: KeyboardDateInputProps | PureDateInputProps;
    // ...
}
```

**Comment by mnemanja** [comment]
Actually I think it should be like this a `typeof KeyboardDateInputProps`

```ts
export interface MakePickerOptions<T extends any> {
    Input: typeof KeyboardDateInputProps | PureDateInputProps;
    // ...
}
```
