### ISSUE TITLE
cannot read property 'clone' of null

### ISSUE THREAD

**Issue by pooriamo** [mui-org/material-ui-pickers#1277]
Hi

Whenever I set `minDate` for the `Calendar` Component, I get this error. An example setting is like: `minDate={ moment().add(1, 'month') }`. My goal here is to display the calendar in the next month.

**Comment by damir-sirola** [comment]
If you don't want to set initial `value` to a date in next month, you can set `initialFocusedDate` prop
`initialFocusedDate={moment().add(1, 'month')}`

**Comment by pooriamo** [comment]
@damir-sirola I believe that `initialFocusedDate` is not a property of `Calendar` component. right?

**Comment by pooriamo** [comment]
I ended up using `DatePicker` component with `variant="static"`. It seems to be working now. At the time of writing that code, the variant property didn't exist.

**Comment by developdeez** [comment]
Same error. Variant causes error preventing it form showing. Is this fixed?

**Comment by developdeez** [comment]
Is there a way to set maxDate to null so it gets ignored. Then when I have enddate populated it can be set?
