### ISSUE TITLE
Required TypeScript version

### ISSUE THREAD

**Issue by eps1lon** [mui-org/material-ui-pickers#1282]
With #1252 `@material-ui/pickers` requires Typescript 3.5 to get type checking. The linked PR assumes the `Omit` helper type from `typescript` [which was only added in 3.5](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/#the-omit-helper-type).

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.4 |
| material-ui          |  master  |
| React                |  16.9.0 |
| Browser              |         |
| Peer library         |         |  |
| Typescript | 3.2.2 |

## Steps to reproduce

https://github.com/mui-org/material-ui/pull/17175

## Expected behavior

Library works with TypeScript 3.x

## Actual behavior

Requires 3.5

## Live example

N/A

#1273 is likely caused by the same issue.

**Comment by Flash619** [comment]
```javascript
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>
```

Could you add the above to the type definitions for this project and simply use that in place until more users adopt TypeScript 3.5?
