### ISSUE TITLE
Cannot set two digit hour in keyboard mode

### ISSUE THREAD

**Issue by JavierLight** [mui-org/material-ui-pickers#1286]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.0     |
| material-ui          |    4.2.1     |
| React                |    16.8.6     |
| Browser              |    Chrome     |
| Peer library         |    moment 2.24.0 |

## Steps to reproduce

Using moment to get long date format for all locales. Try specifically for `es` (Spain). Format for this locale is `DD/MM/YYYY H:mm`.

Try to set any two digit hour using the keyboard mode.

Using mask to override format does not look robust enough for me... I would like to be able to provide locale format to component, being able to insert two digit hours for all of them.

## Expected behavior

Setting 09:24 using keyboard mode should set 9:24.
Setting 11:24 using keyboard mode should set 11:24

## Actual behavior

Setting 09:24 using keyboard mode sets 9:24.
Setting 11:24 using keyboard mode sets 1:12

When picking 11:24 using the UI selector, it works fine.

## Live example

https://codesandbox.io/s/material-ui-pickers-usage-demo-0re4g

**Comment by dmtrKovalenko** [comment]
Use HH selector. We need to know how much numbers will be in a mask. Or pass the `mask` explicitly `__:__`

**Comment by JavierLight** [comment]
I think the suggested solution is not good enough. If I use the `HH` selector I won't be able to support multi-locale.

If some locale uses `H:mm` it means it will display `9:35` instead of `09:35`, but in any case the user should be able to introduce a two digits value for hour in the keyboard mode...

I think that getting a date format from a peer library, modifying that format to make sure format/mask is always `hh:` or `HH:` is just a workaround, but in my opinion this is something this library should support.

When using the inline mode, time is displayed properly both for `H:mm` and `HH:mm`, the problem is keyboard mode.

**Comment by keycad** [comment]
We're also experiencing the issue and found this, will there be any other fix? I think this scenario will happen to every user of your library developing a multi-culture app, where spanish or other `H` languages and cultures must be handled

**Comment by kwmcrell** [comment]
Experiencing something similar with month and day as well (M/d/yyyy).  Is there anyway to disable the mask functionality?

**Comment by dmtrKovalenko** [comment]
You can replace formatter with a help of `rifmFormatter` property

**Comment by dmtrKovalenko** [comment]
More details in @istarkov/rifm

**Comment by suryaVemp** [comment]
Hi @dmtrKovalenko is it something like this you had in mind?
``` javascript

const parseDateTimeWithFormat = (str, format) => {
      const dateTime = moment(str, format);
      if (dateTime.isValid) return dateTime.format(format);
      //if not valid date time return the str
      return str;
};


rifmFormatter={str => {
       const res = parseDateTimeWithFormat(str,format);
       return res;
}}
```

**Comment by dmtrKovalenko** [comment]
Fixed in v4

**Comment by NZainchkovskiy** [comment]
I could'n deal with it neither in v3 via rifmFormatter, nor in v4.
In v3 it's really hard to use rifmFormatter, because it's passes only formatted value, so it's difficult to parse. Maybe someone have an example for it?
In v4 mask just ignored for one-digit hour format, so input become unmasked. 
Am I missing something, or "Fixed in v4" is unmasked behaviour?

Thank you!
