### ISSUE TITLE
Possibility to pass rifmReplacer prop (or smth like that) down to Rifm's 'replace' prop along with rifmFormatter

### ISSUE THREAD

**Issue by janbejvl** [mui-org/material-ui-pickers#1288]
**Is your feature request related to a problem? Please describe.**
Feature is related with masking input when custom rifmFormatter is passed to KeyboardDatePicker. Current behavior is that when one pass custom rifmFormatter fn, then mask is gone. This is because of the Rifm component is lacking proper mask function and then it's not be able to show mask properly (mask is gone). Here is sandbox forked from rifm example https://codesandbox.io/s/istarkovrifm-date-format-d85xs. Here if you comment out line 69 
```// replace={addMask}```
then mask is gone.

**Describe the solution you'd like**
I think it would be nice to have a possibility to pass a prop to KeyboardDatePicker called for example 'rifmReplacer', that would do proper masking for me and would be passed down to Rifm component.

**Comment by dmtrKovalenko** [comment]
Make sure that we are using only `0.8` version of rifm

**Comment by dmtrKovalenko** [comment]
There is already `refuse` prop

**Comment by janbejvl** [comment]
Could you please describe how can refuse prop be useful in that?
AFAIK refuse prop has nothing to do with masking itself. Refuse prop is of type RegExp that say smth like 'user cannot write other characters than numbers' (which is default behavior) or 'make the behavior different based on passed regexp'.
What I meant with this feature request was ability to pass custom format function along with rifmFormatter, because when I use rifmFormatter, then mask ( __ /__ / ____ ) is gone and is not shown at all at the start of typing the date.
Thanks.
