### ISSUE TITLE
Allow partially erasing date by keyboard without moving rest of date string

### ISSUE THREAD

**Issue by Talal916** [mui-org/material-ui-pickers#1289]
**Is your feature request related to a problem? Please describe.**
Deleting characters in the middle of a date/time/datetime string through the keyboard results in the rest of the string shifting left. 

![Undesired behavior](https://i.imgur.com/Qyv0wMa.gif)
https://material-ui-pickers.dev/demo/datepicker

#

**Describe the solution you'd like**
I'd like to able to edit parts of the date and time without the rest of the date/time/datetime being affected. This is the standard behavior for most datepickers and the keyboard pickers used by Material-UI result in unexpected behavior for users.

This is a demo of the desired behavior, using the native picker.
https://material-ui.com/components/pickers/
![Desired behavior](https://i.imgur.com/f151TCo.gif)

**Comment by Talal916** [comment]
![](https://i.imgur.com/SCEhwm5.gif)
#
Here's another example of the current behavior being unpleasant

**Comment by croraf** [comment]
Yes, this is a very bad user experience. 

When nothing is selected but cursor is in the field:

- DEL sets the next figure to "_" or the letter representation of the figure ("d", "m", "y"). I don't know if the cursors position should change or stay where it was?
- backspace sets the previous figure to "_" or the letter representation of the figure. The cursor should move 1 figure back.

When some figures are selected then:

- DEL should put all these figures to "_" or letter representation of the figures. Not sure where the cursor position should end?
- backspace should put all these figures to "_" or letter representation of the figures. The cursor should be set to the beginning of the selection.

**Comment by dmtrKovalenko** [comment]
Already fixed in v4-alpha👨‍🏭
