### ISSUE TITLE
Supplying onAccept without onChange leads to an error

### ISSUE THREAD

**Issue by mschipperheyn** [mui-org/material-ui-pickers#1291]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |       3.2.4  |
| material-ui          |       4.3.3  |
| React                |       16.9  |
| Browser              |        chrome |
| Peer library         |         | luxon 1.12.0 |

## Steps to reproduce

1. 2. 3.

```
<DatePickerMat
				{...rest}
				keyboard
				autoOk
				clearable
				showTodayButton
				disableOpenOnEnter
				id={id}
				inputProps={restInput}
				name={`${name}${required ? ` *` : ''}`}
				label={label}
				cancelLabel={i18n._(t('ui.cancel')`Cancelar`)}
				todayLabel={i18n._(t('ui.today')`Hoje`)}
				clearLabel={i18n._(t('ui.clear')`Limpar`)}
				okLabel={i18n._(t('ui.ok')`OK`)}
				invalidLabel={i18n._(t('ui.unknown')`Desconhecido`)}
				invalidDateMessage={i18n._(t('ui.date.invalid')`Data invalido`)}
				value={value}

				onAccept={console.log}

				format={DATEFORMAT}
				placeholder={placeholder}
				keyboardIcon={<CalendarIcon color="primary" />}
				animateYearScrolling={false}
				readOnly={readOnly}
				leftArrowIcon={<ArrowLeftIcon />}
				rightArrowIcon={<ArrowRightIcon />}
				error={!!((displayError || touched || submitFailed) && theError)}
				helperText={
					helperText || ((displayError || touched || submitFailed) && theError)
				}
				emptyLabel=""
				className={className}
			/>
```
## Expected behavior

It should not be necessary to specify an empty onChange handler

## Actual behavior

It bombs without it. 
```
useKeyboardPickerState.js:37 Uncaught TypeError: _onChange is not a function
    at eval (useKeyboardPickerState.js:37)
    at eval (usePickerState.js:55)
    at onChange (usePickerState.js:89)
    at Object.eval [as onChange] (useViews.js:20)
    at Calendar._this.handleDaySelect (Calendar.js:131)
    at eval (DayWrapper.js:14)
```
## Live example
sorry, no time

**Comment by ericrobinsondev** [comment]
This is easily replicable, I've run into the same issue trying to only use onAccept without onChange

**Comment by charleskoehl** [comment]
Same here. Quick fix is to add the following prop if you only need onAccept:
`onChange={() => {}}`

**Comment by oliviertassinari** [comment]
What are your thoughts on removing the `onAccept` prop? Related to https://github.com/mui-org/material-ui-pickers/pull/1923#issuecomment-650725400.

**Comment by oliviertassinari** [comment]
I'm closing for https://github.com/mui-org/material-ui/issues/24151. We need to remove this prop.
