### ISSUE TITLE
KeyboardDatePicker Readonly

### ISSUE THREAD

**Issue by FroggDev** [mui-org/material-ui-pickers#1294]
Hi,

Maybe i did something wrong but i tried to set the KeyboardDatePicker input as readonly and the input label pass under the input layout + the calendar button is style clickable so i can edit the readonly input !

![readonly](https://user-images.githubusercontent.com/3765812/64031737-51fb8500-cb49-11e9-92b1-75dc330c47b6.png)

![calendar](https://user-images.githubusercontent.com/3765812/64031781-6b043600-cb49-11e9-9fe0-0058fb7741bf.png)

This is how i tried to set the read only :
```
 <KeyboardDatePicker
            inputProps={{ readOnly: true }}
            InputProps={{ shrink: true }}
```
By the way i didnt found any information about readonly in the doc.

Is there something i am missing ?
 
thanks

**Comment by dmtrKovalenko** [comment]
Why not to use just `DatePicker` then?

**Comment by FroggDev** [comment]
I did first, but I encountered compatibility issues.

To work around the problem I use an InputText in readonly instead of KeyboardDatePicker.

`{  
readOnly===true ? (
 <InputText {..txtProps} inputProps={{ readOnly : true }} />  
 ) : (
 <KeyboardDatePicker {..dateProps} />
 )
 }`
