### ISSUE TITLE
Add classes prop

### ISSUE THREAD

**Issue by mehrdad-shokri** [mui-org/material-ui-pickers#1296]
**Is your feature request related to a problem?  
![screenshot-localhost_3000-2019 09 01-18_06_06](https://user-images.githubusercontent.com/13661520/64077208-2f04d880-cce3-11e9-8852-ea7a8227f85a.png)
I'm creating a persistent box, which users use it to add events/schedules to a calendar.  
As you see my clock isn't centered on its box and I need it to be. 

**Describe the solution you'd like**
As you're aware material-ui components have a prop named [``classes``](https://material-ui.com/customization/components/#overriding-styles-with-classes), that way the library allows customization of the components. Adding this prop to allow customizing clockContainer, the clock itself would be beneficial

**Describe alternatives you've considered**  

**Additional context**

**Comment by mehrdad-shokri** [comment]
I've figured out that I need to remove ``max-width: 325px;`` from ``.MuiPickersBasePicker-pickerView`` but I don't know how

**Comment by dmtrKovalenko** [comment]
Duplicate. Please read the docs

**Comment by mehrdad-shokri** [comment]
Sorry couldn't catch it.
https://material-ui-pickers.dev/guides/css-overrides
