### ISSUE TITLE
missing doc for __willBeReplacedGetFormatString and hooks in TypeScript

### ISSUE THREAD

**Issue by patcito** [mui-org/material-ui-pickers#1298]
![image](https://user-images.githubusercontent.com/26435/64081528-bc0b5a00-cd02-11e9-8aa3-02d05abcf806.png)

I'm trying to use the keyboard datepicker in typescript and I'm not sure how to call __willBeReplacedGetFormatString in typescript. It doesn't help that I'm not super proficient in typescript yet but it would be great if you could show me an example of how to get this working in typescript and hooks:

```
format={props.__willBeReplacedGetFormatString({
          moment: 'YYYY/MM/DD',
          dateFns: 'yyyy/MM/dd',
        })}
```

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.4     |
| material-ui          |  3.2.4        |
| React                |     16    |
| Browser              |   Chrome      |
| Peer library         |    date-fns     |  |

## Steps to reproduce

1. Try to use the code [here](__willBeReplacedGetFormatString) in TypeScript

## Expected behavior
Find an example in TypeScript

## Actual behavior
No example

**Comment by dmtrKovalenko** [comment]
This thing is only **our docs**, it is using to replace format prop accordinaly to selected date library https://github.com/mui-org/material-ui-pickers/blob/next/docs/utils/utilsService.ts#L44

**Comment by dmtrKovalenko** [comment]
Use only string in the format prop
