### ISSUE TITLE
Question: How to go about integration testing this with static data?

### ISSUE THREAD

**Issue by traverse** [mui-org/material-ui-pickers#1299]
Hi I was wanting to test the calendar in my application that does a bit of mapping on the days where it renders specific days with specific colors and clickability. I was using static data for now but ran into a problem because the calendar uses the current day in some of its functionality.

How would I got about testing this with static data, are there any parts that I can mock?

**Comment by dmtrKovalenko** [comment]
You can use any library to mock the date object. like for example we are doing [here](https://github.com/mui-org/material-ui-pickers/blob/next/docs/pages/_app.tsx#L8) for our documentation site

**Comment by traverse** [comment]
So something like the following should work:
```javascript
jest.spyOn(Date, 'now').mockReturnValue(/* test value here */)
```
Might be a nice addition to the documentation. Thanks for the fast response though! 😄
