### ISSUE TITLE
In inline mode, when current day is disable, opening the picker is select the first enabled day.

### ISSUE THREAD

**Issue by ChanaKra** [mui-org/material-ui-pickers#1300]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.4      |
| material-ui          |    4     |
| React                |   16.8      |
| Browser              |    chrome     |
| Peer library         |     moment     |  |

## Steps to reproduce

1. Create a picker with variant="inline"
2. Add shouldDisableDate that disable current day.
(with moment, for example: shouldDisableDate={(date)=>date.isSame(moment(),'day')} )
3. Open the picker, and close it without selecting any date.

## Expected behavior

No date is selected.

## Actual behavior

When open the picker, the first enabled day is selected.
## Live example

https://codesandbox.io/s/material-ui-pickers-usage-demo-qxylf

**Comment by dmtrKovalenko** [comment]
It is by design.

**Comment by ChanaKra** [comment]
It's not consistent.
To clarify, The problem is that in this case, the first enabled day is not only focused but also the onChange & onAccept functions are invoked.
If you open the picker when the current day is **enable** - the current day get focused, but onChange & onAccept are **not** invoked.

In addition, it's only occurs in inline mode.

**Comment by dmtrKovalenko** [comment]
Yeah, I know. We probably can consider changing it in #1293. But right now if current day is disabled picker will automatically select the closest one. 
But for inline mode any selection triggers `onChange` to be called. 

What behavior you want to see there? Highlight the disabled date?

**Comment by ChanaKra** [comment]
In inline mode, any selection triggers onChange. but open and close picker isn't selection.
For example, when the field is empty, open the picker doesn't select current date.

I expect that the closest enable date will be highlight, but not update the value,
just like when highlight current date:
![image](https://user-images.githubusercontent.com/44194455/64341115-5a900780-cff0-11e9-8caa-5821ed5530a8.png)
