### ISSUE TITLE
Cannot enter non-numeric month strings in KeyboardDatePicker

### ISSUE THREAD

**Issue by kendallroth** [mui-org/material-ui-pickers#1302]
![image](https://user-images.githubusercontent.com/12562420/64266685-00fddf00-cf03-11e9-8b62-95eb172a1054.png)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | `3.2.3`  |
| material-ui          | `4.1.2` |
| React                | `16.8.6` |
| Browser              | `Chrome 76` |
| Peer library         | `@date-io/moment@1.3.9`, `moment@2.24.0` |

## Steps to reproduce

1. Add `KeyboardDatePicker` with `format="YYYY-MMM"`
2. Try to enter a valid date month string (cannot enter non-numeric characters)

## Expected behavior

Either enable entering valid date month strings (based on format).

## Actual behavior

No easy way to allow valid date month strings to be entered, as it does not allow entering non-numeric characters.

## Live example

https://codesandbox.io/s/material-ui-pickers-date-format-bug-p2c9b

**Comment by BikoTienzo** [comment]
Ran into the same issue. I know it's been months already since this was posted, but I hope my work-around could help others.

My default format is set to 'MMMM d yyyy'. What I did was have the onFocus event set the format to 'MM/dd/yyyy' so it can be edited using only numbers, then the onBlur event sets it back to 'MMMM d yyyy'.

**Comment by dmtrKovalenko** [comment]
Fixed in v4

**Comment by llatinov** [comment]
> Ran into the same issue. I know it's been months already since this was posted, but I hope my work-around could help others.
> 
> My default format is set to 'MMMM d yyyy'. What I did was have the onFocus event set the format to 'MM/dd/yyyy' so it can be edited using only numbers, then the onBlur event sets it back to 'MMMM d yyyy'.

Can you give an example how to do this change, please?

**Comment by llatinov** [comment]
> Fixed in v4

Is it possible to get this fixed in v3 as well? v4 seems to have too many breaking changes, and migrating to it might not be the best option, still, v3 is widely used and is good to work properly.

**Comment by dmtrKovalenko** [comment]
@llatinov no, pass the numeric format. Or use **not keyboard** picker

**Comment by dmtrKovalenko** [comment]
Or you can pass `rifmFormatter={str => str}` it will disable masking

**Comment by oliviertassinari** [comment]
> Is it possible to get this fixed in v3 as well?

Sorry, we don't have the bandwidth for doing it.
