### ISSUE TITLE
[core] Implement forwardRef

### ISSUE THREAD

**Issue by SBRKH** [mui-org/material-ui-pickers#1303]
Hi,
First of all, thank for your work !

I would like to know if is it possible to pass ref to my DatePicker ?

In my case, I use your Date Picker in a form using react-final-form.
I have wrappers for each of my inputs to customize the error message. However, I am obliged to pass a ref to each of my components in order to recover the size of said component and display a popper of this size.
Currently, from what I have seen in the doc, it is impossible for me to pass a reference to my DatePicker.

Do you have a solution to offer me or can you add the possibility to pass some?

Thank you for your time and answer !

**Comment by LucaPizzagalli** [comment]
Did you find a solution on this?

**Comment by oliviertassinari** [comment]
You are right, all the public components should leverage `React.forwardRef`, forward the ref on the "root element". This breaks the expectation developers have with the other core components.

**Comment by oliviertassinari** [comment]
@LucaPizzagalli The implementation of such behavior should be relatively straightforward. Is this something you would want to work on? :) For instance, I would envision something similar to:

```diff
index d41a1e85..02a042f2 100644
--- a/lib/src/views/Calendar/Calendar.tsx
+++ b/lib/src/views/Calendar/Calendar.tsx
@@ -92,26 +92,29 @@ export const useStyles = makeStyles(theme => ({
   },
 }));

-export const Calendar: React.FC<CalendarProps> = ({
-  date,
-  isMonthSwitchingAnimating,
-  onMonthSwitchingAnimationEnd,
-  focusedDay,
-  changeFocusedDay,
-  onChange,
-  minDate,
-  maxDate,
-  slideDirection,
-  disableFuture,
-  disablePast,
-  currentMonth,
-  renderDay,
-  reduceAnimations,
-  allowKeyboardControl,
-  isDateDisabled,
-  disableHighlightToday,
-  showDaysOutsideCurrentMonth,
-}) => {
+export const Calendar = React.forwardRef(
+  (props: CalendarProps, ref?: React.Ref<HTMLDivElement>) => {
+  const {
+    date,
+    isMonthSwitchingAnimating,
+    onMonthSwitchingAnimationEnd,
+    focusedDay,
+    changeFocusedDay,
+    onChange,
+    minDate,
+    maxDate,
+    slideDirection,
+    disableFuture,
+    disablePast,
+    currentMonth,
+    renderDay,
+    reduceAnimations,
+    allowKeyboardControl,
+    isDateDisabled,
+    disableHighlightToday,
+    showDaysOutsideCurrentMonth,
+    ...other,
+  } = props;
+
   const now = useNow();
   const utils = useUtils();
   const theme = useTheme();
@@ -159,7 +162,7 @@ export const Calendar: React.FC<CalendarProps> = ({

   return (
     <>
-      <div className={classes.daysHeader}>
+      <div ref={ref} className={classes.daysHeader} {...other}>
         {utils.getWeekdays().map((day, i) => (
           <Typography
             aria-hidden
```
