### ISSUE TITLE
[DateTimePicker] crashes with hooks-out-order error from React

### ISSUE THREAD

**Issue by agonzalezjr** [mui-org/material-ui-pickers#1304]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I implement a DateTimePicker that can be set to read-only (not open the dialog) or editable dynamically like it is done [here](https://github.com/agonzalezjr/materialui-readonly-datepicker/blob/master/src/App.tsx), setting the `open` property dynamically will cause an error like this:

```
Warning: React has detected a change in the order of Hooks called by PickerWithState. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useContext                 useContext
3. useState                   useCallback
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in PickerWithState (at App.tsx:14)
    in MuiPickersUtilsProvider (at App.tsx:40)
    in div (at App.tsx:28)
    in App (at src/index.tsx:7)
```

## Expected Behavior 🤔

The DateTimePicker component should just be re-rendered as read-only or not. It would be great if there was a `readOnly` prop in the component out of the box.

## Steps to Reproduce 🕹

Setup in a Sandbox here: https://codesandbox.io/embed/materialui-readonly-datepicker-klttf

Steps:

1. Click the checkbox
2. See Console Errors
3. If you want, comment out the code that "crashes" and uncomment the one that doesn't. 
4. It will work as expected in that scenario.

Alternatively, clone this repo: https://github.com/agonzalezjr/materialui-readonly-datepicker (it's just a `create-react-app ... --typescript` with `MaterialUI` installed and `App.tsx` modified to reproduce the issue.

```
npm i
npm run start
```

In the main web page, click the checkbox.

## Context 🔦

A `DateTimePicker` that can be set to read-only dynamically. It would be great if there was a `readOnly` prop in the component out of the box.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Material-UI | `v4.4.0`  |
| React       |   `v16.9.0`      |
| Browser     |      Chrome `v76.0.3809.132`   |
| TypeScript  |   `v3.5.31`      |
| @material-ui/pickers      |    `v3.2.5`     |

**Comment by dmtrKovalenko** [comment]
You must not change open property to undefined dynamically. 
If you need to - please implement your own state for open prop.

**Comment by agonzalezjr** [comment]
Hi @dmtrKovalenko - Thanks for taking a look! 

I tried this. However, setting the open property from a boolean state does not work because when set to `false`, it never opens the dialog (as desired for "readOnly"), but when set to `true`, it keeps the dialog open all the time without a way to close it. And that's the only two choices for a boolean, so I tried `undefined` next 🙂

Do you mean there are other event handlers I could use to be notified of dialog events or do you have an example of what you are suggesting?

--

Another question if you don't mind: do you know why it works without error in one of the scenarios in the sample but not the other?

**Comment by dmtrKovalenko** [comment]
You need to add some state. https://material-ui-pickers.dev/guides/controlling-programmatically

Everything you need is to only control the open property by yourself all the time

**Comment by agonzalezjr** [comment]
Ok, that works! Thank you so much!

I have updated the sandbox with the fixed code https://codesandbox.io/s/materialui-readonly-datepicker-klttf
