### ISSUE TITLE
Date Picker inside Shadow DOM

### ISSUE THREAD

**Issue by sravannerella** [mui-org/material-ui-pickers#1307]
Hello, Material UI Picker Dev Team, 

Recently, for one of my projects, I tried to integrate material Date picker within the shadow dom and it's not working as expected. 

So, I tried a few things. 
1) Just integrated date picker inside the Shadow DOM but the date picker styles are not applying. It shows the dates in vertical order but the click away listener and everything works as expected.
2) To fix that, I followed [Issue: Material UI Shadow DOM Support #12011](https://github.com/mui-org/material-ui/issues/12011#issuecomment-401550066) and got the styles applying and functionality working but when clicking outside the date picker does not dismiss.

Though 2nd one kind of work, I still want the date picker to be fully functional like it is in the regular DOM. Could you please point to the correct way of doing it.

**Comment by motss** [comment]
Are you using React with Shadow DOM?

**Comment by oliviertassinari** [comment]
Closing as I believe we don't support shadow DOM in the core, nor we aim to (we rarely see this request).
