### ISSUE TITLE
DateTimePicker version 3.2.5 keep re-render

### ISSUE THREAD

**Issue by baoduy** [mui-org/material-ui-pickers#1308]
Hi,
After upgrading to version 3.2.5 my page keeps re-rendering infinitely. Seems some sates are not managed properly. The issue fixed once downgraded to 3.2.4. Please take a look.

Thanks
Duy

**Comment by dmtrKovalenko** [comment]
It will rerender if you abuse `onError` prop

**Comment by baoduy** [comment]
@dmtrKovalenko Thanks for the reply. Not sure what wrong with my code, but I'm not even aware the onError is there and not using it as well.

**Comment by dmtrKovalenko** [comment]
Spent 30 minutes in Profiler today trying to find cascade rerenders and didn't find anything. Please provide some valid description or example

**Comment by natac13** [comment]
Hey so I am experiencing this issue of re-rendering when the date is changed.

This is my setup for `DateTimePicker`
```js
const DateTimePickerField = ({ field, form, ...other }) => {
  const currentError = form.errors[field.name];
  return (
    <DateTimePicker
      format="MMM dd, yyyy @ p"
      showTodayButton
      autoOk
      inputVariant={other.variant}
      name={field.name}
      value={field.value}
      label={other.label}
      helperText={currentError}
      error={Boolean(currentError)}
      onError={(_, error) => {
        // handle as a side effect
        if (error !== currentError) {
          form.setFieldError(field.name, error);
        }
      }}
      onChange={(date) => {
        return form.setFieldValue(field.name, date, true);
      }}
      {...other}
    />
  );
};
```

I am using it with Formik like so
```js
const DateSelector = (props) => {
  const { datesSelectedList, index } = props;
  return (
    <FormControl
      className={classnames({
        [style.dateField]: true,
        [style.unfilled]: !datesSelectedList[index],
      })}
    >
      <Field
        name={`classDates.${index}.start`}
        required
        render={(p) => (
          <DateTimePickerField
            variant="outlined"
            autoOk
            disablePast
            initialFocusedDate={addDays(index + 30)(
              new Date().setHours(9, 0, 0, 0)
            )}
            label="Start Day & Time"
            {...p}
          />
        )}
      />
    </FormControl>
  );
};
```

And like the OP said when I downgrade to `v3.2.4` everything works great. But the upgrade to `v3.2.5` or `v3.2.6` causes an infinite re render when the date is changed. 

If you need more information of my setup please let me know and I will do my best to help diagnose this issue. Or just fix whatever I have wrong :laughing:

**Comment by corydeppen** [comment]
I'm seeing the same using v3.2.8.
