### ISSUE TITLE
DatePicker incorrect time value

### ISSUE THREAD

**Issue by PasVV** [mui-org/material-ui-pickers#1310]
# Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.5     |
| material-ui          |    4.3.3    |
| React                |    16.8.6    |
| Browser              |    any    |
| Peer library         |    "@date-io/date-fns": "^1.3.11"    |

## Steps to reproduce

1. Use any `DatePicker` component, listen `date` prop in `onChange` callback
2. Click any date on UI.

## Expected behavior

I except selected date with midnight time, like this: `Tue Sep 10 2019 00:00:00 GMT+0300 (GMT+03:00)`

## Actual behavior

Now `onChange` cb passing date like this: `Tue Sep 10 2019 10:02:00 GMT+0300 (GMT+03:00)` with current time.

## Gif example

![1](https://user-images.githubusercontent.com/24910502/64761953-e8ff0e80-d545-11e9-91bc-365ae7fc13d2.gif)

**Comment by dmtrKovalenko** [comment]
Which vaue are you passing to the component?

**Comment by PasVV** [comment]
> Which vaue are you passing to the component?

Initial - `null`

**Comment by dmtrKovalenko** [comment]
Then it will use `new Date()` as a basic 
You can pass `initialFocusedDate={startOfDay(newDate)}`

**Comment by PasVV** [comment]
Thank you, problem solved. :)
As i see, i missed `initialFocusedDate` prop in docs.

**Comment by ken210** [comment]
For those having the same issue, I solved this problem (for my case) doing the following:

```
const handleChange = (date, value) => {
    const utcMidNight = new Date(Date.UTC(date.getFullyear(), date.getMonth(), date.getDate()));

   // the rest of your handler
}
```

This way I can safely remove the "time" from my date, while I ensure it stays consistent between timezones
