### ISSUE TITLE
Date picker documentation needs to be updated

### ISSUE THREAD

**Issue by Kizmar** [mui-org/material-ui-pickers#1317]
"@material-ui/core": "^4.4.0",
"@material-ui/icons": "^4.2.1",
"@material-ui/pickers": "^3.2.2",
"react": "^16.9.0",
"react-dom": "^16.9.0",
"react-router-dom": "^5.0.1",
"react-scripts": "3.1.1",
"typescript": "^3.6.2"

## Steps to reproduce
The documentation for the date picker doesn't work and the three closed issues I reviewed for the error don't resolve the problem for me. I'm unsure what the actual fix is for this.

[The documentation](https://material-ui.com/components/pickers/#material-ui-pickers) is using `import DateFnsUtils from '@date-io/date-fns';`. If I use the current version of `1.3.11`, I get the `Can't resolve 'date-fns/addDays'` error mentioned below.

[This issue](https://github.com/mui-org/material-ui-pickers/issues/349) says to use `date-fns` version `2.x`. So I installed `"date-fns": "^2.2.1"` and imported it as `import * as DateFnsUtils from 'date-fns';`. In doing so I get the error: `Cannot find module '@date-io/core/IUtils'`.

[This issue](https://github.com/mattlewis92/angular-calendar/issues/591) says to use `date-fns@1.30.1`. So I installed that version. I get the same `Cannot find module '@date-io/core/IUtils'` error.

At this point I decided to install `"@date-io/core": "^1.3.11"`. Running with that, I get the error: `Cannot find module '@date-io/type'`. I attempted to install that and the package doesn't appear to exist.

I also tried installing `"date-fns": "^2.2.1"` with `"@date-io/core": "^1.3.11"`, but I still get the `Cannot find module '@date-io/type'` error.

**[Edit 1]** Looking at the type definitions for `MuiPickersUtilsProvider`; I noticed that's importing `import { IUtils } from '@date-io/core/IUtils';`. `IUtils` has a `moment` property, so I thought I'd try passing `moment` in as the `MuiPickersUtilsProvider.utils` property. I still end up with the `Cannot find module '@date-io/type'` error.

**[Edit 2]** I realized I should check out the CodeSandbox for the [example](https://material-ui.com/components/pickers/#material-ui-pickers). That appears to be working, however when I try to install the same packages it uses, neither `@types/date-ioDate-fns` nor `@types/material-uiPickers` appear to exist. No matter what packages I try, I still run into the `Cannot find module '@date-io/type'.` error.

I'm at a loss here. :( 

## Expected behavior
If I follow the documentation I shouldn't get errors.

## Actual behavior
Getting error: `Can't resolve 'date-fns/addDays'`. [Closed issue here.](https://github.com/mui-org/material-ui-pickers/issues/349)

**Comment by Kizmar** [comment]
As a side note: if one or more of these `date-fns` packages is a requirement of using the date picker, why aren't they added as dependencies in the `@material-ui/pickers` package so we don't have to worry about what we're supposed to install to pass to the provider (`<MuiPickersUtilsProvider utils={DateFnsUtils}>`)?

In regards to **[Edit 1]** in the OP, if it's not included because you can pass in `moment` instead, that makes sense. I already had moment installed because I needed good UTC support and it doesn't appear `date-fns` `format` is there yet.

**Comment by jacobwicks** [comment]
I ran into this error also. I installed @date-io/date-fns and I import DateFnsUtils from '@date-io/date-fns'; which works. But yeah, although the component is nice the documentation is really difficult.

Having an example of a renderDay function in the docs would be nice. I eventually found it in the source code, but it took some diving. I did find several outdated references to it on 2-3 old versions of the official docs, but all the links were broken.

Also, the date picker does not close on selection of a date. It would be nice if it did, or if there was a prop to make it do so. I found this thread while looking how to make it close on select, which is something I am still looking for.

Edit: to close on selection set the prop autoOk={true}

**Comment by dmtrKovalenko** [comment]
`autoOk` is what you need. 
If you have any idea how documentation can be improved — you are welcome. Right now we are spreading a lot of examples through the docs. And there are 2 examples of `renderDay` in the docs. And also providing the list of props with description

**Comment by dmtrKovalenko** [comment]
And here is another problem. In the date-fans version. So you need date-fans v2.

**Comment by Kizmar** [comment]
Revisiting it this morning I noticed what I was missing over the weekend. Got it working. In the component, I was missing `import 'date-fns';`. 

For the record, these are the relevant package versions I have installed:
```
"@material-ui/pickers": "3.2.2",
"@date-io/date-fns": "1.3.9",
"date-fns": "2.2.1",
"@types/date-fns": "^2.6.0",
```

**Comment by jacobwicks** [comment]
Well, if there are example of renderDay then making them easier to find with a search engine would be a good step. I still can't find them even though you have told me they exist!
I have checked at:
https://material-ui-pickers.dev/api/DatePicker
and
https://material-ui.com/components/pickers/#material-ui-pickers

If neither of those are the right site, then providing a more obvious link would be the way to go.

**Comment by dmtrKovalenko** [comment]
Here https://material-ui-pickers.dev/demo/datepicker#dynamic-data 
And here https://material-ui-pickers.dev/demo/datepicker#customization

> It would be good to have a search similar to material-ui docs
