### ISSUE TITLE
Callstack exceeded when using DatePicker (with Formik)

### ISSUE THREAD

**Issue by reinvanimschoot** [mui-org/material-ui-pickers#1318]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |         |
| material-ui          |  4.4.0       |
| React                |     16.9.0    |
| Peer library         |   date-fns:  2.0.1-rc.13      | 

## Steps to reproduce

I just added the DatePicker component in my Formik form like so:

```
type Props = {
  initialValues?: HydrantFormValues;
  onSubmit: (values: HydrantFormValues) => Promise<void>;
  title: string;
};

function Form(props: Props) {
  const classes = useStyles();

  const [selectedDate, handleDateChange] = React.useState<MaterialUiPickersDate>(new Date());

  const initialValues = Object.assign(
    {},
    {
      serial: '',
      installedAt: new Date(),
    },
    props.initialValues,
  );

  const { touched, errors, values, setFieldValue, isValid, handleChange, handleSubmit, isSubmitting } = useFormik({
    initialValues,
    isInitialValid: false,
    enableReinitialize: true,
    onSubmit: props.onSubmit,
  });

  return (
      <Box className={classes.box}>
        <DatePicker
          disableToolbar
          variant="inline"
          format="MM/dd/yyyy"
          margin="normal"
          name="installedAt"
          id="installedAt"
          label="Installed"
          value={selectedDate}
          onChange={handleDateChange}
        />
</Box>
```

## Expected behavior

I expect that the DatePicker component works as expected without crashing.

## Actual behavior

Both with the setValue function from Formik as well as with useState (as shown above), I get an error stating maximum callstack exceeded.

![Screenshot 2019-09-17 at 16 17 01](https://user-images.githubusercontent.com/35171567/65049789-a5057280-d966-11e9-8c1c-245298e9b512.png)

**Comment by dmtrKovalenko** [comment]
Formik [is not officially released](https://jaredpalmer.com/formik/docs/overview) react hooks. So please provide what you are using to generate a formik hook with codesandbox.

**Comment by oliviertassinari** [comment]
The issue has been closed because it does not conform to our issue requirements. 
Please provide a full reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript) _may_ be a good starting point. Thank you!
