### ISSUE TITLE
Styling issue when using a custom spacing function

### ISSUE THREAD

**Issue by r-s-sandbox** [mui-org/material-ui-pickers#1321]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.6     |
| material-ui          |     4.4.2    |
| React                |    16.8.6     |
| Browser              |     Chrome 76    |
| Peer library         |    data-fns 1.3.11     | 

## Steps to reproduce

1. Override styles using custom spacing
2. Instead of number, use a function as per [instructions](https://material-ui.com/customization/spacing/#custom-spacing)

## Expected behavior

Time picker styling of clock numbers should not break

## Actual behavior

The clock numbers of all shifted to the left. 

## Live example

 https://codesandbox.io/s/async-dew-j2hcs

**Comment by bndynet** [comment]
@r-s-sandbox Maybe because you overwrote the `spacing` method in **index.js** file which caused the above case. You can comment it as below to try again:

```
const materialTheme = createMuiTheme({
  //spacing: factor => `${0.25 * factor}rem`
});
```

It seems a bug of component.
