### ISSUE TITLE
Render custom day label in Calendar

### ISSUE THREAD

**Issue by kvnkusch** [mui-org/material-ui-pickers#1322]
Thanks for this project, it's been great for me so far.

I have a use-case for the Calendar component where I'd like to render a custom day labels for the days of the week. It could be an optional prop renderDayLabel (like renderDay), but passed to the CalendarHeader where the day labels are rendered. Let me know if this is feasible, I can work on a PR if necessary.

**Comment by dmtrKovalenko** [comment]
Right now you can do the following. https://codesandbox.io/s/material-ui-pickers-usage-demo-5mxug

Let me know if this fixing your problem

**Comment by InFuz** [comment]
> Right now you can do the following. https://codesandbox.io/s/material-ui-pickers-usage-demo-5mxug
> 
> Let me know if this fixing your problem

Can I use more than one symbol for the day of the week label? Now, even when specifying multiple characters, only the first is displayed.
