### ISSUE TITLE
Formatting for KeyboardDatePicker using moment.js

### ISSUE THREAD

**Issue by wjonesusna2012** [mui-org/material-ui-pickers#1323]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.2    |
| material-ui          |   4.3.2      |
| React                |    16.8.6     |
| Browser              |  Chrome  Version 77.0.3865.75 (Official Build) (64-bit)       |
| Peer library         |  Moment.js 2.24.0 |

## Steps to reproduce

1. Use the live demo to see the incorrectly displayed behavior. Bug appears when using the moment.js utilities as the input to MuiPickersUtilsProvider.

## Expected behavior
I expect the date in the KeyboardDatePicker to be displayed as MM/DD/YYYY

## Actual behavior
I am getting a date displayed as 09/Th/yyyy and the inability to properly change the date with the selector.

## Live example
https://codesandbox.io/s/material-demo-9s9d4

**Comment by dmtrKovalenko** [comment]
This is because of moment has different formatting chars. here is working example -> 
https://codesandbox.io/s/material-demo-u9e2n

> P.S. If you want to get proper formats in examples on docs site you can choose moment in the utils menu (top right corner)
