### ISSUE TITLE
Timepicker MaxDateMessage

### ISSUE THREAD

**Issue by ttridon** [mui-org/material-ui-pickers#1324]
Hi,

I don't understand how the message define in the property MaxDateMessage is supposed to be triggered.
You can't define a MaxDate in the Timepicker properties, but in the Api you can found the property MaxDateMessage.

**Comment by mehrdad-shokri** [comment]
on TimePicker component I would like to set ``minDate`` to "21:00" and ``maxDate`` to "23:45"  
I'm not arguing on prop name but the way it gets initialized. I think on ``DatePicker`` component it should be an instance of ``DateIOType`` but on ``TimePicker`` it should be a string

**Comment by dmtrKovalenko** [comment]
Timepicker is still not supporting disabling periods of time #519. 
This is just our documentation process generation problem :D
