### ISSUE TITLE
Cant show changing time

### ISSUE THREAD

**Issue by leonidkuznetsov18** [mui-org/material-ui-pickers#1326]
For DateTimePicker in props `minDate` added date with time `moment().add(2, "h").toDate().getTime()` , but dont see any updates for time, but if I change day,year or month it works perfect. My format `MM/DD/YYYY h:m A`

**Comment by dmtrKovalenko** [comment]
Yeah timepicker is not supportting time ranges or disabled time. Duplicate of #519
