### ISSUE TITLE
shouldDisableDate crushes DatePicker

### ISSUE THREAD

**Issue by dinumihnea** [mui-org/material-ui-pickers#1336]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.2.6    |
| material-ui          |    4.4.3     |
| React                |    16.9.0     |
| Browser              |    Chrome latest     |
| Peer library         |     date-fns 1.3.11    |

## Steps to reproduce

```
<MuiPickersUtilsProvider utils={DateFnsUtils}>
      <DatePicker
              autoOk
              minDate={new Date('2019-01-07')}
              maxDate={new Date('2019-10-30')}
              orientation="landscape"
              variant="static"
              openTo="date"
              shouldDisableDate={(date) => {
                // true for all dates will crashe entire app.
                //
                // On this step I mocked case when dynamic provided data won't have 
                // any disabled date
                return true;
              }}
              // here I put null to show that is not the case when the selected date is disabled
              value={null}
              onChange={() => {}}
            />
</MuiPickersUtilsProvider>
````

## Expected behavior
Render with all dates enabled (between min and max)

## Actual behavior
App crashes

## Live example
Booking app with disabled dates from the database

**Comment by dmtrKovalenko** [comment]
I am sorry. But here you are saying that all your dates are disabled. 
I have created a PR to fix the crash, but for you will be properly to change the code to `shouldDisableDate={() => false}`
