### ISSUE TITLE
The focus change when we try to introduce the date from the keyboard and the format include letters

### ISSUE THREAD

**Issue by amaia00** [mui-org/material-ui-pickers#1337]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.6      |
| material-ui          |     4..41    |
| React                |     16.8.6    |
| Browser              |    Google and Firefox     |
| Peer library         |     moment and date-fns |

## Steps to reproduce

1. To use the KeyboardDatePicker with a format that contains letters (e.g. `DD/MMM/YYYY` `03/Oct/2019`.
2. Try to replace the date for a different one using the keyboard.
3. The focus of the input has weird behavior.

## Expected behavior

The focus should remain after the last letter entered and not before.

## Actual behavior
The focus sometimes remains before the last letter entered.
![date_picker](https://user-images.githubusercontent.com/7100576/66044955-b450f800-e4f0-11e9-8b1e-2d5b8af443df.gif)

## Live example
https://codesandbox.io/s/material-ui-pickers-usage-demo-95bxc

**Comment by dmtrKovalenko** [comment]
The focus is getting back to the button. It is required by accessibility so it's not an issue.

**Comment by oliviertassinari** [comment]
@dmtrKovalenko The issue doesn't seem to be with which element is focused but the position of the caret (cursor).

@w-inter I couldn't reproduce on https://codesandbox.io/s/condescending-davinci-5g9gt?file=/src/App.js. Without a reproduction, we can't help.

**Comment by JWootton60** [comment]
This is still an issue.  If you use the sandbox that amaia00 posted, [sandbox](https://codesandbox.io/s/material-ui-pickers-usage-demo-95bxc), you will see the problem.

**Comment by oliviertassinari** [comment]
Duplicate of #2159
