### ISSUE TITLE
Day names on calendar do not change

### ISSUE THREAD

**Issue by alenxmedia** [mui-org/material-ui-pickers#1338]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |         |
| material-ui          |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

There is a bug in DatePicker when using moment localization. If you are importing more than locale day names in calendar always stay the same. This bug is visible and present on official demo page.
1. Go to https://material-ui-pickers.dev/localization/moment
2. Open calendar and check day names
3. Change language to en
4. Open calendar and check day names. Day names did not change.

## Live example

https://material-ui-pickers.dev/localization/moment

**Comment by dvh312** [comment]
Confirmed. I spent an hour trying to fix this.

<img width="314" alt="Screen Shot 2019-10-04 at 10 13 32 am" src="https://user-images.githubusercontent.com/5793549/66173516-b3a29800-e68f-11e9-9d4f-c355a5b5d169.png">

**Comment by empav** [comment]
Guys, what's the correct way to translate the calendar in another language different than english?
Tried to import @date-fns/locale/it and used MuiPickersUtilsProvider onto the root of my app but calendar doesn't change. I don't need a dropdown to select a lang, I just need the calendar to show up in a different language.

`
<MuiPickersUtilsProvider utils={DateFnsUtils} locale={itLocale}>
//DatePicker
</MuiPickersUtilsProvider>
`

**Comment by dmtrKovalenko** [comment]
Fixed in v4
