### ISSUE TITLE
React does not recognize the `showTodayButton` prop on a DOM element

### ISSUE THREAD

**Issue by amaia00** [mui-org/material-ui-pickers#1339]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.6      |
| material-ui          |     4..41    |
| React                |     16.8.6    |
| Browser              |    Google and Firefox     |
| Peer library         |     moment and date-fns |

## Steps to reproduce

1. Use the KeyboardDatePicker with the `variant` property `inline`
2. Try to use the property `showTodayButton`

## Expected behavior

The calendar displays the today button

## Actual behavior

An error is thrown 
 
<img width="681" alt="Screen Shot 2019-10-02 at 9 38 14 AM" src="https://user-images.githubusercontent.com/7100576/66048909-67711f80-e4f8-11e9-9d4d-b8788ffdc8e5.png">

## Live example
https://codesandbox.io/s/material-ui-showtodaybutton-f67by

**Comment by dmtrKovalenko** [comment]
Fixed a long time ago :)
