### ISSUE TITLE
Incorrect updating inputValue after click on Clear button

### ISSUE THREAD

**Issue by janbejvl** [mui-org/material-ui-pickers#1346]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.2      |
| material-ui          |    4.3.1     |
| React                |     16.8.6    |
| Browser              |  Chrome       |
| Peer library         |    moment@2.24.0     |  |

## Steps to reproduce
1. focus in KeyboardDatePicker
2. type some invalid date value, e.g. '22.22.2222', or just '22.2'
3. click on Clear btn appeared 

## Expected behavior
Whenever user types any numeric value, user can clear it by clicking Clear button and inputValue dissappears.

## Actual behavior
Currently, this works only with valid date inputValue. If inputValue is incomplete or invalid value, after clicking Clear button this is not updated correctly.

## Live example
Reproducible example: https://codesandbox.io/embed/react-typescript-starter-sbdi4

If you inspect the react tree, after typing '22.22.2222' you might find that after clicking Clear button the state is:
KeyboardDatePickerField - updated correctly (inputValue: "")
WrappedKeyboardPicker - updated correctly (inputValue: "")
KeyboardDateInput - incorrect (inputValue: "22.22.2222")

Thanks.

**Comment by dmtrKovalenko** [comment]
This looks outdated. Sorry for missing response :(
