### ISSUE TITLE
How can test DateRangePicker?

### ISSUE THREAD

**Issue by leonidkuznetsov18** [mui-org/material-ui-pickers#1347]
How can test DateRangePicker? :
- onChange

```
const wrapper = mount(
      shallow(
        <PromotionRange
          {...}
        />,
      ).get(0),
    );
    const startDateTimePicker = wrapper.find("input#startDateTimePicker");
    startDateTimePicker.simulate("change", {
      target: { value: "10/09/2019 10:04 AM" },
    });
```
after simulater change I check changing props, but they do not change!
I have Stateful component with 2 DateTimePicker, and I need to write a test for checking compare date/time between two DateRangePicker (showing error too)

**Comment by fllprbt** [comment]
Same with me on react-testing-library. The `onChange` events fired in the input, don't do anything.
