### ISSUE TITLE
Datepicker inconsistent time between text input or dialog click

### ISSUE THREAD

**Issue by Toub** [mui-org/material-ui-pickers#1348]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.6     |
| material-ui          |    4.4.3    |
| React                |      16.10.1   |
| Browser              |    firefox     |
| @date-io/dayjs        |   1.3.11    |

## Steps to reproduce

1. Configure KeyboardDatePicker with 
- format 'dd/MM/yyyy'
- initialFocusedDate: today - 12:00 UTC
- onChange: (date: Date, value: string) => console.log('[onDateChange]', date, value) 
2. enter '01/01/2000' on text input using keyboard
3. refresh page (to reset component)
4. select date '01/01/2000' using datepicker dialog

## Expected behavior

Step 2 log:

```js
>  [onDateChange] Date 2000-01-01T12:00:00.000Z 01/01/2000 
```

Step 4 log:

```js
>  [onDateChange] Date 2000-01-01T12:00:00.000Z 01/01/2000 
```

## Actual behavior

Keyboard parsed date is localized (my local timezone is GMT+3), so selected date is wrong

Step 2 log:

```js
>  [onDateChange] Date 2000-01-01T12:00:00.000Z 01/01/2000 
```

Step 4 log:

```js
>  [onDateChange] Date 1999-12-31T21:00:00.000Z 01/01/2000 
```

## Suggestion

If it is too hard to fix, please provide one of the following:
- a way to provide the parse method to KeyboardDatePicker
- a 3rd parameter in `onChange` to know if date come from  text input or datepicker dialog

## Live example

__Note:__ open the console to see the logs.

[https://codesandbox.io/s/material-ui-pickers-usage-demo-bopjp?fontsize=14](https://codesandbox.io/s/material-ui-pickers-usage-demo-bopjp?fontsize=14)

## Related issues

https://github.com/mui-org/material-ui-pickers/issues/1310

**Comment by Toub** [comment]
Just added a live example.

**Comment by lkostrowski** [comment]
Just had the same issue. I think parsing should not be that hard, because we need to provide format - in this case each keyboard input can manipulate date object.
E.g we compare `10/10/2019` to `10/10/2018` and we know that diff is in `yyyy` segment.

I will take a look at this, maybe I can figure this out

**Comment by lkostrowski** [comment]
I did some digging and actually its implemented here:
https://github.com/mui-org/material-ui-pickers/blob/0c8028c048fd026761aebf339d1a5898c1b93029/lib/src/_shared/hooks/useKeyboardPickerState.ts#L59

I also don't have this bug in MUIP examples, where date-fns are used.

So now I would check if dayjs adapter isn't a problem here

**Comment by NoahDavidATL** [comment]
I also need to be able to format what time zone the date picker displays. It's currently showing GMT-005, but I want it to display UTC time. No idea how to do that.

**Comment by johannlucas** [comment]
@DonkeyAfterDark me too man, if you figure it out please tell me...

**Comment by johannlucas** [comment]
I actually figure out, but I don't know if is the best solution:

```node
class UTCUtils extends DateFnsUtils {
    date(d) {
        d = moment(d);
        var year = d.format('YYYY');
        var month = d.format('M');
        var day = d.format('D');
        var hours = d.format('HH');
        var minutes = d.format('mm');

        return new Date(year, month, day, hours, minutes);
    }
}
```
```node
<MuiPickersUtilsProvider utils={UTCUtils}>
```
