### ISSUE TITLE
KeyboardDatepicker loosing focus when typing "/"

### ISSUE THREAD

**Issue by Toub** [mui-org/material-ui-pickers#1349]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.6     |
| material-ui          |    4.4.3    |
| React                |      16.10.1   |
| Browser              |    firefox     |
| @date-io/dayjs        |   1.3.11    |

## Steps to reproduce

1. Configure KeyboardDatePicker with 
- format 'dd/MM/yyyy'

2. Start entering a date: '01'

3. The cursor is still before the "/", so press "/" key

## Expected behavior

Component stay focused if user enters an invalid character

## Actual behavior

Component is loosing focus

**Comment by dmtrKovalenko** [comment]
Provide a way to reproduce it

**Comment by Toub** [comment]
Sorry, the bug was due to "Firefox developer tools" responsive mode.
