### ISSUE TITLE
Global overrides support missing

### ISSUE THREAD

**Issue by marcusjwhelan** [mui-org/material-ui-pickers#1356]
**Is your feature request related to a problem? Please describe.**
Trying to add @media change width of items or text size depending on screen size. One size
does not fit all. 

**Describe the solution you'd like**
Would be nice to have a list of CSS items to build off of. Currently in the docs there are only
a few and some don't even work, for instance `MuiPickersModal: dialogAction` options do not work currently with material-ui 4.4.3

**Describe alternatives you've considered**
It would be nice not to have to copy my entire custom theme just to add a couple overrides. Tried just having the Overrides in and it reset all my settings on top of that one element. So I had to copy and paste my entire custom theme into another file and then paste the overrides in there for it to work.

**Comment by marcusjwhelan** [comment]
holy cow batman. Had to uninstall. no way to customize easily

**Comment by spudcud** [comment]
I also ran into the issue that `MuiPickersModal: dialogAction` doesn't work. It is in the samples but no luck. You have to override MuiButton directly in order to get it to change.

**Comment by oliviertassinari** [comment]
This is also the same issue as #1340 at the difference that only point 2. is required to solve the problem. Given that a couple of style sheets already have a name, it's about a systematized solution.

On the documentation side of the CSS overrides, relying on the infrastructure of the core would solve the problem, hence it's a matter of advancing https://github.com/mui-org/material-ui/issues/19706.

**Comment by Philipp91** [comment]
Side question: Is this the right way to import the type for the overrides?

```
import {MuiPickersOverrides} from '@material-ui/pickers/src/typings/overrides';
                                                        ^^^
```

**Comment by dmtrKovalenko** [comment]
Must be without src

**Comment by Philipp91** [comment]
Well then it complains: `TS2307: Cannot find module '@material-ui/pickers/typings/overrides'.`

So perhaps you need to add an export?

**Comment by oliviertassinari** [comment]
> So perhaps you need to add an export?

@Philipp91 For this matter, please see #1874.

**Comment by dmtrKovalenko** [comment]
It is fixed already and both props and css overrides available as for v4 alpha
