### ISSUE TITLE
Today button returns current seconds

### ISSUE THREAD

**Issue by zsid** [mui-org/material-ui-pickers#1357]
![](https://giphy.com/gifs/time-clock-konczakowski-d3yxg15kJppJilnW)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  v3.2.7       |
| Peer library         | date-fns        |  |

## Steps to reproduce
Hi,

When we enter time, the input is usually having the seconds as `00`. I also couldn't find an option to show seconds (we don't need that feature really 😄).

What is happening now is we are very particular to always having `00` as the seconds in our times. The only place when that is happening is when the user clicks `today` which I believe returns `new Date()` and that has whatever seconds we currently have at the moment.

## Expected behavior
* Is it possible to have `today` button to return the current date and time with `00` seconds since when we manually enter date/time it is always `00` seconds.

Keep up the good work and thanks!

(PS: I hope my gif has loaded)

**Comment by dmtrKovalenko** [comment]
Fixed in v4 already
