### ISSUE TITLE
KeyboardDateTimePicker allows Keyboard interaction if set readOnly

### ISSUE THREAD

**Issue by BGehrels** [mui-org/material-ui-pickers#1359]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.7 |
| material-ui          | 4.4.3  |
| React                | 16.10.1 |
| Browser              | Firefox 69.0.3|
| Peer library         | moment |

## Steps to reproduce

1. Render a KeyboardDateTimePicker
```
      <KeyboardDateTimePicker
        value={moment('2019-10-17T18:30')}
        key={field.code}
        label="Label *"
        disablePast
        ampm={false}
        format="DD.MM.YYYY HH:mm"
        readOnly={true}
        variant="inline"
      />
```
2. Klick into the Text field
3. Hit Delete Key

## Expected behavior

The field is locked and can't be edited

## Actual behavior
The fields content can be edited

## Workaround
also add
```
        disabled={true}
```
While the existence of this is documented, the destinction between readOnly and disabled is not really clear from the documentation.

**Comment by grachet** [comment]
Same problem but disabled={true} change the bottom border style

**Comment by ilbrando** [comment]
I'm experiencing the same. Great components by the way :-)

**Comment by oleksiydubovykTR** [comment]
Same for all the three Keyboard* components. It disables the icon, but not editing the input value. Basically it only applies readonly to the container but not the underlying input.
Related question on SO: https://stackoverflow.com/questions/58098407/readonly-is-not-applying-for-input-field-of-keyboarddatepicker-of-material-ui-in

**Comment by CristianoYL** [comment]
My temporary solution is adding this additional prop to KeyboardDatePicker `inputProps={{ readOnly: <yourReadOnlyProp> }}`
