### ISSUE TITLE
onChange called when opening the picker 

### ISSUE THREAD

**Issue by eliseidanciu** [mui-org/material-ui-pickers#1362]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.2.7    |
| material-ui                 |     4.5.1    |
| React                          |   16.8.6    |
| Browser                      |  chrome  |
| Peer library                 |  moment 2.24.0  |

## Steps to reproduce

1. set initial date to null
2. disable today date
3. set prop variant="inline"
4. click on the datepicker to open it (don't select a date)

## Expected behavior

TextField remains empty until a date is selected

## Actual behavior

onChange is called passing the pre-selected date as a parameter (behaviour is similar to onOpen prop)

## Live example
https://codesandbox.io/s/old-moon-853mg

**Comment by netcoding87** [comment]
Funny, yesterday we encountered the same issue. But not with setting the `shouldDisableDate`. Instead we set the `maxDate` property to a date in the past.

### Live example
[https://codesandbox.io/s/objective-proskuriakova-3qfnh](https://codesandbox.io/s/objective-proskuriakova-3qfnh)

**Comment by YunitsynNikita** [comment]
Same issue

**Comment by YunitsynNikita** [comment]
This is the same post https://github.com/mui-org/material-ui-pickers/issues/1300, but still... Can we just open picker without selecting first allowed date?

**Comment by dmtrKovalenko** [comment]
@YunitsynNikita no. If your date is disabled we cannot render it as selected.
