### ISSUE TITLE
Minimum date displayed

### ISSUE THREAD

**Issue by kodermax** [mui-org/material-ui-pickers#1363]
**Is your feature request related to a problem? Please describe.**
I would like to see an option that would set the ability to see the date below that set when the modal window was opened. That is, if I set 1970, then I will see this date first, but I can also choose a date below this.

**Describe the solution you'd like**
This option is similar to minDate, but need something like minDisplayDate option

**Comment by dmtrKovalenko** [comment]
I don’t understand. MinDate will not display dates before

**Comment by kodermax** [comment]
This means that when I open the date picker I want to see the screen starting in 1960, not 1905
![image](https://user-images.githubusercontent.com/590985/75990996-d10db380-5f06-11ea-82a7-40fe351bc678.png)

**Comment by dmtrKovalenko** [comment]
Use `minDate`

**Comment by kodermax** [comment]
This will result in the user being unable to select a date less than minDate. I just want him to be able to choose a date less than 1960
