### ISSUE TITLE
Localized picker

### ISSUE THREAD

**Issue by empav** [mui-org/material-ui-pickers#1367]
Guys, what's the correct way to translate the picker into another language different than english?
Tried to import @date-fns/locale/it and used MuiPickersUtilsProvider onto the root of my app but calendar doesn't change. I don't need a dropdown to select a lang, I just need the calendar to show up in a different language.

`
<MuiPickersUtilsProvider utils={DateFnsUtils} locale={itLocale}>
<App />
</MuiPickersUtilsProvider>
`

**Comment by sclavijo93** [comment]
@epavan did you get this to work?

**Comment by dmtrKovalenko** [comment]
This should be enough. Isn’t it?
