### ISSUE TITLE
Infinite loop on Firefox ESR 52.8.0

### ISSUE THREAD

**Issue by eduleite** [mui-org/material-ui-pickers#1370]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.7 |
| material-ui          | 4.5.2 |
| React                | 16.11.0 |
| Browser              | Firefox ESR 52.8.0 |
| Peer library         | date-fns: 2.6.0, @date-io/date-fns: 1.3.11  | 

## Steps to reproduce

See this codesandbox: https://codesandbox.io/s/laughing-haibt-p8uuk

When run on chrome, the calendar popup opens fine, but on this specific version of Firefox used in my company, the browser becomes unresponsive and hangs.

## Expected behavior

I Expect the popup to open.

## Actual behavior

The browser hangs.

## Live example

https://codesandbox.io/s/laughing-haibt-p8uuk

**Comment by dmtrKovalenko** [comment]
Already fixed in v4-alpha👨‍🏭
