### ISSUE TITLE
KeyboardDatePicker cannot infer mask on using moment localized format 

### ISSUE THREAD

**Issue by sergiohgz** [mui-org/material-ui-pickers#1374]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/iTzWLKkXTyf3a/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.7 |
| material-ui          | 4.5.2 |
| React                | 16.11.0 |
| Browser              | All |
| Peer library         | moment@2.24.0 |

## Steps to reproduce

1. Use `MuiPickersProvider` with utils from `@date-io/moment`
2. Define a `KeyboardDatePicker` with `format="L"`
3. Try to write the date, only one char is write down

## Expected behavior

The mask inferred should be based on transforming `L` moment format with the locale.

## Actual behavior

Currently, the function [`makeMaskFromFormat`](https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/_helpers/text-field-helper.ts#L136-L138) takes the string from format (in this case, moment.js `L` format) and replace every character (ignoring case) for a digit (in this case, only one char).
This cannot scale because cannot transform localized format into their real form.
Examples of different formats with their mask:

| Locale       | Format        | Mask          |
|------------- |---------------|---------------|
| English (US) | `MM/DD/YYYY`  | `__/__/____`  |
| Spanish      | `DD/MM/YYYY`  | `__/__/____`  |
| Danish       | `DD.MM.YYYY`  | `__.__.____`  |
| Hungarian    | `YYYY.MM.DD.` | `____.__.__.` |
| Arabic       | `YYYY/MM/DD`  | `____/__/__`  |

## Live example

[![Edit @material-ui/pickers moment format L mask issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/material-uipickers-playground-y630b?autoresize=1&fontsize=14&view=preview)

**Comment by matiasbuildops** [comment]
This is replicated with Luxon, as well.

**Comment by ImADrafter** [comment]
+1 I was trying to find a workarround, but it seems impossible for the picker to deduce format on your locale 😐

**Comment by dmtrKovalenko** [comment]
Fixed in v4
