### ISSUE TITLE
DatePicker is focused when date is null

### ISSUE THREAD

**Issue by arve0** [mui-org/material-ui-pickers#1377]
![datepicker focused](https://user-images.githubusercontent.com/4810521/68032390-e905ca00-fcbd-11e9-9704-bb7a5e5c8386.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.7       |
| material-ui          |   4.4.3      |
| React                |       16.8.6  |
| Browser              |     latest chrome, safari, firefix    |
| Peer library         |    date-fns     | 2.0.0-beta.2 |

## Steps to reproduce

1. click on *Select date*
2. cancel date input
3. date picker is now focused

```jsx
import React, { useState } from "react";
import DateFnsUtils from "@date-io/date-fns"; // choose your lib
import {
  DatePicker,
  TimePicker,
  DateTimePicker,
  MuiPickersUtilsProvider
} from "@material-ui/pickers";

function App() {
  const [selectedDate, handleDateChange] = useState(null);

  return (
    <MuiPickersUtilsProvider utils={DateFnsUtils}>
      <DatePicker
        label="Select date"
        value={selectedDate}
        onChange={handleDateChange}
      />
    </MuiPickersUtilsProvider>
  );
}

export default App;
```
## Expected behavior

`DatePicker` should not have focus after cancelling popup.

## Actual behavior

`DatePicker` focuses after cancelling popup.

## Live example

https://codesandbox.io/s/material-ui-pickers-usage-demo-tzdu9

**Comment by dmtrKovalenko** [comment]
Fixed in v4
