### ISSUE TITLE
Import declaration conflicts in TypeScript 3.7

### ISSUE THREAD

**Issue by mfellner** [mui-org/material-ui-pickers#1378]
In TypeScript 3.7, a breaking change is introduced affecting local and imported type declarations:

https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-rc/#local-and-imported-type-declarations-now-conflict

This breaks type declarations like this one (https://github.com/mui-org/material-ui-pickers/blob/v3.2.7/lib/src/index.ts):

```ts
import { MaterialUiPickersDate } from './typings/date';

export type MaterialUiPickersDate = MaterialUiPickersDate;
```

Error:
```
Import declaration conflicts with local declaration of 'MaterialUiPickersDate'
```

The solution is to simply re-export the type:

```ts
export  { MaterialUiPickersDate } from './typings/date';
```

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| typescript |     3.7.1-rc    |
| @material-ui/pickers |     3.2.7    |
| material-ui          |    4.5.2     |
| React                |    16.11.0     |
| Browser              |     Chrome    |
| Peer library         |   date-fns@2.6.0      |  |

## Steps to reproduce

1. Install typescript@3.7.1-rc
2. Try to compile the code or lint it with ts-lint.

## Expected behavior

Code compiles OK.

## Actual behavior

Error:
```
Import declaration conflicts with local declaration of 'MaterialUiPickersDate'
```

**Comment by LoicMahieu** [comment]
I confirm the issue with 3.7.2

**Comment by mvestergaard** [comment]
Has anyone got any ideas of a workaround for this problem in the meantime? We'd really like to upgrade to TS 3.7 asap.

**Comment by mvestergaard** [comment]
Found a workaround. Importing from `@material-ui/pickers/DatePicker/DatePicker` instead of `@material-ui/pickers/DatePicker` avoids this issue.

**Comment by gaelollivier** [comment]
> Found a workaround. Importing from `@material-ui/pickers/DatePicker/DatePicker` instead of `@material-ui/pickers/DatePicker` avoids this issue.

@mvestergaard That seems to do it, thanks for the workaround!

**Comment by blitzard7** [comment]
@mvestergaard that worked for me, too. Thanks!

**Comment by dmtrKovalenko** [comment]
WIP

**Comment by deeptikanta** [comment]
node_modules/@material-ui/core/Portal/Portal.d.ts:2:10 - error TS2440: Import declaration conflicts with local declaration of 'PortalProps'.

2 import { PortalProps } from '../Portal';
getting a error in this.

**Comment by oliviertassinari** [comment]
@deeptikanta Do you have a reproduction with v4.0.0-alpha.5?

**Comment by deeptikanta** [comment]
@oliviertassinari no
