### ISSUE TITLE
DatePicker Static and using webpack the calendar dates are reversed

### ISSUE THREAD

**Issue by gfiury** [mui-org/material-ui-pickers#1385]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.2.7    |
| material-ui          |     4.5.2    |
| React                |     16    |
| Chrome              |   78      |
| @date-io/moment         |     1.3.11    |
| webpack-cli         |     3.3.9    |
| webpack-dev-server|     3.8.2    |
| webpack |     4.40.2    |

## Steps to reproduce
import { DatePicker, MuiPickersUtilsProvider } from "@material-ui/pickers";
import MomentUtils from '@date-io/moment';
```
<MuiPickersUtilsProvider utils={MomentUtils}>
                    <DatePicker
                        autoOk
                        variant="static"
                        openTo="date"
                        value={new Date()}
                        onChange={this.props.changeDate}
                        minDate={new Date()}
                    />
</MuiPickersUtilsProvider>
```

## Expected behavior

As expected of any calendar, the numbers are shown from left to right, even the arrows are reversed.

## Actual behavior

![Calendar Reverse](https://user-images.githubusercontent.com/20029282/68395838-47fc9080-014f-11ea-9e37-29549b18e058.png)

## Changing the Calendar to non static works fine

```
<MuiPickersUtilsProvider utils={MomentUtils}>
                    <DatePicker
                        autoOk
                        openTo="date"
                        value={this.props.date}
                        onChange={this.props.changeDate}
                        shouldDisableDate={this.props.disableDates}
                        minDate={new Date()}
                    />
</MuiPickersUtilsProvider>
```

![Calendar not static](https://user-images.githubusercontent.com/20029282/68395924-682c4f80-014f-11ea-89cc-99fe782dd654.png)

**Comment by dmtrKovalenko** [comment]
😱 do you have an rtl mode enabled? Please make a reproduction with codesandbox.

**Comment by dmtrKovalenko** [comment]
Not reproducing https://codesandbox.io/embed/confident-engelbart-etmf7?codemirror=1

Check your theme and jss config for rtl
