### ISSUE TITLE
When a date is clicked, add that to the state without clicking OK button in the date picker

### ISSUE THREAD

**Issue by Zabi-Progton** [mui-org/material-ui-pickers#1386]
_First of all this is one beautiful component to use in any application that follows the material guidelines._

When I click the date/time textfield is clicked, I want that date to be selected instantly without clicking on the OK button below, this would save my user one click, and I wanted to know if this can be implemented. Lmk

**Comment by dmtrKovalenko** [comment]
`autoOk` Will do that for you

**Comment by joelvh** [comment]
@dmtrKovalenko I've been using this component for over a year and we just enabled `autoOk` and it works with the inline date picker (using v2.2.4), but it doesn't work with the modal one. Any idea why it wouldn't?

**Comment by dmtrKovalenko** [comment]
Ohh 😮 it’s pretty old version. I don’t remember
