### ISSUE TITLE
Change copy "Invalid Date Format" for KeyboardDatePicker

### ISSUE THREAD

**Issue by alan345** [mui-org/material-ui-pickers#1387]
Is there a feature where we can change the copy of this error message `Invalid Date Format` or just hide it?
![image](https://user-images.githubusercontent.com/15246526/68703171-ec5f4800-053e-11ea-8525-c66ef87cd0a7.png)
for KeyboardDatePicker:  https://material-ui-pickers.dev/api/KeyboardDatePicker
Thanks!!

**Comment by dmtrKovalenko** [comment]
What do you mean by copy?

**Comment by DoWhileGeek** [comment]
@dmtrKovalenko copy === text

**Comment by alan345** [comment]
thanks @DoWhileGeek!

Is there a feature where we can change the text of this error message `Invalid Date Format` or just hide it?

**Comment by alan345** [comment]
any idea @dmtrKovalenko ?
Thanks for your help!

**Comment by dmtrKovalenko** [comment]
Just pass a prop `helperText` it will change the message. Also `error` prop will render red error state. The same as core mui input

**Comment by alan345** [comment]
thanks @dmtrKovalenko !

```
       <KeyboardDatePicker
              helperText={''} />
```
