### ISSUE TITLE
KeyboardDatePicker looses focus on each keystroke when TextFieldComponent prop set to non-trivial component

### ISSUE THREAD

**Issue by robert-skarzycki** [mui-org/material-ui-pickers#1388]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/14afmHqKZ3ctsk/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.7      |
| material-ui          |  4.6.1       |
| TypeScript           |  3.7.2      |
| React                |   16.8.4      |
| Browser              |   Chrome 78     |
| Peer library         |   moment      |

1. Have a KeyboardDatePicker and assign something more "complex" to `TextFieldComponent` prop - for instance you want to have a  `TextField` from `@material-ui/core`, but with `fullWidth=true` (see https://codesandbox.io/s/awesome-elion-f6ge5 - "wrapped" scenario)
2. Start typing a date with keyboard.
3. After each keystroke, input looses focus.

## Expected behavior
I expect same behavior when I just pass "bare" `TextField` component to the `TextFieldComponent` prop (see "Just TextField" scenario on https://codesandbox.io/s/awesome-elion-f6ge5)

## Actual behavior
When `TextFieldComponent` receives something more "complex" than just "bare" component, it looses focus for every keystroke.

## Live example

https://codesandbox.io/s/awesome-elion-f6ge5

**Comment by dmtrKovalenko** [comment]
Solution is pretty easy. https://codesandbox.io/s/funny-violet-nqjgn
The problem here is that you are creating **new textfield** on each render.
