### ISSUE TITLE
KeyboardDatePicker consumes only 1 digit for day and month when typing with keyboard

### ISSUE THREAD

**Issue by robert-skarzycki** [mui-org/material-ui-pickers#1389]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/d2Zkc4CAss8iXy4U/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.7     |
| material-ui          |     4.6.1    |
| TypeScript           |  3.7.2       |
| React                |   16.8.4      |
| Browser              |   Chrome 78      |
| Peer library         |    moment     |  |

## Steps to reproduce

1. Have a `KeyboardDatePicker` with some localized format.
2. Type a date with keyboard, e.g. Christmas Eve, i.e. (in US format) 12/24/2019 (you type without slashes, so actually type `12242019`).
2. Notice that instead of `12/24/2019`, you receive `1/2/2420`, because apparently picker allows only one digit for day/month.

## Expected behavior

Maybe it is debatable, because day and month may have one or two digits (e.g. for 3rd January the format is `1/3/2019`), but I'd rather expect from `KeyboardDatePicker` to expect two digits for day and month and allowing to jump to the next part of the date with tab or right arrow.

## Actual behavior
`KeyboardDatePicker` "consumes" only one digit for day and month, so instead of `12/24/2019`, you receive `1/2/2420`.

## Live example
https://codesandbox.io/s/festive-jennings-kkwo4

**Comment by dmtrKovalenko** [comment]
It is a known defect. For now you can use custom `rifmFormatter` if it is critical. Or use 2-digit formats

**Comment by robert-skarzycki** [comment]
@dmtrKovalenko - can we put such a "known issues" / "FAQ" list on the documentation page?

**Comment by dmtrKovalenko** [comment]
Yeah, if you could open a PR and even provide workaround it will be super helpfull
