### ISSUE TITLE
Firefox 57.0.4 ScrollIntoViewOptions error

### ISSUE THREAD

**Issue by brxkensmile** [mui-org/material-ui-pickers#1390]
In FireFox 57.0.4 on year selection view I got this:

>TypeError: 'block' member of ScrollIntoViewOptions 'center' is not a valid value for enumeration Scroll Logical Position.

@material-ui/pickers: "^3.2.7",
date-fns: "^2.7.0",
react: "^16.11.0",

**Comment by dmtrKovalenko** [comment]
Should be fixed in 3.0.8
