### ISSUE TITLE
Wrong german time format

### ISSUE THREAD

**Issue by Spenhouet** [mui-org/material-ui-pickers#1391]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.7      |
| material-ui          |   4.6.1      |
| React                |     16.8.2    |
| Browser              |    Chrome (electron)     |
| Peer library         |    date-fns     |  |

## Steps to reproduce

1. Change locale to german ("de")
2. Look at time components

## Expected behavior

The time components show the time in the 24h format with `ampm = false`.

## Actual behavior

The time components show the time in the AM/PM format with `ampm = true`.

## Additional Information

The AM/PM format does not exist in Germany. Just translating AM/PM into German is just wrong.
In Germany only the 24h format is used.
I would expect the localization to also automatically change the `ampm` setting of all components to `false`.

If this is not possible at least add a global `ampm` option to the `MuiPickersUtilsProvider`.

**Comment by dmtrKovalenko** [comment]
You must set ampm manually

**Comment by Spenhouet** [comment]
@dmtrKovalenko So you don't care if the localization isn't working?

**Comment by dmtrKovalenko** [comment]
I know about this problem, but now there is no way to determine 12h/24h mode only from localization perspective

**Comment by Spenhouet** [comment]
That is why I suggested that there could be a `ampm` option in the `MuiPickersUtilsProvider`. This could than be used as default value for the components.
Than it is only necessary to implement the `ampm` check once instead of for every component.
