### ISSUE TITLE
Click on disabled dates

### ISSUE THREAD

**Issue by ghost** [mui-org/material-ui-pickers#1396]
![](https://media0.giphy.com/media/12mVjLI5Pgyh3O/giphy.gif)

**Is your feature request related to a problem? Please describe.**
Yes, it's annoying not being able to get a response or something to happen when clicking on a greyed out/disabled date.

**Describe the solution you'd like**
Add a prop of some sort that allows you to add functionality when you click on a disabled date e.g. when you click on a date, a popup comes up or something is logged into the console.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dmtrKovalenko** [comment]
Use custom day renderer https://material-ui-pickers.dev/demo/datepicker#customization

**Comment by ghost** [comment]
Thanks for letting me know this exists. Do you have a basic solution that does something (e.g. message in console) when a date from 'shouldDisableDate' is clicked? (it's greyed out)
