### ISSUE TITLE
Missing type MaterialUiPickersDate when Update from 3.2.6 to v3.2.8

### ISSUE THREAD

**Issue by maikeledev** [mui-org/material-ui-pickers#1399]
##  Steps to reproduce

Missing type MaterialUiPickersDate when Update from 3.2.6 to v3.2.8

## Actual behavior

@material-ui/pickers has no exported member 'MaterialUiPickersDate'

It seems you removed the export statement, but didn’t add any comment in the release
export declare type MaterialUiPickersDate = MaterialUiPickersDate

**Comment by lytc** [comment]
```js
import { MaterialUiPickersDate } from '@material-ui/pickers/typings/date';
```

**Comment by dmtrKovalenko** [comment]
You should not use it. It is very internal thing, use the type of linked adapter. Date, Moment, etc..

**Comment by ruohola** [comment]
@dmtrKovalenko How to type annotate the parameter of a function then that is passed as the `onChange` prop of `KeyboardDatePicker`?
