### ISSUE TITLE
Missing "onClear" prop on type definitions

### ISSUE THREAD

**Issue by whitehatgg** [mui-org/material-ui-pickers#1400]
'onClear' prop is missing on the type definitions

`TS2322: Type '{ value: number | null | undefined; variant: "dialog"; clearable: boolean | undefined; label: string | null; renderDay: (day: any, selectedDate: any, dayInCurrentMonth: any, dayComponent: any) => any; ... 13 more ...; InputProps: { ...; }; }' is not assignable to type 'IntrinsicAttributes & DateValidationProps & BasePickerProps & { variant?: "inline" | "static" | "dialog" | undefined; } & ... 4 more ... & { ...; }'.
  Property 'onClear' does not exist on type 'IntrinsicAttributes & DateValidationProps & BasePickerProps & { variant?: "inline" | "static" | "dialog" | undefined; } & ... 4 more ... & { ...; }'.`

**Comment by oliviertassinari** [comment]
@gonzrb Please provide a minimal reproduction test case with v4.0.0-alpha. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/gifted-wilbur-g4bgc?file=/src/App.jsx) _may_ be a good starting point. Thank you!
