### ISSUE TITLE
Is there any props for not allowing dates based on the criteria of minDate and maxDate?

### ISSUE THREAD

**Issue by CarlosOrozc** [mui-org/material-ui-pickers#1401]
Is there any props for not allowing dates based on the criteria of minDate and maxDate?

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |3.1.2         |
| material-ui          |   4.1.3     |
| React                |    16.8.6     |
| Browser              |   Chrome      |

**Comment by dmtrKovalenko** [comment]
Please be more descriptive if you are opening bug. If you need to ask questions— use stackoverflow
