### ISSUE TITLE
[TimePicker] customized time picker

### ISSUE THREAD

**Issue by AbdullahElrubi** [mui-org/material-ui-pickers#1402]
Hello, 
I've been searching for this specific time picker but I couldn't fine any near example for it and want it to be among this package if it's possible.

here's a screenshot for it.
![image](https://user-images.githubusercontent.com/45941037/69494169-ed8a6080-0ec0-11ea-9360-058f056c29af.png)

**Comment by AbdullahElrubi** [comment]
is there're any updates ?

**Comment by dmtrKovalenko** [comment]
No, I am sorry but we will not add such displaying of time picker. Right now I am working on redesign of date/time pickers but timepicker will stay a "clock".

**Comment by oliviertassinari** [comment]
@AbdallahElroby You could leverage the autocomplete until we find a good solution for desktop.

**Comment by AbdullahElrubi** [comment]
@oliviertassinari any Idea on how I should use it.
Thanks

**Comment by dmtrKovalenko** [comment]
Actually it should not be a problem. Just create 3 dropdowns with different values. 
1st) hours 01-12
2nd) minutes 01-59
3rd) am/pm 

and just construct your date object with some methods for. E.g. for `date-fns` it will be `setHours` , `setMinutes` and just a little bit code for set am/pm: just settings 12:00 or 00:00 based on user choise
