### ISSUE TITLE
[TimePicker] Minutes "snap back" for small changes in iOS

### ISSUE THREAD

**Issue by wmrockwood** [mui-org/material-ui-pickers#1403]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    ^3.2.3     |
| material-ui          |    ^4.3.1     |
| TypeScript           |     3.5.3    |
| React                |    ^16.9.0     |
| Browser              |     Safari 13 (and 12)    |
| Peer library         |    date-fns     | 

## Steps to reproduce

1. navigate to https://material-ui-pickers.dev/demo/datetime-picker in mobile Safari
2. select date and hour to get to minutes
3.make a small adjustment in time (typically 1 to 3 minutes) in either direction

## Expected behavior

Picker displays selected time

## Actual behavior

The selection immediately jumps back, either to the previously selected time or another nearby value.

## Live example

![RPReplay_Final1574715579](https://user-images.githubusercontent.com/4448062/69579975-94dec480-0fa1-11ea-83a8-fd9064662d79.gif)

**Comment by NGuldager** [comment]
Any progress or comments on this issue?
This is an issue we're experiencing as well.

**Comment by oliviertassinari** [comment]
I couldn't reproduce, does it happen on https://next.material-ui-pickers.dev/demo/timepicker too?

**Comment by NGuldager** [comment]
Just reproduced using an iPhone 11 on iOS 13.5.1 with the above link.
Especially noticable when you drag the selection around and release.

**Comment by oliviertassinari** [comment]
@NGuldager I couldn't reproduce, however, there is an `event.preventDefault()` issue. We shouldn't be able to scroll the container.

![Jul-06-2020 17-04-37](https://user-images.githubusercontent.com/3165635/86608451-dfe69e80-bfaa-11ea-9d88-0f27aec38a79.gif)

**Comment by oliviertassinari** [comment]
Ok, my bad, I could also reproduce, I'm opening a different issue for the above.
