### ISSUE TITLE
Can I change KeyboardDatePicker month and year label format?

### ISSUE THREAD

**Issue by IRanwa** [mui-org/material-ui-pickers#1404]
<img width="391" alt="Hi-Job Business 2019-11-26 14-46-47" src="https://user-images.githubusercontent.com/43082658/69608407-628aa100-104d-11ea-98d3-a4c36dc4eef8.png">

Is there a way to change this month year format to something like 11月2019年?

**Comment by Tugsbileg** [comment]
> <img alt="Hi-Job Business 2019-11-26 14-46-47" width="391" src="https://user-images.githubusercontent.com/43082658/69608407-628aa100-104d-11ea-98d3-a4c36dc4eef8.png">
> 
> Is there a way to change this month year format to something like 11月2019年?

can you change this ?

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.dev/guides/formats

**Comment by Tugsbileg** [comment]
> https://material-ui-pickers.dev/guides/formats
it's not 
i change calendar format
pls HLP

**Comment by IRanwa** [comment]
> > https://material-ui-pickers.dev/guides/formats
> > it's not
> > i change calendar format
> > pls HLP

![Screenshot](https://user-images.githubusercontent.com/43082658/71081858-0af7d500-21b6-11ea-9264-3125f10c9909.PNG)

I was able to change the format. This is how I did it. I used MomentUtils not DateFnsUtils.

`import "moment/locale/ja";
import MomentUtils from "@date-io/moment";`

```
class LocalizedUtils extends MomentUtils {
  getCalendarHeaderText(date){
    return date.format("MM月YYYY年");
  }
}
```

```
<MuiPickersUtilsProvider locale="ja" utils={LocalizedUtils}>
<KeyboardDatePicker
     format="MM月DD日"
     //value={filterData.startDate}
     //onChange={this.changeStartDate}
    cancelLabel="キャンセル"
    okLabel="確定"
    />
</MuiPickersUtilsProvider> 
```

**Comment by IRanwa** [comment]
> https://material-ui-pickers.dev/guides/formats

Thank a lot for the information.
