### ISSUE TITLE
DateTimePicker minutes disappear in Safari 13

### ISSUE THREAD

**Issue by ryub3n** [mui-org/material-ui-pickers#1405]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    ^3.2.8     |
| material-ui          |    ^4.6.1     |
| TypeScript           |         |
| React                |    ^16.8.6     |
| Browser              |   Safari 13.0.3 (iPadOS 13.2.3/ MacOS Mojave 10)     |
| Peer library         |   moment ^2.24.0 & moment-timezone ^0.5.27     |  |

## Steps to reproduce

1. Navigate to https://material-ui-pickers.dev/demo/datetime-picker in Safari
2. Select date and hour to get to minutes

## Expected behavior

Should seamlessly show the minutes selection view with the numbers.

## Actual behavior

When the minutes view opens the numbers disappear and reappear when you change the minute.
Confirmed this occurs Safari 13.0.3 for iPadOS 13.2.3 and MacOS Mojave 10. Works on iOS though. Oddly the inline variant works fine.

## Live example
![DateTimePickerSafari](https://user-images.githubusercontent.com/24279903/69637645-13f5fa80-107f-11ea-9aec-9245a636ef63.gif)

**Comment by banada** [comment]
I can reproduce this issue on Chrome and Safari on iPad.

**Comment by mcabs3** [comment]
Is there any progress on this issue?
