### ISSUE TITLE
Entering a date before 1884 causes an extra minute to be added to DateTimePicker

### ISSUE THREAD

**Issue by Ansari-Tech** [mui-org/material-ui-pickers#1408]
#789  Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.8  |
| material-ui          |4.3.0         |
| React                | 16.9.0        |
| Browser              |Chrome  78.0.3904.97         |

## Steps to reproduce

1. Type 1111/11/11 11:11 into a DateTimePicker
2. Watch as it magically becomes 1111:11/11 11:12
3. Change year to 2009 and see that the error stays 

## Expected behavior
Entering 1111/11/11 11:11 (or any date before 1884) should not add an extra minute to the DateTimePicker. 

## Actual behavior
Entering 1111/11/11 11:11 (or any date before 1884) adds an extra minute to the inputted time. This can be an issue if the user accidentally enters a date before 1884, and then corrects it, leaving the erroneous extra minute. 

## Live example
https://material-ui-pickers.dev/demo/datetime-picker

**Comment by dmtrKovalenko** [comment]
Which library is used?

**Comment by dmtrKovalenko** [comment]
I can’t reproduce it on documentation. So I think it is a bug of specific peer library you are using
