### ISSUE TITLE
KeyboardDatePicker making wrong mask for moment's Long Date Formats

### ISSUE THREAD

**Issue by yagotome** [mui-org/material-ui-pickers#1410]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.8     |
| material-ui          |     4.6.1    |
| TypeScript           |     3.7.2    |
| React                |     16.8.6    |
| Browser              |    Chrome v78     |
| Peer library         |    `moment@2.24.0` and `@date-io/moment@1.3.11`    |

## Steps to reproduce

1. Use `KeyboardDatePicker` with _moment_ and passing prop `format="L"` ([moment's Long Date Format](https://momentjs.com/docs/#/customization/long-date-formats/))
2. Try to type some date 

## Expected behavior

Getting input filled by the typed date based on a mask according to `L` format, i.e., `__/__/____`.

## Actual behavior

The mask is `_`, therefore it is allowed to type only 1 digit, such as defined here:

https://github.com/mui-org/material-ui-pickers/blob/6a83da1f14253a1f55f17023b7f1becff6493758/lib/src/_helpers/text-field-helper.ts#L137

## Live example

https://codesandbox.io/s/material-ui-pickers-usage-demo-2n4df?fontsize=14&hidenavigation=1&theme=dark

**Comment by dmtrKovalenko** [comment]
Pass mask manually
