### ISSUE TITLE
UMD support for latest version of Material-ui

### ISSUE THREAD

**Issue by lyvyu** [mui-org/material-ui-pickers#1411]
Hey Guys, 

I tried to use umd version with latest version of material-ui package and it's not working at all. It tries to load required packages like `@material-ui/core/Typography, @material-ui/core/styles...etc` but it fails.

Do you plan to add UMD support for latest version of material-ui ?! 
Is there anything I can do to make it work ?! 

Thanks in advance !!!

**Comment by dmtrKovalenko** [comment]
Hey! Yes it will be cool if you can make a PR that matches our mud version to the core names with our rollup build system

**Comment by lyvyu** [comment]
I wish I could help but I think I need help myself, cannot make it work at all !!! :D 
Tried a couple of things but none of thos worked.

Any ideas how to make it running ?!

**Comment by dmtrKovalenko** [comment]
Already done.
