### ISSUE TITLE
keyboard pickers: InputProps or pattern prop

### ISSUE THREAD

**Issue by Forfold** [mui-org/material-ui-pickers#1412]
**Is your feature request related to a problem? Please describe.**
It would be nice to have an `InputProps` property for the keyboard picker components similar to how `InputAdornmentProps`, `KeyboardButtonProps`, etc exists. I have my `mask` prop set, but I am also trying to set a `pattern` prop on this component, but it doesn't seem like it is passed down to the root element.

**Describe the solution you'd like**
Either an `InputProps` prop or a `pattern` prop. `InputProps` would likely be more future-proof though.

**Comment by Forfold** [comment]
Is this project still being maintained?

**Comment by dmtrKovalenko** [comment]
Yes, please read the docs one more time. all the props are passing down to [TextField](https://material-ui.com/components/text-fields/#textfield)
