### ISSUE TITLE
Problme to get the year, day and month selected by the user

### ISSUE THREAD

**Issue by RuiGuilherme** [mui-org/material-ui-pickers#1413]
I use this method: 
```javascript
onChange={async date => {
    const UserDate = new Date(date);
    console.log(UserDate.getFullYear(), UserDate.getMonth(), UserDate.getDay());
}}
```

If I enter 1999 (Year) - 01(Month) - 06(Day), the return I have from log is:

> 1999 0 3

**Comment by dmtrKovalenko** [comment]
Please give more context or provide reproduction with codesandox

**Comment by RuiGuilherme** [comment]
> Please give more context or provide reproduction with codesandox

Sorry my english: I need to send the year, month and day for a function. Follows the complete DatePicker...

```javascript
    <DatePicker
            disableFuture
            openTo="year"
            format="dd/MM/yyyy"
            views={["year", "month", "date"]}
            invalidDateMessage="Data inválida"
            onChange={async date => {
                const UserDate = new Date(date);
                const year = UserDate.getFullYear();
                const month = UserDate.getMonth();
                const day = UserDate.getDay();
                    CheckAge(year, month, day) ? await this.setState({nascimento: date}) : alert("error");
            }}
        />
```

If I enter 1999-01-06 (YYYY-MM-dd) and punt a **console.log(year, month, day)** before the CheckAge() the output is: 
> 1999 0 3

The expected was:
> 1999 01 06

**Comment by dmtrKovalenko** [comment]
This issue needs reproduction. But I am sure there is no issues
