### ISSUE TITLE
Date & Time picker is missing the date and time icon section in the dialog

### ISSUE THREAD

**Issue by Manish-Giri** [mui-org/material-ui-pickers#1419]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif)

On my windows machine, the DateTime Picker in [Components Demo](https://material-ui-pickers.dev/demo/datetime-picker) does not have the section (in the dialogbox) which consists of the **date and time icons**.  More details in screenshots below.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.2.8    |
| material-ui          |         |
| TypeScript           |         |
| React                |         |
| Browser              |    Chrome v78,  Firefox Dev Edition v71     |
| Peer library         |         |  |

## Steps to reproduce

1. Go to Components Demo and select Date & Time Picker at https://material-ui-pickers.dev/demo/datetime-picker
2. Select DateTimePicker under "Basic Usage"

## Expected behavior

The picker's dialogbox at the top should also consist of the date (calendar) and time icons, which I observed when I visited the same page on my mac machine. Screenshot -

![x](https://user-images.githubusercontent.com/11348778/70472238-c7f27f00-1a9c-11ea-83e4-0ee2bb8b67ad.png)

## Actual behavior

On my Windows machine, on both Chrome and Firefox, that section of the dialogbox is missing. Here are the screenshots. 

Light Theme -

![1a](https://user-images.githubusercontent.com/11348778/70498805-97830300-1ae5-11ea-8e6d-27878d413ccd.png)

Dark Theme -

![1b](https://user-images.githubusercontent.com/11348778/70498818-a2d62e80-1ae5-11ea-837c-6c4d14a1d909.png)

Console (if required) -

![1c](https://user-images.githubusercontent.com/11348778/70498830-acf82d00-1ae5-11ea-83ad-ce9b970bc5bf.png)

## Live example
https://material-ui-pickers.dev/demo/datetime-picker

I came across this when working with MUI Pickers [on another project](https://github.com/taskcluster/taskcluster/pull/2106#issuecomment-563436510).

**Comment by dmtrKovalenko** [comment]
This is because your window height is to small. So if tabs will appear it will require to
show scroll bar. 
But you can pass manually `showTabs={true}` to enable for any device.

**Comment by Manish-Giri** [comment]
@dmtrKovalenko I passed `showTabs={true}` to the `KeyboardDateTimePicker` component, but that didn't make any difference. The [KeyboardDateTimePicker Component API page](https://material-ui-pickers.dev/api/KeyboardDateTimePicker) lists a `hideTabs` prop, so I also used `hideTabs={false}`, but that too didn't work.

Is there something I'm doing wrong?

**Comment by dmtrKovalenko** [comment]
Then it is not overridable. Try to increase window height

**Comment by Manish-Giri** [comment]
My browser is already full screen (check screenshots above), and I'm on a 15.6" laptop. I can't increase window height anymore.

**Comment by dmtrKovalenko** [comment]
You can, in devtools. It’s not an issue so I am closing this
