### ISSUE TITLE
[question] can a InvalidDateMessage override helperText?

### ISSUE THREAD

**Issue by PedroCNunes** [mui-org/material-ui-pickers#1420]
Hi,

Is there any way to override the "helperText" when there is an invalid date? Because when I don't have a "helperText" and the user inserts an invalid format the "invalidDateMessage" appears. But when I add the "helpText" the "invalidDateMessage" never appears.

```
<KeyboardTimePicker
        className="timepicker-new-event"
        name={field.name}
        value={field.value}
        ampm={false}
        variant="dialog"
        label="Hours"
        views={["hours", "minutes"]}
        keyboardIcon={null}
        onChange={date => form.setFieldValue(field.name, date, true)}
        invalidDateMessage="Invalid Format"
        helperText="XPTO"
/>
```

Hope you can help me. Thank you in advance :)

**Comment by dmtrKovalenko** [comment]
No, passed helper text always has bigger priority.

**Comment by dmtrKovalenko** [comment]
You can use onError and show error manually passing to `heperText`
