### ISSUE TITLE
KeyboardDatePicker ignores specified format for intput

### ISSUE THREAD

**Issue by spik3r** [mui-org/material-ui-pickers#1422]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/137MDVkGCzkZvW/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.8  |
| material-ui          |  4.7.2  |
| TypeScript           |  3.8  |
| React                |  16.12 |
| Browser              | Chrome |
| Peer library         |  moment 2.24 |  |
| Peer library         |  date-io/moment 1.3.13 | 

## Steps to reproduce

1. 
Create a KeyboardDatePikcer 
```<MuiPickersUtilsProvider utils={MomentUtils}>
      <Grid container justify="space-around">
        <KeyboardDatePicker
          disableToolbar
          variant="inline"
          autoOk
          format="MMM DD, YYYY"
          margin="normal"
          id="date-picker-inline"
          label="Date picker inline"
          value={selectedDate}
          onChange={handleDateChange}
          KeyboardButtonProps={{
            "aria-label": "change date"
          }}
        />
      </Grid>
    </MuiPickersUtilsProvider>
```
2. Select a date using the Calendar widget - Should work as expected
![image](https://user-images.githubusercontent.com/5329441/70614591-84dc0b80-1c56-11ea-8af5-b996229dd49e.png)

3. Try to change the date using input - Notice how the Date gets changed to seemingly random numbers, and it's an instant error.
![image](https://user-images.githubusercontent.com/5329441/70614527-71c93b80-1c56-11ea-82a9-c71f3e6ef8f2.png)

## Expected behavior
KeyboardDatePicker should work for both Calendar widget and input regardless of date format (or at least have the option to disable the input while still being able to use the Calendar widget)

## Actual behavior
input does not work for text based date formats like `MMM DD, YYYY`  and simply pressing backspace or trying to change the date results in an error

## Live example

https://codesandbox.io/s/material-demo-l5cis

**Comment by Reshad-A** [comment]
I have had the same issue for the past couple of days and I figured a workaround I hope it helps.

I am using regular expression for refuse and rifmFormatter properties to do away with weird date formatting issue and accept month name as string.
Also for onChange I am passing an empty function instead I am using onBlur and onAccept to handleDateChange()
 
```
 public render() {
        const {
            datePickerData: {
                content: { reference, validationRules, placeHolder },
            },
            showError,
        } = this.props;

<div style={{ position: "relative" }}>
    <MuiPickersUtilsProvider utils={MomentUtils}>
      <KeyboardDatePicker
             disableToolbar={true}
             variant="inline"  
             inputVariant="outlined"  
             rifmFormatter={val=> val.replace(/[^\.\ \,\[a-zA-Z0-9_]*$]+/gi, '')}
             refuse={/[^\.\ \,\[a-zA-Z0-9_]*$]+/gi}  
             format={"MMM, DD YYYY"} 
             autoOk 
             value={this.selectedDay}
             id={`datePicker-${reference}`} 
             onChange={()=>{}}  
             onAccept={this.handleDateChange}
             onBlur={this.handleDateChange} 
              />
    </MuiPickersUtilsProvider>
</div>
};

public handleDateChange= (selectedDate:any) => {  
        let newDate=null;
        if(selectedDate===null)return;
        if(!moment.isMoment(selectedDate)){
         let el = selectedDate.currentTarget.defaultValue; 
         let elementValue = moment(el).toDate();
         newDate = elementValue;
        }else{
            newDate = selectedDate.toDate();
        }
  if(moment(this.selectedDay).format('YYYY-MM-DD')!== moment(newDate).format('YYYY-MM-DD')){
               this.selectedDay = newDate;  
           }      
    };  
```

**Comment by spik3r** [comment]
Thanks @Reshad-A I'll give that a try.

**Comment by dmtrKovalenko** [comment]
Fixed in v4

**Comment by Manshadi1359** [comment]
I tested in v4 for Jalali and not fixed.

**Comment by abhaya-sharma** [comment]
same issue , but for dd/mm/yyyy format. it throws an error for any date after the 12th of a month because for some reason it applies the logic that you cant go beyond 12 months.
