### ISSUE TITLE
Picker should open by clicking anywhere in whole input field conditionally

### ISSUE THREAD

**Issue by raza2022** [mui-org/material-ui-pickers#1423]
I just want a small feature which is that when user click on input (whole input not just calander icon) then datapicker should open, I searched it in API Documentation and issues too, but surprisingly not found anything, Yes I know I can achive it with `open` key by component but I just thougth it will be good if a single key/value pair added as `onClickOpen={true/false}` or similer like that, please be humble in response as I just started with material framework.

**Comment by dmtrKovalenko** [comment]
Umm use not KeyboardPicker
