### ISSUE TITLE
Can't adjust zIndex

### ISSUE THREAD

**Issue by sandorvasas** [mui-org/material-ui-pickers#1425]
I consider this as a bug, since it halts more complex usage of the picker. 
Simple case: we have a modal at z=2100, but whatever props I try to set, it's impossible to change the `<div role='presentation' style='z-index:1300......` container of the datepicker. Need a prop to be able to set that.

**Comment by oliviertassinari** [comment]
@sandorvasas The component uses `theme.zIndex.modal`. You can customize the value directly with the theme.
