### ISSUE TITLE
Use Popper over Popover for desktop?

### ISSUE THREAD

**Issue by developdeez** [mui-org/material-ui-pickers#1426]
Just noticed this but when date picker is opened in dropdown-like form the scroll of the page is hidden. Causes the design to shift slightly.

**Comment by oliviertassinari** [comment]
@developdeez The design shift you are referring to is related to another issue on https://github.com/mui-org/material-ui side. You can learn more about it their. In your case,  you might need to apply the `.mui-fixed` class name on the fixed or absolute positioned elements.

---

However, your feedback uncovers another interesting behavior. The full-screen version of the picker opens a dialog modal, blocking the interactions with the rest of the page are expected and the usage of the `Modal` component sounds like the best choice for mobile.

But the inline version uses it too, it blocks interactions with the rest of the page. I really think that it shouldn't on a desktop. I think that the usage of the `Popper` component would be **much** better for this use case. We have a related discussion in https://github.com/mui-org/material-ui/issues/17353 and https://github.com/mui-org/material-ui/issues/11243#issuecomment-546939897.
