### ISSUE TITLE
Calendar month change bug when selecting date of static calendar

### ISSUE THREAD

**Issue by jpodpro** [mui-org/material-ui-pickers#1428]
![Image of meme](https://i.chzbgr.com/full/7450119168/hE866DEDD/youre-getting-old)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |3.2.8|
| material-ui          |4.6.1|
| TypeScript           |n/a|
| React                |16.11.0|
| Browser              |Chrome 78, Safari 12.0.3|
| Peer library         |date-fns 2.8.1|  |

## Steps to reproduce
1. Display static calendar
2. Navigate one month before and select any date.
3. Navigate 2 months forward, then one month back.
4. Click any date and observe the month changing to itself.

Note that the opposite direction will also produce the same month changing to itself bug.

## Expected behavior
Date will become selected with no month scroll transition.

## Actual behavior
Month scrolls to same month with date selected.

## Live example
Using the static calendar on the demo page this behavior can be observed.
https://material-ui-pickers.dev/demo/datepicker

**Comment by oliviertassinari** [comment]
@jpodpro Thanks for the reproduction. I can confirm it on my end.

**Comment by oliviertassinari** [comment]
However, the good news is that it doesn't happen on the next version at https://next.material-ui-pickers.dev/demo/datepicker#static-mode. It was likely fixed in #1416.

@dmtrKovalenko Should we close?

**Comment by dmtrKovalenko** [comment]
@oliviertassinari I am planning to revisit all the issues and close them after 1st prerelease is ready. I was looking on some issues while doing the upgrade

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Awesome, I believe you have already fixed this one.

**Comment by dmtrKovalenko** [comment]
Fixed already as for v4-alpha.9
