### ISSUE TITLE
Add built-in localization support

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1429]
We should support new localization feature. 

- [ ] Rename props to look conventional to material ui text props :
If we should rename the prop to `titleText` to something that starts to look like a convention:
- backIconButtonText
- labelRowsPerPage
- labelDisplayedRows
- nextIconButtonText
- getLabelText
- clearText
- closeText
- loadingText
- noOptionsText
- openText

_Originally posted by @oliviertassinari in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzM1MDA1Njky/pull_request_reviews/more_threads_

- [ ] Make it possible to localize all formats from the localization feature. It should be a killer feature

**Comment by dmtrKovalenko** [comment]
Requires new way to pass formats right to the pickers and new `date-io` version

**Comment by oliviertassinari** [comment]
Yes! DatePicker and DataGrid are probably the two components that will benefit the most from an out of the box localization support.

**Comment by oliviertassinari** [comment]
Reopening until the counterpart change on https://github.com/mui-org/material-ui, if this is all right :).

**Comment by oliviertassinari** [comment]
Closing for https://github.com/mui-org/material-ui/issues/23674
