### ISSUE TITLE
Theme not correctly propagated to the component

### ISSUE THREAD

**Issue by Spomky** [mui-org/material-ui-pickers#1430]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  latest version starting from ^3.2.8       |
| material-ui          | latest version starting from ^4.6.1 |
| TypeScript           |  |
| React                | latest version starting from ^16.2 |
| Browser              | Firefox / Chrome / Edge |
| Peer library         | moment |  |

## Steps to reproduce

Hi,

I have a from with 2 date pickers and a select.
The theme customizations are correctly propagated to the select, but not to the date pickers.
The spacing and the font are not identical (see screenshot).

## Expected behavior

The style of the datepickers should be consistent with the theme.

## Actual behavior

![Screenshot_2019-12-20 Comparaison PPA Tx Ch » Grand Angle](https://user-images.githubusercontent.com/1091072/71256461-14597c80-2331-11ea-91ed-6c0cb0d401f2.png)

## Live example

…just let me som time to prepare a live example…

**Comment by nossila** [comment]
@Spomky what did you do to solve it? I'm experiencing the same.
