### ISSUE TITLE
[DatePicker] Feature request: controllable active view

### ISSUE THREAD

**Issue by jedwards1211** [mui-org/material-ui-pickers#1436]
My product manager isn't happy with the KeyboardTimePicker UX and to provide the UX he wants I need to make my own custom input and show the picker view while the input is focused.

I need to be able to control whether picker is showing hours or minutes view based on where the cursor is in the input.  The `openTo` prop only affects the initial view...I need something that switches the view when the prop changes.

**Comment by mbrookes** [comment]
@jedwards1211 Please consider providing a comprehensive feature request. As it stands, the issue risks being closed for being too vague. (Perhaps your PM would like to add some value?)

**Comment by jedwards1211** [comment]
### Description of solution

I could make a PR, basically I want to add an `openView` prop to `Picker`, and have effect hook call `setOpenView(props.openView)` whenever that prop changes.  The other changes would be making the various picker types forward that prop.

If it's not acceptable to have the open view be semi-controlled, we could instead make `Picker` accept `openView` and `onOpenViewChange`, and if `onOpenViewChange` is provided, it will store the open view externally via those props instead of storing the open view in local state.

### Alternatives I've considered

At the moment I add the `key` prop in `<TimePicker variant="static" key={openView} openTo={openView} />` to force the picker to remount with `openView` showing.

**Comment by oliviertassinari** [comment]
@jedwards1211 Interesting. I think that having a fully controllable view prop would make sense. We could apply the same logic to the date picker. However, it sounds like a niche use case with a low priority. I think that we can wait for the major upgrade @dmtrKovalenko is undertaking before actually/considering solving this problem.

**Comment by oliviertassinari** [comment]
This use case should be handle by the `displayedValue` state of https://github.com/mui-org/material-ui/issues/24150.
