### ISSUE TITLE
Demo for the Calendar API

### ISSUE THREAD

**Issue by ejbee3** [mui-org/material-ui-pickers#1438]
**Is your feature request related to a problem? Please describe.**

I am experimenting with the Calendar API and I would like to use it on a project, but I don't know what it does or how to use it!

**Describe the solution you'd like**

All I'd like is a demo of how to use the API.

**Describe alternatives you've considered**

I posted a similar question/issue on StackOverflow about 10 minutes ago. I tried mimicking the DateTimePicker that I'm currently using in my project, but to no avail.

*Edit* [Link.](https://stackoverflow.com/questions/59532924/does-anyone-have-any-experience-working-with-the-material-ui-pickers-calendar-a)

**Comment by dmtrKovalenko** [comment]
Please point a link to your stackoverflow question

**Comment by dmtrKovalenko** [comment]
Moving discussion to stackoverflow
