### ISSUE TITLE
Bug when updating to @material-ui/core 4.8.3

### ISSUE THREAD

**Issue by kingeric027** [mui-org/material-ui-pickers#1441]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.7        |
| material-ui          | 4.8.3        |
| TypeScript           |  3.4       |
| React                |  16.8.6       |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. Update material-ui/core to version 4.8.3 (yarn add @material-ui/core) from 4.5.1 in an app that uses @material-ui/pickers
2. Run the app (npm start)
3. Observe the error message: 
"Type '{ renderDay: (day: MaterialUiPickersDate, selected: MaterialUiPickersDate, dayInCurrentMonth: boolean) => Element; value: Moment; variant: "static"; onChange: (day: MaterialUiPickersDate) => void; ... 9 more ...; rowsMax: undefined; }' is missing the following properties from type 'Pick<PureDateInputProps, "ref" | "label" | "select" | "style" | "title" | "className" | "innerRef" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | ... 265 more ... | "inputVariant">': color, size  TS2739"

## Expected behavior

I expected to be able to start the app and the DatePicker component to still work.

## Actual behavior
The app fails to compile with the error message: 
"Type '{ renderDay: (day: MaterialUiPickersDate, selected: MaterialUiPickersDate, dayInCurrentMonth: boolean) => Element; value: Moment; variant: "static"; onChange: (day: MaterialUiPickersDate) => void; ... 9 more ...; rowsMax: undefined; }' is missing the following properties from type 'Pick<PureDateInputProps, "ref" | "label" | "select" | "style" | "title" | "className" | "innerRef" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | "suppressHydrationWarning" | ... 265 more ... | "inputVariant">': color, size  TS2739"

## Live example
Not sure if I am doing something wrong of if this is a bug! Here is what my code looks like where I am using the <DatePicker> component. All of this worked fine prior to upgrading to 4.8.3. 

`import MomentUtils from "@date-io/moment";`
`import { DatePicker, Day, MuiPickersUtilsProvider } from "@material-ui/pickers";`
`import { MaterialUiPickersDate } from "@material-ui/pickers/typings/date";`

<MuiPickersUtilsProvider utils={MomentUtils}>
            <DatePicker
              // eslint-disable-next-line
              renderDay={renderDay}
              value={selectedDate}
              variant="static"
              onChange={handleDateChange}
              format="YYYY-MM-DD"
              disableToolbar={true}
              style={undefined}
              onFocus={undefined}
              onBlur={undefined}
              className={undefined}
              ref={undefined}
              innerRef={undefined}
              rows={undefined}
              rowsMax={undefined}
            />
</MuiPickersUtilsProvider>

**Comment by mbrahimi617** [comment]
I'm getting this error as well using MomentUtils:
![image](https://user-images.githubusercontent.com/31360324/72198381-6f473680-33fa-11ea-9be0-ad37a58f1098.png)
