### ISSUE TITLE
minDate is being set on initial click if value is empty and minDate is in the future

### ISSUE THREAD

**Issue by Solavon** [mui-org/material-ui-pickers#1444]
I couldn't find a good meme I'm sorry ;-;

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.8     |
| material-ui          |    4.8.3     |
| TypeScript           |    3.5.3     |
| React                |    16.12.0     |
| Browser              |    Chrome Version 79.0.3945.117 (Official Build) (64-bit)    |
| @date-io/moment    |    1.3.13    |
| moment    |    2.24.0    |

## Steps to reproduce

1. value is null/empty
2. minDate is greater than today
3. Click on datepicker

## Expected behavior

To open the datepicker and allow me to set the date

## Actual behavior

Sets the minDate as the value

## Live example

https://codesandbox.io/s/material-picker-auto-set-mindate-if-greater-than-today-bj7mc

**Comment by dmtrKovalenko** [comment]
Yes, it is by design. Right now we are not supporting "empty date". So if your selected date is disabled picker will find the closest enabled date. 
To change the behavior set the `initialFocusedDate`
