### ISSUE TITLE
[question] How to set weekStart without localization?

### ISSUE THREAD

**Issue by radulle** [mui-org/material-ui-pickers#1446]
I am trying to find a way to set weekStart to Monday without using localization.

**Comment by oliviertassinari** [comment]
What's wrong with using localization?

**Comment by radulle** [comment]
Good question, 
If I want to start week on  Saturday instead of having just `weekStart={6}` i have to:
```
import locale from "dayjs/locale/en";
locale.weekStart = 6
<MuiPickersUtilsProvider utils={dayjsUtils} locale={locale}>
```
But when I take a better look to be honest, you are completely right. There is nothing wrong with using `locale` as it covers most of the cases. For these exotic cases it's perfectly fine. I was too hasty.

**Comment by oliviertassinari** [comment]
Hum, it sounds like something is off. Material-UI default locale is en-US, so I would expect the first day of the week to be Sunday (en-US), not Monday (en-GB). http://chartsbin.com/view/41671.

**Comment by oliviertassinari** [comment]
I don't know enough to triangle the root issue. It could be an issue with dayjs that doesn't set weekStart correctly. It could be an issue with how we use dayjs or how you use it. Do you have a reproduction?

I think that @dmtrKovalenko will be able to 💡 us.

**Comment by radulle** [comment]
Miss-understanding, I wrote **Saturday** not Sunday so it is ok behavior. It was better that I have picked Wednesday as an example due to possible confusion issues. I think you can close this one.
