### ISSUE TITLE
Month View when clicking on Month From Date View Picker

### ISSUE THREAD

**Issue by gopinath-sixt** [mui-org/material-ui-pickers#1448]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.8      |
| material-ui          |   4.0.0.beta      |
| TypeScript           |         |
| React                |   16.8.6      |
| Browser              |   Chrome      |
| Peer library         |         |  |

## Steps to reproduce

1. Added views={["year", "month", "date"]} in DatePicker 
2. When click on Month(eg: Tue, Jan) from picker, user can't able see the month view

## Expected behavior
User able to see the month view when click on the month

## Actual behavior
User can't able to see the month view when click on the month

## Live example
https://codesandbox.io/s/material-ui-pickers-usage-demo-s8otv

**Comment by DharmedraKumar** [comment]
I am also facing the same issue. Can someone provide any workaround so that on click of month, month options can be seen

**Comment by jaynsuthar** [comment]
I'm also facing the same issue. It will be great if anyone can provide the work around to that problem.

**Comment by sagishalom18** [comment]
Anyupdate?

**Comment by sagishalom18** [comment]
well I found a solution ..  use this settings:
openTo="month" views={['month', 'year', 'date']}
