### ISSUE TITLE
Multiples KeyboardDatePicker on the same page (Freezeing / Slow problem)

### ISSUE THREAD

**Issue by RayanXY** [mui-org/material-ui-pickers#1449]
## The Problem

I have a page where there are three KeyboardDatePicker and if anyone of them is without any preseted date (blank, waiting for the user fill it) the mask doesn't work, accepts letter (it's suppose to be numbers only) and it gets very slow, you wait some seconds for the input show up. But if comes with any date preseted, I can erase and everything works fine. How can I let the field blank without this? Is a perfomance problem? The three date are the same component

## New

After some testing, I discovered that it's only the KeyboardDatePicker that causes this, and he only show up when a certain option is selected in a "Select". But I made it show up along with the page, not depending on the condition and it worked just fine. There's something with condition that may interfere with the perfomance of KeyboardDatePicker?

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case with the latest version (v4.0.0-alpha.5 as we are writing). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/cool-cherry-v3cbt) _may_ be a good starting point. Thank you!
