### ISSUE TITLE
Document format string format

### ISSUE THREAD

**Issue by scrozier** [mui-org/material-ui-pickers#1450]
I don't see any documentation of the possible formats for the `format` prop. I've looked everywhere I can think of, including the date-fns library I'm using. Yes, I can figure some of it out through trial and error, but it's frustrating to do that for some of the lesser-used options.

It would be great to have a link to the appropriate reference in the description of the `format` prop.

If you can point me in the right direction, I'm happy to do a PR for this.

And if I'm missing the obvious answer, sorry. [sheepish emoji goes here]

Thanks!

**Comment by devMartinoz** [comment]
Just having the same problem right now. Cant find the format for the AM/PM value :(

**Comment by dmtrKovalenko** [comment]
Check the documentation for your library. I’m case of date-fns here are all available formats https://date-fns.org/v2.9.0/docs/format

**Comment by scrozier** [comment]
Thank you! I had found the date-fns page you referenced, but didn't notice that I was looking at an old version, which had obsolete format strings.

And thank you for this project. The pickers look great and the API is very nice!
