### ISSUE TITLE
Formik does not mark as touched when focus on material-ui/pickers

### ISSUE THREAD

**Issue by thanhmd** [mui-org/material-ui-pickers#1452]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.8   |
| formik          | 2.1.2      |
| yup|         | 0.28.0

## Steps to reproduce

Change input or focus on the picker component

## Expected behavior

Set touched object contain the name of the picker component

## Actual behavior

Not working as expected

## Live example

https://codesandbox.io/s/formik-material-ui-date-picker-with-yup-validate-3odn7?from-embed

**Comment by Blackburn29** [comment]
@thanhmd 
While figuring out an issue with the latest 4.0-alpha builds I stumbled upon your issue. Your sandbox is missing the `onBlur` callback from Formik.
```
<KeyboardDatePicker
   ...
  onBlur={props.handleBlur}
/>
```

**Comment by eckertalex** [comment]
I had the same issue as OP. I will try that tomorrow.
Thank you for the response!

EDIT:
Sorry for the late response. Your solution fixes the issue.
