### ISSUE TITLE
Remove Promise based api in favor of loading prop

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1454]
Also use [Snackbar](https://material-ui.com/ru/components/snackbars/) instead of spinner
cc @oliviertassinari

**Comment by oliviertassinari** [comment]
Thanks for opening this issue. We have talked about using the CircularProgress vs using the Skeleton and the bundle size impact it could have. I'm wondering about the frequency of these requirements. Also, I wonder what you have in mind with the Snackbar. 

I think that there is an option we haven't explored yet.

**What if we expose a customization API and leave the implementation of the loading behavior up to the users? (of course, we could need a demo, at least to make sure the DX is OK).**

This would allow us to have a lighter component, and to constraint us to make sure the customization acceptable. Do you have usage stats on the current demo, relative to the others? It could help to know how frequent this need is. For instance, if it's less than 10%, not built-in support could make sense.
