### ISSUE TITLE
Allow displaying two months at a time

### ISSUE THREAD

**Issue by Misiu** [mui-org/material-ui-pickers#1455]
**Is your feature request related to a problem? Please describe.**
Currently, on the desktop, there isn't a good way to allow users to select a date range that has dates from two months (start in January and end in February)

**Describe the solution you'd like**
I'd like to be able to display two months when selecting a date range, similar to Google Flights:
![image](https://user-images.githubusercontent.com/1741838/72619711-2df4e080-393e-11ea-8862-a9128767aecb.png)

**Describe alternatives you've considered**
For now, displaying single month is an option, but from UX perspective two months view would be better

**Comment by oliviertassinari** [comment]
I cover a potential API for this in https://github.com/mui-org/material-ui-pickers/issues/1293#issuecomment-538374383.

**Comment by Misiu** [comment]
@oliviertassinari yes, that kind of API would be great.

**Comment by oliviertassinari** [comment]
Implemented in #1602.

**Comment by Shwan119** [comment]
Hi @oliviertassinari, that's really nice - is it working only for React or Angular too? I need something similar for Angular and have checked https://material.angular.io/components/datepicker/overview but it does not have something like yours that have implemented to display 2 months!

Thank you!

**Comment by oliviertassinari** [comment]
@Shwan119 Material UI only focus on React. We can't help you on this one.
