### ISSUE TITLE
Custom end icon for KeyboardDateTimePicker does not work

### ISSUE THREAD

**Issue by rsmaan4u8** [mui-org/material-ui-pickers#1461]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.2.8    |
| material-ui          |    4.1.1     |
| TypeScript           |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. Specify custom end icon with InputProps  

## Expected behavior

Should show icon specified in InputProps. Please see link below.

## Actual behavior

Icon does not change

## Live example

https://codesandbox.io/s/sharp-proskuriakova-2xmun?fontsize=14&hidenavigation=1&theme=dark

**Comment by oliviertassinari** [comment]
Closing as we plan to migrate to a `renderInput` API in the next version, similarity to the [Autocomplete](https://material-ui.com/components/autocomplete/).
