### ISSUE TITLE
Specify which element we want the popover element attach to

### ISSUE THREAD

**Issue by DanielYKPan** [mui-org/material-ui-pickers#1464]
![A GIF or MEME to give some spice of the internet](url)

**Is your feature request related to a problem? Please describe.**
Is it possible to provide a html element, and then we could ask picker to attach the popover calendar to that element? Right now the calendar would always be attached to Body

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oliviertassinari** [comment]
@DanielYKPan Could you share more information on your use case? Thanks.

**Comment by dmtrKovalenko** [comment]
Note: You can pass any props right to mui popover with `PopoverProps` prop.
