### ISSUE TITLE
Usability: users don't understand they can click the year to change it.

### ISSUE THREAD

**Issue by mschipperheyn** [mui-org/material-ui-pickers#1467]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.8      |
| material-ui          |   4.8.2      |
| TypeScript           |         |
| React                |   16.9      |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

When you open the date picker, it allows you to click the year to quickly change it. 
Users don't get that, especially ios users. So we are getting complaints from people wanting to enter their birthday and having to click 40 years, one month at a time. So in a registration flow, this is a great way to lose a user. I would say F*** this if I wasn't aware. 

We need some kind of way to create a label or tooltip on the < month >  selector to alert people to this possibility.

## Expected behavior

Make it clear to the user that they can click year to change date.

## Actual behavior

No way to alert the user to this possibility in an intuitive manner.

**Comment by mschipperheyn** [comment]
Ah, I can customize it myself! Hmm, that would be a great one for the Docs.

**Comment by dmtrKovalenko** [comment]
We redesigned pickers! And it looks like we solved your problem. Check https://next.material-ui-pickers.dev

**Comment by mschipperheyn** [comment]
<img width="472" alt="Screen Shot 2020-01-23 at 10 13 27" src="https://user-images.githubusercontent.com/384959/72987771-d46f3480-3dc9-11ea-821b-ecfbaa40fecc.png">
Ok, for those still using the current version. This is our solution
