### ISSUE TITLE
datePicker autoOk auto accepts date when picking year

### ISSUE THREAD

**Issue by molaux** [mui-org/material-ui-pickers#1468]
Hi,

I recently upgraded to 3.2.9 version and was facing a problem with the DatePicker : 

In previous version, when using DatePicker with autook and views in static container, I was able to pick the year, then the month, and only when I was picking the day, the date was accepted. 

In new version, onAccept is triggered as soon as I pick a year in year view (and the month view is briefly appearing, before my custom dialog closes because of acceptation)

Here is the relevant config of my date picker (at least, I think...) :

```javascript
<DatePicker
  variant="static"
  openTo="date"
  views={['year', 'month', 'date']}
  autoOk
  value={this.state.date} 
  onChange={this.handleChange.bind(this)}
  onAccept={this.handleAccept.bind(this)}
  />
```

I was able to recover the previous behavior by downgrading to 3.2.0 and wonder if my problem is related to this commit : https://github.com/mui-org/material-ui-pickers/commit/41fa5373397b5a6b01a690d9db5b861ca6be4d1a

Is there a new way to achieve this in latest versions (autoOk while enabling ability to choose by year, then month, then day) ? 

Thanks in advance for your help

**Comment by dmtrKovalenko** [comment]
What do you mean under the new version? 
Please create a reproduction with https://codesandbox.io/

**Comment by molaux** [comment]
I mean at least 3.2.1 and 3.2.9.
I will try to reproduce with codesandebox

**Comment by molaux** [comment]
https://codesandbox.io/s/sweet-rhodes-skpvp

When I click current year ("2020") on top of the box, to open year view,  then choose another year, then the date is accepted (the accepted date is displayed on the right)

**Comment by dmtrKovalenko** [comment]
This was also fixed in v4, checkout this demo https://next.material-ui-pickers.dev/demo/datepicker#responsiveness
