### ISSUE TITLE
Picker's (and picker's button) onClick not stopping event propagation

### ISSUE THREAD

**Issue by larsblumberg** [mui-org/material-ui-pickers#1477]
![A GIF or MEME to give some spice of the internet](https://miro.medium.com/max/1052/1*t24C7QZ78nXwGjn4bXlcNA.jpeg)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    latest     |
| material-ui          |    latest     |
| TypeScript           |         |
| React                |     latest    |
| Browser              |    all     |
| Peer library         |    date-fns     |

## Steps to reproduce

1. Catch onClick in the parent node of the picker
2. Pass prop `onClick={e=>e.stopPropagation}` to picker component
3. Click button of picker and close dialog
4. onClick of parent component will still fire
5. In my special case that unfortunately toggles the material UI expansion area where the picker is placed within

## Expected behavior

* event propagation is stopped
* IMHO, stopping event propagation should be the default behavior of the button, and maybe even of the embedded input element

## Actual behavior

* event propagation is not stopped

## Live example

https://codesandbox.io/s/material-ui-pickers-usage-demo-fd1qq

```
import React from "react";
import DateFnsUtils from "@date-io/date-fns";
import {
  MuiPickersUtilsProvider,
  KeyboardDatePicker
} from "@material-ui/pickers";

function App() {
  return (
    <div onClick={() => alert("I alert immediately after the picker dialog is closed")}>
      <MuiPickersUtilsProvider utils={DateFnsUtils}>
        <KeyboardDatePicker onClick={e => e.stopPropagation()} />
      </MuiPickersUtilsProvider>
    </div>
  );
}

export default App;
```

**Comment by oliviertassinari** [comment]
The current behavior sounds like the expected one. Core components behave identically. @larsblumberg you probably want to filter the event. What's your use case?

**Comment by larsblumberg** [comment]
The date picker is inside an [`<ExpansionPanelSummary>`](https://material-ui.com/components/expansion-panels/) element which [toggles the expansion when clicked](https://material-ui.com/components/expansion-panels/#additional-actions):

<img width="673" alt="Screenshot 2020-01-28 at 11 32 39" src="https://user-images.githubusercontent.com/5980316/73256256-e5e97f80-41c1-11ea-9dde-1b85b74c59d6.png">

As you're saying the event propagation is the expected behavior; hence I need to manually stop the `onClick` event propagation from the picker's button. Unfortunately I don't know yet how to install a custom click listener on that button in order to stop the propagation.

**Comment by oliviertassinari** [comment]
@larsblumberg We had a similar concern in the past in https://github.com/mui-org/material-ui/issues/16565 and https://css-tricks.com/dangers-stopping-event-propagation/. We had to solve related issues impacting the interaction between different core components, like the Slider and the SwipeableDrawer.
It's a tricky problem. I don't have a good answer.

But it sounds a lot like something that is ExpansionPanel related, and not Picker related. https://material-ui.com/components/expansion-panels/#additional-actions?

I think that we can close.

**Comment by larsblumberg** [comment]
I read the websites you've linked, thanks a lot. Now I understand why we don't want to easily stop event propagation.

In my particular case I wrapped the date picker into a div which actually does stop event propagation. However well-knowing that it's done intentionally to prevent the expansion panel from toggling.
