### ISSUE TITLE
Incorrect formatting in KeyboardTimePicker

### ISSUE THREAD

**Issue by abrbhat** [mui-org/material-ui-pickers#1479]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.10      |
| material-ui          |    4.9.0     |
| TypeScript           |     x    |
| React                |    16.8.6     |
| Browser              |    Chrome     |
| Peer library         |     moment  2.24.0   |  |

## Steps to reproduce

Remove the last character in minute value. P from PM shifts left into time field.

## Expected behavior

Characters 'P' and 'A' should not shift into time fields which are numeric.

## Actual behavior

Characters 'P' and 'A' shift into time fields which are numeric.

## Live example

![test](https://user-images.githubusercontent.com/4189727/73442746-61426100-437b-11ea-9583-2c76f58f551c.gif)

**Comment by dmtrKovalenko** [comment]
This will not be possible. I know that it can be confusing but ... as for me it is not really such problem that needs so much work
