### ISSUE TITLE
I can't find docs on ParsableDate

### ISSUE THREAD

**Issue by alexanderkjeldaas** [mui-org/material-ui-pickers#1481]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/3ohhwwXPEgtI7fmGuQ/giphy.gif)

I'm using "2019-02-20" as a string and then `Date.now()` which fails.  I need to know what type `ParsableDate` represents.

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.dev/getting-started/parsing
