### ISSUE TITLE
Better documentation regarding building and publishing

### ISSUE THREAD

**Issue by PickleyD** [mui-org/material-ui-pickers#1487]
I've forked the repository and made a change. I'd like to test this change in a real application before making a pull request. 

I'm having difficulty working out how to either use my fork directly from Github or publish the package in a way where it is consumable. I believe some change is made to include the built files so I suspect it requires some alterations to the .gitignore and .npmignore files?

If it's only my inexperience showing then please could someone offer some advice here? If it looks like other people also find the same thing tricky perhaps some official documentation would be useful.

**Comment by oliviertassinari** [comment]
We have seen this use case come up a couple of time on the main repository. So far our best answer has been: open a pull request, get codesandbox ci create a new version, install it. However, you could also modify the node_modules localy or publish a new version.

**Comment by dmtrKovalenko** [comment]
Yeah, we need to improve docs. In short to test application locally

1. Go to `lib` folder
2. `yarn build`
3. `cd build`
4.  `yarn link`
5.  Go to your app folder where `@material-ui/pickers` installed
6.  Run `yarn link @material-ui/pickers`

Or just run `yarn dev` and test your changes locally on the documentation site

**Comment by oliviertassinari** [comment]
@dmtrKovalenko We have recently removed any mention to yarn link as it wasn't reliable in the documentation. I wonder if the situation has improved or if it was specific to our setup.

**Comment by PickleyD** [comment]
Thanks so much for the fast responses.

Unfortunately @dmtrKovalenko 's solution does not work for me. I took a clean fork and tried using yarn link but in my client app I get `Cannot read property 'keyboardDate' of undefined` when using the DatePicker or `Cannot read property 'fullTime12h' of undefined` when using the TimePicker.

**Comment by dmtrKovalenko** [comment]
It looks like you have outdated dependencies. Try to remove node_modules and run `yarn` from the root again

**Comment by PickleyD** [comment]
Thanks for the suggestion but the error is still occurring.

**Comment by tuxracer** [comment]
@PickleyD upgrading `@date-io/luxon` from 1.x to 2.x fixed the issue for me. you may have to update your corresponding @date-io package
