### ISSUE TITLE
Unexpected behavior regarding timezones

### ISSUE THREAD

**Issue by mk0y** [mui-org/material-ui-pickers#1490]
![weird](https://media3.giphy.com/media/tQNCUcgtKwVMY/giphy.gif?cid=790b7611d012072d4c59899257eb53b87759c08fe149b387&rid=giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.8        |
| material-ui          | 4.4.3        |
| TypeScript           |         |
| React                |  16.9.0       |
| Browser              | Chromium 79.0.3945.130        |
| Peer library         |  @date-io/moment       | 2.2.0 |

## Steps to reproduce

1. Date `2019-03-03T14:17:47+00:00` gives timezone +01:00
2. Date `2019-04-03T14:17:47+00:00` gives timezone +02:00 (notice 03 and 04 difference)

## Expected behavior

Same timezone for same timezone format `ddd, MMM Do YYYY, h:mm:ssa Z`.

## Actual behavior

Getting different timezones.

## Live example

https://codesandbox.io/s/material-ui-pickers-usage-demo-zpsb1

**Comment by dmtrKovalenko** [comment]
Moment will automatically parse the date as into your local timezone. If you need to customize this behaviour you need to use moment-timezone and pass it to the `instance` property of `MuiPickersUtilsProvider`

**Comment by mk0y** [comment]
Alright thanks. So it's moment bug.

**Comment by dmtrKovalenko** [comment]
It's not a bug. Pure moment is not able to show date in the different timezone, just like a native `Date`

**Comment by mk0y** [comment]
Hm, I see. I was confused why then for month of March is one timezone and for April same year another. So it's simply not working without moment-timezone.

**Comment by dmtrKovalenko** [comment]
Maybe because in March there is a switch to DST (clock shifting)
