### ISSUE TITLE
Material UI KeyboardDatePicker setting date to minDate if the value is null

### ISSUE THREAD

**Issue by karthickshanmugam0689** [mui-org/material-ui-pickers#1491]
Material-UI KeyboardDatePicker is unable to prevent the date selection on setting minDate. 

## Environment

"@material-ui/core": "4.3.1",
"@material-ui/icons": "3.0.2",
"@material-ui/pickers": "3.2.2",
"@material-ui/styles": "4.3.0",

## Steps to reproduce

1. Set minDate of KeyboardDatePicker to say 04.02.2020 and value to null
2. You can see that by default KeyboardDatePicker sets the value of the datepicker to 04.02.2020 since it is set as minDate

## Expected behavior

The expected behaviour is it shouldnt set the minDate as date value itself. Instead the days before the minDate should be disabled

Example for the same
<KeyboardDatePicker
          autoOk={true}
          data-testid={apiName}
          variant="inline"
          minDate={minDate || undefined}
          minDateMessage={minDateMessage}
          maxDate={maxDate || undefined}
          label={label}
          value={value ? value : null}
          animateYearScrolling={true}
          onChange={handeChange}
          disabled={!!disabled}
          required={required}
          error={error}
          helperText={helperText}
          className={className}
        />

**Comment by dmtrKovalenko** [comment]
But yout min date is **today**, when no value is available picker will use today. If selected value is disabled it will try to find the closest enabled date to select it

**Comment by karthickshanmugam0689** [comment]
Actually the issue here is even if i select 17.02.2020 as minDate, by default handleChange event is triggered somehow. The issue is not selecting today. It is happening even if I select someother date as minDate.

**Comment by dmtrKovalenko** [comment]
Use 17.01 as minDate -> **If selected value is disabled it will try to find the closest enabled date and select it**

**Comment by karthickshanmugam0689** [comment]
Is there any other way to prevent the date selection to minDate. This is causing issue in our system and we need to prevent it. Can you let us know if there are any other possibility to prevent it

**Comment by dmtrKovalenko** [comment]
Do not make the date in your `value` prop to be disabled

**Comment by karthickshanmugam0689** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17645486/73729668-c4dedc80-4735-11ea-8b68-5637eea4cb30.gif)
Steps to reproduce:
1. Set minDate to 17.02.2020
2. Click on the calendar icon to open the datepicker for which the value prop as of now is holding null value

By default the calendar modal is still open but onChange event is triggered with the date parameter being the minDate set.

This is the case which we need to prevent.

I read somewhere that there is isFinished parameter coming from onChange event handler method, but couldnt find anywhere in the docs  of material-ui-picker.

**Comment by karthickshanmugam0689** [comment]
More detailed view of the issue 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/17645486/73730473-18055f00-4737-11ea-8f34-e22dd3c03ffa.gif)

End Date picker depends on the date selected in Start Date picker.  So the scenario is like below

1. Set Start Date to 18.02.2020 - here we have the logic to set the minDate of endDate picker as 18.02.2020 to disable the dates before 18.02.2020 for endDate as we have the requirement that endDate should be equal to or greater than startDate
2. Click on the datepicker of endDate - here the minDate set is defaulted as the value of endDate thereby calling the onChange callback. We need to prevent this and this has to happen only on date selection in the calendar view.

**Comment by dmtrKovalenko** [comment]
Set your value to `18.02.2020`

**Comment by karthickshanmugam0689** [comment]
But the case here is i dont want to set the endDate. I just want the endDate to be selected by the user and not by the system. Just setting the minDate is setting up the date itself thus calling the onChange callback which we felt is unnecessary and should be triggered on user input. Is there any other way to handle it?

**Comment by karthickshanmugam0689** [comment]
Also I have did this is codeSanbox for your reference

https://codesandbox.io/s/intelligent-goodall-o7cxy

Here I set the minDate to be 12th February 2020. By default the value is being set to 12th February 2020 though I just set the minDate. This is not what we want.

This is happening only in autoOk and varian="inline" props passed to KeyboardDatePicker. This is not what we want

**Comment by dmtrKovalenko** [comment]
Here is working example https://codesandbox.io/s/sparkling-cloud-2zxtk
