### ISSUE TITLE
Datepicker component odd varient="inline" behaviour

### ISSUE THREAD

**Issue by hbermani** [mui-org/material-ui-pickers#1492]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   X      |
| material-ui          |      X   |
| TypeScript           |         |
| React                |      X   |
| Browser              |      Chrome   |
| Peer library         |         |  |

## Steps to reproduce

1. Follow Docs to install library and usage guidance
2. Log onSubmit results to console 
3. Select a date and press submit  (Date result shows in console as expected)
4. Add variant="inline" to Datepicker, the DatePicker shows inline but when pressing submit the date is not displaying on console log. 

## Expected behavior
For the DatePicker component to behave the same whether in dialog or inline varient, i.e. for the date to show in the console log

## Actual behavior
Date is not submitted to state.

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript) _may_ be a good starting point. Thank you!
