### ISSUE TITLE
Feature Request: Passing dateTime value to onClose

### ISSUE THREAD

**Issue by IAmMarcellus** [mui-org/material-ui-pickers#1494]
**Is your feature request related to a problem? Please describe.**
There's no way to know why the modal was closed (i.e. whether it was accepted or rejected).  I'd like to notify the user that the field is required if they open the modal and then cancel it, without selecting a datetime, but there's no way to know if they user has selected a datetime and accepted it or just canceled and left it blank.

**Describe the solution you'd like**
The onClose prop would pass the DateTime value to its function, or null if the user canceled without selecting a new value and the field will remain blank.  If the field already has a value and the user opens the modal and closes it without selecting a new one, the prop would just pass the same value.

**Describe alternatives you've considered**
One alternative is to pass an "accepted" boolean instead of the value, indicating whether the value was accepted or canceled. Another option would be to have an onCancel prop that fires whenever the user closes the modal without accepting it.  However, neither of these would be ideal for knowing if the field is still blank.

**Additional context**
The onClose method does fire after the onChange method, so most of the time I can check the state to see if the value exists or is still blank. However, the setState function doesn't always fire immediately, so its very possible that the onCanel function would fire before the state is updated and the value would still appear blank.

**Comment by dmtrKovalenko** [comment]
The field will be blank if value in your state is null. So when `onClose` is dispatched and value is null you can prompt the field

**Comment by oliviertassinari** [comment]
> The onClose method does fire after the onChange method, so most of the time I can check the state to see if the value exists or is still blank.

This is great, we have the same behavior with the autocomplete. I don't think that we should mix concerns.

**Comment by oliviertassinari** [comment]
Hum, actually, on the autocomplete, we have a second reason argument. 

```tsx
export type AutocompleteCloseReason = 'toggleInput' | 'escape' | 'select-option' | 'blur';
```

We could imagine the same here.
