### ISSUE TITLE
Select day not in current month?

### ISSUE THREAD

**Issue by frankruegamer** [mui-org/material-ui-pickers#1495]
**Is your feature request related to a problem? Please describe.**
I know that it is possible to display days not in the current month using the `renderDay`. But even using the following technique which doesn't duplicate logic and css of the library like the [example](https://material-ui-pickers.dev/demo/datepicker#customization), I wasn't able to actually make these days selectable.

```
function renderDay(day: Date | null, selectedDate: Date | null, dayInCurrentMonth: boolean, dayComponent: JSX.Element) {
  return React.cloneElement(dayComponent, {...dayComponent.props, hidden: false});
}
```

**Describe the solution you'd like**
Provide a way to make those days selectable.

**Comment by frankruegamer** [comment]
Is there something ambiguous in my post that I need to clarify?

**Comment by dmtrKovalenko** [comment]
Already shipped in v4

**Comment by frankruegamer** [comment]
I'm sorry but I fail to see where the functionality was added in v4. None of the examples on https://next.material-ui-pickers.dev/demo/datepicker have this functionality either.

Would you mind pointing me in the right direction? @dmtrKovalenko

**Comment by dmtrKovalenko** [comment]
Sorry it was not released, https://dev.material-ui-pickers.dev/api/DatePicker
Here check for `showDaysOutsideCurrentMonth`

**Comment by frankruegamer** [comment]
Thank you :+1:
