### ISSUE TITLE
When no mask prop is supplied, entering a date via keyboard input only accepts 1 character

### ISSUE THREAD

**Issue by binomialstew** [mui-org/material-ui-pickers#1497]
In order for the keyboard input field to properly accept a value, it seems to require a `mask` prop to be supplied to the DatePicker, but I don't see this in the examples. Would it work well to set a default mask?

Opening this issue in case this can be improved for v4:
Using `DatePicker`(with no `mask` prop), `@material-ui/pickers@4.0.0-alpha.1`, when clicking the pencil icon and then editing the keyboard input, only 1 character is allowed.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  4.0.0-alpha.1       |
| material-ui          |4.9.1|
| React                |16.8.6         |
| Peer library         |   confirmed reproducible with `date-fns` or` moment`      |  |

## Steps to reproduce

1. [Open sandbox](https://codesandbox.io/embed/cranky-meadow-zb7sq?fontsize=14&hidenavigation=1&theme=dark)
1. Click calendar icon button in date field
1. Make viewport narrow enough to render the toolbar with pencil icon on the right
1. Click pencil icon button to view keyboard input
1. Try editing the existing date

## Expected behavior

Expect to see the typed date in the input

## Actual behavior

Field shows 0 and does not allow more than one character

## Live example

https://codesandbox.io/embed/cranky-meadow-zb7sq?fontsize=14&hidenavigation=1&theme=dark

**Comment by dmtrKovalenko** [comment]
This thing is already fixed in develop

**Comment by binomialstew** [comment]
I'd like to track this fix so we don't forget to remove the workaround when released, but I wasn't able to find a develop branch. Can you point me to the commit?
