### ISSUE TITLE
KeyboardTimePicker do not have midDate/maxDate properties

### ISSUE THREAD

**Issue by Harasz** [mui-org/material-ui-pickers#1505]
**Is your feature request related to a problem? Please describe.**
My problem is with KeyboardTimePicker. I can not set minDate/maxDate, but i have properties to set a message when date is more then maximal date or less then minimal (maxDateMessage and minDateMessage properties)

**Describe the solution you'd like**
It is simple I would like to have a properties minDate/maxDate as it is in KeyboardDatePicker.

**Describe alternatives you've considered**
I think this is redundant here.

**Additional context**
I think this is redundant here.

**Comment by feraraujofilho** [comment]
Any news ??

**Comment by lbartroli** [comment]
why this issue was closed? I'm hitting the same issue, need to display an error message for maxDate and looks like we cannot set maxDate or maxTime inside this component.

**Comment by lbartroli** [comment]
NVM, looks like here is the answer: https://github.com/mui-org/material-ui-pickers/issues/1369#issuecomment-590062822
