### ISSUE TITLE
Where is the DateIOType exported from ?

### ISSUE THREAD

**Issue by hamza0867** [mui-org/material-ui-pickers#1506]
Hello guys,

First I wanna thank for the amazing job that you are doing.
I am working on a library that uses material-ui-pickers and I am using typescript to build it.
I noticed that the type of the onChange function in the docs is this: 
```typescript
(date: DateIOType) => void
```
I just want to know where can I import the DateIOType from ??

Thank you so much

**Comment by dmtrKovalenko** [comment]
There is a hint on documentation about it 
![image](https://user-images.githubusercontent.com/16926049/74683420-964f1000-51d1-11ea-8d9f-c5010bb6ff92.png)

But in real world it is declaring right inside used `@date-io/{lib]` module

**Comment by samimessaoudi** [comment]
![image](https://user-images.githubusercontent.com/39248787/75913597-867f2f00-5e53-11ea-8b9d-ee01c08c381e.png)
@date-io/moment Doesn't Export DateIOType
Where To Find It Exactly ?

**Comment by dmtrKovalenko** [comment]
You should not use it. If you are using moment you need `useState<Moment>`
