### ISSUE TITLE
Bug with typescript and overrides-mui.d.ts

### ISSUE THREAD

**Issue by hamza0867** [mui-org/material-ui-pickers#1510]
![A GIF or MEME to give some spice of the internet](https://user-images.githubusercontent.com/6094917/56953761-2c2b8880-6b35-11e9-8f17-5e52fda781af.png)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.10     |
| material-ui          |   4.9.2      |
| TypeScript           |     3.7.5    |
| React                |     16.12.0    |
| Browser              |     chrome    |
| Peer library         |     date-fns    |  |

## Steps to reproduce

1. clone this repo: https://github.com/hamza0867/material-ui-pickers-bug.git
2. run `yarn install && yarn compile`
3. you should see the message of the error

P.S: The repo contains a README that explains a bit more

## Expected behavior

I expect the app to compile

## Actual behavior

The app does not compile and shows the following error:
```bash
node_modules/@material-ui/core/styles/overrides.d.ts:101:64 - error TS2344: Type 'ComponentNameToClassKey[Name]' does not satisfy the constraint 'string'.
  Type '"fixed" | "required" | "rtl" | "square" | "active" | "disabled" | "track" | "default" | "error" | "progress" | "message" | "middle" | "media" | "hidden" | "body" | "button" | "caption" | ... 400 more ... | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.

101   [Name in keyof ComponentNameToClassKey]?: Partial<StyleRules<ComponentNameToClassKey[Name]>>
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

## Live example

The live example is not working for some reason ( maybe it does not run the commands that are in package.json )
But cloning a simple repo with minimalist configuration shouldn't be a problem.
Here is the link to the sandbox for reference: https://codesandbox.io/s/github/hamza0867/material-ui-pickers-bug

**Comment by dmtrKovalenko** [comment]
Its already fixed

**Comment by codingedgar** [comment]
I get the same exact error with today's version of the override types

**Comment by codingedgar** [comment]
My solution was:

```ts
/* eslint-disable @typescript-eslint/no-empty-interface */
import { MuiPickersOverrides } from '@material-ui/pickers/typings/overrides';

type overridesNameToClassKey = {
  [P in keyof MuiPickersOverrides]: keyof Required<MuiPickersOverrides>[P];
};
declare module '@material-ui/core/styles/overrides' {
  export interface ComponentNameToClassKey
    extends Required<overridesNameToClassKey> {}
}
```
