### ISSUE TITLE
TextFieldComponent openTo="year" caused anchorEl invalid warning

### ISSUE THREAD

**Issue by bancs23** [mui-org/material-ui-pickers#1511]
After updated to latest Material-ui i got a datepicker with custom input component by using TextFieldComponent and set variant="inline" and open picker with year selection at first place then month and date selection.

month and date selection picker got position issue which is not prompt from the custom input. 
and got this following warning:

> Material-UI: the `anchorEl` prop provided to the component is invalid.
> The anchor element should be part of the document layout.
> Make sure the element is present in the document or that it's not display none.

this issues only happen when using TextFieldComponent. without custom component it working fine.

**Comment by kerosan** [comment]
TextFieldComponent props expect <TextField/> component from material-ui/core 
in my case I have override mui theme to make TextField like my custom Input

**Comment by dmtrKovalenko** [comment]
This was fixed in v4

**Comment by flackeryy** [comment]
For everyone who face this issue for v3. 

```js
function App() {
  const [value, setValue] = useState()
  const rootRef = useRef()
  
  <DatePicker
      value={value}
      onChange={(e) => setValue(e)}
      PopoverProps={{
        anchorEl: () => rootRef.current
      }}
      TextFieldComponent={(props) => <TextField {...props}  />}
    />
}
```

**Comment by Jaspreet123456** [comment]
![Uploading Screenshot from 2024-09-24 18-16-03.png…]()
