### ISSUE TITLE
'KeyboardDatePicker' is not exported from '@material-ui/pickers'

### ISSUE THREAD

**Issue by r0hann** [mui-org/material-ui-pickers#1519]
Even when I imported KeyboardDatePicker, this package is showing "**'KeyboardDatePicker' is not exported from '@material-ui/pickers'**" error. And also when I check index file I could not find 'KeyboardDatePicker'

**Comment by 839998664** [comment]
Facing the same issue as well...Tried using the DatePicker instead but it throws an error..."Cannot read property 'breakpoints' of null"

**Comment by dmtrKovalenko** [comment]
Sorry, it's my fault. I have published a prerelease `alpha` version under the `latest` tag. 
Already fixed. 

Simply make `yarn add @materail-ui/pickers@next` and you will get proper version.

**Comment by hadasmaimon** [comment]
I use the "4.0.0-alpha.7" version and I get the same error:
"'KeyboardDatePicker' is not exported from '@material-ui/pickers'."
@dmtrKovalenko any help?

**Comment by dmtrKovalenko** [comment]
@hadasmaimon read the docs and breaking changes

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Does it worth to have a "Upgrade to v4" guide? Like we had in https://next.material-ui-pickers.dev/guides/upgrading-to-v3?

I wonder, the more we push forward, the more it might feel that the next stable release will be a brand rewrite of the componnets. Maybe this tradeoff: have one but focus on the high-level changes, only? Regarding the timing, should we wait to have made more progress?

**Comment by dmtrKovalenko** [comment]
@oliviertassinari I am working on more breaking changes as we discussed before, the guide – yes we definitely need it. I planned to make all breaking changes and then simply collect all the release notes into one giant. 

But it looks like we will have TOO MANY breaking changes. I feel it will take 5 or 6 pages to describe all the changes we done. We need to consider making codemod scripts for update

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Haha, right. In this case, maybe we should only describe the high-level changes, where they should spend more time on, then encourage people to "rewrite" the usage they have of the component?

For the Autocomplete, we did something a bit similar, replacing demos with a component, the developers had to rewrite. It has been going well.

**Comment by dmtrKovalenko** [comment]
This sounds reasonable.

**Comment by GouthamJM** [comment]
> yarn add @material-ui/pickers@latest
Typo

**Comment by TOcvfan** [comment]
I use version 4.0.0-alpha.12 and I also get this error, I have also tried yarn add @material-ui/pickers@latest and next but with same result..

**Comment by oliviertassinari** [comment]
@TOcvfan This module does no longer exists after v3. You can use the regular component.

**Comment by anielski** [comment]
I use TimePicker and DatePicker instead of KeyboardDatePicker and KeyboardTimePicker - it works;).

**Comment by yehonadav** [comment]
what happened to KeyboardDateTimePicker? 
version 4.0.0-alpha.12 does not have it, if its gone ? how do we replicate it's functionality?

**Comment by oliviertassinari** [comment]
> what happened to KeyboardDateTimePicker?

@yehonadav https://next.material-ui.com/guides/pickers-migration/
