### ISSUE TITLE
Named exports

### ISSUE THREAD

**Issue by nesvet** [mui-org/material-ui-pickers#1520]
Hi. Please, do not use named exports. Module bundlers, such as Rollup, can't import what wasn't actually exported by a module (I suppose because of tree shaking algorithm). This makes Rollup users to do something like:

```javascript
"namedExports": {
	"react": [ "createContext", "useMemo", "createElement", "useContext", "useRef", "useEffect", "useLayoutEffect", "Component", "useCallback", "Fragment", "useState", "useDebugValue", "cloneElement", "memo", "forwardRef", "useReducer" ],
	"prop-types": [ "func", "oneOfType", "object", "string", "element", "arrayOf", "bool", "number", "oneOf", "node", "instanceOf" ],
	"@material-ui/core/styles": [ "makeStyles", "createStyles", "withStyles", "useTheme", "fade" ],
	"@material-ui/core": [ "Typography", "Grid", "IconButton", "makeStyles", "ButtonBase", "useTheme", "Fade", "CircularProgress", "useMediaQuery" ]
}
```

This is the actual list of dependencies and their named exports, needed to specify and used by `@material-ui/pickers`.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 4.0.0-alpha.3        |
| material-ui          |4.9.3         |
| rollup          |1.31.1         |
| @rollup/plugin-commonjs         |11.0.2         |

**Comment by dmtrKovalenko** [comment]
Umm 🤔 I think rollup is handling pickers output perfectly, didn’t it? We are using rollup as well

**Comment by TrySound** [comment]
Hi. It's ok to use named exports and actually there is coming new feature in rollup to solve this issue. Track it here https://github.com/rollup/plugins/pull/149

For now you can use simple trick. Add this to your rollup config

```js
import * as react from 'react';
import * as propTypes from 'prop-types';

commonjs({
  namedExports: {
    react: Object.keys(react),
    'prop-types': Object.keys(propTypes)
  }
})
```

Material-ui is already distributed with es modules. You do not need to specify named exports for it.

**Comment by dmtrKovalenko** [comment]
BTW yesterday released proper support for path imports like `@material-ui/pickers/Datepicker` and it is not conflicting with named imports anymore

But only for v4 alpha.

**Comment by dmtrKovalenko** [comment]
Ohh just realized that you are using v4. Maybe latest changes broke something for you? Please describe you me issue

**Comment by TrySound** [comment]
@dmtrKovalenko All good. Nothing is changed here.
