### ISSUE TITLE
Undefined `format` prop throws error in v4

### ISSUE THREAD

**Issue by pedro-pedrosa** [mui-org/material-ui-pickers#1521]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 4.0.0-alpha.3 |
| material-ui          | 4.3.2 |
| TypeScript           |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

Use a date time picker in the following way:
```ts
<DateTimePicker
  value={props.value}
  onChange={props.onChange}
  format={props.useCustomFormat ? 'HH:mm' : undefined}
/>
```

## Expected behavior

I was expecting to be able to conditionally pass a custom format or fallback to the default one

## Actual behavior

I'm getting an error saying `format` is required. This happens because `defaultProps` from `useDefaultProps` is being merged using object spread syntax like `{ ...defaultProps, ...props }` which will overwrite the `format` value from default props if `format` exists in `props` even though it is undefined.

In my opinion I shouldn't have to resort to object spreading in my code to conditionally include `format` in the props object depending on some condition. If the value is undefined, it should fallback to a default value.

## Live example

https://codesandbox.io/s/snowy-snow-ljg5y

**Comment by dmtrKovalenko** [comment]
Yeah, thanks it’s a bug

**Comment by dmtrKovalenko** [comment]
No, its not a bug. This prop was renamed to `inputFormat`
