### ISSUE TITLE
Align bundle size optimization with material ui

### ISSUE THREAD

**Issue by andriijas** [mui-org/material-ui-pickers#1527]
**Is your feature request related to a problem? Please describe.**
I've implemented these optimizations https://material-ui.com/guides/minimizing-bundle-size/

And now my concern is that material-ui-pickers doesn't adapt the same pattern

**Describe the solution you'd like**

In `.babelrc` Id like to add to `plugins`

```
    [
      "babel-plugin-import",
      {
        "libraryName": "@material-ui/pickers",
        "libraryDirectory": "esm",
        "camel2DashComponentName": false
      },
      "pickers"
    ],
```

and instead of doing this in my app code:

```
import {
  DateTimePicker as MuiDateTimePicker,
  DateTimePickerProps
} from "@material-ui/pickers/DateTimePicker";
```

I want to do this:

```
import {
  DateTimePicker as MuiDateTimePicker,
  DateTimePickerProps
} from "@material-ui/pickers";
```

**Additional context**
material-ui-pickers seems to lack esm - please include in bundle :) 

Thanks!

**Comment by oliviertassinari** [comment]
@andriijas I believe we would get this for free with https://github.com/mui-org/material-ui/issues/19706.

**Comment by andriijas** [comment]
@oliviertassinari thanks for quick reply, good work on that proposal! Have a nice weekend.

**Comment by andriijas** [comment]
@oliviertassinari maybe this should be a serpate issue but

shouldn't it be possible to optimize styles imports as well?

```
    [
      "babel-plugin-import",
      {
        "libraryName": "@material-ui/core/styles",
        "libraryDirectory": "esm",
        "camel2DashComponentName": false
      },
      "styles"
    ],
```

Under the hood:
```
-import { makeStyles } from "@material-ui/core/styles";
+import makeStyles from "@material-ui/core/styles/esm/makeStyles";

```

**Comment by dmtrKovalenko** [comment]
We are providing esm build only from the core. It works perfectly with create react app. And in v4 already added support for path imports with esm like in material-ui/core
