### ISSUE TITLE
Allow override of responsive wrapper

### ISSUE THREAD

**Issue by JeffBaumgardt** [mui-org/material-ui-pickers#1535]
**Is your feature request related to a problem? Please describe.**
Given development of a new component in code sandbox I spent far too long trying to figure out why my component looked different in code sandbox and my dev environment. It finally hit me when I figured out that in code sandbox the development preview is so small it's considered mobile.

I am working on a date range picker myself until one is available and I've spent most of my time perfecting what is now the mobile view and the desktop view does not work at all. I.e. labelFunc is completely ignored due to a mask being applied on the input and so on.

**Describe the solution you'd like**
It would be nice to have either a prop or context override switch to define which wrapper to use, regardless of the current breakpoint of the viewport

**Describe alternatives you've considered**
Twiddle my thumbs until an 'official' date range picker comes along. But I have product managers demanding something now and I can't push back on them any longer. Other alternative would be to use a completely different date range picker, but then lose all cohesiveness on style and aesthetics of the app.

**Additional context**
Mobile
![Mobile](https://user-images.githubusercontent.com/777527/75165777-21ec0380-56e0-11ea-9695-d9b54d87d951.png)

Desktop
![Desktop](https://user-images.githubusercontent.com/777527/75165794-287a7b00-56e0-11ea-8989-826b335e30e8.png)

**Comment by JeffBaumgardt** [comment]
The short issue is that I don't want the `KeyboardPicker`

**Comment by dmtrKovalenko** [comment]
I did not really understand:
If you are using `v4-alpha` – this behavior is by design and exhaustively covered here https://next.material-ui-pickers.dev/demo/datepicker
If not - you may want to update to the `v4-alpha`
