### ISSUE TITLE
No mask shown after changed the format

### ISSUE THREAD

**Issue by leonHk** [mui-org/material-ui-pickers#1538]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  4.0.0-alpha.3       |
| material-ui          |    4.5.2     |
| TypeScript           |         |
| React                |         |
| Browser              |         |
| Peer library         |         | 

## Steps to reproduce

Use a date time picker in the following way:
`<DatePicker  
         autoOk 
        mask ="__-___-____"
       placeholder= "DD-MMM-YYYY"
       format= "dd-MMM-yyyy"
         invalidDateMessage= 'invalid'
         disableFuture
          value={fromDate} 
             onChange={this.handleFromChange}
/>`

## Expected behavior

I was expecting to be able to show the mask as `__-___-____` during input.

## Actual behavior
If I don't specified the format and mask prop, the mask can be show success like below picture.
<img width="280" alt="3" src="https://user-images.githubusercontent.com/46306814/75327890-13f0db00-58b8-11ea-9a4c-7cb7ede63730.png">
However, if I set the format = 'dd-MMM-yyyy' with `mask = '__-___-____' ` . The mask cannot be shown like below picture
<img width="277" alt="2" src="https://user-images.githubusercontent.com/46306814/75327888-13584480-58b8-11ea-993e-7401c9cc9e73.png">
From console, the following warning shown
<img width="861" alt="1" src="https://user-images.githubusercontent.com/46306814/75327883-118e8100-58b8-11ea-85ea-5283549c5e56.png">

**Comment by dmtrKovalenko** [comment]
I think warning message is clear, isn’t it?
Your mask is not valid, it means that using mask user cannot type the date

**Comment by dmtrKovalenko** [comment]
In your particular case MMM will pare quite input like “June” or “Mar” but it is not possible due to `acceptRegex` and `mask` props

**Comment by leonHk** [comment]
Sorry, I am not understand because I am new in @material-ui/picker. In my case, I would to allow user input the date which is dd-MMM-yyyy format and show the mask during input (e.g. `13-Feb-____`)  May I have any advise?

Thanks

**Comment by dmtrKovalenko** [comment]
There is no way to predict how much letters will be in `MMM` it can be 3 (Feb) or 4 (June). So only use unmasked input. But better use MM
