### ISSUE TITLE
Unexpected behaviour of KeyboardTimePicker when ampm is false with dayjs

### ISSUE THREAD

**Issue by airled** [mui-org/material-ui-pickers#1540]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.10     |
| material-ui          |    4.9.4 (core)     |
| TypeScript           |    -    |
| React                |     16.13.0     |
| Browser              |   Firefox (73.0.1) (64-bit) and Chromium (80.0.3987.122)      |
| Peer library         |    dayjs (1.8.21) with @date-io/dayjs@1.x  (1.3.13)    | 

## Steps to reproduce
Use material-ui/pickers with dayjs (see versions above) and see live example below.
## Expected behavior
Backspace should remove digit to the left and place underscore instead of digit like in [this example](https://material-ui-pickers.dev/demo/timepicker#inline-mode)
## Actual behavior
Backspace resets to 0 digit left to cursor and changes digits left to that 0.
## Live example
https://codesandbox.io/s/young-pond-05rdo

**Comment by dmtrKovalenko** [comment]
This was fixed by v4
