### ISSUE TITLE
Question: how to enter the date using the keyboard in KeyboardDateTimePicker

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [mui-org/material-ui-pickers#1541]
Hello. Just for the question, the documentation did not find the answer to my question.
The situation is such that when I enter only the date (without time) in KeyboardDateTimePicker, I will be shown that the date is not valid, although the date is valid, I just did not enter the time, because it is not always required. How can this situation be defeated? If you select only the dates in the modal - everything is ok and time is automatically set.
Example: https://codesandbox.io/s/hidden-waterfall-lrnm7

![image](https://user-images.githubusercontent.com/12486958/75526120-3868c680-5a22-11ea-90fb-02732b2b7027.png)

**Comment by dmtrKovalenko** [comment]
There is no way. Use `DatePicker` and `TimePicker` separately
