### ISSUE TITLE
wrong display format in calender's popup 

### ISSUE THREAD

**Issue by alainib** [mui-org/material-ui-pickers#1542]
Hello

i'm trying to implement a calender with french/english local (user choice),  

![Capture d’écran 2020-02-28 à 10 34 06](https://user-images.githubusercontent.com/7910081/75537012-84ae0980-5a16-11ea-8f14-a15bbccc1830.png)

 

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   "^3.2.10"       |
| "@material-ui/core"|  "^4.9.4"| 
|"@material-ui/icons"|  "^4.9.1"| 
|"@material-ui/lab"| "^4.0.0-alpha.44"| 
|"formik-material-ui"| "^2.0.0-beta.1"|
|"formik-material-ui-pickers"| "^0.0.8"|								
|  "date-fns" | "^2.10.0"     |
| React                |      16.2.0   |
| Browser              |     firefox    |
|    "@date-io/date-fns" | "1.x",        |         

## Steps to reproduce

       import React from "react";

	import {Formik, Form, Field, useField} from "formik";

	import DateFnsUtils from "@date-io/date-fns";
	import {MuiPickersUtilsProvider} from "@material-ui/pickers";
	import {DatePicker} from "formik-material-ui-pickers";

	import frLocale from "date-fns/locale/fr";

	export const MyDatePickerField = ({...props}) => {
	  /*
	  const [field, meta, helpers] = useField(props);
	  console.log(field);
	  */
	  return (
	    <MuiPickersUtilsProvider utils={DateFnsUtils} locale={frLocale}>
	      <Field component={DatePicker} format="dd/MM/yyyy" {...props} className="MuiFormControl-root MuiTextField-root " />
	    </MuiPickersUtilsProvider>
	  );
	};

## Expected behavior

 how to correct the display from "ven., sept. 14" to "vendredi 14 septembre" or completly remove the pink div  ?

**Comment by dmtrKovalenko** [comment]
Fixed in v4
