### ISSUE TITLE
Cannot get the field value in data object

### ISSUE THREAD

**Issue by juanwilde** [mui-org/material-ui-pickers#1543]
I have this `KeyboardDateTimePicker`
```
                  <KeyboardDateTimePicker
                    name="date"
                    fullWidth
                    format="DD/MM/YYYY - H:mm"
                    ampm={false}
                    disabled={isLocked}
                    InputLabelProps={{ shrink: true }}
                    margin="normal"
                    label={t('assistance.form.fields.date')}
                    value={date}
                    onChange={handleOnChange}
                  />
```
When I trigger `handleOnChange` I'm getting this event
```
_isAMomentObject: true
_i: "1973-12-31T04:04:48+00:00"
_f: "YYYY-MM-DDTHH:mm:ssZ"
_tzm: 0
_isUTC: false
_pf: {empty: false, unusedTokens: Array(0), unusedInput: Array(0), overflow: -1, charsLeftOver: 0, …}
_locale: Locale {_calendar: {…}, _longDateFormat: {…}, _invalidDate: "Invalid date", _ordinal: "%dº", _dayOfMonthOrdinalParse: /\d{1,2}º/, …}
_d: Mon Dec 31 1973 05:04:48 GMT+0100 (Central European Standard Time) {}
_isValid: true
__proto__: Object
```
and this data object
```
"31/12/2019 - 13:04"
```

Problem is that I have more than one `KeyboardDateTimePicker` in the same form and I'd like to know the field name to update the state accordingly.

Thanks

**Comment by dmtrKovalenko** [comment]
The value is momentjs object. If you don’t use moment you can use date-fns utils to render picker and you will get the `Date` object in `onChange` callback

**Comment by juanwilde** [comment]
Sorry, maybe I didn't write it properly, but why I'm asking is in case of having more than one picker in the same component, how can I get the name of the picker changed. Because so far I'm only getting the value

**Comment by dmtrKovalenko** [comment]
@JuanWilde just take the same name as you are passing to picker.

**Comment by Domino987** [comment]
@dmtrKovalenko I think what he means is that the would like the get the event of the click to get event.target.name for example on the onChange callback.

**Comment by juanwilde** [comment]
Exactly. Imaging I have 2 pickers and one handler for the onChange event. I'd like to know which of those pickers triggered the change.
