### ISSUE TITLE
Ability to set DatePicker placeholder color. (Different color than text)

### ISSUE THREAD

**Issue by developdeez** [mui-org/material-ui-pickers#1551]
Have tried many of the stylings mentioned here and there doesnt seem to be a way to set placeholder to a color.
Im not talking about the text color. Just placeholder. The text that usually getting overwritten. Not the type and it floats to the top type of placeholder.

Expected (Grey to Black): 
![image](https://user-images.githubusercontent.com/13059525/75629497-70dde100-5b97-11ea-9fb7-deee4fe78b13.png)
![image](https://user-images.githubusercontent.com/13059525/75629500-7509fe80-5b97-11ea-8bfc-5c67430414d9.png)

Actual (Black to Black):
![image](https://user-images.githubusercontent.com/13059525/75629504-7d623980-5b97-11ea-82e5-bea6838d0307.png)
![image](https://user-images.githubusercontent.com/13059525/75629508-80f5c080-5b97-11ea-85b6-ca7f263f9c99.png)

**Comment by dmtrKovalenko** [comment]
This takes 5 minutes of googling. https://codesandbox.io/s/youthful-swirles-vh7lr
Please stop opening such issues on Github, open them on StackOverflow instead -- we expect only bug reports and feature requests on github

**Comment by developdeez** [comment]
Ok asked on stack. Not using a functional component and honestly a little weird to edit that color using css like other components.

**Comment by developdeez** [comment]
Im not even using functional component so its extra to find details on something that is so clearly undocumented.
