### ISSUE TITLE
Allow Icon Support for <DatePicker />

### ISSUE THREAD

**Issue by imcharliesparks** [mui-org/material-ui-pickers#1552]
![date pickers](https://i.imgflip.com/3r26en.jpg)

**Is your feature request related to a problem? Please describe.**
I've implemented your `<DatePicker />` component and would like to be able to be able to add an icon to the end of the textfield without having to provide a custom one.

**Describe the solution you'd like**
Something along the lines of `TextFieldProps` that you can provide an Icon to, or even a `hasIcon` flag that would render the default icon used by that type of picker.

**Describe alternatives you've considered**
I've considered writing a custom textfield input, but don't think it's worth the time.

**Additional context**
Library is cool!

**Comment by dmtrKovalenko** [comment]
Please describe your issue better, I don't understand what do you mean under `hasIcon` flag - datepicker will render an icon if there is a button to open, if not - no icon will be displayed. 
You can use `inputAdornent` API to provide a custom icon.

In future please use stackoverflow and [material-ui-pickers] tag to ask questions

**Comment by imcharliesparks** [comment]
@dmtrKovalenko, there is no support for `inputAdornment` on for the `<DatePicker />` component, according to your docs, that is why I requested this feature. I would like to use the `<DatePicker />` but give it an icon without providing a custom `<TextField />`, the way `<KeyboardDatePicker />` allows you to do.

**Comment by dmtrKovalenko** [comment]
you can use `InputProps` and `endAdornment` for `<DatePicker />` and `keyboardIcon` for `KeyboardDatePicker`

**Comment by imcharliesparks** [comment]
@dmtrKovalenko, thank you for that, it worked. It would be great to see `InputProps` added to the API docs for `<DatePicker />`, to avoid someone else having the same question.

Thanks for all the help!

**Comment by dmtrKovalenko** [comment]
`InputProps` are listed in text field api in material-ui
