### ISSUE TITLE
Make `Today` button work with 'autoOk' flag

### ISSUE THREAD

**Issue by imcharliesparks** [mui-org/material-ui-pickers#1553]
![date pickers again](https://i.imgflip.com/3r26en.jpg)
(sorry for the same meme on two requests)

**Is your feature request related to a problem? Please describe.**
I've implemented the `<DatePicker />` component and have the `autoOk` flag turned on. I also have the "Today" button enabled. At present, the user has to hit today, then click on the already highlighted date to get `autoOk` to close the calendar modal.

**Describe the solution you'd like**
It would be nice if, when `autoOk` is enabled, and the user hits "Today", it would have the same functionality as clicking a date with the `autoOk` flag enabled (i.e. closing the modal and setting the date without having to hit the confirm button).

**Describe alternatives you've considered**
No alternative I can think of that doesn't involve serious digging and custom method handlers

**Comment by oliviertassinari** [comment]
What version are you using? Did you try the v4 alpha?

---

In https://github.com/mui-org/material-ui-pickers/issues/1293, I have proposed to make autoOk the default behavior because it seemed to be more common. What do you think?

**Comment by dmtrKovalenko** [comment]
@oliviertassinari yes, it looks like a nice idea, I missed that while doing API changes

**Comment by imcharliesparks** [comment]
Thank you for taking the time to respond and act on this! 

@dmtrKovalenko @oliviertassinari
