### ISSUE TITLE
Question about Typo in documentation

### ISSUE THREAD

**Issue by FriendlyUser** [mui-org/material-ui-pickers#1556]
![image](https://user-images.githubusercontent.com/13860264/75795388-15425d80-5d27-11ea-8977-576265bfed2f.png)
I feel like the main page should say maintenance instead of project maintain

See https://material-ui-pickers.dev/

**Comment by oliviertassinari** [comment]
Starting this year:
- I have turned down all individual's donations to my Patreon to direct them to the "Material-UI OSS" OpenCollective.
- "Material-UI Inc." financially supports Dmitriy to advanced the mission of the company as a whole (date picker included).

Assuming we move forward with https://github.com/mui-org/material-ui/issues/19706, I think that we can ignore this problem, it will resolve itself with time.
