### ISSUE TITLE
Automatic locale?

### ISSUE THREAD

**Issue by ZYinMD** [mui-org/material-ui-pickers#1557]
My app is used by people around the world, and I hope to provide their native familiar calendar UI. I thought it must be a very common use case, but I read the docs about locale and i18n, and didn't find examples of how it's done.

Is it possible to automatically render different calendars based on the user's browser locale or language settings? 

One example of such things is the native `Date.prototype.toLocaleDateString()`, which automatically produces different results based on the value of `window.navigator.language`, which I'm very grateful for. I'm  using it in the non-calendar places in my app.

**Comment by airled** [comment]
You can pass locale as prop to `MuiPickersUtilsProvider`. 
Example for dayjs:
```js
...
import DayjsUtils from "@date-io/dayjs";
import { MuiPickersUtilsProvider } from "@material-ui/pickers";
import ru from 'dayjs/locale/ru'
import en from 'dayjs/locale/en'
...
return (
    <MuiPickersUtilsProvider utils={DayjsUtils} locale={en}>
...
```
Example for date-fns:
```js
...
import DateFnsUtils from "@date-io/date-fns";
import { MuiPickersUtilsProvider } from "@material-ui/pickers";
import fr from "date-fns/locale/fr";
import ru from "date-fns/locale/ru";
...
return (
    <MuiPickersUtilsProvider utils={DateFnsUtils} locale={fr}>
...
```
Create map object
```js
langs = {
  "en-US": en,
  "ru-RU": ru
}
```
and so on. Fetch locale by browser language and pass it as prop to mui provider. Don't forget to install proper `@date-io` version.

**Comment by oliviertassinari** [comment]
This seems to be a generic JavaScript question. I think that we can close it for StackOverflow.

Note that in the documentation, we use the `accept-language` dependency to match the supported locales of the website with the user's preference of locale. This works client-side only, for the server-side, it will depend on your stack, for express, you could find this middleware interesting: https://github.com/i18next/i18next-express-middleware/blob/013af5ed30410bb5375375c7aa1fe6219c2b783a/src/LanguageDetector.js.

**Comment by ZYinMD** [comment]
Thanks! Indeed I was aware I could import dozens of locales into my code and then manually pass in the user's locale, but just want to double check before reinventing the wheel.
