### ISSUE TITLE
KeyboardTimePicker - how to hide the button

### ISSUE THREAD

**Issue by chenop** [mui-org/material-ui-pickers#1561]
Tried to look for it in the API but could not find.
Is there a way to hide the picker button while using KeyboardTimePicker?

![image](https://user-images.githubusercontent.com/446575/76020585-5fe0f700-5f2c-11ea-8966-40cfb0c2a0e6.png)

**Comment by dmtrKovalenko** [comment]
I don't think you need to, but yeah it is possible using `KeyboardButtonProps={{ disabled: true, style: { display: 'none' }}`

**Comment by oliviertassinari** [comment]
@chenop What's your use case for hiding the calendar icon?

**Comment by chenop** [comment]
I have a web app which is compatible for mobile & desktop.
For the mobile I use TimePicker (with the dialog)
For the desktop version I use the KeyboardTimePicker but I thought it might be easier for the user to just type the time with the keyboard and not with the dialog - and I don't see why I should display the picker button.

Mobile
![image](https://user-images.githubusercontent.com/446575/76119317-da2a7d80-5ff7-11ea-96fb-736deba901e3.png)

Desktop
![image](https://user-images.githubusercontent.com/446575/76119242-b109ed00-5ff7-11ea-97db-73a350a3fb00.png)

**Comment by oliviertassinari** [comment]
Thanks for sharing
