### ISSUE TITLE
DesktopDatePicker change format issue - not updating date

### ISSUE THREAD

**Issue by iteashopcms** [mui-org/material-ui-pickers#1568]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 4.0.0-alpha.3 |
| material-ui          |  4.6.1 |
| Peer library         |   date-fns      |

## Steps to reproduce
1.Select date
2. Select date in format "dd/MM/yyyy" 
3. Change format in App.jsx to "MMM/dd/yyyy" (Added comments)
4. (Date does not change)

## Expected behavior
When I change the format dinamically, datepicker should rerender the selected date and display in the expected format.

## Actual behavior

For example, if format is "dd/MM/yyyy" and I switch to "MMM/dd/yyyy", value (date) does not update its format automatically, when it should.

## Live example

https://codesandbox.io/s/vigorous-khorana-zvfo8?file=/src/App.js

**Comment by frankruegamer** [comment]
I am experiencing the same issue, with alpha 4 as well. To add to this: The mask does update correctly, and the inputFormat only after selecting a date.

**Comment by oliviertassinari** [comment]
I could reproduce the issue: https://codesandbox.io/s/vigorous-khorana-zvfo8?file=/src/App.js. It comes from a missing dependency in an effect:
https://github.com/mui-org/material-ui-pickers/blob/2323a4b3e4e8479909ad5a9de4a671320506360f/lib/src/_shared/KeyboardDateInput.tsx#L86

I think that we should forbid all cases like this one (`// eslint-disable-line`).

@frankruegamer Do you want to work on a pull request? :)

**Comment by vdyachenko** [comment]
Hey @oliviertassinari! I just raised the PR regarding this issue. But I didn't find a proper place to add some testcase, any suggestions?

Thanks!
