### ISSUE TITLE
TimePicker: Can't select 2 am on the day DST goes into effect

### ISSUE THREAD

**Issue by IAmMarcellus** [mui-org/material-ui-pickers#1569]
![image](https://user-images.githubusercontent.com/26859964/76379455-7caf6d00-6326-11ea-9c3d-fabb3ffcd2bb.png)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.10 |
| material-ui          | 4.9.0 |
| TypeScript           | 3.5.3 |
| React                |16.8.6|
| Browser              |Chrome|
| Peer library         |Luxon 1.21.2|  |

## Steps to reproduce

1. Change system date to March 8th, 2020
2. Use time picker to set time to 2 am
3. Time will automatically skip to 3 am

## Expected behavior

2 am doesn't exist on the day that daylight saving time goes into effect (time goes from 1:59 to 3:00), however,  a time picker is expected to work independently of the date so DST shouldn't affect the time picked (i.e. the user should still be able to select 2 am without it switching)

## Actual behavior

Time switches from 2 am to 3 am because the TimePicker creates a DateTime object on the current day and  2 am doesn't exist on that day. The developer can't simply fix this by changing to a day that isn't affected by DST and then reverting back to 2 am because they have no way of knowing if the user intentionally selected 3 am or if it changed.

## Live example
 
N/A (the problem is dependent on your system date)

## Possible Solutions
1. Could pass the selected time as a string to the onChange method so that the developer can check the DateTime hour against the string and if they're different change the DateTime to a different day/week/etc. that isn't affected by daylight saving time.
2. Could allow the developer to set a default date for the TimePicker so that the DateTime object passed to the onChange method isn't a date affected by DST (this is the better option IMO).

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case with the latest version (v4.0.0-alpha.5 as we are writing). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/cool-cherry-v3cbt) _may_ be a good starting point. Thank you!

**Comment by IAmMarcellus** [comment]
@oliviertassinari As I mentioned in the original post, I can't provide a reproduction test case because the problem is dependent on your system time and I can't set that in a sandbox. The **only** way to reproduce this is to set the time on your **local system** to March 8th, 2020 (or the day that DST goes into effect for another year), then pull out **any** timepicker (the example sandbox you shared will work perfectly fine as is), and then try to set the time to 2 am. You'll see that you won't be able to and it'll auto switch to 3am, even though timepicker should work independently of the date. To see why this is a problem, lets say that a restaurant owner uses a time picker to set his opening and closing times and he's just switched to a late night schedule so he changes it to close at 2am. Well if he happens to try and do this on the week that DST goes into effect, it will switch to 3am as soon as he tries to change the closing time for that Saturday night to 2am Sunday morning (the day DST happens). However, the owner won't know why it switches because he's just trying to change the general closing time for every Saturday, so he shouldn't have to worry about the fact that 2am doesn't exist on that particular Saturday night/Sunday morning.

**Comment by pavel-remo** [comment]
Confirmed, this happened to us yesterday.

**Comment by IAmMarcellus** [comment]
If anyone is trying to set the time to 2am on Sunday, they will get this error this week if they're using a date library that starts the week on Monday (e.g. Luxon), or next week if they use a library that starts the week on Sunday.

@oliviertassinari I must apologize as I just figured out that I actually can reproduce this error in a sandbox by hardcoding the date to next Sunday so it doesn't rely on your system time for the date: https://codesandbox.io/s/mystifying-shockley-jlu59?file=/src/App.js. Sorry for not realizing that before!
