### ISSUE TITLE
TextFieldComponent leaves anchorEl undefined

### ISSUE THREAD

**Issue by defkev** [mui-org/material-ui-pickers#1570]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.10 |
| material-ui          | 4.9.5 |
| TypeScript           | 3.3.3 |
| React                | 16.12.0 |
| Browser              | FF Nightly |
| Peer library         | moment |  |

## Steps to reproduce

1. Add any inline picker with a custom `TextFieldComponent`

## Expected behavior

`anchorEl` should either be `event.currentTarget` or `ref.current` of the `TextFieldComponent`

## Actual behavior

`anchorEl` will be undefined
if manually defined using `PopoverProps` (using `event.currentTarget` or `ref.current`) it will be invalid???
only workaround is to wrap the picker with a `<div ref={...}>` and use its `ref.current` as the anchor

## Live example

Fiddle: https://codesandbox.io/s/mystifying-almeida-hjbpw

**Comment by raevillena** [comment]
setting the state to undefined seems more reasonable than setting it to null?

`    this.state = {
      selectedDate: new Date(),
      anchor: undefined
    };`

**Comment by raevillena** [comment]
Sorry, I don't understand what did you expect with the fiddle, I just fixed the error and posted suggestion here

**Comment by defkev** [comment]
I use the `Boolean(this.state.anchor)` to test wherever the popover is `open`
Doesn't really matter wherever its `null`, `undefined`, or `0`
What matter is that `anchorEl` isn't a DOM node.
Still, bonus points for afford.

**Comment by raevillena** [comment]
Yeah, ancholEl always needs an object to be passed in. feeding it with something else explains

**Comment by dmtrKovalenko** [comment]
Done in v4.0.0-alpha.3. Just forwardRef in your custom component
