### ISSUE TITLE
cannot modify offset value by hand

### ISSUE THREAD

**Issue by aMahdaoui** [mui-org/material-ui-pickers#1576]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.4      |
| material-ui          |    4.7.0     |
| TypeScript           |    js     |
| React                |      16.9.0   |
| Browser              |     chrome (latest)    |
| Peer library         |         date-fns 2.10.0 (also with moment)  |

## Steps to reproduce

1. use KeyboardDatePicker with format includes offset(timezone), like this 
```
 <KeyboardDatePicker 
          readOnly={false} 
          value={this.state.date} 
          onChange={this.handleDateChange} 
          clearable={true}
          format="DD/MM/YYYY HH:mm:ss xxx" // (for date-fns)
         // format="DD/MM/YYYY HH:mm:ss Z" (for moment)
        
 />
```
2. click date input and try to change date by hand  

## Expected behavior
be able to change date and change the timezone value

## Actual behavior
after clicking date input, the offset timezone format changed from `+01:00` to `010` and invalid date format error appears  
![image](https://user-images.githubusercontent.com/34797980/76519610-9bfee500-6461-11ea-9d20-380222c5f580.png)

## Live example
https://codesandbox.io/s/keyboarddatepicker-disabled-problem-with-calednar-icon-xc6o5

## P.S 
when i use the calendar popup to change date it works fine

**Comment by dmtrKovalenko** [comment]
You need to change mask prop. it should be like `__/__/__ __:__ +__:__` 
Working example: https://codesandbox.io/s/keyboarddatepicker-disabled-problem-with-calednar-icon-w4pn6

But please, use StackOverflow to ask questions
