### ISSUE TITLE
Weird display of DateTimePicker

### ISSUE THREAD

**Issue by tiaringhio** [mui-org/material-ui-pickers#1577]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.10     |
| material-ui          |     4.9.5    |
| TypeScript           |     js    |
| React                |    16.12.0     |
| Browser              |    chrome(latest)     |
| Peer library         |   date-fns 1.3.13      |  |

## Steps to reproduce

I'm using this configuration, the picker works perfectly but is display weirdly, i'm not using any css right now.

```javascript
<DateTimePicker
  open={this.state.isDatePickerOpen}
  onOpen={() => this.setState({ isDatePickerOpen: true })}
  onClose={() => this.setState({ isDatePickerOpen: false })}
  className="date-time-picker"
  disablePast={true}
  id="date-picker-dialog"
  label="Date picker dialog"
  format="dd/MM/yy, HH:mm"
  value={this.state.date}
  onChange={date => this.setState({ date }, this.updateDate)}
/>
```
## Expected behavior

![image](https://user-images.githubusercontent.com/37662752/76628240-b5c12a80-653c-11ea-8d76-3b32228bbed1.png)

## Actual behavior

![image](https://user-images.githubusercontent.com/37662752/76628198-a7730e80-653c-11ea-9899-c43b282dc02f.png)

## Live example

https://codesandbox.io/s/zealous-grothendieck-ht89g

**Comment by dmtrKovalenko** [comment]
Not reproducing on your live example
