### ISSUE TITLE
slideEnter animation for picker is wrong on annual transitions (e.g., moving date up 1yr)

### ISSUE THREAD

**Issue by iPzard** [mui-org/material-ui-pickers#1584]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    ^3.2.10     |
| material-ui          |    ^4.9.1     |
| TypeScript           |    n/a     |
| React                |    16.12.0     |
| Browser              |    Chrome     |
| Peer library         |    date-fns ^2.9.0     |

## Steps to reproduce
1. Update the state/date to go **forward** one **month**.
2. Update state/date to **backward** one **year**.
3. The transition for step 2 goes the wrong way.

## Expected behavior
Transition the correct direction, like months do.

## Actual behavior
The annual transition direction stays in the same direction set by the prior monthly transition.
It seems there is some logic to determine which direction the transition will go based on current and next month. But when moving up or down 1 year, it displays unexpected behavior by maintaining the prior transition direction, rather than determining the right direction on the fly.

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case with the latest version (v4.0.0-alpha.5 as we are writing). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/cool-cherry-v3cbt) _may_ be a good starting point. Thank you!

**Comment by oliviertassinari** [comment]
We have stopped support on v3. If you can reproduce the issue with v4, please let us know :).

**Comment by iPzard** [comment]
Looks like v4 of **@material-ui/pickers** is not out yet. Do you know when this is anticipated?

**Comment by oliviertassinari** [comment]
@iPzard You can already use the alpha: http://next.material-ui-pickers.dev/.

**Comment by iPzard** [comment]
Cool, thanks!
