### ISSUE TITLE
Cant trigger the minDateMessage for KeyboardTimePicker

### ISSUE THREAD

**Issue by feraraujofilho** [mui-org/material-ui-pickers#1585]
Feature:

At this moment, I have a disablePast props on my keyboardDatePicker component that triggers the mindDateMessage when that date is in the past. However, I cant trigger the minDateMessage in my KeyboardTimePicker since there is no disablePast props.

Solution:

Implement either a dateMin or disablePast props

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case with the latest version (v4.0.0-alpha.5 as we are writing). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/cool-cherry-v3cbt) _may_ be a good starting point. Thank you!

**Comment by oliviertassinari** [comment]
keyboardDatePicker was removed in v4.
