### ISSUE TITLE
Color prop

### ISSUE THREAD

**Issue by c0m1t** [mui-org/material-ui-pickers#1586]
**Is your feature request related to a problem? Please describe.**
I was wondering if there could be a `color` prop which could take `"primary" | "secondary"` as value. Maybe there could be  a`"dark"` color as well if `theme.palette.type="dark"`.  
Right now,  things like `color="primary"` for buttons and `backgroundColor:theme.palette.primary.main"` in `makeStyles` are hardcoded.

**Describe the solution you'd like**
I think it can be handled by adding some classes like `colorPrimary` and `colorSecondary`, like `material-ui` handles its `color`. And probably there should be a `Provider` to provide this `color` cause `color` prop has to be accessible by many components and at different nesting levels.

**Describe alternatives you've considered**
An easier way which I do it myself is to enclose the components by a `ThemeProvider` which would swap `primary` and `secondary` color if user provides `color="secondary"`

**Comment by dmtrKovalenko** [comment]
We are not wrapping our component in custom there provider. Just leveraging existing context, if you need to override a theme - you can wrap picker in the custom theme provider and override any style you need. 

But we are following material design specs, they explicitly describe which color should be applied to an element. So we will not add any additional props for changing colors
