### ISSUE TITLE
Button "TODAY" add optinal callback method

### ISSUE THREAD

**Issue by cristianManrique** [mui-org/material-ui-pickers#1587]
**Is your feature request related to a problem? Please describe.**

It's amazing how now we can load events from API when we change the month.

I create API call to load events with dates from API when we changes a month, It' work.

But I'm always frustrated when we click on "TODAY" button because I can not apply the callback method to re-call API

** User case **
On open Datepickers,  I load and display events on the calendar, after I change month, do an API call to reload events with dates, then I click to Today Button, Calendar goes back to actual month with a current date but I wish i can add a callback to re-load events from API.

** Solution **
Like "onMonthChange" method add "onTodayClick" props to add a callback method when we click on TODAY button

**Comment by oliviertassinari** [comment]
@RayanXY Please provide a full reproduction test case with the latest version (v4.0.0-alpha.5 as we are writing). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/cool-cherry-v3cbt) _may_ be a good starting point. Thank you!

**Comment by oliviertassinari** [comment]
@cristianManrique This sounds like a bug. Shouldn't `onMonthChange` be called when clicking on the today button change the currently displayed month?

**Comment by oliviertassinari** [comment]
I have tested it, it works fine.
