### ISSUE TITLE
[TypeScript miss match] Error Type '"size"' is not assignable to type

### ISSUE THREAD

**Issue by vimiPonyai** [mui-org/material-ui-pickers#1594]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   ^3.2.10      |
| material-ui          |     ^4.5.1    |
| TypeScript           |  ^3.5.2       |
| React                |     ^16.8.6    |
| Browser              |   chrome      |
| Peer library         |    @date-io/moment: ^1.3.13     |  |
| Peer library | "moment": "^2.24.0", |

Facing issue:
```
ERROR in [at-loader] ./node_modules/@material-ui/pickers/_helpers/text-field-helper.d.ts:27:219 
    TS2344: Type '"ref" | "label" | "select" | "style" | "title" | "children" | "color" | "margin" | "hidden" | "size" | "open" | "disabled" | "onAccept" | "okLabel" | "cancelLabel" | "clearLabel" | ... 307 more ... | "onYearChange"' does not satisfy the constraint '"ref" | "label" | "select" | "style" | "title" | "children" | "color" | "margin" | "hidden" | "open" | "disabled" | "onAccept" | "okLabel" | "cancelLabel" | "clearLabel" | "todayLabel" | ... 308 more ... | "openTo"'.
  Type '"size"' is not assignable to type '"ref" | "label" | "select" | "style" | "title" | "children" | "color" | "margin" | "hidden" | "open" | "disabled" | "onAccept" | "okLabel" | "cancelLabel" | "clearLabel" | "todayLabel" | ... 308 more ... | "openTo"'.
```

Since i am not similar with frontend, so i am still trying to add live example. But i just setup by the
https://material-ui-pickers.dev/getting-started/usage

**Comment by vimiPonyai** [comment]
it seems without any issue using `"@material-ui/core": "^4.9.7",` but any idea to reslove that issue? Thanks

**Comment by dmtrKovalenko** [comment]
Try update material-ui to the latest version

**Comment by oliviertassinari** [comment]
@dmtrKovalenko A side note, I have noticed that the next branch runs with a 1 month old version:
https://github.com/mui-org/material-ui-pickers/blob/4d04b43589133ce555af5b9cba45063924d013b9/yarn.lock#L1638-L1639

It could help to update it.

**Comment by vimiPonyai** [comment]
Thanks all of you. @dmtrKovalenko @oliviertassinari 
Since this problem already solved. So I close this issue item.
