### ISSUE TITLE
Implement forwardRef

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1604]
While https://github.com/mui-org/material-ui-pickers/pull/1593 is a great step forward, I believe there is still work needed to be done in order to match the expectations developers have built using the core components:

### 1. Public components missing forwardRef:

- Calendar
https://github.com/mui-org/material-ui-pickers/blob/5560ade36a42a038bfef0cae25055ebc50577982/lib/src/views/Calendar/Calendar.tsx#L96
- ClockView
https://github.com/mui-org/material-ui-pickers/blob/5560ade36a42a038bfef0cae25055ebc50577982/lib/src/views/Clock/ClockView.tsx#L84

### 2. Ref not forwarded on the root element:

The ref is forwarded to the underlying `<input>` element, which is not the root element: 

- StaticTimePicker
- MobileTimePicker
- DesktopTimePicker
- TimePicker
- DatePicker
- MobileDatePicker
- StaticDatePicker
- DekstopDatePicker
- DateTimePicker
- MobileDateTimePicker
- StaticDateTimePicker
- DekstopDateTimePicker 

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | v4.0.0-alpha.4  |

## Steps to reproduce

https://codesandbox.io/s/gracious-haibt-0pnhc

**Comment by stunaz** [comment]
Hello @oliviertassinari , why isnt this part of V4... I think it was fine with material-ui@v4..... but with material-ui@v5 it breaks all over the place.

**Comment by oliviertassinari** [comment]
@stunaz ?
