### ISSUE TITLE
Programmatically fire open picker option is missing in 4.0.0-alpha.4

### ISSUE THREAD

**Issue by debojyoti** [mui-org/material-ui-pickers#1605]
As per the release note of 4.0.0-alpha.4, the ref is passed to the input field.

But still, a pickerRef is required to open the picker programmatically.

Or more specifically, ref to wrapper is required

**Comment by dmtrKovalenko** [comment]
There is `open` prop for that https://material-ui-pickers.dev/guides/controlling-programmatically
