### ISSUE TITLE
Display week numbers

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1611]
Got a feature request to be able display week numbers in calendar.

**Comment by HolgerWeber** [comment]
![pickerWithWeeks](https://user-images.githubusercontent.com/17291425/77894507-aa2c6e00-7275-11ea-89da-fb54ffb3c54e.png)
We really would appreciate to have it similar like this.
Thanks

**Comment by oliviertassinari** [comment]
@dmtrKovalenko I'm happy to see you changed your mind 👍 (#521), I was proposing this API in https://github.com/mui-org/material-ui-pickers/issues/1293#issuecomment-538374383:

```js
  /**
   * If `true`, a column is added to show the week numbers of the year.
   *
   * default false
   */
  showWeekNumbers: PropTypes.bool,
```

**Comment by oliviertassinari** [comment]
Duplicate of #521
