### ISSUE TITLE
DatePicker - leave value blank/empty until user takes action?

### ISSUE THREAD

**Issue by WGriffing** [mui-org/material-ui-pickers#1613]
Hello,

First, my apology if I'm posting in the wrong place or if this has been answered before. I did search, but didn't find any similar questions.

With that out of the way, my question is whether it's possible to use `DatePicker` (or `KeyboardDatePicker`, etc.) and have it initialize without automatically filling in the current date when the value passed in is `null`?

For my use case, the valid values of my DatePicker input are `null` as well as a user-specified date. The behavior seems to be that `null` values are turned into `nowRef.current` (via `useValueToDate` method (see: https://github.com/mui-org/material-ui-pickers/blob/master/lib/src/_shared/hooks/usePickerState.ts ) during initialization. 

For my case, I need the value to stay `null`/empty unless my user explicitly picks a date so I am looking for a way to prevent this automatic initialization from occurring.

Is there a prop or setting that I should look into? Or, perhaps a workaround that anyone can suggest?

Thanks.

**Comment by oliviertassinari** [comment]
@WGriffing Do you have a reproduction? What happens with @material-ui/pickers@4.0.0-alpha.4?

**Comment by WGriffing** [comment]
> @WGriffing Do you have a reproduction? What happens with @material-ui/pickers@4.0.0-alpha.4?

@oliviertassinari Thanks for the quick response.

Here's a very basic reproduction: https://codesandbox.io/s/datepicker-problem-3ix1y

When the page loads, see how the date is already filled in with today's date? I'm trying to avoid that behavior. I prefer it to remain blank until the user picks a date.

I tried upping the picker dependency to 4.0.0-alpha.4, but I get errors from CodeSandbox.

**Comment by oliviertassinari** [comment]
@WGriffing I would expect

```jsx
<DatePicker defaultValue={null} />
```

to solve the problem. If it doesn't work, unless more information is provided, I think that the behavior should be categorized as a bug.

For v4, I can confirm the same behavior: https://codesandbox.io/s/bold-williams-nnpd0.

**Comment by WGriffing** [comment]
@oliviertassinari 

Thanks for your help. 

I don't see a `defaultValue` prop in the docs: https://material-ui-pickers.dev/api/DatePicker . Did you mean `value={null}` instead?  Adding `value` that to the CodeSandbox produced the desired effect for me.

My use case is more complicated than the example I showed (Formik + formik-material-ui + formik-material-ui-pickers) and using `value` prop doesn't resolve it there, unfortunately. However, I think we have proven that the issue is elsewhere in one of the other packages so I will not take up any more of your time.

**Comment by oliviertassinari** [comment]
Actually, it seems to work fine. I think that we should label it as a feature request for a `defaultProp`.

**Comment by EdwardSalter** [comment]
What was the outcome of this issue? Looking at the CodeSandbox examples above it looks like the control behaves as expected when using a standard DatePicker control with TextField but not for my use case where I am using the static variant to have the Calendar always visible.
The DatePicker accepts null as it's `value` prop but somewhere during it's initialisation it calls the attached `onChange` callback with the first non-disabled date it comes across therefore the calendar has this date selected.
Interestingly, if the Calendar component is used instead, passing a `null` value to the `date` prop results in a runtime error.

**Comment by WGriffing** [comment]
For me, the problem was that the field I connected to my `DatePicker` sometimes didn't exist. I knew this and I had assumed that a non-existent attribute in my data variable would work the same as `null` and result in an empty `DatePicker` waiting for user action. That was a bad assumption, but I couldn't figure out my error so I opened an issue to see if I was missing anything obvious (which I was).

Once Oliver helped me understand how it was supposed to work, I had to apply it to my situation.

The fix for me was to inspect my data variable (within my `Formik` component's `initialValues` prop) and check if my date field was not present. If it's not present, I create it and set it to `null`. If it is present, I simply use its value.

**Comment by amitkumarc2fo** [comment]
Any solution for `static` variant of `DatePicker`?
https://github.com/mui-org/material-ui-pickers/issues/1613#issuecomment-610266442

**Comment by amitsainii** [comment]
> What was the outcome of this issue? Looking at the CodeSandbox examples above it looks like the control behaves as expected when using a standard DatePicker control with TextField but not for my use case where I am using the static variant to have the Calendar always visible.
> The DatePicker accepts null as it's `value` prop but somewhere during it's initialisation it calls the attached `onChange` callback with the first non-disabled date it comes across therefore the calendar has this date selected.
> Interestingly, if the Calendar component is used instead, passing a `null` value to the `date` prop results in a runtime error.

Any solution for `static` variant of `DatePicker`?

**Comment by jr-duarte** [comment]
Se estiver usando hookform controller

```
<Controller
      name={name}
      control={control}
      render={({ field, fieldState: { error } }) => (
        <DatePicker
          {...field}
          value={field.value || null}
          inputFormat="dd/MM/yyyy"
          renderInput={(params) => (
            <TextField
              {...params}
              {...other}
              fullWidth
              error={!!error}
              helperText={error?.message}
            />
          )}
        />
      )}
    />
```

**Comment by KristiyanTs** [comment]
You could control the state of the date picker's TextField slot like this:

 ```
           <DatePicker
              slotProps={{
                textField: {
                  error: false,
                },
              }}
            />
```
