### ISSUE TITLE
Invalid date value turns value to "1970-01-01" in KeyboardDatePicker

### ISSUE THREAD

**Issue by yulyasystem** [mui-org/material-ui-pickers#1614]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.9      |
| material-ui/core          |   4.9.0      |
| React                |  16.12.0       |
| Browser              |    Firefox, Google Chrome     |
| date-io/date-fns       |   1.3.13 |  |
| date-fns       |   2.9.0 | 
## Steps to reproduce

1. In KeyboardDatePicker start to clear using Backspace on the keyboard

## Expected behavior
Expected not date to be selected or subtituted.

## Actual behavior
Date value is substituted to "1970-01-01"

I was trying to check for invalid date in "onChange" but it does not work.

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript) _may_ be a good starting point. Thank you!

Also, can you reproduce it with v4.0.0-alpha.4?
