### ISSUE TITLE
Customizing days headers

### ISSUE THREAD

**Issue by vla9isla8** [mui-org/material-ui-pickers#1616]
Hello!
I want show selected day of a week in days header component.
Need ability to set custom **renderDayLabel** function like **renderDay** or add new css class  **dayLabelSelected** to be able customizing elements.

**Comment by dmtrKovalenko** [comment]
I am not sure that is rare case, so I would recommend using combination of override + `:nth-child` in order to implement it. 

In v4 we will release better style overrides for picker content, so it will be easier to achieve override

**Comment by vla9isla8** [comment]
@dmtrKovalenko There is no information in material-ui theme overrides about selected day. I don't see another option to apply styles to MuiPickersCalendarHeader dayLabel. If you know how, share with me, please :)

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Have you considered the option to allow developers to extend the `defaultHighlight` prop to make it fully controllable?

Basically we could expose the value/onChange of StaticDatePicker under a different prop for DatePicker. I could imagine selected/onSelectedChange, similar to what http://react-day-picker.js.org/examples/selected-state has.
@vla9isla8 with this state, would you be able to implement your customization?
