### ISSUE TITLE
Basic DateRangePicker example

### ISSUE THREAD

**Issue by ghost** [mui-org/material-ui-pickers#1618]
Hello,

Can me already use this DatePicker?
https://material-ui-pickers-git-feature-daterangepicker.mui-org.now.sh/demo/daterangepicker

I want to use this:
https://i.imgur.com/pfnx7fX.png

Thanks!

**Comment by oliviertassinari** [comment]
Not yet.

**Comment by Angelk90** [comment]
@oliviertassinari : Can't use it yet?

**Comment by oliviertassinari** [comment]
@Angelk90 It was published on npm now. I think that we should take another 2 months to polish it.
