### ISSUE TITLE
TypeError: utils.toJsDate is not a function upon changing anything in datepicker

### ISSUE THREAD

**Issue by pipje2001** [mui-org/material-ui-pickers#1625]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |^4.0.0-alpha.4 |
| material-ui          |^4.9.0|
| TypeScript           |no|
| React                |^16.10.2|
| Browser              |Vivaldi|
| Peer library         |date-fns ^2.0.0-beta.5|  |

## Steps to reproduce

Use any date/time picker with alpha 4? 
I updated from alpha 1, upon updating i needed to change some prop names and use LocalizationProvider as described in all the patch notes. 

## Expected behavior

The date to change

## Actual behavior

The modal opens fine (although there is a wierd black line around it?), but when i click on a month i get this error: TypeError: utils.toJsDate is not a function.

## Live example

Working on in (can't get it to reproduce yet)
https://codesandbox.io/s/competent-sunset-zovym
Cant even get the sandbox to work, for some reason DateFnsUtils is undefined
## DatePicker:

<MobileDatePicker
              variant="outlined"
              label="Date"
              openTo="month"
              views={['year', 'month', 'date']}
              inputFormat="dd/MM/yyyy"
              defaultHighlight={new Date().setHours('00', '00', '00')}
              value={lessonDate}
              onChange={e => {
                setLessonDate(e);
                setLessonDateError(false);
                setLessonStartTime(e);
                setLessonStartTimeError(false);
                setLessonEndTime(e);
                setLessonEndTimeError(false);
              }}
              error={lessonDateError !== false}
              helperText={lessonDateError}
              fullWidth
            />

**Comment by oliviertassinari** [comment]
> Cant even get the sandbox to work, for some reason DateFnsUtils is undefined

@pipje2001 I could reproduce that problem. Opening #1627. In the meantime, you can start from https://codesandbox.io/s/gracious-haibt-0pnhc.

**Comment by oliviertassinari** [comment]
The issue has been closed because it does not conform to our issue requirements. 
Please provide a full reproduction test case. This would help a lot 👷 .
