### ISSUE TITLE
How to customize start day of week to arbitrary values (not based on the locale)?

### ISSUE THREAD

**Issue by sandeepkumar-vedam-by** [mui-org/material-ui-pickers#1626]
How can I display start day of the week as Wednesday? I didn't see any props to pass day number.

**Comment by dmtrKovalenko** [comment]
Hey, thanks for issue. What’s your use case? If there is a locale where week starts from Wednesday — you can set this locale and pickers will change the first day of week

**Comment by sandeepkumar-vedam-by** [comment]
It's not about locale. Sometimes as per business requirement customer may want to show start day of the week as any day. Example: Currently, material-ui-pickers are showing Sunday as starting day of week but I want to display Wednesday as starting day of week.

**Comment by dmtrKovalenko** [comment]
Haha, I had no idea that somebody will need to change first day of week outside of locale. 

Now it is possible only with overriding `getWeeksArray`method of date-io

**Comment by sandeepkumar-vedam-by** [comment]
Yes. We have to override getWeekArray method. I am playing with sandbox url as you mentioned in one ticket https://codesandbox.io/s/material-ui-pickers-usage-demo-p753d?file=/src/App.jsx

I am trying to reduce (minus) no of days as per weekDays order. Please see below snippet

Will this work? Please suggest approach.

<img width="184" alt="startday" src="https://user-images.githubusercontent.com/62013324/78635507-03bf1900-78c4-11ea-829b-d97c9cebea6e.PNG">

**Comment by sandeepkumar-vedam-by** [comment]
Could you please give suggestions or help on this issue? @dmtrKovalenko @oliviertassinari

**Comment by sandeepkumar-vedam-by** [comment]
@dmtrKovalenko Customized `getWeeksArray` method of date-io. It's working as of now. I'll check all scenarios with my solution. Thanks

**Comment by oliviertassinari** [comment]
@sandeepkumar-vedam-jdas Could you share your solution? Hopefully, it will help others :)

**Comment by sandeepkumar-vedam-by** [comment]
@oliviertassinari @dmtrKovalenko Sure :)
Here is the sandbox link: https://codesandbox.io/s/material-ui-pickers-usage-demo-ox9n8?file=/src/App.jsx

We can pass any week day in constructor and it will update the calendar start day of the week accordingly.

```jsx
import React, { useState } from "react";
import LuxonUtils from "@date-io/luxon"; // choose your lib
import {
  DatePicker,
  TimePicker,
  DateTimePicker,
  MuiPickersUtilsProvider
} from "@material-ui/pickers";

class DataWrapper {
  default = [
    {
      index: 0,
      name: "Sun",
      dayName: "S"
    },
    {
      index: 1,
      name: "Mon",
      dayName: "M"
    },
    {
      index: 2,
      name: "Tue",
      dayName: "T"
    },
    {
      index: 3,
      name: "Wed",
      dayName: "W"
    },
    {
      index: 4,
      name: "Thu",
      dayName: "T"
    },
    {
      index: 5,
      name: "Fri",
      dayName: "F"
    },
    {
      index: 6,
      name: "Sat",
      dayName: "S"
    }
  ];
  dayNames = ["S", "M", "T", "W", "T", "F", "S"];

  processedDayNames = [];

  startDay = {};

  // constructor() {
  //     this.processWeekDayOrder('Wed');
  // }
  setStartDay(dayName) {
    const x = this.default.filter(day => dayName === day.name);
    this.startDay = x[0];
  }

  processWeekDayOrder() {
    const days = [...this.dayNames];
    const remainingDays = days.splice(0, this.startDay.index);
    this.processedDayNames = days.concat(remainingDays);
    console.log("days", this.processedDayNames);
    return this.processedDayNames;
  }
}

export class CustomLuxonUtils extends LuxonUtils {
  dayNames = ["S", "M", "T", "W", "T", "F", "S"];

  wrapper;

  constructor() {
    super();
    this.wrapper = new DataWrapper();
    this.wrapper.setStartDay("Thu");
  }

  getWeekdays() {
    return this.wrapper.processWeekDayOrder();
  }

  getWeekArray(date) {
    console.log("date", date);
    const index = this.wrapper.startDay.index;
    const endDate = date
      .endOf("month")
      // if a month ends on sunday, luxon will consider it already the end of the week
      // but we need to get the _entire_ next week to properly lay that out
      // so we add one more day to cover that before getting the end of the week
      .plus({ days: index !== 0 ? this.dayNames.length + 1 - index : 1 })
      .endOf("week");
    const startDate = date
      .startOf("month")
      .startOf("week")
      // must subtract 1, because startOf('week') will be Mon, but we want weeks to start on Sun
      // this is the basis for every day in a our calendar
      .minus({ days: index !== 0 ? this.dayNames.length + 1 - index : 1 });

    const { days } = endDate.diff(startDate, "days").toObject();

    const weeks = [];
    new Array(Math.round(days))
      .fill(0)
      .map((_, i) => i)
      .map(day => startDate.plus({ days: day }))
      .forEach((v, i) => {
        if (i === 0 || (i % 7 === 0 && i > 6)) {
          weeks.push([v]);
          return;
        }

        weeks[weeks.length - 1].push(v);
      });
    console.log("weeks", weeks);
    // a consequence of all this shifting back/forth 1 day is that you might end up with a week
    // where all the days are actually in the previous or next month.
    // this happens when the first day of the month is Sunday (Dec 2019 or Mar 2020 are examples)
    // or the last day of the month is Sunday (May 2020 or Jan 2021 is one example)
    // so we're only including weeks where ANY day is in the correct month to handle that
    return weeks.filter(w => w.some(d => d.month === date.month));
  }
}

function App() {
  const [selectedDate, handleDateChange] = useState(new Date());

  return (
    <MuiPickersUtilsProvider utils={CustomLuxonUtils}>
      <DatePicker value={selectedDate} onChange={handleDateChange} />
      <TimePicker value={selectedDate} onChange={handleDateChange} />
      <DateTimePicker value={selectedDate} onChange={handleDateChange} />
    </MuiPickersUtilsProvider>
  );
}

export default App;
```

**Comment by oliviertassinari** [comment]
@sandeepkumar-vedam-jdas Awesome! It starts with Thursday instead of Wednesday. Is it expected?

<img width="296" alt="Capture d’écran 2020-04-10 à 15 55 25" src="https://user-images.githubusercontent.com/3165635/78995918-bf41b080-7b43-11ea-8774-14ddc3c4d686.png">

**Comment by sandeepkumar-vedam-by** [comment]
@oliviertassinari You can pass any day name in constructor. Currently, i passed Thu so it is displayed as T as start day. If you pass Wed and it will start with W and display calendar days accordingly.

**Comment by sandeepkumar-vedam-by** [comment]
@oliviertassinari Also, how to display week numbers in calendar as first column? Do we have any customization for that?

**Comment by oliviertassinari** [comment]
> You can pass any day name in constructor.

@sandeepkumar-vedam-jdas Great, so we can close the issue.

> how to display week numbers in calendar as first column? Do we have any customization for that?

See #521.

**Comment by markatlish** [comment]
@oliviertassinari This effectively means US-based users can't use material-ui-pickers w/ Luxon, a nasty surprise.  Luxon hardcodes the week start to Monday (see https://github.com/moment/luxon/issues/373) and material-ui-pickers doesn't support overriding it easily (see https://github.com/mui-org/material-ui-pickers/issues/1626#issuecomment-612031743)

**Comment by oliviertassinari** [comment]
@markatlish Luxon isn't very popular, so not a high priority for us. In https://github.com/mui-org/material-ui-pickers/issues/1898 I propose we inline date io to have more flexibility to fix this problem.

**Comment by robincsamuel** [comment]
@sandeepkumar-vedam-by Thanks for sharing the solution :)

I had to make a small modification to make it work (I'm using v4). The `getWeekArray` & `getWeekDays` methods weren't getting overridden. I had to change that to an arrow function.
