### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1627]
The documentation [encourages](https://next.material-ui-pickers.dev/getting-started/installation) the usage of:

```jsx
// pick a date util library
import DateFnsUtils from '@material-ui-pickers/adapter/date-fns';
```

Unfortunately, it doesn't seem to work: https://codesandbox.io/s/ecstatic-solomon-v4gvv.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | v4.0.0-alpha.5 |

**Comment by dmtrKovalenko** [comment]
Haha typo -> `@material-ui/pickers/adapter/date-fns`
@material-ui[/]pickers

**Comment by oliviertassinari** [comment]
A good one to fix 😆 but it might not be enough.
The reproduction uses `@material-ui/pickers/adapter/date-fns`.

**Comment by dmtrKovalenko** [comment]
Oh god, I forgot to fix this before release

**Comment by oliviertassinari** [comment]
@dmtrKovalenko I think that it's fine, it's an alpha anyway. I think that we should more aim on making releases on a fixed schedule than aiming for releasing a specific set of changes :).

**Comment by mifrej** [comment]
Could we please release next alpha with this.

**Comment by oliviertassinari** [comment]
@mifrej a new alpha version has been release with the changes.

**Comment by mifrej** [comment]
Already on it! Keep the great work! Thanks
