### ISSUE TITLE
Customizing the number of days in a month

### ISSUE THREAD

**Issue by sole6** [mui-org/material-ui-pickers#1628]
**Is your feature request related to a problem? Please describe.**
I want to create a datepicker with 30 days per month (yes It is weird :))

**Describe the solution you'd like**
I would like to customize the date picker to handle limiting the days to 30 in a month.
My goal is to create an Ethiopian Calendar. https://en.wikipedia.org/wiki/Ethiopian_calendar
I was able to do most of the localization, except for setting the number of days in a month. As u can see, the calendar has 30 days of 12 months and one 5/6 days month.

Is there a way to it this?

**Comment by oliviertassinari** [comment]
> I want to create a datepicker with 30 days per month

@sole6 Could you explain the problem you are trying to solve? Thanks

**Comment by sole6** [comment]
> > I want to create a datepicker with 30 days per month
> 
> @sole6 Could you explain the problem you are trying to solve? Thanks

Updated the description

**Comment by dmtrKovalenko** [comment]
You can do that based on date-io https://github.com/dmtrKovalenko/date-io
It is a simple abstraction with already implemented `jalaali` and `hijiri` calendars. You can simply extend one of the current utils and override appropriate methods. 

And will be even better if you will be able to publish your package to npm, so anybody will be able to use Ethiopian Calendar with material-ui-pickers. 

I`ll close this issue, let me know if you need any help

**Comment by sole6** [comment]
> You can do that based on date-io https://github.com/dmtrKovalenko/date-io
> It is a simple abstraction with already implemented `jalaali` and `hijiri` calendars. You can simply extend one of the current utils and override appropriate methods.
> 
> And will be even better if you will be able to publish your package to npm, so anybody will be able to use Ethiopian Calendar with material-ui-pickers.
> 
> I`ll close this issue, let me know if you need any help

Thanks for the feedback.
I started an experiment with it. Maybe I am doing it wrong, but how do I configure the start and end of the month. When I try to pass date, I get an error
 ```
Uncaught TypeError: date.clone is not a function
    at MomentUtils.startOfMonth
```

Maybe this is not the place to post this question.
