### ISSUE TITLE
Regulate date range validation strategy

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1635]
There are couple of questions about validation. 

1) What if some day is between selected range? Should we block selecting range?
2) If so — should we provide `shouldDisableRange` instead of `shouldDisableDate` prop in order to improve performance. 
3) Do we need any prop for maximal/minimal date range length?

**Comment by oliviertassinari** [comment]
1. What does it mean?
2. 
3. Could it be already implemented user-land by controlling the `maxDate` prop? It seems so, if it's the case, I would be in favor of leaving to the users. I mean, unless it has been a frequent request on https://www.daterangepicker.com/ or alternative popular date range pickers.

**Comment by dmtrKovalenko** [comment]
@oliviertassinari I mean if weekends are disabled – should we allow to select only range from Monday to Friday? 
![image](https://user-images.githubusercontent.com/16926049/79111748-ca841e80-7d85-11ea-9f63-1b181ecdf813.png)

Or we need to only disable making range end not selectable? 
![image](https://user-images.githubusercontent.com/16926049/79111791-dc65c180-7d85-11ea-98f0-1a9f463ab068.png)


https://codesandbox.io/s/sparkling-brook-f92d4?file=/src/App.jsx

**Comment by oliviertassinari** [comment]
@dmtrKovalenko I think that we could go with the simplest option. "Disabled days" are days people can't start selecting or end selecting from. Then, later on, we could add a `contiguousRange` prop, so prevent end-users from having a range the go over disabled dates. What do you think?

**Comment by dmtrKovalenko** [comment]
Ok, so we can change this issue for now

**Comment by oliviertassinari** [comment]
@dmtrKovalenko What do you think of exposing a method to allow the developers to implement custom logic? (contiguous, max length, etc.)

**Comment by dmtrKovalenko** [comment]
Yeah it could be an option, but too complicated.

**Comment by oliviertassinari** [comment]
Cool, let's wait for user requests :)

**Comment by oliviertassinari** [comment]
Linking https://github.com/mui-org/material-ui-pickers/issues/1759#issuecomment-628894726 as we are discussing the same problem.
