### ISSUE TITLE
Date range picker with time

### ISSUE THREAD

**Issue by Angelk90** [mui-org/material-ui-pickers#1636]
**Is your feature request related to a problem? Please describe.**
In addition to selecting a start and end data, I would also need to select a start and end time beyond the data.

**Describe the solution you'd like**
I click on the input field, I am asked to select a start date, as soon as I select the start date it asks me for a 24 hour format start time, then I am asked to select the second date the end date when the end date was selected asks me to select the second time the end time format 24 hours.

@oliviertassinari , @dmtrKovalenko : #47 

https://github.com/mui-org/material-ui-pickers/issues/364#issuecomment-554266873

![](https://user-images.githubusercontent.com/20476002/68929088-dd210a00-078b-11ea-8860-a34ea10ab09c.png)

![](https://developer.mindsphere.io/resources/mindsphere-webcomponents/images/datetimerange-picker.png)

![](https://i.pinimg.com/originals/69/9f/cb/699fcbc208df42b14a8bee710b845bcf.png)

**Comment by Angelk90** [comment]
@oliviertassinari , @dmtrKovalenko: Is there any news?

**Comment by oliviertassinari** [comment]
It's not a priority for now, maybe this summer in the enterprise version.

**Comment by sebastianvoss** [comment]
@oliviertassinari As this recently got closed, I'm curious if this is still a valid feature request. We would benefit from such addition (we have licensed the enterprise version).
