### ISSUE TITLE
[DateRangePicker] Support a single input field

### ISSUE THREAD

**Issue by Angelk90** [mui-org/material-ui-pickers#1637]
**Is your feature request related to a problem? Please describe.**
Having two input fields for selecting a range of dates, start and end, is very annoying.

**Describe the solution you'd like**
Have only one input field, which can have the start and end date as in the figure, in addition to the time if it is selected.

@dmtrKovalenko , @oliviertassinari : 

![](https://user-images.githubusercontent.com/20476002/77849355-5bc29500-71cb-11ea-8463-c11a6e58fb0d.png)

**Comment by oliviertassinari** [comment]
> is very annoying.

@Angelk90 Could you expand on what's very annoying?
For benchmark, I have only seen this approach used in https://ej2.syncfusion.com/react/demos/#/material/daterangepicker/default

**Comment by Angelk90** [comment]
@oliviertassinari :  On which benchmark have you seen it?

For the kind of user experience I want to give for the ui I'm using, having only one input field would be better for me.

React:

http://projects.wojtekmaj.pl/react-daterange-picker

https://technikhil314.github.io/react-datetimerangepicker


https://github.com/v0ltoz/react-datetimepicker

https://github.com/aadilhasan/react-range-picker

Other:

https://ngx-daterange.netlify.com

https://www.daterangepicker.com

**Comment by oliviertassinari** [comment]
@dmtrKovalenko I would propose we close as "won't fix".

**Comment by dmtrKovalenko** [comment]
Yes, because it is not matched with material design guidelines and there is actually no real requirement to combine inputs.

**Comment by maikeledev** [comment]
It could be nice to have a prop for this. In my current project, I was using another option with a single input, but now that you finished the date range I have to switch and keep the styles.

**Comment by Angelk90** [comment]
@mesvil7 : Which one were you using?
Could you post a photo of the calendar you use?

**Comment by maikeledev** [comment]
@Angelk90 
<img width="539" alt="Screen Shot 2020-04-15 at 3 04 21 PM" src="https://user-images.githubusercontent.com/1686006/79390204-87b07b00-7f2c-11ea-96c6-908c3abc261f.png">
It's a combination of TextField and the Calendar.

You can probably replicate the same with material daterangepicker static mode.
something like this using React.
```
<Box position="relative">
  <TextField  value={calendarValue} onClick={toggleCalendar} ... /> 
     { isOpenCalendar && (
      <React.Fragment>
        <StaticDateRangePicker
          displayStaticWrapperAs="desktop"
          value={selectedDate}
          onChange={date => handleDateChange(date)}
        />
         <span className={classes.overlay} onClick={toggleCalendar}>
            &nbsp;
         </span>
      </React.Fragment>
     )}
</Box>
```

**Comment by oliviertassinari** [comment]
I have replaced the "won't fix" label with "waiting for upvotes". It might be a frequent use case, we will see.

<img width="527" alt="Capture d’écran 2020-04-18 à 13 03 19" src="https://user-images.githubusercontent.com/3165635/79636032-27f8e080-8175-11ea-8cd5-d474fa605ace.png">

*crowdin.com*

**Comment by dmtrKovalenko** [comment]
I do want to clarify why 2 inputs were required by material design guidelines:

1) Accessibility — with 1 input it is extremely hard to input date with only keyboard for blind people
2) Highlighting current selection (start or end) — by clicking on specific input we are moving current selection according to input.  

We could probably mimic this behavior with styles (like react dates doing) — render styles for 1 input but render 2 html inputs inside.

**Comment by ravi-poonia** [comment]
if someone is looking for simple patch 

```
<DateRangePicker
     renderInput={({ inputProps, ...startProps }, endProps) => {
          const startValue = inputProps.value;
          delete inputProps.value
          return (
            <TextField
              {...startProps}
              inputProps={inputProps}
              value={`${startValue}-${endProps.inputProps.value}`}
           />
)}/>

```

**Comment by sherinshaju** [comment]
> if someone is looking for simple patch
> 
> ```
> <DateRangePicker
>      renderInput={({ inputProps, ...startProps }, endProps) => {
>           const startValue = inputProps.value;
>           delete inputProps.value
>           return (
>             <TextField
>               {...startProps}
>               inputProps={inputProps}
>               value={`${startValue}-${endProps.inputProps.value}`}
>            />
> )}/>
> ```

awsome brooo

**Comment by Angelk90** [comment]
@ravi-poonia : Could you put a simple example on codesandbox?

**Comment by MahdiTa97** [comment]
> if someone is looking for simple patch
> 
> ```
> <DateRangePicker
>      renderInput={({ inputProps, ...startProps }, endProps) => {
>           const startValue = inputProps.value;
>           delete inputProps.value
>           return (
>             <TextField
>               {...startProps}
>               inputProps={inputProps}
>               value={`${startValue}-${endProps.inputProps.value}`}
>            />
> )}/>
> ```

I have made it typesafe using Typescript by refactoring it:
```jsx
<DateRangePicker
  renderInput={(startProps, endProps) => {
    const { value: startValue, ...restStartInputProps } =
      startProps.inputProps || {};
    const endValue = endProps?.inputProps?.value;

    return (
      <TextField
        {...startProps}
        label={null}
        inputProps={restStartInputProps}
        value={`${startValue || 'From'} - ${endValue || 'To'}`}
      />
    );
  }}
/>
```
