### ISSUE TITLE
Open year selection also on month click.

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1638]
Click on month should open year selection. Not only triangle icon click. 

Original comment: 
Trying the version on: https://v4-0-0-alpha-5.material-ui-pickers.dev/demo/daterangepicker
Clicking on the month does not allow me to select the years as shown in the figure on the right:
![](https://camo.githubusercontent.com/44ef41029253ef586894909f9f7263fafc340410/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f737065632d686f73742f6d696f2d73746167696e672532466d696f2d636f6d706f6e656e747325324631353636343235363839393232253246617373657473253246316c756978686f466644536b3744434270647541686651354950316f6a443844492532467069636b65722d63686f6f73696e672d646174652d63616c656e6461722e706e67)

_Originally posted by @Angelk90 in https://github.com/mui-org/material-ui-pickers/issues/1293#issuecomment-612049119_

**Comment by Angelk90** [comment]
@dmtrKovalenko : https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1584058305895%2Fassets%2F1XIALcbRFq7fpoFwbM8rVYm8l6eSQWMYj%2Fselect-year-baseline.mp4

**Comment by dmtrKovalenko** [comment]
Wow I am stupid. 

There is no year selection for date range. Only for datepicker. And it’s expected.

**Comment by Angelk90** [comment]
@dmtrKovalenko : 
It seems that there is actually the possibility, the arrow there is an example on android java.
Look: ![](https://user-images.githubusercontent.com/38727469/78702966-6ff74800-78d7-11ea-9f8a-e652161d62b7.gif)

**Comment by dmtrKovalenko** [comment]
Can you attach what will be displayed after click? Maybe month view?

**Comment by Angelk90** [comment]
@dmtrKovalenko , @oliviertassinari : 
I don't know, I found it here: https://github.com/material-components/material-components-android/issues/1159#issuecomment-610531352

Being that the picker design exists only for android, the one referred to in the official doc material.io, is for android.

**Comment by Angelk90** [comment]
@dmtrKovalenko : Year view.

![Screenshot_20200418-173109](https://user-images.githubusercontent.com/20476002/79642046-86d15080-819b-11ea-9231-4f3b26e46d76.png)
![Screenshot_20200418-173125](https://user-images.githubusercontent.com/20476002/79642049-89cc4100-819b-11ea-8b2f-6bd110b02765.png)
