### ISSUE TITLE
Add tooltips to explain the UI

### ISSUE THREAD

**Issue by Angelk90** [mui-org/material-ui-pickers#1639]
@dmtrKovalenko , @oliviertassinari : 
![](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1584058305895%2Fassets%2F0B54x0KDcs5U-VkN4TG9Mdk9PRWc%2Fpicker-desktop-tooltips.png)

**Comment by oliviertassinari** [comment]
So far, the motivation for not including these tooltips was to reduce the bundle size of the date picker, not requiring to import the `Tooltip` component. However, as we are now moving from Popover to Popper, the bundle size consideration has decreased. I wonder if we can get away with only the usage of the `title` attribute.

A few notes:

- After how long should the tooltip display? A value around >1s would be another argument for the simplicity of `title`.
- What's the bundle size overhead of Tooltip?
- Can we imagine an option where developers can inject their own Tooltip component?
- We will need to update core to provide localization on these wordings.

**Comment by Angelk90** [comment]
@oliviertassinari : 
My suggestions are:
- Have a flag where you decide whether or not to have this option enabled, default enabled
- Use a component wrapper, so the developer could inject his own component tooltip, and use a default one if the user has not injected any or specify that it is necessary to inject one and use the one of material ui as an example so it does not overload the module material- ui-pickers.

**Comment by Angelk90** [comment]
@oliviertassinari : Another thing I don't know if you noticed, for example take the first image.
If you see the first calendar is made up of 30 days, then there after the 30th day, there are the following days which are part of the month after, but are displayed, this option exists.
Same for the days before the 1st of this month, many calendars have this option, I don't know if I explained myself well.

**Comment by oliviertassinari** [comment]
@Angelk90 Regarding the previous and next month displayed disabled (`theme.palette.text.secondary`), please open a new issue. I think that it's a legit request, but it's off-topic.

<img width="231" alt="secondary" src="https://user-images.githubusercontent.com/3165635/79018807-0005ed80-7b75-11ea-914c-2a5327d3a430.png">

**Comment by Angelk90** [comment]
@oliviertassinari : Could you open it?

**Comment by oliviertassinari** [comment]
I think that we should go with the simplest option: the `title` attribute. You will find the same one in:
- https://jqueryui.com/datepicker/ for the arrow keys.
- Material-UI Autocomplete and TablePagination for the actions.
- http://react-day-picker.js.org/ for the shortened days.

The diff would look something like this for the arrows:

```diff
diff --git a/lib/src/_shared/ArrowSwitcher.tsx b/lib/src/_shared/ArrowSwitcher.tsx
index 3ea35d48..a229b303 100644
--- a/lib/src/_shared/ArrowSwitcher.tsx
+++ b/lib/src/_shared/ArrowSwitcher.tsx
@@ -80,6 +80,7 @@ const PureArrowSwitcher: React.FC<ArrowSwitcherProps> = ({
         data-mui-test="previous-arrow-button"
         size="small"
         aria-label={leftArrowButtonText}
+        title={leftArrowButtonText}
         {...leftArrowButtonProps}
         disabled={isLeftDisabled}
         onClick={onLeftClick}
@@ -101,6 +102,7 @@ const PureArrowSwitcher: React.FC<ArrowSwitcherProps> = ({
         data-mui-test="next-arrow-button"
         size="small"
         aria-label={rightArrowButtonText}
+        title={rightArrowButtonText}
         {...rightArrowButtonProps}
         disabled={isRightDisabled}
         onClick={onRightClick}
diff --git a/lib/src/views/Calendar/CalendarHeader.tsx b/lib/src/views/Calendar/CalendarHeader.tsx
index ab9c1302..50501c04 100644
--- a/lib/src/views/Calendar/CalendarHeader.tsx
+++ b/lib/src/views/Calendar/CalendarHeader.tsx
@@ -96,8 +96,8 @@ export const CalendarHeader: React.SFC<CalendarHeaderProps> = ({
   rightArrowButtonProps,
   leftArrowIcon,
   rightArrowIcon,
-  leftArrowButtonText = 'previous month',
-  rightArrowButtonText = 'next month',
+  leftArrowButtonText = 'Previous month',
+  rightArrowButtonText = 'Next month',
   getViewSwitchingButtonText = getSwitchingViewAriaText,
 }) => {
   const utils = useUtils();
```

Regarding the parts of the UI we might want to cover, I can think of:

- arrow previous month
- arrow next month
- arrow open year display
- days abbreviation

@Angelk90 Do you want to work on a pull request that goes in this direction? In any case, I don't think that it's more of an attention to the details.

---

Later on (in 1 year+?), I think that we could accept a `TooltipComponent` prop at the root, something we would forward down with the context, and have:

```jsx
const TooltipComponent = React.forwarfRef(function TooltipComponent(props, ref) {
  return React.cloneElement(props.children, props));
}));
```

as a default value, a value we could switch with `TooltipComponent={MuiTooltip}`;

**Comment by Angelk90** [comment]
@oliviertassinari : 

`
const TooltipComponent = React.forwardRef((props, ref) =>  React.cloneElement(props.children, props));`

@dmtrKovalenko: what do you think about it?

**Comment by oliviertassinari** [comment]
I believe we have two sides for the issue:

1. adding the missing `title` attributes
2. allowing to customize the title rendering with the `Tooltip` component or else.

We now have https://github.com/mui-org/material-ui/issues/20991 to collect feedback and traction on 2. I think that we can only focus on the first part of the problem for closing this issue.
