### ISSUE TITLE
Display preview and next months in secondary color

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1641]
Looking at the specification, we might want to provide an option to display the preview and next month' days in a secondary color (`theme.palette.text.secondary`). The concern was first raised in https://github.com/mui-org/material-ui-pickers/issues/1639#issuecomment-612178027.

I don't think that it's something we want to prioritize for the next stable release, but we could consider it later.

![](https://camo.githubusercontent.com/8f6eeda08c7f46ec2cbcd98fbc302793395e24c2/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f737065632d686f73742f6d696f2d73746167696e672532466d696f2d636f6d706f6e656e7473253246313538343035383330353839352532466173736574732532463042353478304b44637335552d566b4e345447394d646b39505257632532467069636b65722d6465736b746f702d746f6f6c746970732e706e67)
*material.io*

<img width="231" alt="secondary" src="https://user-images.githubusercontent.com/3165635/79018807-0005ed80-7b75-11ea-914c-2a5327d3a430.png">

*calendar.google.com*
*mail.google.com*

**Comment by dmtrKovalenko** [comment]
We do have prop `showDaysOutsideCurrentMonth`

**Comment by oliviertassinari** [comment]
Duplicate of #1341
