### ISSUE TITLE
Allow to repplace dialog action(OK and Cancel button) on DatePicker by another component

### ISSUE THREAD

**Issue by voquochuyhuy** [mui-org/material-ui-pickers#1647]
![Untitled](https://user-images.githubusercontent.com/37115874/79071494-345ce380-7d06-11ea-84dc-aac6f43d262e.png)
Hello everyone,
I have search for many hours and can't find the way to custom the bottom of datepicker like the image above.
Is there any way to do this.

I hope to get the answer and sorry for my English.
Thank you very much

**Comment by oliviertassinari** [comment]
@voquochuyhuy What version are you using?

**Comment by oliviertassinari** [comment]
@voquochuyhuy You could use the static version of the date range picker and compose a couple of textboxes to reach the same output.

**Comment by voquochuyhuy** [comment]
@oliviertassinari Thank for fast reply.
I'm using @material-ui/pickers": "^3.2.10" and "@material-ui/core": "^4.3.1".
But I don't understand "use the static version of the date range picker",that mean i have to use another npm package?. I want to know is there anyway to replace ok and cancel button on datepicker dialog because I have to custom it from @material-ui/pickers to the date range picker like the image above

**Comment by voquochuyhuy** [comment]
Oh,I find I can solve my problem by use calendar in my custom model, so it's easy to handle dialog action. Anyway , thanks alot
