### ISSUE TITLE
[DatePicker] Update to match the specification (desktop)

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1648]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | v4.0.0-alpha.5  |

## Steps to reproduce

https://next.material-ui-pickers.dev/demo/datepicker#basic-usage

## Actual behavior

<img width="383" alt="Capture d’écran 2020-04-13 à 00 11 25" src="https://user-images.githubusercontent.com/3165635/79081186-557bff00-7d1b-11ea-8f0a-616324205d1a.png">

## Expected behavior

<img width="421" alt="Capture d’écran 2020-04-13 à 00 07 00" src="https://user-images.githubusercontent.com/3165635/79081168-29607e00-7d1b-11ea-8546-efea151e1566.png">

1. The component should have a higher density on desktop. It should be 258x281 instead of 320x358.
2. The popper should be positioned to start on the right side, not at the center.
3. The day chip should be 28x28 (maybe less, not sure) instead of 36x36 pixels.
4. The year chip should be 54x28 instead of 72x36 pixels.
5. The colors of the range don't match. Try to set the same primary color as in material.io `#7001f3` to get an idea of the issue. I propose this diff:

```diff
diff --git a/lib/src/DateRangePicker/DateRangePickerDay.tsx b/lib/src/DateRangePicker/DateRangePickerDay.tsx
index 9f54cb31..bff27496 100644
--- a/lib/src/DateRangePicker/DateRangePickerDay.tsx
+++ b/lib/src/DateRangePicker/DateRangePickerDay.tsx
@@ -2,7 +2,7 @@ import * as React from 'react';
 import clsx from 'clsx';
 import { DAY_MARGIN } from '../constants/dimensions';
 import { useUtils } from '../_shared/hooks/useUtils';
-import { makeStyles, fade } from '@material-ui/core/styles';
+import { makeStyles, fade, lighten } from '@material-ui/core/styles';
 import { Day, DayProps, areDayPropsEqual } from '../views/Calendar/Day';

 interface DateRangeDayProps extends DayProps {
@@ -38,8 +38,8 @@ const useStyles = makeStyles(
     },
     rangeIntervalDayHighlight: {
       borderRadius: 0,
-      color: theme.palette.primary.contrastText,
-      backgroundColor: fade(theme.palette.primary.light, 0.6),
+      color: theme.palette.getContrastText(lighten(theme.palette.primary.main, 0.8)),
+      backgroundColor: lighten(theme.palette.primary.main, 0.8),
       '&:first-child': startBorderStyle,
       '&:last-child': endBorderStyle,
     },
@@ -66,7 +66,7 @@ const useStyles = makeStyles(
       },
     },
     dayInsideRangeInterval: {
-      color: theme.palette.getContrastText(fade(theme.palette.primary.light, 0.6)),
+      color: theme.palette.getContrastText(lighten(theme.palette.primary.main, 0.8)),
     },
     notSelectedDate: {
       backgroundColor: 'transparent',
```

**before**

<img width="429" alt="Capture d’écran 2020-04-13 à 00 34 11" src="https://user-images.githubusercontent.com/3165635/79081523-8447a480-7d1e-11ea-81d9-1344a4dc1a84.png">

**after**

<img width="443" alt="Capture d’écran 2020-04-13 à 00 33 18" src="https://user-images.githubusercontent.com/3165635/79081508-709c3e00-7d1e-11ea-9ae6-a5457e40e92e.png">

**baseline**

<img width="357" alt="Capture d’écran 2020-04-13 à 00 34 33" src="https://user-images.githubusercontent.com/3165635/79081527-90cbfd00-7d1e-11ea-8b67-57d50715760d.png">

Looking again, 0.8 isn't enough. Maybe 0.85 or 0.9.

**Comment by dmtrKovalenko** [comment]
Related to sizes. I am not sure – do core components precisely following sizes from guidelines? Because IMHO 32x32 is too small for mobile, isn't it? 

![image](https://user-images.githubusercontent.com/16926049/79102622-c0592480-7d73-11ea-9f05-8e8b9c4fb3fe.png)

**Comment by dmtrKovalenko** [comment]
oh goodness, really components have different sizes for desktop. Looks like all of our sizes are for mobile. Thanks for catching it!

**Comment by oliviertassinari** [comment]
Sorry, I should have mentioned that mobile and desktop should have different dimensions. Thanks for inlining the screeshot from the specification with the actual dimensions.

**Comment by oliviertassinari** [comment]
Regarding the media query logic. I would be eager to try a logic based on touch vs click support as the primary pointer device (instead of the screen width). It's definitely related to #1653.

**Comment by oliviertassinari** [comment]
> Related to sizes. I am not sure – do core components precisely following sizes from guidelines? Because IMHO 32x32 is too small for mobile, isn't it?

@dmtrKovalenko Regarding your concern about the size. 

The core components try to follow the size of the specification, as much as possible, but we have divergences, especially when the specification isn't consistent or dropping 1px simplifies the CSS.

I think that we can benchmark with a couple of frequently used date pickers, to get a sense of where we are on the spectrum (sorted from too small to too large):

- Google Calendar: visual: 24x**24**, bounding box: 36x28
- ant.design: visual: 24x**24**, bounding box: 36x30
- jQuery UI: visual: 34x**24**, bounding box: 36x26
- daterangepicker.com visual/bounding box: 32x**27**
- 💅 Material Design / Gmail: visual: 28x**28**, bounding box: 32x32
- blueprintjs.com: visual/bounding box: 32x**30**
- elastic.github.io/eui: visual/bounding box: 32x**32**
- booking.com: visual/bounding box: 35x**36**
- ⚾️ next.material-ui-pickers.dev: 36x**36**, bounding box: 40x40
- Google flights: visual/bounding box: 44x**44**
- airbnb.com: visual/bounding box: 48x**47**

---

Site note, we add vertical spacing on the rows and horizontal spacing on the columns. I think that we should aim for a single place (single element/selector) to handle CSS spacing, to make overrides simpler.

<img width="71" alt="Capture d’écran 2020-04-25 à 13 12 24" src="https://user-images.githubusercontent.com/3165635/80278441-82a2b700-86f6-11ea-840c-5efa6748f093.png">
<img width="316" alt="Capture d’écran 2020-04-25 à 13 12 31" src="https://user-images.githubusercontent.com/3165635/80278442-833b4d80-86f6-11ea-8d8d-e9edec6babde.png">
