### ISSUE TITLE
Selecting a date should close the picker

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1651]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | v4.0.0-alpha.5 |

## Steps to reproduce

1. Open https://next.material-ui-pickers.dev/demo/datepicker#basic-usage
2. Click on the first calendar icon
3. Select a date
4. The popup is still open

## Expected behavior

The popup should close.

I think that we could consider a `disableCloseOnSelect` prop as the Autocomplete has for the current behavior.

**Comment by CarsonF** [comment]
FYI `autoOk={true}` does this

**Comment by oliviertassinari** [comment]
@CarsonF Thanks for raising this point up. It seems that we should handle desktop and mobile the opposite way, meaning `autoOk={true}` on a pointer device and `autoOk={false}` on a touch device. This would match the experience that is most commonly implemented. For instance, take Google Calendar, or Gmail as an example (compare the mobile app, with the web app).
