### ISSUE TITLE
onChange should not trigger if selecting the same date

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1652]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | v4.0.0-alpha.5 |

## Actual behavior

https://codesandbox.io/s/holy-breeze-c6ucy?file=/src/App.js

## Expected behavior

https://codesandbox.io/s/material-demo-3sl56?file=/demo.js

We have recently fixed this aspect with the Autocomplete and the Select components, I figure it would be great to have it here too.

**Comment by dmtrKovalenko** [comment]
What the motivation overall? I am not aware of this issue but want to understand the original problem we are trying to solve. 
For example when in the input you will copy and paste the same input `onChange` will be triggered, right? Why we should avoid it here?

**Comment by oliviertassinari** [comment]
The overall motivation is consistency with the native `<select>` or `<input type="date" />` elements. The related issues: https://github.com/mui-org/material-ui/issues/20351.
