### ISSUE TITLE
Don't pass `InputAdornmentProps` through `PureDateInput`

### ISSUE THREAD

**Issue by Philipp91** [mui-org/material-ui-pickers#1656]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 4.0.0-alpha.5        |
| material-ui          |   4.9.10      |
| TypeScript           |  3.8.3       |
| React                |    16.13.1     |
| Peer library         | date-fns 2.12.0        ||

## Steps to reproduce

Pretend to be on mobile. (Actually even if you're not, due to how `useMediaQuery` returns false upon first render and then only does the matching later in its effect, you'll see the error message even on desktop.)

```
<DatePicker value={value} onChange={this.onChange} InputAdornmentProps={{}}/>
```

## Expected behavior

Ignores the `InputAdornmentProps` in case of mobile.

## Actual behavior

```
Warning: React does not recognize the `InputAdornmentProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputadornmentprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (created by ForwardRef(TextField))
    in ForwardRef(TextField) (created by WithStyles(ForwardRef(TextField)))
    in WithStyles(ForwardRef(TextField)) (created by PureDateInput)
    in PureDateInput (created by MobileWrapper)
    in MobileWrapper (created by ResponsiveWrapper)
    in ResponsiveWrapper (created by WrapperComponent)
    in WrapperComponent (created by PickerWithState)
    in PickerWithState
    in Unknown (created by ForwardRef)
    in ForwardRef (created by ...)
```

## Live example

https://codesandbox.io/s/great-pond-zrj7o (This should reproduce unless you have a huge screen.)

**Comment by oliviertassinari** [comment]
@Philipp91 Thanks for opening this issue. We plan to break the TextField component free from the DatePicker components to:
- empower more customization, to make it easier to compose logic and avoid issues like this one.
- to allow the developers to swap the TextField with another textbox from their design system and save the bundle size cost.
- to make it easier to understand what's going one with props on this big component.

What do you think of the API of https://material-ui.com/components/autocomplete/#combo-box?

**Comment by Philipp91** [comment]
Do you mean specifically the `renderInput` prop? Would every developer then have to link together the two libraries by specifying that prop manually? (And would every developer then have to worry about the question raised in this bug originally?)

**Comment by oliviertassinari** [comment]
On a side note, I have noticed this the other day, I'm eager to find a way to remove all this duplication of props forwarding:

https://github.com/mui-org/material-ui-pickers/blob/7bed283699ef768936a3ec7c5dc89571492dddd4/lib/src/Picker/makePickerWithState.tsx#L51-L134

**Comment by Philipp91** [comment]
Not sure if this could help: https://github.com/kimamula/ts-transformer-keys (might be more trouble to integrate in a library like material-ui-pickers than it's worth)
