### ISSUE TITLE
KeyboardDateTimePicker: format with AM/PM does not allow backspace from end of input string

### ISSUE THREAD

**Issue by cduflo** [mui-org/material-ui-pickers#1662]
Steps to reproduce:
1. Navigate: https://material-ui-pickers.dev/demo/datetime-picker
2. Locate this picker under Customization
![Screen Shot 2020-04-14 at 5 17 22 PM](https://user-images.githubusercontent.com/15986207/79362334-523f6980-7efb-11ea-8c80-5046679d61af.png)
3. Click cursor on the end of the input, after "...PM", before calendar icon
4. Try to backspace/delete
5. Notice nothing happens

This seems to only happen if the format includes an AM/PM marker (ex. format="yyyy/MM/dd hh:mm a"). It seems to affect DateFns or MomentFns equally.

A codesandbox can be found here https://codesandbox.io/s/keyboarddatetimepicker-backspace-issue-9rgu4?file=/demo.js

**Comment by dmtrKovalenko** [comment]
Fixed in v4-alpha👨‍🏭
