### ISSUE TITLE
Mobile version open calendar below the input field

### ISSUE THREAD

**Issue by Angelk90** [mui-org/material-ui-pickers#1665]
**Describe the solution you'd like**
By clicking on the input field, I would like the calendar to open as shown.

**Additional context**

![image](https://user-images.githubusercontent.com/20476002/79382948-e3422f00-7f53-11ea-9f8f-5bc14944c35b.png)

**Comment by dmtrKovalenko** [comment]
You can use `DesktopDateRangePicker`  with`showToolbar` and `calendars={1}` props.
