### ISSUE TITLE
[DateRangePicker] Provide a renderDelimiter API

### ISSUE THREAD

**Issue by gradinarot** [mui-org/material-ui-pickers#1667]
How can we style the MuiPickersDateRangePickerInput-toLabelDelimiter in the DateRangePicker? Thanks

**Comment by dmtrKovalenko** [comment]
You can override this style `MuiPickersDateRangePickerInput-toLabelDelimiter ` globally
https://material-ui-pickers.dev/guides/css-overrides

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Side questions:

- What's your perspective on using an arrow icon "->" instead of a text label? Or only a dash "-"?
- With the `renderAPI` direction, will we need to expose a new component? Like a `DatePickerRangeSeparator`?

```jsx
<DateRangePicker
  renderInput={(startIInput, endInput) => (
    <div>
      <TextField {...startInput} />
      <DatePickerRangeSeparator />
      <TextField {...endInput} />
    </div>
  )}
/>
```

**Comment by dmtrKovalenko** [comment]
As I described I am planning to make this API
Note that `renderDelimiter` is optional 
```jsx
<DateRangePicker
   renderStartInput={props => <TextField {...props} />}
   renderDelimiter={() => <ArrowRightIcon /> }
   renderEndInput={props => <TextField {...props} />}
/> 
```

Also, it is possible to add a className to the renderDelimiter argument `(className) => <Typography className={className}> to </Typography>`

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Sounds great
