### ISSUE TITLE
[DateRangePicker] Ability to override DateRangePickerInput

### ISSUE THREAD

**Issue by ifndefdeadmau5** [mui-org/material-ui-pickers#1669]
**Is your feature request related to a problem? Please describe.**
I want to have different view for DateRangePickerInput

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/8914311/79524585-e5afa080-809b-11ea-9c84-36a060a341e6.png)

In order to implement above appearance, I need ability to override whole input components or dedicated prop which can be possibly named as `single` or something

**Comment by dmtrKovalenko** [comment]
calendars={1} there is a working demo

**Comment by ifndefdeadmau5** [comment]
@dmtrKovalenko I'm talking about `<DateRangePickerInput />`, not `<Calendar />`.
All the Demo has two TextField per one `<DateRangePicker />` which not suitable for my use case

**Comment by dmtrKovalenko** [comment]
Duplicate of #1637

**Comment by ifndefdeadmau5** [comment]
@dmtrKovalenko my bad, thanks!
