### ISSUE TITLE
Improve treeshaking

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1670]
Make possible to tree-shake `Desktop|Mobile` wrappers. For instance, in the below report, DesktopDatePicker and MobileDatePicker have the same bundle size output: 25.9 kB, excluding the peer dependencies like @material-ui/core.

![image](https://user-images.githubusercontent.com/16926049/79562246-6928bc00-80b3-11ea-8639-500454109c78.png)

*https://bundlephobia.com/result?p=@material-ui/pickers@4.0.0-alpha.5*

**Comment by dmtrKovalenko** [comment]
(Break exported modules by files) so we need to have 
`MobileDatePicker.tsx`
`DesktopDatePicker.tsx`
`DatePicker.tsx` 

In order to make possible to remove unused code of `MobileWrapper` for `DesktopDatePicker`

**Comment by kwinto** [comment]
What tool makes such pretty reports?

**Comment by dmtrKovalenko** [comment]
https://bundlephobia.com/result?p=@material-ui/pickers@4.0.0-alpha.5

**Comment by oliviertassinari** [comment]
💯 for such effort.

Do we have a way to track/tests the changes we perform in at the pull request level so we are not required to publish on npm to have feedback (feedback every release vs within 10 minutes)? I see the [size snapshot](https://github.com/mui-org/material-ui-pickers/blob/next/lib/.size-snapshot.json) but it's at the package level.

Would it make sense to solve this problem after we migrate the picker to the mono-repository so we can benefit from the [module size tracker](https://material-ui.com/size-snapshot)?

I'm worried about some of the changes we do/plan to do if we have no visibility on the bundle size impact at the module level.

**Comment by dmtrKovalenko** [comment]
Yeah, let’s going to wait for merge. For now I’ll test it with pure linking to CRA app and check bundlesize

**Comment by aamirafridi** [comment]
This is my import
```javascript
import {
  DesktopDateRangePicker,
  LocalizationProvider,
  LocalizationProviderProps,
  MobileDateRangePicker,
  RangeInput,
} from "@material-ui/pickers";
```

I can see e.g. ClockView gets bundled as well. Any way to avoid this?

![image](https://user-images.githubusercontent.com/55896/87780558-df5dcb80-c826-11ea-9ee7-f14b8cc6c22a.png)
