### ISSUE TITLE
Avoid inline style as much as possible

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1679]
Inline are problematics for a couple of reasons:

1. Require `!important` to be overridden with CSS. For newcomer developers, it harder to comprehend. For experienced developers, it feels like a code debt.
2. It's inconsistent with how components are styled.
3. It opens CSP concerns: https://github.com/mui-org/material-ui/issues/19938

https://github.com/mui-org/material-ui-pickers/blob/70bb56f91866bb9f26161f123419fa2e9c4cec00/lib/src/views/Calendar/Calendar.tsx#L194

**Comment by dmtrKovalenko** [comment]
Haha its only one place that I actually all the time forgetting to fix. Thanks with issue it will be easier

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Thanks :)
