### ISSUE TITLE
Closer UX between range picker and single picker on desktop

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1682]
This is a proposal to unify the behavior of the single and range date picker.

1. Looking at https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html, I don't think that the `DesktopDatePicker` should use the Modal component. The scroll shouldn't be blocked nor the underlying window hidden. Instead, we could replace it with Popper + TrapFocus + <kbd>Escape</kbd> + onBlur logic. I don't see any downside going in this direction. It seems to be a clear win. It's how the date range picker behaves.
2. I wonder about providing a `openOnFocus` and `openOnClick` prop to replicate a common UX competitive date pickers have. It's also how the date range picker behaves.
In any case, the current default with an icon to open the popup is great. I think that the closer we are to the native date-time picker implementation of the browsers, the better.
Well, reading https://www.hassellinclusion.com/blog/input-type-date-ready-for-use/, `<input type=”date” />` might not be a good option from an accessibility standpoint 🙃
3. It seems that StaticDateRangePicker should have `allowKeyboardControl` set to true.
4. Selecting a date on the DatePicker doesn't close the popup while it does with a DateRangePicker: #1651. I think that we should apply DateRangePicker behavior to DatePicker as well as identify if we can share the logic to prevent this class of issues in the future.

**Comment by Philipp91** [comment]
4. (?) In the regular DatePicker, one can switch to a year selection view, which is not possible (but would also be very useful) in the DateRangePicker.

**Comment by oliviertassinari** [comment]
@Philipp91 For this case, maybe we should encourage a two "wired" single date picker?

**Comment by Philipp91** [comment]
I don't understand? You mean not using the DateRangePicker but just connecting two DatePickers such that one's `value` is the other's `minDate` and vice versa?

**Comment by oliviertassinari** [comment]
@Philipp91 Yeah it was my proposal, but maybe not if we want to support range picker for months or years.

**Comment by Philipp91** [comment]
Oh, maybe there's a misunderstanding. I don't mean a UI for selecting "Jan 2020 through Apr 2020" without specifying days. I just mean improving the UX for "Jan 1st 1990 through Jan 31st 1990". Just try entering that on any of the [demo range pickers](https://next.material-ui-pickers.dev/demo/daterangepicker) without using the keyboard -- it takes a long time to get to 1990.

**Comment by oliviertassinari** [comment]
@Philipp91 No objection here, I was looking a step ahead 😁

<img width="307" alt="Capture d’écran 2020-04-18 à 22 49 06" src="https://user-images.githubusercontent.com/3165635/79670963-d4af7e00-81c6-11ea-9e29-b1a82850689d.png">
