### ISSUE TITLE
DateRangePicker ignores toolbarTitle

### ISSUE THREAD

**Issue by Philipp91** [mui-org/material-ui-pickers#1683]
| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    4.0.0-alpha.5     |

## Steps to reproduce

`<DateRangePicker toolbarTitle="Test test" ...`

## Expected behavior

I can see "Test test" in the UI.

## Actual behavior

The title remains "SELECT DATE RANGE".

## Live example

https://codesandbox.io/s/daterangepicker-momentdateadapter-4pi0b?file=/src/index.tsx

**Comment by Philipp91** [comment]
It also rejects `minDateMessage` (https://codesandbox.io/s/daterangepicker-momentdateadapter-wzzgn?file=/src/index.tsx) and a few others. `clearable` is advertised in the [documentation](https://next.material-ui-pickers.dev/api/DateRangePicker) but marked as invalid by TypeScript already (and it also deosn't work, https://codesandbox.io/s/daterangepicker-momentdateadapter-ecewh?file=/src/index.tsx).

**Comment by crispero** [comment]
+1
