### ISSUE TITLE
Unable to override dialog props.

### ISSUE THREAD

**Issue by adeelibr** [mui-org/material-ui-pickers#1690]
![surprise gif](https://media.giphy.com/media/xNrM4cGJ8u3ao/giphy.gif)

## Environment

@date-io/date-fns: 1.3.11
@material-ui/core: 4.9.8
@material-ui/pickers: 3.2.10
date-fns: 2.11.1
react: 16.8.6
react-dom: 16.8.6
react-scripts :2.1.3

## Steps to reproduce

```
function App() {
  const [selectedDate, handleDateChange] = useState(new Date());

  const props = {
    DialogProps: {
      role: "example",
      PaperProps: {
        elevation: 6
      }
    }
  };

  return (
    <MuiPickersUtilsProvider utils={DateFnsUtils}>
      <TimePicker value={selectedDate} onChange={handleDateChange} {...props} />
    </MuiPickersUtilsProvider>
  );
}
```

I am trying to change the elevation for the time picker, but I am unable to override it.

## Expected behavior

- Be able to override `Dialog` component used via props

## Actual behavior

Unable to override `Dialog` props

## Live example

https://codesandbox.io/s/elastic-banach-4nbf1?file=/src/App.jsx

**Comment by dmtrKovalenko** [comment]
There is special `DialogProps`

**Comment by adeelibr** [comment]
This is what I am trying but it is not working

```code
<TimePicker 
 value={selectedDate} 
 onChange={handleDateChange}
 DialogProps={{
   PaperProps: { elevation: 6 }.
 }}
/>
```

**Comment by oliviertassinari** [comment]
@adeelibr Could you try with v4.0.0-alpha.5?

**Comment by adeelibr** [comment]
> @adeelibr Could you try with v4.0.0-alpha.5?

I have tried with that as well, it doesn't work.

**Comment by dmtrKovalenko** [comment]
Thanks. Sorry for early close

**Comment by maciej-gurban** [comment]
Would be great if you could provide a fix or a workaround for this in 4.x version. Currently prevents our team from taking the component into use since we want to use static version and need to override a few of the styles, Paper included

**Comment by dmtrKovalenko** [comment]
Doesn't reproduce: here is working example. I suppose you are trying to pass `DialogProps`, but for desktop mode we use Popper or Popover.

**Comment by oliviertassinari** [comment]
It's to be noted that if a prop isn't supported but provided, it should raise a warning, if nothing is raised, something is wrong.

The issue has been closed because it does not conform to our issue requirements. 
Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/material-ui-date-picker-ppt05) _may_ be a good starting point. Thank you!
