### ISSUE TITLE
@date-io/moment not working - "Uncaught TypeError: utils.getDayText is not a function"

### ISSUE THREAD

**Issue by fnpro** [mui-org/material-ui-pickers#1691]
Greetings! When I try to use @date-io/moment, I get an error. Please see the example:

https://codesandbox.io/s/material-demo-q98wm?file=/demo.js

Please click on the calendar icon, you will will get the error, "Uncaught TypeError: utils.getDayText is not a function"

Thank you!

**Comment by fnpro** [comment]
Okay, I see that I must use v1 for @date-io/moment, as it says in #1440 and in the [docs](https://material-ui-pickers.dev/getting-started/installation#peer-library).

**Comment by oliviertassinari** [comment]
@fnpro `@date-io/moment` shouldn't be present in your package.json. It has become an internal dependency after v3.

**Comment by fnpro** [comment]
@oliviertassinari Okay, sounds fine. Should this be reflected in the docs? [This part in the docs](https://material-ui-pickers.dev/getting-started/installation#peer-library) (v3.2.9 documentation) seems to indicate that @date-io/moment should be installed to the package.json. Am I missing something?

Also, do I still have to import `MomentUtils` (@date-io/moment) into the code for `MuiPickersUtilsProvider`, and if so, where under `@material-ui/pickers` would I import it from?

**Comment by oliviertassinari** [comment]
@fnpro I was referring to v4, http://next.material-ui-pickers.dev/.

**Comment by fnpro** [comment]
Okay, sorry--when you said "after v3," I thought you meant after v3.0.0, rather than after v3 as a whole. My bad.

Thanks a ton.

**Comment by single-stop-justin** [comment]
@fnpro @oliviertassinari The latest utils do not work with the latest MUI pickers. I removed moment as instructed above, and forked the CodeSandbox:

https://codesandbox.io/s/material-demo-fmgzd?file=/package.json

How do I get the latest Utils into the Provider with the latest version of MUI?

`"@date-io/date-fns": "2.8.0",`

```
RangeError
Format string contains an unescaped latin alphabet character `n`
eval
https://fmgzd.csb.app/node_modules/date-fns/esm/format/index.js:90:13
format
https://fmgzd.csb.app/node_modules/date-fns/esm/format/index.js:71:45
    at DateFnsUtils.formatByString (https://fmgzd.csb.app/node_modules/
date-io/date-fns/build/index.esm.js:228:31
    at DateFnsUtils.format (https://fmgzd.csb.app/node_modules/
date-io/date-fns/build/index.esm.js:225:17
    at getDisplayDate (https://fmgzd.csb.app/node_modules/
material-ui/pickers/esm/makePickerWithState-5a79cb8a.js:257:38
    at useKeyboardPickerState (https://fmgzd.csb.app/node_modules/
material-ui/pickers/esm/makePickerWithState-5a79cb8a.js:544:21
    at PickerWithState (https://fmgzd.csb.app/node_modules/
material-ui/pickers/esm/makePickerWithState-5a79cb8a.js:582:21
renderWithHooks
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:14803:18
mountIndeterminateComponent
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17482:13
beginWork
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:18596:16
HTMLUnknownElement.callCallback
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:188:14
Object.invokeGuardedCallbackDev
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:237:16
invokeGuardedCallback
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:292:31
beginWork$1
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23203:7
performUnitOfWork
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22154:12
workLoopSync
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:22130:22
performSyncWorkOnRoot
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21756:9
scheduleUpdateOnFiber
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21188:7
updateContainer
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24373:3
eval
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24758:7
unbatchedUpdates
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21903:12
legacyRenderSubtreeIntoContainer
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24757:5
Object.render
https://fmgzd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24840:10
evaluate
/index.js:6:9
  3 | import ReactDOM from 'react-dom';
  4 | import Demo from './demo';
  5 | 
> 6 | ReactDOM.render(<Demo />, document.querySelector('#root'));
    |         ^
  7 |     
View compiled
▶ 10 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error
```

**Comment by dmtrKovalenko** [comment]
We are working on @material-ui/pickers v4. The not supported `v3` version is only working with `@date-io/*` v1

**Comment by single-stop-justin** [comment]
@dmtrKovalenko  So none of these will work with their respective newest package until then? When is v4 due out?

```
@date-io/moment
@date-io/date-fns
@date-io/luxon
```

**Comment by oliviertassinari** [comment]
> When is v4 due out?

It will be v5, stable version in 6 to 12 months (one alpha/beta every week in the meantime).

**Comment by single-stop-justin** [comment]
Thanks!!
