### ISSUE TITLE
RangeError: Format string contains an unescaped latin alphabet character `n`

### ISSUE THREAD

**Issue by asimhafeezz** [mui-org/material-ui-pickers#1698]
installed versions

> "@date-io/date-fns": "^1.3.11",
> "@material-ui/pickers": "^3.2.8",
> "date-fns": "^2.11.1",

code:

> import "date-fns";
> import React from "react";
> import DateFnsUtils from "@date-io/date-fns";
> import {
>   MuiPickersUtilsProvider,
>   DatePicker,
>   TimePicker
> } from "@material-ui/pickers";
> import Autocomplete from "@material-ui/lab/Autocomplete";
> 
> import {
>   TextField,
>   Button
> } from "@material-ui/core";
> 
> export default function MaterialUIPickers() {
> 
>   // The first commit of Material-UI
>   const [pickUpDate, setpickUpDate] = React.useState(new Date());
>   const [pickUptime, setpickUptime] = React.useState(new Date());
>   const [returnDate, setreturnDate] = React.useState(new Date());
>   const [returntime, setreturntime] = React.useState(new Date());
> 
>   const handlePickUpDateChange = date => {
>     setpickUpDate(date);
>   };
> 
>   const handlePickUpTimeChange = date => {
>     setpickUptime(date);
>   };
> 
>   const handleReturnDateChange = date => {
>     setreturnDate(date);
>   };
> 
>   const handleReturnTimeChange = date => {
>     setreturntime(date);
>   };
> 
>   return (
>     <div>
>       <div>
>         <MuiPickersUtilsProvider utils={DateFnsUtils}>
>           <div className="container-fluid">
>             <div
>               className="row"
>             >
> 
>               <div className="col-md-2 col-sm-6 col-xs-6 p-1">
>                 <DatePicker
>                   disableToolbar
>                   disablePast
>                   fullWidth
>                   variant="inline"
>                   format="dd/MM"
>                   label="Pick-Up Date"
>                   value={pickUpDate}
>                   onChange={handlePickUpDateChange}
>                 />
>               </div>
> 
>               <div className="col-md-1 col-sm-6 col-xs-6 p-1">
>                 <TimePicker
>                   fullWidth
>                   label="P-Time"
>                   value={pickUptime}
>                   onChange={handlePickUpTimeChange}
>                 />
>             </div>
>           </div>
>         </MuiPickersUtilsProvider>
>       </div>
>     </div>
>   );
> }
> 

everything is fine working in my nextjs project and now i am trying to do in create-react-app ...same code same versions ... but again getting this error...
is there something am i doing wrong?!

**Comment by oliviertassinari** [comment]
@asimhyff Please provide a reproduction with v4, we have switch our focus to a new major.

**Comment by oliviertassinari** [comment]
Check your peer dependency warnings (from npm or yarn), this combination of versions is invalid:

> "@date-io/date-fns": "^1.3.11",
"@material-ui/pickers": "^3.2.8",
"date-fns": "^2.11.1",

**Comment by asimhafeezz** [comment]
> "@material-ui/lab": "^4.0.0-alpha.50",

now i installed it... and now it's giving an error that

> Attempted import error: 'MuiPickersUtilsProvider' is not exported from '@material-ui/pickers'.

but it is imported correctly...  code is above...you can see.
one more thing i did "npm install" and still getting this error.
