### ISSUE TITLE
DateRangePicker custom inputFormat don't work

### ISSUE THREAD

**Issue by dbuchet** [mui-org/material-ui-pickers#1704]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    4.0.0-alpha.5     |
| material-ui          |     4.9.10    |
| TypeScript           |         |
| React                |     16.13.1    |
| Browser              |         |
| Peer library         |     date-fns    |  |

## Steps to reproduce
DateRangePicker inputs do not display selected dates if:

- `inputFormat` mismatch default mask "__/__/____"
- `disableMaskedInput` props is set

Only way seems to use `rifmFormatter`, but `rifmFormatter` is not triggered when using `inputFormat`. And `inputFormat` is required to properly display inputs placeholders (btw, how to change theses placeholder? :p)

## Expected behavior
Inputs should display the selected dates according to the specified `inputFormat`

## Actual behavior
State is updated, but inputs do not display selected dates

## Live example
https://codesandbox.io/s/sad-fire-vm9eg

**Comment by dmtrKovalenko** [comment]
1) You must not used such formats for date input. Format must be numeric to be keyboard friendly (literally nobody wants to type “Tuesday”)
2) You can pass `placeholder` and `helperText` prop which will overwrite the generated text
3) Please try v4-alpha.6 where we fixed placeholder generation and mask logic. 

And please let me know if you have any issues.
