### ISSUE TITLE
onChange triggers when opening inline datepicker

### ISSUE THREAD

**Issue by francarmona** [mui-org/material-ui-pickers#1705]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     3.2.10    |
| material-ui          |   4.9.9      |
| TypeScript           |     3.4.5    |
| React                |     16.11.11    |
| Browser              |    Chrome     |
| Peer library         |    moment 2.24.0     |  |

## Steps to reproduce

1. KeyboardDatePicker with `variant="inline"` and `shouldDisableDate={anyFunctionToDisableDates}`
2. Open the date picker and close without selecting any date

## Expected behavior
No date should be selected.

## Actual behavior
onChange callback is triggered and first enabled date is selected.

## Live example

https://codesandbox.io/s/material-ui-picker-demo-6x6yb

**Comment by oliviertassinari** [comment]
@francarmona Can you reproduce the issue with the latest version, v4.0.0-alpha.x?

**Comment by dmtrKovalenko** [comment]
It is desired behavior for v3.x and it is fixed for v4
