### ISSUE TITLE
DateTimePicker should call onChange when date is picked

### ISSUE THREAD

**Issue by Philipp91** [mui-org/material-ui-pickers#1709]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    ^4.0.0-alpha.5     |

## Steps to reproduce

On desktop.

1. Open [DateTimePicker demo](https://next.material-ui-pickers.dev/demo/datetime-picker)
2. Open the "Clear Initial State" picker at the bottom. You can also use the default picker at the top and skip to step (6.)
3. Pick a date. Note how the text field is not filled -- `onChange()` was not called yet. This is fine, as the picker doesn't know the time yet. The picker will automatically open the hours view.
4. Pick hour and minute and close the picker. The selected date/time is now in the textbox as intended -- `onChange()` was called when you selected the minute.
5. Remember the date you picked and open the picker a second time.
6. Pick a (different) date.
7. The picker will automatically move on to the hours view.
7. Ignore that and close the picker by clicking outside, before selecting another time.

## Expected behavior

The value should now be `"<date picked last> <time picked the first time>"`.

## Actual behavior

The value is `"<date picked the first time> <time picked the first time>"`.
That is, the date picked the second time is completely ignored.

Moreover, if you open the picker again, you'll see the second date still highlighted, you can select a third date, close again, and that will be ignored too. So the "open" picker has an (inner) state that is detached from the textbox/outer value.

## Suggestion

`isFinish` should only be used to determine whether there's another view to move to and whether the picker should auto-close. It should *not* be used to determine whether to call `onChange()` (on the outer picker) or not. Instead the outer `onChange()` should be called whenever the inner state is complete, i.e. it has all the components that it needs.

As a simplification, it would also be fine to call `onChange()` even in step (3.) above, i.e. when only a date was selected. Within the picker's UI, the current time is used, so that can be sent to `onChange()` too. That should simplify things to "always call `onChange()` when the inner value is valid and the user selected any day/hour/minute". Or in other words, only refrain from syncing the inner value to the outer with `onChange()` when (a) it's invalid or (b) the user only opened the picker to look at the already-selected value without changing it.

**Comment by oliviertassinari** [comment]
@Philipp91 This issue echos to a preview discussion we had. For the date time picker, shouldn't we force people to validate their choice with a `"Ok"` button? Not firing any change event until it's done?

**Comment by Philipp91** [comment]
An OK button in a popover seems weird to me. The way the popover shows up under the textbox on the screen, it seems like clicking outside of it (especially back in the textbox, but also perhaps into the next field in the same form) should save the selected value.

And would you add the same button to the DatePicker? The behavior should be consistent.

There is also the issue of the mobile keyboard view switching button being visible on desktop, even though it doesn't really seem to be useful there. Perhaps there shouldn't be a DateTimePicker for desktop, i.e. the DateTimePicker should never use the Popover?

My personal preference (biased by the fact that, in my application, most pickers are DateTimePickers but most dates are entered without any time) is to do what I proposed in the first post, i.e. keep the popover, fire the change event early/always.

**Comment by oliviertassinari** [comment]
@Philipp91 Let's benchmark the `onChange` behavior for date-time pickers.

- https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date
- https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/
- https://ej2.syncfusion.com/react/demos/#/material/datetimepicker/default
- https://reactdatepicker.com/#example-select-time
- https://elastic.github.io/eui/#/forms/date-picker#time-selection
- https://blueprintjs.com/docs/#datetime/dateinput
- http://eonasdan.github.io/bootstrap-datetimepicker/

It's related to #1640

**Comment by Philipp91** [comment]
> These ones have an OK button

Right. Not only that, but also their respective date-only pickers do _not_ have an OK button. So they have this inconsistency between picker types.

> These ones select at the end of an on click sequence

From what I can tell, they also always select ("as we go"). They just jump to "12:00 AM" whenever a date is selected.

> It's related to #1640

Right. ~It's essentially a duplicate issue~. I also have this use case of date-only values. Just the proposed solution is different. I personally don't like OK buttons in popovers. And more importantly, I don't like my date-only pickers behaving differently from the date-time pickers in that only the latter require you to click an OK button.

**Comment by oliviertassinari** [comment]
We had two duplicate issues so far for this problem: #1148 and #1879. It sounds like we need to dedicate more time to the problem.

- For the auto close behavior of the popup, I don't think that it needs to be configurable, the one we already have sounds great.
- For the change event and `autoOk={true}`, the solution looks relatively simple, I would propose that we reproduce the behavior of:
  - The native date time picker: https://material-ui.com/components/pickers/#date-amp-time-pickers
  - The most popular react date picker yet: https://reactdatepicker.com/#example-select-time
  - Elastic: https://elastic.github.io/eui/#/forms/date-picker#time-selection

  We fire the change event any time the user select something (day, year, quarter, time).

- For `autoOk={false}` support of the date-time picker, I think that it should mean an "OK" button is present. For instance:

  - https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date
  - https://www.telerik.com/kendo-react-ui/components/dateinputs/datetimepicker/
