### ISSUE TITLE
StaticDateRangePicker Error

### ISSUE THREAD

**Issue by a-m-dev** [mui-org/material-ui-pickers#1715]
Hello 

i was checking the library and i found this [https://v4-0-0-alpha-5.material-ui-pickers.dev/demo/daterangepicker#static-mode](url)

i was wondering why this is written in TypeScript?
if its in alpha version it needs to be used as simply as possible with pure react,  right now i cant convert it to pure react and im keep getting this error in my console 
```
Uncaught TypeError: Cannot read property 'keyboardDate' of undefinedblah blah blah

The above error occurred in the <RangePickerWithStateAndWrapper> component:
blah blah blah

Uncaught (in promise) TypeError: Cannot read property 'keyboardDate' of undefined
blah blah blah


```

please provide a gist of pure javascript for this 😭
and try to show it in pure javascript file not shitty type script 😭 to know how it works in react and then we check that in typescript!

**Comment by dmtrKovalenko** [comment]
Please provide more information and reproduction using codesandbox.

**Comment by oliviertassinari** [comment]
> i was wondering why this is written in TypeScript?
> please provide a gist of pure javascript for this

@a-m-dev This will be resolved with https://github.com/mui-org/material-ui/issues/19706.
