### ISSUE TITLE
defaultHighlight doesn't update automatically

### ISSUE THREAD

**Issue by pipje2001** [mui-org/material-ui-pickers#1718]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |4.0.0-alpha.5|
| material-ui          |4.9.12|
| TypeScript           |no|
| React                |16.13.1|
| Browser              |Vivaldi|
| Peer library         |moment 2.24.0|  |

## Steps to reproduce

1. Set defaultHighlight to a value which is null when component mounts
2. Change the defaultHighlight to a date value 
3. defaultHighlight doesn't change

## Expected behavior
defaultHighlight to change to the new value

## Actual behavior

defaultHighlight stays the value it got when component mounted

## Live example

https://codesandbox.io/s/agitated-firefly-1nmmj?file=/src/App.js

Although this sandbox doesn't work (no idea why once again)
You can see what i am trying to acomplish, it worked fine in 4.0.0-alpha.1, but in 4.0.0-alpha.5 It doesn't update it still thinks that defaultHighlight is null and return the time when the component mounted. I tried to find out if somethingelse is causing this but the only change i did was updating pickers to the newest version. Anyone got an idea on how to fix this? 

P.S. If someone knows what is wrong with the sandbox please tell me because i do want to give a better example but i just cant get sandbox to work

**Comment by oliviertassinari** [comment]
@pipje2001 What do you think of this proposal? #1677 What's your use case for the prop?

**Comment by pipje2001** [comment]
@oliviertassinari I use for one simple reason:
In my DB events have a start and an end date, both need to be on the same day, So i let users first select the lessonDate (dd/mm/yyyy), And then they are able to select the startTime and endTime The start and end time will use the lessonDate set earlier so they are on the same day. 

I use defaultHighlight because i dont want to set the startTime and end endTime (by setting the lessonDate) because this will show the user a time value in the input field before they actually selected a time.

I think having defaultHighlight is a must have for a date/time picker

**Comment by oliviertassinari** [comment]
@pipje2001 Interesting, so you don't want the value to be selected in the input, but you want to pre-select the value when the popup is open, correct?

**Comment by pipje2001** [comment]
Yep

**Comment by oliviertassinari** [comment]
@pipje2001 What should be the expected behavior when closing the popup without any interaction, should the value be selected?

**Comment by pipje2001** [comment]
@oliviertassinari Nope, it should stay null, this way i prevent getting wrong values by accident. It forces users to choose a date and a time

**Comment by oliviertassinari** [comment]
@pipje2001 Ok, awesome this is very interesting, the more I dive into the date/time picker the more it feels that we could provide similar props than the https://material-ui.com/components/autocomplete/#playground. In https://github.com/mui-org/material-ui-pickers/issues/1677#issuecomment-616741537, @Philipp91 was looking for a selection of the value when the popup is closed.

So maybe we should:

- Keep the defaultHighlight prop, as an equivalence with `autoHighlight` but with more granularity.
- Introduce a `autoSelect` prop

**Comment by pipje2001** [comment]
@oliviertassinari That would work, I am happy as long as there is something like defaultHighlight.

Apart from that do you have any idea about the issue i was having?

**Comment by Philipp91** [comment]
> In #1677 (comment), @Philipp91 was looking for a selection of the value when the popup is closed.

Not sure what you mean by "popup". The situation is even more nuanced than that. I want to provide a default value. If the user is on **mobile**, that's just the default value that is selected when the dialog is opened and the picker didn't have any "real" value yet. But the mobile dialog has a "Cancel" button and clicking that should result in no change. If the user is on **desktop**, it's the default value selected in the popover. However, if the user just leaves the popover by clicking outside, it should be in the picker's text box. I'm not sure when `onChange` should be fired in this case.

So to me, there's a difference between closing a **modal dialog** (by clicking its overlay background, or by clicking "Cancel") and closing a **non-modal popover** (by clicking outside). The former means "abort" (and the dialog has an "OK" button that means the opposite) and the latter means "move on". In particular, it's possible to "move on" by clicking right into the next (text/picker/...) field within the same form when the popover is open, whereas that's not possible when the dialog is open.

**Comment by oliviertassinari** [comment]
> Not sure what you mean by "popup".

@Philipp91 If we use the same language as https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html, I meant dialog. Ok, awesome, thanks for sharing.

**Comment by pipje2001** [comment]
@oliviertassinari Should i just go back to using 4.0.0-alpha1? I am willing to help find the problem i am having but I dont know what you guys changed internally, just a name change cant cause my problem right?

**Comment by pipje2001** [comment]
So this sandbox actually works:  https://codesandbox.io/s/elated-hermann-ge5ux?file=/src/App.js

The defaultHighLight is now actually working but this is just a workaround, Also if i give start time 2 a value of null and a defaultHighLight of moment().set({ h: 0, m: 30, s: 0, ms: 0 }) results in the defaultHighLight of start time 1 being the defaultHighLight of start time 2.

Example: https://codesandbox.io/s/gracious-brattain-yv1nb?file=/src/App.js 

It looks like defaultHighLight wont change after its initially set.

if you look here https://github.com/mui-org/material-ui-pickers/compare/v4.0.0-alpha.3...v4.0.0-alpha.7 and go to files and search for defaultHighlight in file lib/src/_helpers/date-utils.ts, some stuff is added with defaultHighlight, no idea what it actually does but that could help you guys finding the origin of the problem

**Comment by oliviertassinari** [comment]
I'm closing for #1677
