### ISSUE TITLE
Deny to enter date less than 01.01.1900 in DateRangePicker

### ISSUE THREAD

**Issue by AlexanderVishnevsky** [mui-org/material-ui-pickers#1720]
Hi there! Found some bug in DateRangePicker component.

![ezgif-3-cf2bb36775fc](https://user-images.githubusercontent.com/26820006/80505668-4cc33400-897d-11ea-91f7-ec5eca98b9e0.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  v4.0.0-alpha.5  |

## Steps to reproduce

https://v4-0-0-alpha-5.material-ui-pickers.dev/demo/daterangepicker#basic-usage

## Expected behavior

Giving error after entering first two symbols in year field under 19

## Actual behavior

Uncontrolled range

**Comment by oliviertassinari** [comment]
Why did you close the issue?

**Comment by AlexanderVishnevsky** [comment]
I think this problemcaused by [this issue ](https://github.com/mui-org/material-ui-pickers/issues/1721).

**Comment by AlexanderVishnevsky** [comment]
> Why did you close the issue?
I think this problem caused by [this issue ](https://github.com/mui-org/material-ui-pickers/issues/1721).

**Comment by AlexanderVishnevsky** [comment]
> Why did you close the issue?

I think this problem caused by #1721.
