### ISSUE TITLE
StaticDateRangePicker. Unable to override Toolbar Component

### ISSUE THREAD

**Issue by michsee** [mui-org/material-ui-pickers#1723]
There is no ability to override Toolbar Component, also `showToolbar` prop doesn't have an affect

https://codesandbox.io/s/sweet-carson-1elvr

UPD:

```
<DateRangePickerView
          open={wrapperProps.open}
          DateInputProps={DateInputProps}
          calendars={calendars}
          minDate={minDate}
          maxDate={maxDate}
          disablePast={disablePast}
          disableFuture={disableFuture}
          shouldDisableDate={shouldDisableDate}
          showDaysOutsideCurrentMonth={showDaysOutsideCurrentMonth}
          onMonthChange={onMonthChange}
          disableHighlightToday={disableHighlightToday}
          reduceAnimations={reduceAnimations}
          currentlySelectingRangeEnd={currentlySelectingRangeEnd}
          setCurrentlySelectingRangeEnd={setCurrentlySelectingRangeEnd}
          startText={startText}
          endText={endText}
          {...pickerProps}
        />
```

In case above ^, DateRangePickerView component doesn't receive `showToolbar` prop, in this way further condition `const toShowToolbar = showToolbar ?? wrapperVariant !== 'desktop';` will always return true for staticWrapper as "mobile"

That's why property showToolbar={false} doesn't work

**Comment by thalisses** [comment]
I belive that `rightArrowIcon`, `leftArrowIcon` and props about arrowIcon isn't work at `StaticDateRangePicker`

**Comment by mak-elena** [comment]
It is in general a problem of Date Range Pickers, not only of a static one.
Do you have any update on this issue?
