### ISSUE TITLE
DateTime Picker Format

### ISSUE THREAD

**Issue by karthikjagadeeswaran** [mui-org/material-ui-pickers#1725]
## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Material-UI | above V4  |
| React       |    16     |

````
<DateTimePicker
 label="Date Time
 value="2020-03-31T18:30:00.000Z"
 format="yyyy-MM-dd HH:mm:ss"
 onChange={(date:Date|null)=>form.setFieldValue(props.name,String(date))}
 />
````
Actually i am using the datetime picker in formik i want the output format as `yyyy-MM-dd HH:mm:ss` but it is coming like `Wed Apr 22 2020 00:00:00 GMT+0530 (India Standard Time)` and also it doesn't support UTC time.can you anyone help?

**Comment by oliviertassinari** [comment]
Please provide a full reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript) _may_ be a good starting point. Thank you!

**Comment by karthikjagadeeswaran** [comment]
Thanks for the reply but the issue is solved.i made a mistake on giving the value

**Comment by oliviertassinari** [comment]
@karthikjagadeeswaran If you could share the final solution, for the future users coming here, it would be awesome. Thanks 🙏.

**Comment by karthikjagadeeswaran** [comment]
```
const [ Value, setValue ]=useState(new Date())
<DateTimePicker
                            fullWidth
                            inputVariant="outlined"
                            autoOk
                            ampm={false}
                            label={"label"}
                            value={Value}
                            format="yyyy-MM-dd HH:mm:ss"
                            onChange={(date:Date|null)=>(setValue(date)}
                        />
```
if you don't have value just put `null` on feild
Thanks @oliviertassinari for Your Help
