### ISSUE TITLE
[4.0.0-alpha.5] DateTimePicker errors when value is null and view switched to input

### ISSUE THREAD

**Issue by kyle-mccarthy** [mui-org/material-ui-pickers#1737]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 4.0.0-alpha.5        |
| material-ui          |4.9.12 |
| TypeScript           |3.8.3 |
| React                | 16.13.1 |
| date-fns         | 2.12.0 | 

## Steps to reproduce

1. Use date time component with state initialized to null
2. Open the date time picker
3. Click the pencil icon in the top right of the component
3. Errors appear in console, it looks like it forward props to the input element in the dom

## Expected behavior

When the value is null, component should not error when switching to input view

## Actual behavior

Errors appear in dom when switching to input view while value is null.

```
Warning: React does not recognize the `invalidDateMessage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `invaliddatemessage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
   ...
```

## Live example

https://codesandbox.io/s/festive-zhukovsky-m3edc?file=/src/DateTimeField.tsx

**Comment by dmtrKovalenko** [comment]
There is no error on the provided codesandbox. https://codesandbox.io/s/festive-zhukovsky-m3edc?file=/src/DateTimeField.tsx

From the error message you provided: There is no more prop `invalidDateMessage` prop. They gone at the `4.0.0-alpha.6`. Please provide a reproduction with alpha.7.

**Comment by kyle-mccarthy** [comment]
Hi just wanted to make sure that you followed the reproduction steps, the error happens on the user interaction. See the attached gif.

Also it looks like `MobileDateTimePicker` is broken in alpha.6 and alpha.7.

```
renderInput is not a function
    at PureDateInput (https://m3edc.csb.app/node_modules/
material-ui/pickers/dist/material-ui-pickers.js:640:10
```

![2020-05-11 11 22 35](https://user-images.githubusercontent.com/7758522/81585521-e6c1ae00-9379-11ea-99f7-8aab85542f04.gif)

**Comment by dmtrKovalenko** [comment]
Issue is not reproducing on `v4.0.0-alpha.9`
