### ISSUE TITLE
Server hydration mismatch

### ISSUE THREAD

**Issue by mlasy** [mui-org/material-ui-pickers#1739]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    4.0.0-alpha.5     |
| material-ui          |     4.9    |
| TypeScript           |  n       |
| React                |    ^16.9.0     |
| Browser              |     chrome    |
| Peer library         |     moment    |  |

## Steps to reproduce

1. Setting up a new `next.js` project
2. Use LocalizationProvider with `locale=de`
3. Get an Error `Prop `placeholder` did not match. Server: "01.01.2019" Client: "01/01/2019"`

## Expected behavior
No error is shown, calendar is displaying german locale (`01.01.2019`). 

## Actual behavior
Calendar is still showing `01/01/2019`
## Live example
https://codesandbox.io/s/upbeat-bash-m8so8?file=/pages/index.js
or 
```import React from "react";
import { LocalizationProvider, DateRangePicker } from "@material-ui/pickers";
import MomentAdapter from "@material-ui/pickers/adapter/moment";
import moment from "moment";
import "moment/locale/en-gb";
import "moment/locale/de";
moment.locale("de");
export default () => {
  const [locale, setLocale] = React.useState("de");
  const [selectedDate, handleDateChange] = React.useState([null, null]);
  return (
    <div>
      <LocalizationProvider
        dateLibInstance={moment}
        dateAdapter={MomentAdapter}
        locale={locale}
      >
        <DateRangePicker
          startText="Check-in"
          endText="Check-out"
          value={selectedDate}
          onChange={date => handleDateChange(date)}
        />
      </LocalizationProvider>
    </div>
  );
};
```

**Comment by oliviertassinari** [comment]
@mlasy Are you sure about your reproduction? I can't see the same issue. Here is a closer working version: https://codesandbox.io/s/relaxed-ritchie-9j87f?file=/pages/index.js (but not enough)
