### ISSUE TITLE
KeyboardDatePicker - stopPropagation

### ISSUE THREAD

**Issue by jvhellemondt** [mui-org/material-ui-pickers#1741]
Hi all :)

I am combining the TreeView of the Material UI lab with the KeyboardDatePicker. 

The KeyboardDatePicker is within the label of a TreeItem. I am able to stop propagation (toggle collapse on the TreeItem) everywhere I click within the KeyboardDatePicker, except for the IconButton within the InputAdornment. The IconButton props can be modified (via InputAdornment), except the onClick prop. I wish to preserve the current functionality of the onClick event (opening the picker), and add (combine) stopPropagation on the event.

Have I overlooked anything and is this (already) possible - or is this a valid feature request?

Thanks in advance.

**Comment by oliviertassinari** [comment]
@jvhellemondt Please provide a full reproduction test case **with the latest version**. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript) _may_ be a good starting point. Thank you!

**Comment by jvhellemondt** [comment]
Hi Olivier, thank you for your reply. Please find the test case below.

https://codesandbox.io/s/infallible-rgb-0k6ej

**Comment by oliviertassinari** [comment]
@jvhellemondt Thanks, I'm adding @joshwooding to the conversation for the TreeView. I see a couple of topics to explore:

- Is stop propagation the best solution to this problem? https://css-tricks.com/dangers-stopping-event-propagation/. `event.muiHandled` could be an alternative
- Have you considered restricting the expansion action to the tree view icons?
- We do no longer maintain pickers v3. Could you upgrade the reproduction to v4.0.0-alpha.5? Thanks

**Comment by jvhellemondt** [comment]
Hi @oliviertassinari (and welcome @joshwooding),

Thank you again for your reply. Learned something again.

I think v4 helps me out here. I can see (https://v4-0-0-alpha-5.material-ui-pickers.dev/localization/date-fns) that I can pass an onClick to the IconButton in the DatePicker component now. Better yet, I can control the entire endAdornment (which I couldn't in v3, I believe).

To answer your question though:
- This article (on first read) is hard to understand for me. I am not sure the examples given apply to my situation. I did notice the author writes "Stopping propagation should be thought of like canceling an event, and it should only be used with that intent.", I believe that is my intent. Although JS itself is also confusing sometimes, so is that my intent? (don't answer this one)

*** While we're on this question, it (stopPropagation) is also used in pickers v4 => see the handleMenuOpen function (https://v4-0-0-alpha-5.material-ui-pickers.dev/localization/date-fns).

- I may be able to control the expansion event to allow only certain components (only the tree view icon is not enough). Good call. I'll investigate.

- I upgraded to v4. It gives bugs within codesandbox (Utils is not a constructor)... :( I'll check if the bugs are there locally as well.


I'll get back to you. Thanks for helping out.

**Comment by jvhellemondt** [comment]
Unfortunately my first possible solution didn't work out. I think the documentation is not fully up to date yet. 

I v3 (https://material-ui-pickers.dev/localization/date-fns) you could add the more icon within the datepicker component (for localization options). This is a difference as the datepicker component did not always include the keyboard icon (it does in v4 on desktop I believe). When the keyboard is 'added', the localization icon seems to be replace by it.

I'll try the second option now.

**Comment by jvhellemondt** [comment]
It's starting to get too hacky.

Another option is maybe to be able to provide an additional function to the onClick event of the IconButton component? Or pass the openPicker as a callback function to the onClick prop?

**Comment by jvhellemondt** [comment]
@oliviertassinari 
> ...
> * Is stop propagation the best solution to this problem? https://css-tricks.com/dangers-stopping-event-propagation/. `event.muiHandled` could be an alternative
> ...

Could you let me know how to implement event.muiHandled? Should it be as simple as calling the following function in the onClick={...}?

`const stopPropagation = (event) => {
  event.muiHandled = false;
};`

**Comment by jvhellemondt** [comment]
@oliviertassinari 
> ...
> * Have you considered restricting the expansion action to the tree view icons?
> ...

I have chosen this approach without using event.stopPropagation or event.preventDefault. Both seemed to disable the onSubmit I also had in the component.

In short, I made the treeview component controlled.
