### ISSUE TITLE
Add inputRef prop to unify behaviour with material-ui/core

### ISSUE THREAD

**Issue by RmStorm** [mui-org/material-ui-pickers#1742]
**Is your feature request related to a problem? Please describe.**
I would like the behaviour of specifying refs to be more similar to the core Material-UI library. Specifically the `TextField` component in Material-UI basically allows you to specify a ref on the underlying element in [two ways](https://material-ui.com/api/text-field/):
```js
<TextField
  inputRef={myRef}
/>
<TextField
  inputProps={{ref:myRef}}
/>
```
these behave identically as far as I can tell.

Currently the `inputProps` way is available in the picker library but specifying `inputRef` directly is not. I am using the `inputRef` way of doing things for my `TextFields` and I hoped it would work for my `datePicker` as well but it didn't. Since I haven't been using React for all that long it took me a while to figure out that I had to use the `inputProps` field instead.
 
**Describe the solution you'd like**
Implement an `inputRef` prop on the pickers that behaves the same way as the `inputRef` on the `TextField` component.

**Describe alternatives you've considered**
Just using `inputProps` is fine but it would be more newbie friendly if this behaviour is the same across different components.

**Additional context**
I haven't been using React all that long and how to use refs in the picker library has quite some history: e.g. [here](https://github.com/mui-org/material-ui-pickers/issues/1591), [here](https://github.com/mui-org/material-ui-pickers/issues/1303) and [here](https://github.com/mui-org/material-ui-pickers/issues/322). Having to sift to a bunch of old issues can be quite cumbersone and unifying this behaviour with the main Matierl-UI library would ease usage for quite many people I think!

**Comment by oliviertassinari** [comment]
Solved in #1719
