### ISSUE TITLE
DateRangePicker: Some glaring issues and potential fixes

### ISSUE THREAD

**Issue by adventofryz** [mui-org/material-ui-pickers#1744]
### **Problems**: 

1. When you use the date range picker, you almost always click only one of the dates to pick a range (which allows the user to select both the start date and end date). So, there is no point in having two Textfield boxes. 

2. The delimiter is not removable or customizable. (Have to do it manually). 
What if I would like to call the start label as 'From' and end label as 'To'. Then that hardcoded "to" text becomes redundant.
 What about changing the delimiter styling to be an 🡪 instead of a hardcoded "to" text.

3. On phones or smaller devices/viewports, it automatically uses flex-direction column and breaks the layout. So now, I have to inspect, find the element, and set it to stay as a row. 

### **Solution**
In order to solve all of the issues above, please make the date range picker **a single field** which when clicked opens up the date range picker. the single field has both the dates with a delimiter like a "right arrow" or a "-". 

Here is a probable solution:

![Group 2](https://user-images.githubusercontent.com/22504701/81178472-ec517980-8fb0-11ea-81af-dc52a2067b43.png)

**Comment by oliviertassinari** [comment]
@adventofryz There is a new `renderInput` API coming in the next alpha release. (v4.0.0-alpha.6) #1671. Regarding the standalone use case (without any input field), you should be able to use the Static version of the component. For the request of a single input field, see #1637
