### ISSUE TITLE
What use TextFieldComponent with DatePicker onClick do not propagate to the child

### ISSUE THREAD

**Issue by IgorTurko** [mui-org/material-ui-pickers#1745]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   4.0.0-alpha.5     |
| material-ui                  |   4.9.13      |
| React                          |    16.12     |
| Browser                      |    Chrome     |
| Peer library                |  moment-io|

I have this DatePicker
```
<DatePicker
  TextFieldComponent={props => TextField(props)}
   value={date}
   onChange={newDate => onChange(newDate)}
/>
```

And this TextField:
```
const TextField = props => {
  console.log('aaa', props);
  return (
    <input
      {...props.inputProps}
      onChange={props.onChange}
      onBlur={props.onBlur}
      onClick={props.onClick}
      value={props.value}
      className="input"
      type="text"
      readOnly
    />
  );
};
```

Everything looks like this:
![image](https://user-images.githubusercontent.com/4738307/81179096-dc866500-8fb1-11ea-8302-b5aadbd74402.png)

But there are several problems:
* Warning: `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? Check the render method of `KeyboardDateInput``
* When I click on input nothing happens. However I am expecting to see popup with the dates. Console.log from `TextField` does not contain onClick.

**Comment by oliviertassinari** [comment]
@IgorTurko We are changing the API in v4.0.0-alpha.6 #1671. You will no longer have to worry about forwarding the ref correctly.

@dmtrKovalenko A note in case you need this in the future, we have a special prop-type for a component type that should forward Ref: https://github.com/mui-org/material-ui/blob/939205f077c3524a30afd2aaa20e826f1ff01b6e/packages/material-ui-utils/src/elementTypeAcceptingRef.js.

**Comment by IgorTurko** [comment]
@oliviertassinari I've just install latest alpha6, but there is the same problem, no onClick event

**Comment by oliviertassinari** [comment]
@IgorTurko Do you have a reproduction?

**Comment by IgorTurko** [comment]
@oliviertassinari actually I was wrong onClick propagate as it should. The problem was that my <input /> was marked as readonly and onClick has this code:
```
     openPicker() {
        return !readOnly && !disabled && setIsOpen(true);
      }
```

so I just remove readOnly. Thanks.
