### ISSUE TITLE
Missing `renderInput` prop-type

### ISSUE THREAD

**Issue by IgorTurko** [mui-org/material-ui-pickers#1750]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   4.0.0-alpha.6     |
| material-ui                  |   4.9.13      |
| React                          |    16.12     |
| Browser                      |    Chrome     |
| Peer library                |  moment-io|

I have this DatePicker with latest alpha6
```
          <DatePicker
            variant="outlined"
            autoOk
            //renderInput={TextField}
            value={date}
            disabled={isLoading}
            onChange={newDate => onChange(newDate.format(apiDateFormat))}
            maxDate={maxDate}
            disablePast
          />
```

When I comment out the `renderInput` props I get error "renderInput is not a function";
![image](https://user-images.githubusercontent.com/4738307/81269801-89182380-9052-11ea-85fb-b0dfc930dd51.png)

Am I doing something wrong? Or `renderInput` required now?

**Comment by dmtrKovalenko** [comment]
You must provide `renderInput` Prop. Which is required from v4-alpha.6

**Comment by IgorTurko** [comment]
@dmtrKovalenko do we have this as an example somewhere?

**Comment by dmtrKovalenko** [comment]
Everywhere in the docs for v4.alpha. Check https://next.material-ui-pickers.dev

**Comment by oliviertassinari** [comment]
> Am I doing something wrong? Or renderInput required now?

@dmtrKovalenko Don't we miss a prop-type warning? Compare the error "recovery" experience between

- https://codesandbox.io/s/condescending-hoover-m5jk7?file=/index.js
- https://codesandbox.io/s/material-demo-e1fz5

**Comment by oliviertassinari** [comment]
I have repurposed a bit the issue to focus on the missing prop-type. 

> Am I doing something wrong? Or renderInput required now?

I imagine that it's not the only prop type missing. I guess we should wait for the migration in the mono-repository to benefit from this constraint: "CI fail if there is a missing prop-type".

**Comment by CodingDive** [comment]
Partially related to this issue: I'd love to see some more examples or documentation on the `renderInput` prop. Is it possible to use a non-material UI `Input` component? What kind of props would be required to make it work?

Alternatively, which props need to get passed to which component when `TextField` doesn't do the trick? What props would get passed to the `InputLabel` vs the `Input` component or do we just spread all of them to the `Input`?

**Comment by oliviertassinari** [comment]
@CodingDive Please see #1751.

**Comment by danielstern** [comment]
Still getting this error

**Comment by LukasTy** [comment]
This library is no longer maintained @danielstern.
Consider upgrading to `@mui/x-date-pickers` by following [this guide](https://mui.com/material-ui/guides/pickers-migration/).
