### ISSUE TITLE
Demo page with alpha-6 not found

### ISSUE THREAD

**Issue by AlexanderVishnevsky** [mui-org/material-ui-pickers#1753]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | v4-0-0-alpha-6     |

## Steps to reproduce

1. https://v4-0-0-alpha-6.material-ui-pickers.dev/

## Live example

![image](https://user-images.githubusercontent.com/26820006/81296164-28044600-907a-11ea-96a6-70865529ef38.png)

**Comment by dmtrKovalenko** [comment]
Thanks I forgot to alias domain. For now use https://next.material-ui-pickers.dev

**Comment by dmtrKovalenko** [comment]
Fixed https://v4-0-0-alpha-6.material-ui-pickers.dev/
