### ISSUE TITLE
Wrong highlighting of days out of the month

### ISSUE THREAD

**Issue by kerosan** [mui-org/material-ui-pickers#1756]
versions:
    "@material-ui/pickers": "^4.0.0-alpha.6",
    "@material-ui/core": "^4.9.11",
 
expected: June 31 is out of the month and 1,2,3,4,5,6 is current month
actual:
![image](https://user-images.githubusercontent.com/10149363/81313578-b84d8580-9090-11ea-8411-b8cf16b53aeb.png)

**Comment by dmtrKovalenko** [comment]
Provide a way to reproduce the issue. [This](https://codesandbox.io/s/material-ui-pickers-v4-jfm6g) code sandbox template could help.

![image](https://user-images.githubusercontent.com/16926049/81314280-9b658200-9091-11ea-85f0-fd6f146d2505.png)

It is not reproducing for me https://codesandbox.io/s/snowy-platform-zl6gg?file=/src/App.jsx

**Comment by kerosan** [comment]
done https://codesandbox.io/s/nice-brattain-0g5lt

![image](https://user-images.githubusercontent.com/10149363/81321408-3f076000-909b-11ea-87a7-9a82e2c3f93b.png)

**Comment by michsee** [comment]
reproduced here https://codesandbox.io/s/nice-brattain-0g5lt. If we move to June, 1-6 days, marked as disabled, but we can remove `reduceAnimations={true}` and everything ok!!

**Comment by kerosan** [comment]
oh thanks 👍

**Comment by dmtrKovalenko** [comment]
Hmm. I’d like to investigate why reduceAnimation has such weird side effect
