### ISSUE TITLE
Cannot clear inputValue on KeyboardDatePicker 

### ISSUE THREAD

**Issue by mkurapov** [mui-org/material-ui-pickers#1757]
![A GIF or MEME to give some spice of the internet](https://media3.giphy.com/media/IeKgCDlpTqRQbZEhBF/giphy-downsized.gif?cid=6104955ef0b88bc0a13c0b8a5e91ff2f13c15303cf30fb2a&rid=giphy-downsized.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.8   |
| material-ui          |      4.8.0   |
| TypeScript           |     3.7.3    |
| React                |     16.12.0    |
| Browser              |    Chrome     |
| Peer library         |    date-fns 2.8.1     |  |

## Steps to reproduce

1. Set KeyboardDatePicker to clearable
2. Set `inputValue=undefined` or Press clear when selecting date

## Expected behavior
Date on the picker to be blank
![Screen Shot 2020-05-07 at 1 39 14 PM](https://user-images.githubusercontent.com/15069181/81337452-3cd7de00-9068-11ea-8bbd-7adbb9ebf77c.png)

## Actual behavior
Picker shows today's date
![Screen Shot 2020-05-07 at 1 39 34 PM](https://user-images.githubusercontent.com/15069181/81337462-3f3a3800-9068-11ea-9f22-ac5f61064851.png)

## Example
With something like this:
```tsx
<KeyboardDatePicker
    clearable
    value={selectedDate}
    inputValue={undefined} // either initially, setting programmatically, or pressing Clear button
    onChange={date => handleDateChange(date)}
    format="MM/dd/yyyy"
/>
```
I want to have the date field cleared

**Comment by oliviertassinari** [comment]
@mkurapov We have stopped support on v3. Could you reproduce and provide a codesandbox with the issue on v4.0.0-alpha.7? Thanks.

**Comment by mkurapov** [comment]
This was fixed by simply using the `value` attribute, and using `null` instead of `undefined`:
```tsx
<KeyboardDatePicker
    clearable
    value={null}
    onChange={date => handleDateChange(date)}
    format="MM/dd/yyyy"
/>
```
