### ISSUE TITLE
fmt is undefined for luxon

### ISSUE THREAD

**Issue by c0nscience** [mui-org/material-ui-pickers#1767]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.10     |
| material-ui          |    4.9.5     |
| React                |     16.13.0    |
| luxon |     1.19.3    | 
| @date-io/luxon| 2.6.0 |

## Steps to reproduce

1. Put in the code for DateTimePicker from the example
```js
const Test = () => {
  const [state, setState] = useState(DateTime.utc())
  return <MuiPickersUtilsProvider utils={LuxonUtils}>
    <DateTimePicker label={'Foo'}
                    value={state}
                    onChange={setState}/>
  </MuiPickersUtilsProvider>
}
```
2. Replace with LuxonUtils of date-io lib

## Expected behavior
A field to enter date and time

## Actual behavior

Got an error saying: TypeError: fmt is undefined

## Live example

https://codesandbox.io/s/laughing-framework-lb0jr

## Note
This is not really a bug in the date picker library. I would add a comment or note in the docs to reflect, that you need to provide a value for `format` in case you are using luxon.

**Comment by c0nscience** [comment]
This for example fixes the issue:
```js
    <DateTimePicker label={'Foo'}
                    value={state}
                    format='fullDateTime24h'
                    onChange={setState}/>
```

**Comment by dmtrKovalenko** [comment]
You must not use date-io v2 with material-ui-pickers v3.

**Comment by c0nscience** [comment]
Yep works. Just didn't read the documentation carefully 🤦‍♂️ Apologies
