### ISSUE TITLE
[DateRangePicker] Implement isRangeAvailable props

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1775]
1. We use the same default behavior as https://www.daterangepicker.com/#examples, hoping that in 5 years of business as a leading solution, they did some good tradeoff. Same behavior as AntD: **users can select the same day without any error**.
2. We introduce a new API for implementing custom range, optimizing for **flexibility**

```jsx
/**
 * Determine if the current range can be selected by the user.
 * For instance, it can be used to prevent the selected range to end the weekend.
 */
isRangeAvailable?: (range: [ParsableDate, ParsableDate]) => boolean;
```

While 1. is breaking, 2. could be implemented later on.

**Comment by oliviertassinari** [comment]
Does it mean that the resolution of #1759 will require a different approach?
