### ISSUE TITLE
Open the KeyboardDatePicker dialog to open when the input field is clicked

### ISSUE THREAD

**Issue by anjayluh** [mui-org/material-ui-pickers#1788]
I need to have a datepicker component that has the calendar icon. It should be able to open when the calendar icon is clicked. But it should also open the dialog when the input field is clicked

**Describe the solution you'd like**
Maybe add a prop or avail a function to call on the onclick prop
onclick={openDialog}

**Describe alternatives you've considered**
I have found that there is an onclick prop but I don't know how to add the function to trigger the dialog to open

**Additional context**
<MuiPickersUtilsProvider utils={DateFnsUtils}>
  <KeyboardDatePicker
    variant="inline"
    fullWidth
    margin="normal"
    format={dateFormat}
    KeyboardButtonProps={{
      "aria-label": "change date",
    }}
    autoOk
    name={field.name}
    value={field.value || null}
    helperText={showError && error}
    error={Boolean(showError)}
    onClose={handleTouch}
    onChange={handleChange}
    onTouchEnd={handleTouch}
    onBlur={handleTouch}
    onClick={}//This could be where it applies
    PopoverProps={{
      anchorOrigin: { horizontal: "left", vertical: "bottom" },
      transformOrigin: { horizontal: "left", vertical: "top" },
    }}
    {...other}
  />
</MuiPickersUtilsProvider>

**Comment by oliviertassinari** [comment]
Please submit support requests and questions to StackOverflow using the tag [material-ui](http://stackoverflow.com/tags/material-ui). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/callemall/material-ui/blob/master/CONTRIBUTING.md).
