### ISSUE TITLE
utils prop in the HOC is way too generic

### ISSUE THREAD

**Issue by paoloiulita** [mui-org/material-ui-pickers#1791]
Hello! While saying thank you for all your effort, i may have an humble suggestion

**Is your feature request related to a problem? Please describe.**

`<MuiPickersUtilsProvider utils={DateFnsUtils}>`

utils is definitely a too much generic name. In fact I have problems using this lib because everywhere i mien everywhere in my app I have something imported as utils, which obviously conflicts. Date pickers are just a part of bigger applications (except for small demo apps) having an utils prop "reserved" at high priority it's not an ideal scenario IMHO.
I solved positioning the HOC as close as the pickers, but this can load to bad code practices such has repetition etc...

Another solution may be switching to hooks

**Describe the solution you'd like**

My solution is simply to call this prop in another way, something like muiPickersUtils.

thank you for your time

**Comment by dmtrKovalenko** [comment]
It is already renamed in v4

**Comment by paoloiulita** [comment]
ok sorry, currently using v3, did not know

**Comment by oliviertassinari** [comment]
@paoloiulita The new name is `dateAdapter`.
