### ISSUE TITLE
Using Calendar with MuiPickersUtilsProvider and useStaticState not working

### ISSUE THREAD

**Issue by gReis89** [mui-org/material-ui-pickers#1793]
![A GIF or MEME to give some spice of the internet](https://i1.wp.com/geekness.com.br/wp-content/uploads/2014/10/E0kQ3xN.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.10       |
| material-ui          |    4.9.14     |
| TypeScript           |         |
| React                |    16.12.0     |
| Browser              |     any    |
| Peer library         |    moment 2.25.3  date-io/moment 2.6.0     |  |

## Steps to reproduce

Trying to use `Calendar` with `MuiPickersUtilsProvider` and `useStaticState` as per [example](https://material-ui-pickers.dev/guides/static-components)

## Expected behavior

Calendar to be displayed

## Actual behavior

Error
Can not find utils in context. You either a) forgot to wrap your component tree in MuiPickersUtilsProvider; or b) mixed named and direct file imports.  Recommendation: use named imports from the module index.

## Live example

https://codesandbox.io/s/fancy-paper-x0pcx?file=/src/App.js

**Comment by oliviertassinari** [comment]
This sounds related to, if not a duplicate of #1650. Also, we have moved our effort to v4, we don't support v3. Can you reproduce the issue on http://next.material-ui-pickers.dev/?

**Comment by gReis89** [comment]
thanks for the refence!

I updated my code to use v4, replaced `Calendar` with `StaticDatePicker` and `MuiPickersUtilsProvider` with `LocalizationProvider` as per new docs, and everything worked.
