### ISSUE TITLE
Typescript: material-ui-pickers/typings/overrides does not exist

### ISSUE THREAD

**Issue by MuratGT** [mui-org/material-ui-pickers#1794]
```
import { Overrides } from "@material-ui/core/styles/overrides";
import { MuiPickersOverrides } from '@material-ui-pickers/typings/overrides' // Cannot find module '@material-ui-pickers/typings/overrides'.ts(2307)

type overridesNameToClassKey = { [P in keyof MuiPickersOverrides]: keyof 
MuiPickersOverrides[P] }

declare module "@material-ui/core/styles/overrides" {
    export interface ComponentNameToClassKey extends overridesNameToClassKey { }
}
```

How do I extend the overrides with the material-picker overrides? This does not work since `MuiPickersDateRangePickerInput` cannot be found in the core overrides.

```
const materialTheme = createMuiTheme({
    overrides: {
        MuiPickersDateRangePickerInput: {
            rangeInputsContainer: {
                maxWidth: 400
            }
        }
    }
});
```

I can fix it by asserting it `as any`, but this I don't want to.

Version:

`"@material-ui/pickers": "4.0.0-alpha.5"`

**Comment by oliviertassinari** [comment]
Linking to https://github.com/mui-org/material-ui/issues/19427 as very much related.

**Comment by dmtrKovalenko** [comment]
I suppose its because you are trying to import `material-ui-pickers` but the package is `@material-ui/pickers`

**Comment by MuratGT** [comment]
Oh sorry, that was a typo. I changed it to `@material-ui`. Same result

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Did #1796 solve this issue?

**Comment by dmtrKovalenko** [comment]
I think no, `/typings/overrides.ts` file didn't change. 
Have no idea what the problem have @MuratGT and there is still no reproduction 🤷‍♂️

**Comment by oliviertassinari** [comment]
@MuratGT Please provide a full reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/master/examples/create-react-app-with-typescript) _may_ be a good starting point. Thank you!

**Comment by MuratGT** [comment]
https://codesandbox.io/s/snowy-framework-kv2qn?file=/src/timerange.test.tsx

**Comment by dmtrKovalenko** [comment]
It doesn't throw an error if downgrade to mui core 4.10.0 (#1849):
https://codesandbox.io/s/zealous-brook-5urzm?file=/src/timerange.test.tsx

There is an issue with missing typings, but it will be fixed in the next release

**Comment by MuratGT** [comment]
You don't get this error?

> Object literal may only specify known properties, and 'MuiPickersDateRangePickerInput' does not exist in type 'Overrides'.ts(2322)

**Comment by dmtrKovalenko** [comment]
Yes, but it is not the same as "Typescript: material-ui-pickers/typings/overrides does not exist" in issue title. If so it is fixed by #1796

**Comment by oliviertassinari** [comment]
I have updated the dependencies of the reproduction of @MuratGT: https://codesandbox.io/s/sparkling-wildflower-6e8wx?file=/src/timerange.test.tsx. This gives us the reported error:

> 'MuiPickersDateRangePickerInput' does not exist in type 'Overrides'

Now, if we apply the guidelines in https://next.material-ui-pickers.dev/guides/css-overrides#typescript, the error is gone: https://codesandbox.io/s/youthful-architecture-f8m19?file=/src/timerange.test.tsx. The bug was fixed 👌.

**Comment by oliviertassinari** [comment]
@MuratGT See #1858 for a follow-up iteration on the problem, in order to polish it. But the bulk of the problem should already be fixed.
