### ISSUE TITLE
[Datepicker] - add ok and cancel button

### ISSUE THREAD

**Issue by hadasmaimon** [mui-org/material-ui-pickers#1795]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
I don't know why I don't find how to add the ok cancel button (It works in the past)
![image](https://user-images.githubusercontent.com/40765442/82452214-a7047000-9ab7-11ea-93d7-4224368d1a70.png)

## Expected Behavior 🤔
expected to have the ok and cancel buttons.
![image](https://user-images.githubusercontent.com/40765442/82452353-d0250080-9ab7-11ea-82a7-ef0264719749.png)

## Context 🔦

![image](https://user-images.githubusercontent.com/40765442/82452491-fea2db80-9ab7-11ea-8321-4361f2821dc3.png)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Material-UI | v 4.0.0-alpha.7  |
| React       |         |
| Browser     |         |
| TypeScript  |         |
| etc.        |         |

**Comment by dmtrKovalenko** [comment]
There is no way to display dialog buttons on the desktop with `<DatePicker />`. 
The only option is to use `MobileDatePicker`.

**Comment by oliviertassinari** [comment]
A couple of buttons and there use cases that come to mind for the date picker:

- "OK" when we don't want the "autoOK" behavior
- "Today" bottom when we get lost
- "Clear" if we want to reset the value to null

That could potentially be useful. I don't know if it's something that should be built-in, or only provide a customization point for doing it.

**Comment by dmtrKovalenko** [comment]
We could think about some option to render `anything` after the calendar. It could be helpful for buttons or displaying related helper information for users. Something like `renderBottomInfo`. 

For instance react-dates have the following prop 
```js
<DateRangePickerWrapper calendarInfoPosition="bottom" renderCalendarInfo={renderCalendarInfo} autoFocus />
```

http://airbnb.io/react-dates/?path=/story/drp-calendar-props--with-info-panel-bottom

**Comment by oliviertassinari** [comment]
A random thought on the possible API:

```jsx
<DatePicker
  renderPopup={(props) => {
    <div>
      <StaticDatePicker {...props} />
      <Button>OK</Button>
    </div>
  }}
/>

**Comment by hadasmaimon** [comment]
good thanks!

**Comment by Jesusz0r** [comment]
how can I override the 'OK' and 'Cancel' text from KeyboardDatePicker?

**Comment by hadasmaimon** [comment]
What do you want to do? do you want to change the ok text? if yes use the `okLabel`
![image](https://user-images.githubusercontent.com/40765442/83554685-d71b2c80-a515-11ea-961b-6c8ee5e4813f.png)

`okLabel='Done'`
