### ISSUE TITLE
Clearing a KeyboardDatepicker value opening the calender unlike KeyboardDatePicker.

### ISSUE THREAD

**Issue by sirajalam049** [mui-org/material-ui-pickers#1799]
I have added a clear button in both DatePicker and KeyboardDatePicker. The ideal behavior should be, the values should be cleared which is happening correctly in KeyboardDatePicker, but in the case of DatePicker, the calendar is opening on clicking the clear button.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.
- [x] The issue is present in the latest release.

## Current Behavior 😯
The calendar is opening on clicking the clear button in DatePickerComponent.

## Expected Behavior 🤔
Just the text field should be cleared, as happening in the case of KeyboardDatePicker.

I have reproduced the issue in the following code sandbox.

https://codesandbox.io/s/material-ui-pickers-usage-demo-8gu6h?file=/package.json

**Comment by sirajalam049** [comment]
Thanks, @oliviertassinari  for v4 example. But there's no separate KeyboardDatepicker and DatePicker. Only DatePicker is imported, which is behaving as KeyboardDatePicker by default. And as there's no documentation for this too, I tried trial and error methods and type definition to make it work like DatePicker without Keyboard input, but I couldn't find it.

In addition, as there's no KeyboardDatePicker in the v4, so the issue is directly for v3. Also, v4 doesn't seem stable and no documentation as of now, so I believe no one will move to v4 right now.

So what solution do we have in that case?

**Comment by oliviertassinari** [comment]
@sirajalam049 I think that you can wait for the release of v4, we will provide a high-level upgrade guide.

**Comment by sirajalam049** [comment]
Just found a way of doing this, adding here in case someone looking for it.

Add  e.stopPropagation(); on the click handler of the close icon button, it won't' pass the click event to the calendar and it won't open.
