### ISSUE TITLE
DateRange, MuiPickersUtilsProvider not exported from '@material-ui/pickers'

### ISSUE THREAD

**Issue by yinonby** [mui-org/material-ui-pickers#1800]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    4.0.0-alpha.7     |
| material-ui          |    4.9.8     |
| TypeScript           |         |
| React                |     16.9.0    |
| Browser              |    chrome     |
| Peer library         |         | date-fns |

## Steps to reproduce
Just install  "@material-ui/pickers": "4.0.0-alpha.7",

## Expected behavior

I realize this is under development; we would like to check some features, but the imports are not working, need to be able to import basic pickers, as well as, DateRangePicker, DateRange, MuiPickersUtilsProvider 

## Actual behavior

'DateRange' is not exported from '@material-ui/pickers'.
'MuiPickersUtilsProvider' is not exported from '@material-ui/pickers'.

**Comment by oliviertassinari** [comment]
@yinonby Why should these modules be exported?

**Comment by dmtrKovalenko** [comment]
I suppose you didn't find a 'next' documentation https://next.material-ui-pickers.dev/

We do not have `MuiPickersUtilsProvider` anymore it was replaced by `LocalizationProvider`. And `DateRange` is only ts type that is exported

**Comment by yinonby** [comment]
Oh right, thanks for the tip, was looking at the wrong installation guide.

**Comment by laurenfv** [comment]
Hello, I am having this same issue as stated above where the actual behavior is: 
```'DateRange' is not exported from '@material-ui/pickers'```.

I am following the installation docs exactly as described in https://next.material-ui-pickers.dev/ and had a teammate follow them independently of me to check. They got the same result.

Thanks!

**Comment by jadewale** [comment]
@dmtrKovalenko  https://next.material-ui-pickers.dev/demo/daterangepicker  Still shows DateRangePicker is exported.

I keep getting DateRangePicker is not exported.

import { DateRangePicker, DateRange, DateRangeDelimiter } from "@material-ui/pickers";

**Comment by oliviertassinari** [comment]
@jadewale make sure you have the right version installed.
