### ISSUE TITLE
DateRangePicker doesn't accept end date same as start date

### ISSUE THREAD

**Issue by yinonby** [mui-org/material-ui-pickers#1801]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |      4.0.0-alpha.7   |
| material-ui          |     4.9.14    |
| TypeScript           |         |
| React                |    16.9.0     |
| Browser              |    chrome     |
| Peer library         |         |  |

## Steps to reproduce

open DateRangePicker and select start and end dates on the same date

## Expected behavior

picker will accept the selected range

## Actual behavior

picker doesn't accept the range

## Live example

https://codesandbox.io/s/interesting-star-ic79t

**Comment by dmtrKovalenko** [comment]
Thanks for rising an issue! Can you please provide more details about the issue? 
Please provide a reproduction, this [codesandbox template](https://codesandbox.io/s/material-ui-pickers-v4-jfm6g) could be useful. 

Thanks ;)

**Comment by yinonby** [comment]
updated the issue with the sandbox

**Comment by oliviertassinari** [comment]
@yinonby Duplicate of #1759?

**Comment by yinonby** [comment]
Yes
