### ISSUE TITLE
Buggy ternary conditions

### ISSUE THREAD

**Issue by Philipp91** [mui-org/material-ui-pickers#1803]
Not sure if this leads to any user-visible issues, but these ternary conditions don't work like the programmer intended:

https://github.com/mui-org/material-ui-pickers/blob/214439dbdaabcb6fc80f61c9f81825ca9dff5b94/docs/_shared/svgIcons/KawaiiIcon.tsx#L35
https://github.com/mui-org/material-ui-pickers/blob/4a1b6b0ccac0c47b7c206850d839bbeff8604872/lib/src/_shared/hooks/useMaskedInput.tsx#L78
https://github.com/mui-org/material-ui-pickers/blob/214439dbdaabcb6fc80f61c9f81825ca9dff5b94/lib/src/views/Calendar/Day.tsx#L195

because `a || b ? c : d` is interpreted as `(a || b) ? c : d`.

https://stackoverflow.com/questions/42026158/precedence-logical-or-vs-ternary-operator#42026340

**Comment by oliviertassinari** [comment]
@Philipp91 It looks good from my end. Thanks for raising, I think that we can close.

1. is documentation, looks broken but not important here, I think that we should ignore
2. looks ok
3. looks ok
