### ISSUE TITLE
How to override date picker headers?

### ISSUE THREAD

**Issue by gReis89** [mui-org/material-ui-pickers#1805]
I'm trying to customize the DatePicker designs as close as possible to my requirements. We are using 3 letters(mon - tue - wed...) to describe our week days but I can't see any option where I can customize the default headers(M - T - W...).

![Screen Shot 2020-05-22 at 19 09 45](https://user-images.githubusercontent.com/11444682/82713135-4a908480-9c60-11ea-9595-cbc4d928b16d.png)

**Comment by dmtrKovalenko** [comment]
It is possible using date-io adapter inheritance. Here is a guide https://next.material-ui-pickers.dev/guides/date-io-customization#global-formats-customization

You need to extend `getWeekdays` method and simply return an array with 7 strings. But make sure that your weekdays will be properly displayed for different locales 😉

**Comment by oliviertassinari** [comment]
Do we have a demo for it? What about we add one?

I have included the concern in https://github.com/mui-org/material-ui/issues/20960.

**Comment by tpeek** [comment]
@dmtrKovalenko Unfortunately, it looks like the behavior for showing just one character for the weekday is hardcoded: 

`{day.charAt(0).toUpperCase()}`

https://github.com/mui-org/material-ui-pickers/blob/v4.0.0-alpha.12/lib/src/views/Calendar/Calendar.tsx#L181

It doesn't matter what `getWeekdays` returns, the date picker will always show just the first letter.
