### ISSUE TITLE
v4 docs API table is not responsive

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1819]
On [API pages](https://material-ui-pickers.mui-org.now.sh/api/DatePicker), the Description column doesn't wrap or expand to fill wide screens.

![image](https://user-images.githubusercontent.com/33569/82785753-14960080-9e18-11ea-980c-582fc02fbc7c.png)

[v3 docs](https://material-ui-pickers.dev/api/KeyboardDateTimePicker) look fine.

**Comment by oliviertassinari** [comment]
@dandv We will get it sorted with https://github.com/mui-org/material-ui/issues/19706 but maybe there is a quick win here.
