### ISSUE TITLE
showTodayButton and showTabs appear to not do anything in v4

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1821]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  4.0.0.alpha-7       |
| material-ui          |  4.10.0       |
| Browser              |  Chromium 83       |
| Peer library         |  date-fns       |

## Steps to reproduce

1. Launch the [CSB](https://codesandbox.io/s/mui-v4-datetimepicker-showtodatbutton-showtabs-have-no-effect-m9fbx?file=/index.tsx) and pick a date from the next month.
2. Set `showTabs={true}`.

## Expected behavior

With `showTodayButton` set in a `DateTimePicker`, when navigating away from the current month, I should see a "Today" button to go back to the current date.

With `showTabs={false}` I expect to see something different than with `showTabs={true}`.

## Actual behavior

No today button.

No difference in displace with `showTabs` false vs. true.

## Live example

https://codesandbox.io/s/mui-v4-datetimepicker-showtodatbutton-showtabs-have-no-effect-m9fbx?file=/index.tsx

![image](https://user-images.githubusercontent.com/33569/82792612-7e1c0c00-9e24-11ea-97cb-1ea832ec12ef.png)

**Comment by dmtrKovalenko** [comment]
It is not working for Desktop mode, because we are not rendering dialog actions. At least for now.

**Comment by WesleyKapow** [comment]
> It is not working for Desktop mode, because we are not rendering dialog actions. At least for now.

Would be great to render them or make them optional. I want desktop view of 2 calendars but with an explicit "SAVE" button.

**Comment by delesseps** [comment]
> > It is not working for Desktop mode, because we are not rendering dialog actions. At least for now.
> 
> Would be great to render them or make them optional. I want desktop view of 2 calendars but with an explicit "SAVE" button.

+1  Today very useful.  Is there any keyboard alternative for selecting today?
