### ISSUE TITLE
Don't display clearable fields in "error" state initially

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1824]
**Is your feature request related to a problem? Please describe.**
Sometimes a null date field should not be flagged as an error:
1. When the user hasn't reached there yet while filling the form
2. When the field is optional.

**Describe the solution you'd like**
Don't set `.Mui-error` initially.

**Describe alternatives you've considered**
I've looked at the ["Clear initial state" example](https://next.material-ui-pickers.dev/demo/datetime-picker#customization), and it has the `Mui-error` class from the start.

![image](https://user-images.githubusercontent.com/33569/82799437-e7088180-9e2e-11ea-852c-22f069ecdf26.png)

**Additional context**
I remember reading it's bad UX to flag all required empty fields as errors, before the user has had a chance to at least tab into them.

**Comment by dmtrKovalenko** [comment]
It is a known bug that is already fixed in `develop` https://dev.material-ui-pickers.dev/demo/datetime-picker#customization
