### ISSUE TITLE
Zero the second in DateTimePicker?

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1825]
**Is your feature request related to a problem? Please describe.**
When I select a time (and esp. a datetime), and the format doesn't include seconds, I expect the second to be zero. Instead, the second seems to be the current second?

https://codesandbox.io/s/material-keyboarddatetimepicker-zero-the-second-z6kgi?file=/index.tsx

I could understand the logic of leaving the second default, as a generalization of a DatePicker returning the current time (instead of 0h0m). Sorry if I missed this behavior in the docs somewhere.

In a scheduling use case, if something needs to happen tomorrow at 09:00 and it happens at 09:00:59 because the date happened to be selected now at second 59, that could be a serious problem.

**Comment by dmtrKovalenko** [comment]
#899

**Comment by dmtrKovalenko** [comment]
No, second is a meaningful part of the time, there was an issue somewhere that was requested to not clear seconds for the output (cannot find it). 

So if you need to annulate seconds you can clear it manually for the value passing down to pickers. use `value={setSeconds(value, 0)}`.

**Comment by oliviertassinari** [comment]
@dandv I think that it's related to #1358, #1526. There is a tradeoff between resetting the none selected parts of the date object to 0 and leaving them alone.

**Comment by Angelk90** [comment]
@oliviertassinari : 

I'm having a similar problem, what I want to achieve is that the seconds and thousandths of seconds are zero.

But when I click on the ok button on the calendar, in addition to the hours you have minutes, I am also given the seconds.

If I change hours or minutes, the seconds remain those set at the beginning.

There is a way to get them to be 0.

```
<DateTimePicker
label={`${t('FROM')} *`}
placeholder={`${t('FROM')} *`}
inputVariant="outlined"
ampm={false}
disablePast
value={from}
onChange={onChangDate('from')}
format="DD/MM/YYYY HH:mm"
margin="dense"
size="small"
fullWidth
error={checkError('from')}
/>
```

**Comment by Angelk90** [comment]
@oliviertassinari , @dmtrKovalenko : 

I'm having a similar problem, what I want to achieve is that the seconds and thousandths of seconds are zero.

But when I click on the ok button on the calendar, in addition to the hours you have minutes, I am also given the seconds.

If I change hours or minutes, the seconds remain those set at the beginning.

There is a way to get them to be 0.

```
<DateTimePicker
label={`${t('FROM')} *`}
placeholder={`${t('FROM')} *`}
inputVariant="outlined"
ampm={false}
disablePast
value={from}
onChange={onChangDate('from')}
format="DD/MM/YYYY HH:mm"
margin="dense"
size="small"
fullWidth
error={checkError('from')}
/>
```
