### ISSUE TITLE
Missing theme typography usage on day numbers

### ISSUE THREAD

**Issue by sylvestrevgen** [mui-org/material-ui-pickers#1830]
I want to use date picker range, so I update material ui pickers to v4.0.0-alpha.7, and update relative material ui packages. After that, my fonts in all datepickers which all worked correctly are missing and calendars day numbers showing with serif font. I don't know how I can pass font-family directly in datepicker or fix this with other solution. What I did wrong or how can I fix this? I use custom fonts, but with Roboto it also don't work.

**Comment by oliviertassinari** [comment]
@sylvestrevgen Do you want to work on the issue with a pull request :)? What do you think of this fix?

```diff
diff --git a/lib/src/views/Calendar/Day.tsx b/lib/src/views/Calendar/Day.tsx
index 4311e3e7..43a30a4c 100644
--- a/lib/src/views/Calendar/Day.tsx
+++ b/lib/src/views/Calendar/Day.tsx
@@ -16,6 +16,8 @@ const muiComponentConfig = { name: 'MuiPickersDay' };
 export const useStyles = makeStyles(
   theme => ({
     day: {
+      ...theme.typography.body1,
+      fontSize: theme.typography.pxToRem(12),
       width: DAY_SIZE,
       height: DAY_SIZE,
       borderRadius: '50%',
@@ -23,8 +25,6 @@ export const useStyles = makeStyles(
       // background required here to prevent collides with the other days when animating with transition group
       backgroundColor: theme.palette.background.paper,
       color: theme.palette.text.primary,
-      fontSize: theme.typography.caption.fontSize,
-      fontWeight: theme.typography.fontWeightMedium,
       '&:hover': {
         backgroundColor: fade(theme.palette.action.active, theme.palette.action.hoverOpacity),
       },
```

**Comment by sylvestrevgen** [comment]
@oliviertassinari Unfortunately, I have a lot of work and I don't have time to do this :( It would be great if you will fix this in your own. I think, your solution resolve this problem by passing all typography body component props in day numbers. Wish you will fix this quickly :)

**Comment by oliviertassinari** [comment]
OK, no problem, we can wait for a new first contributor to jump in :)
