### ISSUE TITLE
Option to mark events on calendar.

### ISSUE THREAD

**Issue by abhi11verma** [mui-org/material-ui-pickers#1832]
**Is your feature request related to a problem? Please describe.**
I am looking to use the material-ui-picker as a calendar widget and put markers on the Days.
Current example of customizing the Day component using renderDay option does work.

The issue is how to modify the dayComponent text color. 
Its possible to mark badge(dots, icons) but how to modify the textcolor of Day based on condition.

**Describe the solution you'd like**
An option to mark events will be good.

Can someone point me how can I customize the Day component to modify text Color.

**Reference Image**
![image](https://user-images.githubusercontent.com/9005396/82992144-5ee7cf00-a01c-11ea-83f5-3d8fb5378b50.png)

**Comment by abhi11verma** [comment]
Found the solution, read somewhere in the docs that clone element can be used.
Pasting the code-snipet here for reference.

```
renderDay={(day, selectedDate, isInCurrentMonth, dayComponent) => {
          const isDeadline = isInCurrentMonth && includes(endDates, moment(day).format('YYYY-MM-DD'));
          const isEvent = isInCurrentMonth && includes(eventDates, moment(day).format('YYYY-MM-DD'));
let CustomDay = <span
            className={classNames(isDeadline && classes.deadline, isEvent && classes.event)}>
            {moment(day).format('D')}
            </span>
          // Here create a clone of the dayComponent with custom children component created above.
          // With the applied changes and styles.
          let element = React.cloneElement(dayComponent, [], CustomDay)
          return <div>{element}</div>
        }}
```



I discovered that next version of the library has <Day/> component which can be customized and used.
I am using 3.9.0 currently.

**Comment by oliviertassinari** [comment]
@abhi11verma Thanks for sharing.

**Comment by bneigher** [comment]
@abhi11verma can you point us to this new component in next branch? I'de love to use it

**Comment by oliviertassinari** [comment]
@abhi11verma In case you would like to contribute, I think that your case would make a great new example in the documentation 👌

**Comment by abhi11verma** [comment]
> @abhi11verma In case you would like to contribute, I think that your case would make a great new example in the documentation 👌

@oliviertassinari  Would love to contribute. Could you point me in the right direction where to start from?

**Comment by dmtrKovalenko** [comment]
There is an example, even 2 with custom day renderers
