### ISSUE TITLE
PopoverProps are not passed down to Popover component

### ISSUE THREAD

**Issue by discourseMonger** [mui-org/material-ui-pickers#1835]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |     v4.0.0-alpha.7    |
| material-ui          |    4.9.13     |
| TypeScript           |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. Try to pass PopoverProps to DatePicker component (like anchorOrigin or transformOrigin). For example, like this:
```js
      <LocalizationProvider dateAdapter={DateFnsUtils}>
        <DatePicker
          label="Basic example"
          value={selectedDate}
          onChange={(date) => handleDateChange(date)}
          renderInput={(props) => <TextField {...props} />}
          PopoverProps={{
            anchorOrigin: {
              vertical: "top",
              horizontal: "right",
            },
            transformOrigin: {
              vertical: "top",
              horizontal: "right",
            }
          }}
        />
      </LocalizationProvider>
```
## Expected behavior

Popover (ie DatePicker) should reposition based on passed anchorOrigin/transformOrigin props (vertical/bottom).

## Actual behavior

Popover position does not change, On versions 3.x PopoverProps worked nicely with variant="inline". Am I missing something here?

**Comment by oliviertassinari** [comment]
@discourseMonger Thanks for the report, though, we will likely rename `PopoverProps` -> `PopperProps`.

**Comment by oliviertassinari** [comment]
Also, we will likely make the placement you are looking after the default #1768.

**Comment by lamhungypl** [comment]
How to change ref of Popper to right button? i use KeyboardDatePicker

**Comment by oliviertassinari** [comment]
@lamhungypl Wait for #1850 to be released.
