### ISSUE TITLE
Picker inconsistently handles changes to timezone

### ISSUE THREAD

**Issue by joshuahiggins** [mui-org/material-ui-pickers#1836]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  `3.2.6` - `4.0.0-alpha.7`  |
| @material-ui/core          |  any |
| React                | any |
| Browser              |  all |
| Peer library         |   moment (any)   |

## Steps to reproduce

1. Set a default timezone `moment.tz.setDefault('America/Phoenix')`
2. Select any date / time in `DateTimePicker`
  * Note the output value of a UTC timestamp
3. Change the default timezone `moment.tz.setDefault('America/New_York')`
  * Note that the `TextField` correctly changed the value to reflect the timezone change
4. Reopen date picker
  * Note that the `DateTimePicker` and `TextField` are visually inconsistent with the time
5. Select a new date
  * Note that the 2 UI components remain visually inconsistent and the output value of a UTC timestamp is still based on the original timezone

## Expected behavior

The components visually display consistently, recognizing the change to the timezone internally.

## Actual behavior

The `DateTimePicker` remains out of sync with the `TextField`. Internally, the `DateTimePicker` continues to utilize the original timezone, even when a new date is selected that includes the new timezone in the Moment object.

On a hacky level, I can get around this by overriding the `isEqual` method on `@date-io/moment`: 

```
MomentUtils.prototype.isEqual = (value, comparing) => {
  if (value === null && comparing === null) return true;
  return moment(value).isSame(comparing) && value?._z?.name === comparing?._z?.name;
}
```

The reason this works is because the picker is closed at the time that the timezone is changed, so when `usePickerState` calls `useEffect`, it immediately passes through the Moment object with the new timezone and same UTC stamp instead of rejecting it since they both have the same UTC time. This is then propagated through the shared components and they all have the correct timezone set the next time I open the component.

I tried to trace the code further to see why exactly it's not propagated the next time you select a date (since it would also receive the correct moment tz then), but I couldn't put my finger on where the state of the original moment object is being re-referenced, perpetuating the usage of the incorrect timezone. I suspect it's in some memo somewhere. 

I even tried to utilize the latest alpha, overriding the Moment utilities via my own memoization to try and re-render the component with new utils every time I change the timezone, but whatever it's referencing internally appears to be the original date object and not the tools themselves.

**Comment by dmtrKovalenko** [comment]
Did you try to pass your `libInstnace={momentTimezone}`. I think that moment timezone should override `isEqualMethod` by itself

**Comment by joshuahiggins** [comment]
Yes I am doing that and even tried a version of that where I manually set a property to force the memo to recognize a change to the library so the constructor would rebuild. 

Moment time zone doesn’t change the core library, it just adds time zone methods to it. Also the evaluation of equality is based on the UTC time stamp, which wouldn’t change if a time zone is different. 

The issue is within the picker code though. It’s using a UTC equality check in that one specific scenario allowing my hacky bypass to work, but somewhere else within the code it’s hanging on to the original moment object which will have time zone information. 

Mind you, the equality hack doesn’t actually fix the problem. It just fixes it in my use case because you guys have a bypass in place where setting a new date while the picker is closed passes it through as accepted immediately. If the picker is open and you select a new date, even though it will register an inequality, it’ll still hang on to the time zone information of the first selection because of whatever it’s doing different compared to when it simply accepts the change during the picker being closed.
