### ISSUE TITLE
Export more types

### ISSUE THREAD

**Issue by michael-land** [mui-org/material-ui-pickers#1839]
**Is your feature request related to a problem? Please describe.**

These types are very useful when integrated with other form libs or build on top of Date Input

```ts
// current
import { DateRange, RangeInput } from '@material-ui/pickers/src/DateRangePicker/RangeTypes';
import { BasePickerProps } from '@material-ui/pickers/src/typings/BasePicker';

// expect
import { DateRange, RangeInput, BasePickerProps } from '@material-ui/pickers';
```
 

**Describe the solution you'd like**

Export types such as BasePickerProps, DateRange, RangeInput

**Describe alternatives you've considered**

**Additional context**

**Comment by oliviertassinari** [comment]
What's your use case?

**Comment by dmtrKovalenko** [comment]
It was done in the next branch. We reexported all the Props for all the components.

**Comment by oliviertassinari** [comment]
@dmtrKovalenko should we export or not the types of the private components that we don't allow to override with `theme.props`? If we don't want to export them, do we?

**Comment by dmtrKovalenko** [comment]
No, but BasePickerProps are actually shared props between all public root components, so we export them

**Comment by oliviertassinari** [comment]
So we can close? :)

**Comment by dmtrKovalenko** [comment]
I`d like to make sure everything is exported, and then close it

**Comment by oliviertassinari** [comment]
@xiaoyu-tamu Could you try the next version out (v4.0.0-alpha.7)? :)

**Comment by michael-land** [comment]
> @xiaoyu-tamu Could you try the next version out (v4.0.0-alpha.7)? :)

Thanks. I will try the next version when it release.

v4.0.0-alpha.7 was released on May 6th.

**Comment by oliviertassinari** [comment]
@xiaoyu-tamu Did you try `v4.0.0-alpha.8`?

**Comment by michael-land** [comment]
Yes, it works👍👍👍
