### ISSUE TITLE
[RFC] Should use pseudo-classes

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#1845]
Material-UI has the concept of pseudo-classes that I believe we could leverage more often in the picker components. The concept is detailed in https://material-ui.com/customization/components/#pseudo-classes, it also comes with an explanation of why and when it can be interesting. 

I have founds these potential states we might likely want to refactor to ease customizations:

- https://github.com/mui-org/material-ui-pickers/blob/23ff4f97411be4921356ee70fabd28b041318134/lib/src/views/Calendar/Day.tsx#L53
- https://github.com/mui-org/material-ui-pickers/blob/23ff4f97411be4921356ee70fabd28b041318134/lib/src/views/Calendar/Day.tsx#L65
- https://github.com/mui-org/material-ui-pickers/blob/23ff4f97411be4921356ee70fabd28b041318134/lib/src/views/Calendar/Year.tsx#L47
- https://github.com/mui-org/material-ui-pickers/blob/23ff4f97411be4921356ee70fabd28b041318134/lib/src/views/Calendar/Year.tsx#L54
- https://github.com/mui-org/material-ui-pickers/blob/7d75a2c663cf4455f9c6f7284cedb76ba97992dd/lib/src/_shared/ToolbarText.tsx#L24

**Comment by dmtrKovalenko** [comment]
Which pseudo-class do you propose for `selected` state? It is not the same as `focused`

**Comment by oliviertassinari** [comment]
@dmtrKovalenko We have been using `selected` so far: https://material-ui.com/customization/components/#pseudo-classes.

**Comment by dmtrKovalenko** [comment]
There is no `selected` pseudo class, as far as I know

**Comment by oliviertassinari** [comment]
The idea would be to create a `selected: {}` style rule to serve this purpose.
