### ISSUE TITLE
incompatible with @material-ui/core": "4.10.1

### ISSUE THREAD

**Issue by michael-land** [mui-org/material-ui-pickers#1849]
see https://github.com/mui-org/material-ui/pull/21201

```
./node_modules/@material-ui/pickers/DateTimePicker.js
Module not found: Can't resolve '@material-ui/core/Modal/TrapFocus' in '/Users/michaelli/Workspaces/jtd-admin/node_modules/@material-ui/pickers'
```

**Comment by oliviertassinari** [comment]
A downside of splitting the repositories, version distribution is harder to coordinate and easier to forget about. Same as: #1619.

**Comment by yanickrochon** [comment]
What's the resolution for this? Just updated `@material-ui/core` and got this.

EDIT : solution is to manually update to `4.0.0-alpha.8`.

**Comment by rosariogueli** [comment]
4.0.0-alpha.8 worked for me 👍

**Comment by santilp95** [comment]
solution?
