### ISSUE TITLE
Static version always stealing focus

### ISSUE THREAD

**Issue by blitzbohne** [mui-org/material-ui-pickers#1853]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.8  |
| material-ui          |  4.8.2 |
| TypeScript           |   -     |
| React                |  16.12.0  |
| Browser              | Chrome 83.0.4103.61  |
| Peer library         |     moment 2.24.0    |

## Steps to reproduce

1. Render a DatePicker in your own Popover instance
2. Set its mode to static and set allowKeyboardControl to false
3. Focus on an input field and let the custom Popover render

## Expected behavior

In static mode and if allowKeyboardControl is set to false it should not steal the focus or at least provide an option to prevent this. 

The reason for preventing stealing focus is that we have an excel like grid and when it steals our focus away, the grid blurs the currently focused cell which is not what we want. I think there is always a valid reason to prevent stealing / trapping the focus.

## Actual behavior

The Popover steals the focus from the input

**Comment by dmtrKovalenko** [comment]
Incomplete. 
Use our bug template to fill the issue. We don't have enough information to response

**Comment by blitzbohne** [comment]
@dmtrKovalenko done as requested

**Comment by dmtrKovalenko** [comment]
See it. 
In v3 it was a bug that was fixed by v4. From v4 it needs to pass `allowKeyboardControl` explicitly to enable autoFocuses.

**Comment by alpfactory-alex** [comment]
I see. I tried to use v4 but its hard to upgrade and it seems the pure Static DatePicker doesn't work yet as after all changes done it complains about "src/_shared/PureDateInput.tsx:120" that renderInput is not a function though I understand the PureDateInput has no use when mode is set to static?

**Comment by alpfactory-alex** [comment]
Ok I returned a dummy component in renderInput() and it seems it renders this instead of the DatePicker itself when its variant is set to static? Is the static mode already be supported on v4?

**Comment by alpfactory-alex** [comment]
Ok my bad figured there's new docs on https://v4-0-0-alpha-7.material-ui-pickers.dev/demo/datepicker all good. Can close this now I think.

**Comment by blitzbohne** [comment]
Ok it still doesn't work? Using StaticDatePicker now it steals the focus away as before. Static one should disable keyboard according to the docs automatically anyway. But even passing allowKeyboardControl=false to StaticDatePicker makes it stealing the focus?

**Comment by blitzbohne** [comment]
@dmtrKovalenko sorry for the confusions. However I can safely confirm in Alpha 7 the issue is still the same and it steals the focus ;(

**Comment by oliviertassinari** [comment]
@alpfactory-alex Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/festive-golick-ej7q7?file=/src/App.jsx) _may_ be a good starting point. Thank you!
