### ISSUE TITLE
Date Range Picker not correctly handling click-off listener on controlled open

### ISSUE THREAD

**Issue by Zanoro9000** [mui-org/material-ui-pickers#1854]
## Environment

| Tech                          | Version |
| ----------------------| ------- |
| @material-ui/pickers | 4.0.0-alpha.7 |
| material-ui                | 4.9.14 |
| TypeScript                 | 3.8.3 |
| React                        | 15.6.2  |
| Browser                    | chrome, firefox |
| Peer library               | moment 2.26 |

## Steps to reproduce

```
  const [open, setOpen] = useState<boolean>(false);
  const [dateRange, setDateRange] = useState<DateRange>();

  const onOpen = () => {
    setOpen(true);
  };

  const onChange = (newRange) => {
    setDateRange(newRange);
  };

  const onAccept = (newRange) => {
    if (newRange[0] && newRange[1]) 
   ...
  };

  const onClose = () => {
    setOpen(false);
  };

  return (
    <>
      <Button id={id} onClick={onOpen} focusRipple >
        <DateRangeIcon />
      </Button>
      <DateRangePicker
        value={dateRange}
        open={open}
        onOpen={onOpen}
        onChange={onChange}
        onAccept={onAccept}
        onClose={onClose}
        renderInput={(startProps, endProps) => (
          <>
            <TextField
              {...startProps}
            />
            <TextField
              {...endProps}
            />
          </>
        )}
      />
    </>
  );

```

1. Use open/close on DateRangePicker example
2. Click button to open DateRangePicker
3. Click away from the dialog - it should close but it stays open
4. Clicking away from the dialog does not close it until you click on anywhere in the dialog, then away, then it behaves properly

## Expected behavior
When clicking the button to open the picker then immediately clicking away, the picker closes.
The expected behavior is shown on the normal date picker example:
https://v4-0-0-alpha-7.material-ui-pickers.dev/guides/controlling-programmatically

## Actual behavior

Example below shows differing behavior with only changing which type of picker is used.

## Live example

https://codesandbox.io/s/gracious-jones-epqfo?file=/src/App.jsx

**Comment by oliviertassinari** [comment]
@Zanoro9000 The DateRangePicker will try to close when the input is blurred. If you open the picker without focusing the input, the picker won't close when clicking outside. You can add ClickAwayListerner or again, focus the input to solve this case. The DatePicker will behave like the DateRangePicker in one of the next releases.
