### ISSUE TITLE
Allow for picker without input

### ISSUE THREAD

**Issue by Zanoro9000** [mui-org/material-ui-pickers#1855]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Id like to be able to use a popup picker without a related text field (and conversely the wrapper that surrounds the text field(s).

**Describe alternatives you've considered**
Right now I have no way of hiding/removing (or styling) the MuiPickersDateRangePickerInput-rangeInputsContainer if I want to use the popup purely on a button with no text field related. This is a problem in grid layouts if I want only to have the button.

**Additional context**
![image](https://user-images.githubusercontent.com/42248257/83659772-f9eb2680-a591-11ea-8902-b39434e10006.png)
This is an example of where it places the empty text field (by passing renderInput as <></> or another hidden element) and it messes with the layout. 

I know this would be difficult with positioning the popup relative to the parent but an option to hide the input or not use it would be great for enabling it to be able to be called only on button press

**Comment by oliviertassinari** [comment]
You should be able to implement this with the `Static` version of the components. Let us know if you face any issues with this approach.
