### ISSUE TITLE
[DateRangePicker] renderDay not being called

### ISSUE THREAD

**Issue by bneigher** [mui-org/material-ui-pickers#1856]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  v4.0.0-alpha7  |
| material-ui          |    v4.10.0     |
| TypeScript           |   No      |
| React                |    16.13.1     |
| Browser              |    Chrome     |
| Peer library         |    moment     | 

## Steps to reproduce

1. Create Wrapping Component:
```
import React, { useState } from 'react'
import classNames from 'classnames'
import { StaticDateRangePicker as DateRangePicker, Day } from '@material-ui/pickers'
import { makeStyles } from '@material-ui/core/styles'
import TextField from '@material-ui/core/TextField'
import moment from 'moment'

const useStyles = makeStyles((theme) => ({}))

const StaticDateRangePicker = (props) => {
	const classes = useStyles()

	return (
		<DateRangePicker
			autoOk
			orientation="portrait"
			variant="static"
			openTo="date"
			disableOpenPicker
			value={props.range}
			onChange={(newRange) => {
				props.onChangedDate(newRange[0], newRange[1] ? newRange[1] : newRange[0])
			}}
			showTodayButton
			disableFuture
			views={['date']}
			renderInput={(startProps, endProps) => (
				<>
					<TextField {...startProps} />
					<TextField {...endProps} />
				</>
			)}
			renderDay={(day, selectedDates, DayComponentProps) => console.log("I'm a sailor")}
		/>
	)
}

export { StaticDateRangePicker }
```

Calling Component

```
render() {
 <StaticDateRangePicker
     range={[moment().subtract(1, "day"), moment()]}
     onChangedDate={(dateA, dateB) => {
	this.onSetDateRange(dateA, dateB)
     }} />
}
```

## Expected behavior

Expect my dream career title to be logged to the console

## Actual behavior

Appears the custom renderDay prop is being ignored, or some condition is overruling the default renderDay method

Anyone else seeing this?

**Comment by oliviertassinari** [comment]
You import `StaticDateRangePicker`, it contains the content of the popup, it's isolated from the inputs.

**Comment by bneigher** [comment]
@oliviertassinari I'm sorry, I don't believe you answered the question...

There is a render method (renderDay) which allows us to make custom day components.  It is called correctly on the static day picker, it is not being called on the static day range picker where the documentation says it is a prop.

I'm not referring to the renderInput method.  Can you reopen or at least address this please?

**Comment by oliviertassinari** [comment]
Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/festive-golick-ej7q7?file=/src/App.jsx) _may_ be a good starting point. Thank you!

**Comment by bneigher** [comment]
@oliviertassinari 
Note the renderDay method not being called
https://codesandbox.io/s/reverent-faraday-fs49n?file=/src/App.jsx
