### ISSUE TITLE
Closing KeyboardDatePicker on Selection

### ISSUE THREAD

**Issue by BagchiMB** [mui-org/material-ui-pickers#1859]
I am trying to close the date picker once I have selected a date, I was not able to find any props for this, a prop CloseOnSelection would help people very much I guess, although I need urgent help rightnow for a live project, any help ??

**Comment by oliviertassinari** [comment]
Please submit support requests and questions to StackOverflow using the tag [material-ui](http://stackoverflow.com/tags/material-ui). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/callemall/material-ui/blob/master/CONTRIBUTING.md).

**Comment by oliviertassinari** [comment]
Also linking #1651 as related.

**Comment by BagchiMB** [comment]
hey @oliviertassinari thank you for your help, it helped although I on my first glance in the docs couldn't find the autoOk prop clear enough, therefore I thought this can be a feature, that is why I opened this issue.
Thanks for the help, should I make a PR for this in the docs to make this clear?
Thank you again so so much, this library is a gem.

**Comment by oliviertassinari** [comment]
Thanks for proposing your help but at this point, it's unclear which solution we will go for.
