### ISSUE TITLE
Unexpected token 'export' while testing

### ISSUE THREAD

**Issue by TomekStaszkiewicz** [mui-org/material-ui-pickers#1862]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    4.0.0-alpha.4     |
| material-ui          |    4.9.7     |
| TypeScript           |    3.8.3     |
| React                |     16.13.1    |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce
1. import DayJsAdapter from '@material-ui/pickers/adapter/dayjs' to a component
2. Create a test for component with that import(jest + enzyme)
3. When running test you get error Unexpected token 'export'

Import: 
`import DayJsAdapter from '@material-ui/pickers/adapter/dayjs';
`

Simple test:
```
import * as React from 'react';
import { mountWithTheme } from 'tests/helpers';
import { DatePicker } from '@material-ui/pickers';

import UserEventDatePicker from '../UserEventDatePicker';

describe('<UserEventDatePicker>', (): void => {
  const fn = jest.fn();
  it('renders DatePicker', (): void => {
    const wrapper = mountWithTheme(<UserEventDatePicker onEdit={fn} eventKey="abc" eventId="abc" />);
    expect(wrapper.find(DatePicker).length).toEqual(1);
  });
});
```

## Expected behavior
Test running as with other MUI components.
## Actual behavior
Test throws error:
![Screenshot from 2020-06-05 11-00-16](https://user-images.githubusercontent.com/46328998/83857850-dce25f00-a71b-11ea-9d3c-d1e6fde2f64d.png)

**Comment by dmtrKovalenko** [comment]
We don’t have alpha.46 version. 

Please update to the latest alpha — this issue should gone

**Comment by TomekStaszkiewicz** [comment]
> We don’t have alpha.46 version.
> 
> Please update to the latest alpha — this issue should gone

I made a typo, it is alpha.4

**Comment by dmtrKovalenko** [comment]
Yes, please try alpha.8
