### ISSUE TITLE
Edit Modal Form: KeyBoardDateTime Picker changes the date format of the prop value

### ISSUE THREAD

**Issue by devchia254** [mui-org/material-ui-pickers#1863]
Hello, I am new in React and its my first time asking a question so please bear with me.

I think I have an issue with the KeyBoardDateTime Picker. I developed a form using Formik to display the dateTime value on a table and added an Edit button on each row to prompt a Modal Form. But when I pass the prop value of dateTime to the `initialValues` of the Modal Form (to display the dateTime value of that respective row), it _**switches the date and month position**_. I am not able to figure out how to maintain the date format.

**In a nutshell**
Table dateTime value is in en-GB format but the Modal Form reads it in en-US format

Please help
![source](https://user-images.githubusercontent.com/44971063/83936344-703b9300-a7f5-11ea-92d6-c6f6b8d9c31d.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.10 |
| @material-ui/core | 4.10.1 |
| @material-ui/icons |     4.9.1 |
| @date-io/date-fns |     1.3.13 |
| material-table |     1.59.0 |
| formik |     2.1.4 |
| yup |     0.29.1  |
| shortid |        2.2.15  |
|         react|         16.12.0  |
|         react-dom|         16.12.0 |
|       react-scripts |        3.0.1 |

## Steps to reproduce
Check the Live example link below
- I have 3 table rows set to test the Edit button to see the prop value changes from table to Modal Form
- You can also submit dateTime value to table too

## Expected behavior

Expect the date to remain as en-GB format.
| Table  | Modal Form|
| -------------------- | ------- |
|  dd/MM/yyyy  |  dd/MM/yyyy |

## Actual behavior

Converts to en-US format
| Table  | Modal Form|
| -------------------- | ------- |
|  dd/MM/yyyy  |  MM/dd/yyyy |

_Note:_ Since it converts to US format, sometimes it will not display in the Modal Form because dateTime value is invalid e.g. en-GB: 24/09/2020 converts to en-US: 09/24/2020 (does not display)

## Live example

 Link: [Code Sandbox](https://codesandbox.io/s/keyboarddatepicker-bug-bmyxb)

**Comment by oliviertassinari** [comment]
We do no longer support @material-ui/pickers@3.x. Please provide a minimal reproduction test case with v4.0.0-alpha.8. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/festive-golick-ej7q7?file=/src/App.jsx) _may_ be a good starting point. Thank you!

**Comment by devchia254** [comment]
Hello Olivier, I will close this issue. I solved it using Moment library.
