### ISSUE TITLE
lack of `error` and `helperText` props makes this useless for forms

### ISSUE THREAD

**Issue by r3wt** [mui-org/material-ui-pickers#1871]
If user never touched the input, even if a field is `required`, no error message displays. this makes this library flawed. i can show error messages for other material-ui fields, but not date picker. you should provide `error` and `helperText` props so that we can override the displayed error message (or lack there of) as needed.

**Comment by oliviertassinari** [comment]
Check out the documentation of v4.0.0-alpha.8. You should find the required props to implement form validation. There is even an example in the docs.
