### ISSUE TITLE
material-ui/pickers@3.2.10 has unmet peer dependency date-io/core and prop-types@^15.6.0

### ISSUE THREAD

**Issue by GiovanniGiampaolo** [mui-org/material-ui-pickers#1872]
I Got this using `yarn `on my `react `project.

```
warning " > @material-ui/pickers@3.2.10" has unmet peer dependency "@date-io/core@^1.3.6".
warning " > @material-ui/pickers@3.2.10" has unmet peer dependency "prop-types@^15.6.0".
```
This is a simple warning that means that I should have into my

1. "@date-io/core@^1.3.6"
2. "prop-types@^15.6.0"

or is there some dependencies missing from material-ui/pickers?

**Comment by oliviertassinari** [comment]
Fixed in v4, we have made both dependencies, as they should be.

**Comment by GiovanniGiampaolo** [comment]
> Fixed in v4, we have made both dependencies, as they should be.

Thanks a lot
