### ISSUE TITLE
DateRange Error

### ISSUE THREAD

**Issue by asimhafeezz** [mui-org/material-ui-pickers#1875]
i just copied and pasted the code of basic DateRangePicker,
it shows this error
![image](https://user-images.githubusercontent.com/56485049/84215315-5349dd00-aadf-11ea-9768-a2000dcd738f.png)

it says, <DateRange> Type arguments can only be used in TypeScript files.
i didn't find the simple .js file code of it.
dependencies:
![image](https://user-images.githubusercontent.com/56485049/84215339-68bf0700-aadf-11ea-8f4f-5005b11f62ab.png)
 
am i doing something wrong here?

**Comment by dmtrKovalenko** [comment]
Yes, because the demo itself is written in typescript. You need to remove `<DateRange>` from the useState.

**Comment by asimhafeezz** [comment]
> > Yes, because the demo itself is written in typescript. You need to remove `<DateRange>` from the useState.
> 
> yes i did... and then it gives another error ...
> ![image](https://user-images.githubusercontent.com/56485049/84237537-f36d2980-ab12-11ea-86ac-b9b880771b84.png)

i am using the date-fns and code of basicDateRangePicker is in root.js
and i am exporting it in picker.js

![image](https://user-images.githubusercontent.com/56485049/84237965-bce3de80-ab13-11ea-980b-08ea45c74c61.png)

is this way is correct?

**Comment by asimhyff** [comment]
> > Yes, because the demo itself is written in typescript. You need to remove `<DateRange>` from the useState.
> 
> yes i did... and then it gives another error ...
> ![image](https://user-images.githubusercontent.com/56485049/84237537-f36d2980-ab12-11ea-86ac-b9b880771b84.png)

i am using the date-fns and code of basicDateRangePicker is in root.js
and i am exporting it in picker.js

![image](https://user-images.githubusercontent.com/56485049/84237965-bce3de80-ab13-11ea-980b-08ea45c74c61.png)

**Comment by oliviertassinari** [comment]
Make sure you are using the correct version (v4)
