### ISSUE TITLE
[KeyboardDatePicker ] TextField lose focus when open Popover

### ISSUE THREAD

**Issue by lamhungypl** [mui-org/material-ui-pickers#1877]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   ^3.2.10      |
| material-ui/core          |    ^4.10.1     |
| TypeScript           |      3.7.2   |
| React                |   ^16.12.0      |
| Browser              |     Chrome    |
| Peer library         |         | "@date-io/moment": "^1.3.13","moment": "^2.26.0" |

## Steps to reproduce

1.
```javascript
                    <KeyboardDatePicker
                    open = {open}
                    onFocus={handleFocus}
                    onBlur={handleBlur}
                    onAccept={handleAccept}
                    clearable
                    value={selectedDate}
                    placeholder="dd-mm-yyyy"
                    onChange={date => handleDateChange(date)}
                    format="DD-MM-YYYY"
                    keyboardIcon={<div   />}
                    variant="inline"
                    autoOk={true}
                    InputProps={{
                        disableUnderline: true,
                    }}
                    KeyboardButtonProps={{
                        disableFocusRipple: true,
                        disableRipple: true,
                        className: classes.button
                    }}
                    PopoverProps={{
                        anchorOrigin: {
                            vertical: "bottom",
                            horizontal: "right"
                        },
                        transformOrigin: {
                            vertical: "top",
                            horizontal: "center"
                        }
                    }}
                    disableToolbar
                    rightArrowIcon={<IoIosPlay />}
                    leftArrowIcon={<IoIosPlay style={{ transform: "rotate(180deg)" }} />}
                    {...rest}
                />
```
2. 
type in input

## Expected behavior

when i typing,  show the popover. 
when matched date / chose on picker, set value to input and hide poppover.

I don't want to use the adornment button, is there a workaround in ver3.

## Actual behavior

TextField lose focus when open Popover

## Live example

https://codesandbox.io/s/inputdatepicker-068qp
![Screen Shot 2020-06-10 at 11 27 26](https://user-images.githubusercontent.com/43105576/84227075-a63a8900-ab0d-11ea-90a7-31cc6dd71356.png)

**Comment by oliviertassinari** [comment]
We do no longer support v3. Please provide a minimal reproduction test case with v4. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/gifted-wilbur-g4bgc?file=/src/App.jsx) _may_ be a good starting point. Thank you!

**Comment by lamhungypl** [comment]
> We do no longer support v3.

It seems v4 has handle this use case [Migrate to Popper from Popover #1850](https://github.com/mui-org/material-ui-pickers/pull/1850)
I will be forced to migrate KeyboardDatepicker to the new version. Is there a guideline? It has been deprecated, and replaced by [DatePicker](https://next.material-ui-pickers.dev/api/DatePicker)?

**Comment by oliviertassinari** [comment]
KeyboardDatePicker is becoming DesktopDatePicker.

**Comment by dmtrKovalenko** [comment]
@lamhungypl  TextField will not keep the focus after open with new Popover version. It needs for a11y https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/datepicker-dialog.html

We planed some kind of another component that works similar to `DateRangePicker` now and will not lose focus and will not allow keyboard control in the calendar. Are you looking for such component?

**Comment by lamhungypl** [comment]
@dmtrKovalenko  yep, I have thought about interacting with the calendar by arrow keyboard, but the DateRangepicker's behavior is still fine. Waiting for new release.
 
I want to custom DatePicker something like: 
- Don't need the Adornment Icon, control hide/show calenda by focus and blur input.
- Validate input date value, error message when lose focus (blur) input or pick a date from calendar
- Value highlight in calendar can be set while typing (or when blur,doesn't matter, as long as correct input value can shown in calendar )
