### ISSUE TITLE
[KeyboardTimePicker][Question] Can I stop Keyboard Time Picker to stop converting my timezoned date time to local date time?

### ISSUE THREAD

**Issue by ghost** [mui-org/material-ui-pickers#1878]
I have date time object with time zone suppose 2020-06-09T05:25:28-7:00. When I pass it to value to Keyboard Time Picker it converts it into local time zone. Is there any way to avoid this happening?

**Comment by oliviertassinari** [comment]
Please provide a minimal reproduction test case with v4. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/gifted-wilbur-g4bgc?file=/src/App.jsx) _may_ be a good starting point. Thank you!

**Comment by ghost** [comment]
`<KeyboardTimePicker
        inputVariant="outlined"
        ampm
        value={"2020-06-08T22:25:28-07:00"}
        label="End Time"
      />`
On code sand box this does not reflect anything due to (may be) latest version of all the packages.
But I will try to reproduce for better clarification.

**Comment by oliviertassinari** [comment]
I'm sorry, we do no longer support v3. Closing.
