### ISSUE TITLE
Responsive DatePicker broken in v4-alpha.8

### ISSUE THREAD

**Issue by michael-land** [mui-org/material-ui-pickers#1882]
https://v4-0-0-alpha-8.material-ui-pickers.dev/demo/datepicker#responsiveness

![image](https://user-images.githubusercontent.com/33362998/84423596-4ebb1c80-abe4-11ea-8356-04166c040d0d.png)

**Comment by oliviertassinari** [comment]
What do you mean by it's broken? Do you have a reproduction?

**Comment by michael-land** [comment]
Should it render mobile date picker on small screen.


https://v4-0-0-alpha-5.material-ui-pickers.dev/demo/datepicker#responsiveness

===

![image](https://user-images.githubusercontent.com/33362998/84430496-6350e200-abef-11ea-803c-9f2d2053d727.png)



https://v4-0-0-alpha-8.material-ui-pickers.dev/demo/datepicker#responsiveness

![image](https://user-images.githubusercontent.com/33362998/84430722-c04c9800-abef-11ea-839d-3273fa6b49fc.png)

**Comment by oliviertassinari** [comment]
@xiaoyu-tamu The description of the section is wrong. We forgot to update it. Do you want to work on it? :)

> Date/Time pickers experience is extremely different on mobile and desktop. Here is how components will look on different devices. The default Datepicker component is responsive, which means that Mobile or Desktop mode will be rendered according to device viewport.

The desktop vs mobile split is determined by the pointer support of the device. If the pointer is touch, it uses the Mobile version. If the pointer is fine (mouse), it uses the Desktop version.
