### ISSUE TITLE
inputFormat issue DateRangePicker

### ISSUE THREAD

**Issue by asimhafeezz** [mui-org/material-ui-pickers#1883]
First ,i am trying to get inputFormat="dd/mm" but as be default it's mm/dd/yyyy ... whenever i try to write "mm" in the formate it always gives 00 value in DateRangePicker as month and in TimePicker as minutes. you can see in the CSD.

second i am trying to hide icon and then open the clock just on clicking on TextField like the DateRangePicker, i dont need to click on the icon specifically... which i tried to do with disableOpenPicker prop but it totally disables the opening.
i looked at the DateRangePicker Api but didn't get one.
which props should i use to get it?

 CSD is here: https://codesandbox.io/s/infallible-moore-j4wbt?file=/src/picker.js

**Comment by asimhyff** [comment]
is someone here to help?

**Comment by oliviertassinari** [comment]
Please submit support requests and questions to StackOverflow using the tag [material-ui](http://stackoverflow.com/tags/material-ui). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/callemall/material-ui/blob/master/CONTRIBUTING.md).
