### ISSUE TITLE
date-fns (DateFnsUtils ) type error on 4.0.0-alpha.8

### ISSUE THREAD

**Issue by omasback** [mui-org/material-ui-pickers#1886]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    4.0.0-alpha.8     |
| material-ui          |    4.10.2     |
| TypeScript           |    3.8.3     |
| React                |    16.13.1     |
| Browser              |    Chrome 83.0.4103.97     |
| Peer library         |    date-fns 2.14.0     |  |

## Steps to reproduce

1. Try to use `<LocalizationProvider>` with `DateFnsUtils` from `@material-ui/pickers/adapter/date-fns`

## Expected behavior

LocalizationProvider dateAdapter prop accepts DateFnsUtils

## Actual behavior

LocalizationProvider dateAdapter does not accept DateFnsUtils

```
Type 'typeof DateFnsUtils' is not assignable to type 'new (...args: any) => MuiPickersAdapter'.
  Type 'DateFnsUtils' is missing the following properties from type 'IUtils<MaterialUiPickersDate>': yearFormat, yearMonthFormat, dateTime12hFormat, dateTime24hFormat, and 12 more.  TS2322

    36 |           }}
    37 |         >
  > 38 |           <LocalizationProvider dateAdapter={DateFnsUtils}>
       |                                 ^
    39 |             <CssBaseline />
    40 |             <ThemeProvider theme={theme}>{props.children}</ThemeProvider>
    41 |           </LocalizationProvider>
```

**Comment by dmtrKovalenko** [comment]
It looks like you have outdated date-io adapter version

**Comment by omasback** [comment]
@dmtrKovalenko I thought the adapter came bundled in with @material-ui/pickers now. Everything was working fine in 4.0.0-alpha.7

**Comment by oliviertassinari** [comment]
@omasback Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/gifted-wilbur-g4bgc?file=/src/App.jsx) _may_ be a good starting point. Thank you!

**Comment by omasback** [comment]
Having some difficulty making a minimal repro, but I think this issue is stemming from my use of `material-table`, which for some reason has a dependency on `@material-ui/pickers` v3

https://codesandbox.io/s/kind-dan-rnu7q?file=/src/App.tsx. 

I'm not sure what the solution is I may just revert to v3 or use another table component for the time being until material-table is updated with v4 pickers dependency.

**Comment by oliviertassinari** [comment]
@omasback Thanks for the update, it should be fine to have multiple version of the picker installed. Make sure your bundler is able to correctly isolate the version used.
