### ISSUE TITLE
Incompatible with date-fns 2.6.2

### ISSUE THREAD

**Issue by nickpalmer** [mui-org/material-ui-pickers#1887]
Because package.json doesn't specify the date-fns versions as a peerDependency yarn is happy to install 2.6.2 if you tell it to install @date-io/date-fns which then crashes this package.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 3.2.10 |
| material-ui          | 4.10.1 |
| React                | 16.3.1 |
| Browser              |  Chrome |
| Peer library         |  @date-io/date-fns 2.6.2 |

## Steps to reproduce

Create a <DatePicker /> with a Provider using date-fns 2.6.2.

## Expected behavior

Should render a date picker.

## Actual behavior

crashes with an error:

```
RangeError
Format string contains an unescaped latin alphabet character `n`
```

However other configurations of DatePicker will crash in other places because it is expecting functions in date-fns that don't exist.

## Live example

https://codesandbox.io/s/intelligent-snow-r2dpo

**Comment by oliviertassinari** [comment]
We have solved the issue in the v4.0.0-alpha version: https://next.material-ui-pickers.dev.
