### ISSUE TITLE
Migration from v1 to v2

### ISSUE THREAD

**Issue by ahmad-reza619** [mui-org/material-ui-pickers#1894]
i'm sorry for not using issue template, because i'm not sure if this is bug or feature req 

I know i'm using obsolete version, but i want to upgrade this libs, since it looks ugly when i'm upgrading material ui to latest version and this libs use material ui right?.

so therefore, i have looked in documentation for v2 but there is no migration docs from v1. it would be very great if someone made a migration documentation for v1 to v2 😄

**Comment by oliviertassinari** [comment]
@ahmad-reza619 I'm sorry, we do no longer support older version, you could start directly from v4.0.0-alpha.8 https://next.material-ui-pickers.dev/.
