### ISSUE TITLE
MuiPickersUtilsProvider with Other Context Providers

### ISSUE THREAD

**Issue by neilchaudhuri** [mui-org/material-ui-pickers#1900]
I am currently working on combining the `DatePicker` with other Chakra UI components into a single library, and I have found that Chakra's `ThemeProvider` does not play nicely with `MuiPickersUtilsProvider`. When the two coexist in a Storybook, they kill the browser. `ThemeProvider` needs to be all encompassing, and Storybook has revealed `MuiPickersUtilsProvider` does not like being a child of `ThemeProvider`.

Are there workarounds? Like another way to supply the date functionality? Or is it simply that MUI's `DatePicker` isn't an option for me?

**Comment by oliviertassinari** [comment]
@neilchaudhuri Do you have a reproduction? It should be working fine.

**Comment by neilchaudhuri** [comment]
Thanks for the quick response. I will need some time to create a reproduction since I am not allowed to share the source, but it shouldn't take long. Basically an app that looks like 

```
<ThemeProvider theme="theme.js">
   <MuiPickersUtilsProvider utils={...}><DatePicker...></DatePicker></MuiPickersUtilsProvider>
</ThemeProvider>
```

...in Storybook. And who knows? It could be a weird issue in Storybook.

Anyway, please feel free to close this issue for now, and I can reopen once I make a reproduction and figure out I didn't do anything silly, which is also quite possible.

**Comment by neilchaudhuri** [comment]
I played around a bit and things seem to be peacefully coexisting. Thanks.
