### ISSUE TITLE
Can't resolve '@material-ui/core/Unstable_TrapFocus'

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1905]
I'm getting `Can't resolve '@material-ui/core/Unstable_TrapFocus'` after updating to alpha 8. Didn't happen in alpha 7. Some missing peer dep?

Relevant dependencies in my package.json:
```
"dependencies": {
    "@apollo/client": "^3.0.0-rc.2",
    "@material-ui/core": "^4.9.14",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.53",
    "@material-ui/pickers": "^4.0.0-alpha.7",
    "gatsby": "^2.23.1",
    "gatsby-theme-material-ui": "^1.0.9",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "styled-components": "^5.1.0"
  },
```

**Comment by oliviertassinari** [comment]
You need both dependencies (core and pickers) to the install the latest version.

**Comment by Jdban** [comment]
For anyone else who runs into this, here are the exact versions you need to fix the issue:

```
    "@material-ui/core": "4.10.2",
    "@material-ui/pickers": "4.0.0-alpha.8"
```

**Comment by dandv** [comment]
@Jdban: saw this again when updating to alpha10... just `npm update @materia-ui/core` every time you update the pickers, I guess.
