### ISSUE TITLE
Make the "OK" button default in the edit box for MobileDateTimePicker

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1906]
**Is your feature request related to a problem? Please describe.**
Not a very often used feature, but you can click the pencil icon to manually enter the time. It would be nice to submit that form on Enter.

![image](https://user-images.githubusercontent.com/33569/84950879-6727ad00-b0a4-11ea-8ce3-f8cc1e88e258.png)

**Comment by oliviertassinari** [comment]
By <kbd>Enter</kbd>, do you mean the form validation feature of mobile virtual keyboards? (This dialog view is for mobile only).

**Comment by dandv** [comment]
I'm using it on the desktop because [the page says](https://dev.material-ui-pickers.dev/demo/datetime-picker) "DateTimePicker is a complex control, so you may consider using `MobileDateTimePicker` for desktop users as well.", but the VK form submission feature would be good too.

**Comment by oliviertassinari** [comment]
@dandv We have removed this guideline in #1884, prefer the desktop version, if you have only desktop use cases, or best case, use the responsive version.
