### ISSUE TITLE
Remove `selectedDate` from the `renderDay` 

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1911]
We probably don't need this argument at all, because we always has access to the currently selected using their own state. 

So proposed change for the API
```tsx
<DatePicker
  renderDay={(date, DayProps)  => <Day {...DayProps} />}
/>
```

> You are right, we changed calendar selected days to be an array when implementing date range picker. Here will be enough to only rename argument (because we have selected date available as state variable). But this makes me think that we don't need this argument at all

_Originally posted by @dmtrKovalenko in https://github.com/mui-org/material-ui-pickers/pull/1904_

**Comment by oliviertassinari** [comment]
What are the pros and cons of both options? In https://github.com/mui-org/material-ui-pickers/pull/1907#discussion_r441875791, it seemed that consistency would help reduce bugs. I think that we should stick to the convention that render props and component props could be switched, with a single param, hence:

```jsx
<DatePicker renderDay={(DayProps) => <Day {...DayProps} />} />
```

**Comment by oliviertassinari** [comment]
Let's stick to render "prop API <=> Component API": one argument with all the relevant options.
