### ISSUE TITLE
Date picker's views={['date']} not working as expected

### ISSUE THREAD

**Issue by TomekStaszkiewicz** [mui-org/material-ui-pickers#1912]
First of all, thank you guys for the project! It is really useful! <3
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   4.0.0-alpha.8      |
| material-ui          |         |
| TypeScript           |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. Create `<DatePicker />`
2. Pass prop `view={['month', 'date']}`

## Expected behavior

If I pass `view={['year', 'month']}` the pickers allows user to pick only year and month, as expected. I expect that when I pass `view={['month', 'date']}` user can only pick month and day. 

## Actual behavior
Passing `view={['month', 'date']}` does nothing. It is possible that I am missing something, but not sure what. Also why the possible props to view is 'date' instead of 'day'? Is it supposed to do something else?

I made this code sandbox to show the issue: 
https://codesandbox.io/s/nostalgic-vaughan-988fw?file=/src/App.js

**Comment by dmtrKovalenko** [comment]
It looks like your sandbox is empty. Try our [codesandbox template](https://codesandbox.io/s/material-ui-pickers-v4-jfm6g) to fill the issue. 

> in the examples looks like you have a typo in prop name `view={['month']}` => `views={['month']}`

**Comment by TomekStaszkiewicz** [comment]
> It looks like your sandbox is empty. Try our [codesandbox template](https://codesandbox.io/s/material-ui-pickers-v4-jfm6g) to fill the issue.
> 
> > in the examples looks like you have a typo in prop name `view={['month']}` => `views={['month']}`

Oh, sorry. I hope this time my changes are saved: https://codesandbox.io/s/modern-night-qf5ww?file=/src/App.jsx

as you can see, when `views={['year', 'month']}` you can only select year and month, same for only `year`. What about `month, date`?

**Comment by oliviertassinari** [comment]
It's worth mentioning that #1903 is relatively close to this problem.
