### ISSUE TITLE
Feat: Improve hover rendering

### ISSUE THREAD

**Issue by bertrandp** [mui-org/material-ui-pickers#1913]
## My use case

Here is the current [week picker](https://material-ui-pickers.dev/demo/datepicker#customization) from the demo page
![weekpick](https://user-images.githubusercontent.com/12247744/85137395-6ed08880-b241-11ea-9aa2-eb02212cb015.png)

It would be great to be able to hover the whole week instead of just one day.

Here is an exemple of [airbnb picker](http://airbnb.io/react-dates/?path=/story/drp-calendar-props--with-7-days-range-selection)
![7 day hover](https://user-images.githubusercontent.com/12247744/85136403-ddace200-b23f-11ea-90e7-d5465ea3cc65.png)

**Comment by dmtrKovalenko** [comment]
We are not working on week picker as separate component (at least for now) it is mostly a demo of how to customize day rendering. 

Make sure that in v4 in the new `<DateRangePicker />` we already implemented range preview on hover
