### ISSUE TITLE
Unusual DatePicker Appearance

### ISSUE THREAD

**Issue by iqbalsetiawan** [mui-org/material-ui-pickers#1920]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    ^3.2.10     |
| material-ui          |    4.10.2     |
| TypeScript           |         |
| React                |    ^16.13.1     |
| Browser              |    Chrome Version 83.0.4103.106     |
| Peer library         |    date-fns 2.0.0-alpha.7     |  |

## Steps to reproduce

1. I'm updating my material ui version from 1.2.0 to 4.10.2
2. Open DatePicker

## Expected behavior

DatePicker would be like a normal appearance

## Actual behavior

DatePicker showing an unusual appearance.

## Live example

![Screen Shot 2020-06-22 at 12 06 17](https://user-images.githubusercontent.com/52906490/85250580-2d2e2080-b481-11ea-849c-66ede307685c.png)

**Comment by dmtrKovalenko** [comment]
You are using date-fns v1, but we require v2
