### ISSUE TITLE
Input keyboard support

### ISSUE THREAD

**Issue by sandeepkumar-vedam-by** [mui-org/material-ui-pickers#1921]
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.9      |
| material-ui          |         |
| TypeScript           |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. I imported KeyboardDateTimePicker and i need to render native input with material-ui popover
2. [Native Picker](https://material-ui.com/components/pickers/#date-amp-time-pickers) Here we have ability to change date and time with up and down keyboard arrows. 
3. How to achieve native input behavior in material-ui pickers?

**Comment by sandeepkumar-vedam-by** [comment]
@oliviertassinari  Thanks for the great plugin. 

Can we achieve above usage from material-ui-pickers?

**Comment by oliviertassinari** [comment]
@sandeepkumar-vedam-by Are you referring to the ability of the native input to handle <kbd>Up</kbd> and the other arrow keys to change the date without opening the popup?

<img width="227" alt="Capture d’écran 2020-06-22 à 12 00 29" src="https://user-images.githubusercontent.com/3165635/85275000-01f70180-b480-11ea-9ad9-948f5fae86a9.png">

**Comment by sandeepkumar-vedam-by** [comment]
Yes exactly but when we click on date icon it should open material-ui-picker popover @oliviertassinari

**Comment by oliviertassinari** [comment]
@sandeepkumar-vedam-by Interesting

**Comment by sandeepkumar-vedam-by** [comment]
> @sandeepkumar-vedam-by Interesting

So, how can we achieve native input as per above image with out opening ui-pickers?

**Comment by sandeepkumar-vedam-by** [comment]
@oliviertassinari Hi

 I have created code sandbox and here is the [demo](https://codesandbox.io/s/material-ui-date-picker-u42vl?file=/demo.js). However, i am seeing below problems

1. Date picker not aligning with textfield in `inline` variant
2. Not able to format date as DD/MM/YYYY as you mentioned in above image

Can you please have a look at demo and help me. Thank You :)

FYI.. @dmtrKovalenko @gabriel-kohen-by @pankaj-goyal-by

**Comment by sandeepkumar-vedam-by** [comment]
@oliviertassinari  Did you get chance to look at codesandbox demo above?
