### ISSUE TITLE
Support for nested imports?

### ISSUE THREAD

**Issue by aamirafridi** [mui-org/material-ui-pickers#1934]
Using the Import like this for treeshaking

```
import {
  DesktopDateRangePicker,
  MobileDateRangePicker,
} from "@material-ui/pickers/DateRangePicker/DateRangePicker";
```

No TS error but JS errored `Cannot find module '@material-ui/pickers/DateRangePicker/DateRangePicker'`

**Comment by aamirafridi** [comment]
I know that this works
```
import {
  DesktopDateRangePicker,
  MobileDateRangePicker,
} from "@material-ui/pickers";
```

**Comment by oliviertassinari** [comment]
@aamirafridi We don't support nested imports for the pickers repository. We might with https://github.com/mui-org/material-ui/issues/19706. I think that the correct solution would be:

```jsx
import DateRangePicker, {
  DesktopDateRangePicker,
  MobileDateRangePicker,
} from "@material-ui/pickers/DateRangePicker";
```

The incentive so far for supporting it is that tree-shaking doesn't work in development, which can harm the DX.

**Comment by aamirafridi** [comment]
Ok thanks :)

**Comment by oliviertassinari** [comment]
Keeping it open to signal that it's not fixed and incentive for more comments.

**Comment by oliviertassinari** [comment]
Done in https://next.material-ui.com/components/pickers/
