### ISSUE TITLE
Lack of AM/PM indicator for 24-hour DateTime picker

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1935]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

While using the [24-hour clock DateTime picker demo](https://dev.material-ui-pickers.dev/demo/datetime-picker#responsiveness) and I found it slightly confusing that the AM/PM indicator was not shown in the calendar view, and in the edit :pencil2: view next to the time.

## Examples 🌈

![MUI datetime picker no AP PM](https://user-images.githubusercontent.com/33569/85915173-19284d00-b7fa-11ea-9741-e0c0347c5e10.gif)

## Motivation 🔦

In the screencast above, you can see that the user doesn't readily know which time of the day they're selecting - 11:00 AM, or 11:00PM. The "PM" is only shown in the edit box, but not at all in the calendar view.

**Comment by dmtrKovalenko** [comment]
![image](https://user-images.githubusercontent.com/16926049/85918866-259abd00-b86f-11ea-955b-d09913215cb7.png)

It displays inside the ClockView. It was done to preserve more space for the calendar content. But probably you are right, we need better toolbar elements positioning

**Comment by oliviertassinari** [comment]
+1 for displaying the PM/AM value in the header on mobile.

**Comment by dandv** [comment]
So far, about 2 thirds of the people I've had use that control, missed seeing the AM/PM, which resulted in it defaulting to whatever half of the day it was when they used it.

**Comment by oliviertassinari** [comment]
@dandv I'm curious, is your product a mobile app?

**Comment by dandv** [comment]
@oliviertassinari: it's a desktop app. The audience is exclusively from the US, maybe that's why?

**Comment by oliviertassinari** [comment]
@dandv Why are you using the mobile date time picker?

**Comment by dandv** [comment]
@oliviertassinari: for the same reason as in [this case](https://github.com/mui-org/material-ui-pickers/issues/1906#issuecomment-645709059). Didn't see an argument against that, so I continued using it.
