### ISSUE TITLE
Not working with MomentUtils

### ISSUE THREAD

**Issue by borm** [mui-org/material-ui-pickers#1944]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
```
TypeError
utils.getYearText is not a function
```

## Steps to Reproduce 🕹
https://codesandbox.io/s/gallant-leftpad-o5990?file=/src/App.jsx

**Comment by borm** [comment]
For now, downgrade to `"@date-io/moment": "^1.3.13"`
https://github.com/mui-org/material-ui-pickers/issues/1440

**Comment by oliviertassinari** [comment]
Duplicate of #1440
