### ISSUE TITLE
Multi-formats parsing support

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1946]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Examples 🌈
Allow parsing user input in several formats. Like `01/01/2020` and `Wed, 1st June` and `June 1`. 

## Proposed API
```jsx
<DatePicker 
  parseFormats={['P', 'DD, do MMM', MMM d']} 
/> 
```

## Motivation 🔦

A lot of datepickers allow to parse inputs in several formats, e.g. https://www.google.com/flights. Also this feature will not require any additional bundlesize thanks to date-io

**Comment by avinashkaman** [comment]
This is not proper solution. Its not working.
