### ISSUE TITLE
utils.getMonth fails when initial date is null (v4.0.0-alpha.8)

### ISSUE THREAD

**Issue by kikoanis** [mui-org/material-ui-pickers#1965]
`utils.getMonth` fails when initial date is null
I tracked it down to this line
https://github.com/mui-org/material-ui-pickers/blob/853e5d2653f925f51278784618beb2e86f64ef0f/lib/src/views/Calendar/MonthSelection.tsx#L42

- [X] The issue is present in the latest alpha release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
It fails on clicking on calendar month/year (as shown in attached photo)

## Expected Behavior 🤔
It should not fail and it should guard against null value

## Steps to Reproduce 🕹
 Steps:

1. Navigate to: https://codesandbox.io/s/material-ui-pickers-usage-demo-8478h?file=/src/App.jsx
2. Click on calendar icon, click on July 2020 list(?)
3. it fails miserably 🤕

![image](https://user-images.githubusercontent.com/615849/86668350-c8f67b00-bfaf-11ea-8688-c331029f11fa.png)

![image](https://user-images.githubusercontent.com/615849/86668715-268ac780-bfb0-11ea-95c2-78b9f24d29dd.png)

## Context 🔦
I am trying to initialize a date picker field from null, no known initial value.

## Your Environment 🌎
Node.JS, OS and Windows

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | 5.0.0-alpha.2 and latest 4.11.0  |
| @material-ui/pickers | v4.0.0-alpha.8  |
| React       |     16.13.0    |
| Browser     |   Chrome, Edge and Firefox      |
| TypeScript  |   3.9.6      |

**Comment by dmtrKovalenko** [comment]
Fixed by #2045

**Comment by Poky85** [comment]
@dmtrKovalenko Could you please publish last alpha on npm? – `v4.0.0-alpha.12`

**Comment by dmtrKovalenko** [comment]
You can find it inside @material-ui/lab@next

**Comment by Poky85** [comment]
@dmtrKovalenko Thank you, I know that development continues in `@material-ui/lab@next` but it has dependency on `@material-ui/core@next`.

I have app using `v4.0.0-alpha.11` with MUI 4 and only need to update to`v4.0.0-alpha.12` to fix the `utils.getMonth()` bug.
