### ISSUE TITLE
calendars prop in DatePicker and StaticDatePicker

### ISSUE THREAD

**Issue by RZsam** [mui-org/material-ui-pickers#1986]
there is `calendars` prop in `StaticDateRangePicker`. I didn't find a way to implement two calendars next to each other I think it's useful props in `DatePicker` too.

**Comment by dmtrKovalenko** [comment]
What the use case of 2 calendars for `DatePicker`?

**Comment by RZsam** [comment]
I used `StaticRangeDatePicker` and now I'm using `StaticDatePicker`.There are prices in each day of both Calendars and it would be easier for users to choose which day to reserve if `StaticDatePicker` Showed current and next month like `StaticRangeDatePicker`

**Comment by oliviertassinari** [comment]
Sorry, this doesn't fully answer the question. What's your use case for a date picker displaying two months at the same time? Are you saying you have two date pickers to pick a range? 🤔

**Comment by RZsam** [comment]
Sorry for bad description, not a range picker.I'm using StaticDatePicker with disablePast prop.Calendar is used to show price in each day and two calendars like rangeDatePicker will help UX
