### ISSUE TITLE
Calendar popup not getting closed when used in a Dialog

### ISSUE THREAD

**Issue by kvskranthikumar** [mui-org/material-ui-pickers#1989]
I am using the latest version - v4.0.0-alpha.9
When we launch the Calender Popup in a dialog, it doesn't close when we click outside the calendar.

Here is the code sandbox to recreate this scenario -

https://codesandbox.io/s/hungry-euclid-mgod9?file=/src/App.jsx

![image](https://user-images.githubusercontent.com/12032164/87324507-ccf54080-c54d-11ea-9615-addcd76a633c.png)

![image](https://user-images.githubusercontent.com/12032164/87324540-db435c80-c54d-11ea-9935-db2b7d12e989.png)

Expected behavior -
The calendar popup should get closed when clicked outside.

**Comment by oliviertassinari** [comment]
@kvskranthikumar Thanks for the report, it sounds like https://github.com/mui-org/material-ui-pickers/issues/1852#issuecomment-657519201.

**Comment by kvskranthikumar** [comment]
Thanks for responding quickly.

I am getting recursive errors as well when using inside dialog -

![image](https://user-images.githubusercontent.com/12032164/87326629-9cfb6c80-c550-11ea-9a2c-c3427c9b5b25.png)

Any idea what could be wrong?

**Comment by oliviertassinari** [comment]
For that, you will need to upgrade to core@v5.0.0-alpha.2 or disable the enforce focus logic.

**Comment by kvskranthikumar** [comment]
Please help me, how to disable the enforce focus logic?

**Comment by BowlingX** [comment]
@kvskranthikumar this would be: (see https://material-ui.com/api/modal/#props)

```tsx
<Dialog disableEnforceFocus />
```

**Comment by kvskranthikumar** [comment]
Thanks, @BowlingX that worked.

**Comment by vicasas** [comment]
> @kvskranthikumar this would be: (see https://material-ui.com/api/modal/#props)
> 
> ```tsx
> <Dialog disableEnforceFocus />
> ```

The errors disappear in the console, but not the DateTimePicker component when it is mounted in a Dialog, it still does not work correctly

**Comment by sachin-agarwal-by** [comment]
@BowlingX @oliviertassinari   I have same issue which is not getting address by adding disableEnforceFocus . Please let m know way to fix.
