### ISSUE TITLE
[TypeScript] Usage with Material Table leads to dateAdapter error: Type 'typeof ...' is not assignable to type 'new (...args: any) => MuiPickersAdapter<unknown>

### ISSUE THREAD

**Issue by OnkelTem** [mui-org/material-ui-pickers#1995]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using together with `material-table` (1.6.x) TS fails with an error on the `dateAdapter` property:

```
TS2322: Type 'typeof MomentUtils' is not assignable to type 'new (...args: any) => MuiPickersAdapter<unknown>'.
   Type 'MomentUtils' is missing the following properties from type 'MuiPickersAdapter<unknown>': yearFormat, yearMonthFormat, dateTime12hFormat, dateTime24hFormat, and 12 more.

  LocalizationProvider.d.ts(6, 5): The expected type comes from property 'dateAdapter' which is declared here on type 'IntrinsicAttributes & LocalizationProviderProps & { children?: ReactNode; }'
```

Sandbox: https://codesandbox.io/s/pickers-next-material-table-problem-4wfud?file=/src/App.tsx

So a mere adding `material-table` into dependencies breaks TS transpilation.

I hope this is not duplicate. There were some issues reporting problems with `material-table`, but I didn't find any reporting particularly this problem.

`material-table` depends on v.3, but it [was noted](https://github.com/mui-org/material-ui-pickers/issues/1886#issuecomment-643666795) that it shouldn't really break things. 

I reported this problem [a day earlier](https://github.com/mui-org/material-ui-pickers/issues/1990#issuecomment-658118246), but I couldn't reproduce it back then.

## Expected Behavior 🤔

No TS Error

## Steps to Reproduce 🕹

1. Install v.4
2. Install material-table
3. `LocalizationProvider`'s `dateAdapter` property raises an error.

Sandbox: https://codesandbox.io/s/pickers-next-material-table-problem-4wfud?file=/src/App.tsx

## Context 🔦

I try to use it along with material-table.

## Your Environment 🌎

see the sandbox.

**Comment by dmtrKovalenko** [comment]
It is a problem of material-table side. They should upgrade and support generic type of picker component that was introduced in the latest `alpha.9` release.

**Comment by OnkelTem** [comment]
@dmtrKovalenko I agree that they should upgrade to v4, but why do you think the usage of v.3 by `material-table` makes TS not compile?

**Comment by OnkelTem** [comment]
Ok, fine. 

Please let me share my impressions. The last three days was a real nightmare for me :)

First I was trying to get v.3 working and after a few hours I came up with that ticket where I'm pointing out that doc examples basically don't work (not a big deal, I know!)

Then I was told to try v.4 and I did. 

I spent hours and hours trying to nail down this issue with not-compiling TS. Created several projects from scratch, testing and comparing many version of react/typescript/libraries. I had to dig through the whole project, disabling module by module, every time recompiling everything, until I've finally narrowed it down enough to find the culprit and it was `material-table`. Good job! Or... is it?

I created a sandbox and then this ticket... to get what? To get it closed right away because: it's not our problem so let _them_ rewrite the related stuff to fit our new _not yet released version_ ;-)

I could have been comfortable with that even now when I have a couple of @ts-ignores in my code just to get it built. But know what? I don't have it working yet! :) Because something else is broken now. The `inputFormat`. It doesn't want to consume a regular format string like "YYYY-MM-DD HH:mm". Meh... I don't have any idea how to get it fixed. And I cannot create a bug report because it's probably not a bug really, but _yet another conflict with something_.

I'm afraid now of making any prognosis on how many hours one needs to get a picker working. A drop-in component they said? :) Oh yeah! :)

But nevermind, it's not a complain, folks. It's a free software after all. And that it was a little emotional — sorry for that, but hell, I spent three days just to get things working and yet I don't have a functioning form! :) 

But I have one concern and one proposition. 

**Concern:** You accept only bug reports here. Like you provided some solid documentation, working examples and there's a big community of people eagerly willing to help seekers. From what I can observe it's not the case yet. Or rather - it's more true for JS but things are a little more complicated with TS.
What does one do when facing so many problems? Creates a support request on StackOverflow? What are chances they're gonna receive a helpful reply before they have to give up due to running out of time? 

**Proposition:** Loosen a little the rules of creating tickets here until things get more stable and examples/docs answer the most of questions. In other words - let people create support tickets here.

I would like also to thank @dmtrKovalenko and @oliviertassinari who provided quick replies in my tickets, and encourage all the developers of this nice lib in the endeavour of releasing the next version. 

Thanks for reading, sorry for being wordy.

**Comment by dmtrKovalenko** [comment]
Sorry, do you have an error with v3? I think that `MuiPickersAdapter` word appeared only for v4.

**Comment by OnkelTem** [comment]
@dmtrKovalenko Not sure. I rewrited my component to use v4 yesteday and haven't tried to rollback to v.3 since then. Maybe it would be really easier. Let me try it now.

**Comment by oliviertassinari** [comment]
> let people create support tickets here

@OnkelTem It's already the case. Now, because the code is provided for free, we only accept issue contributions that are a net positive for the project. For instance, we close anything that has a too high opportunity cost.

**Comment by OnkelTem** [comment]
@oliviertassinari Glad to hear that.

@dmtrKovalenko

Ok, I've restored the version 3 and its surroundings locally.

But now we return to the case of https://github.com/mui-org/material-ui-pickers/issues/1990
Maybe I missed something but it seems to me that you were speaking about v.4, not v.3.

Basically if the date is defined as:

```ts
const [selectedDate, handleDateChange] = useState<Date | null>(new Date());
```
it triggers an error on `onChange={handleDateChange}`. The error is not fatal however.

Here is a copy of the sandbox from 1990: https://codesandbox.io/s/autumn-pond-6n2p7?file=/src/App.tsx

Note that despite the format is set to "yyyy/MM/DD HH:mm" the time part is "00:00".

**Comment by OnkelTem** [comment]
Any news?

The format is set to "yyyy/MM/DD HH:mm" but the time part is "00:00".
