### ISSUE TITLE
Pass `disabled` through to renderDay function

### ISSUE THREAD

**Issue by haxxxton** [mui-org/material-ui-pickers#1996]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Add a 5th argument to the `renderDay` function, passing the calculated `disabled` value.

## Motivation 🔦

Currently when you supply a helper prop like `disablePast` or `disableFuture` to `DatePicker` that is using a `renderDay` function you have to re-calculate if the day that is being custom rendered is disabled as a result of these props. It would be great to be able to leverage the logic that is already being performed by MUIPickers, by passing `disabled` into `renderDay` as an argument.

**Comment by haxxxton** [comment]
Ah, looks like you can extract it from the 4th argument `dayComponent` using `dayComponent.props.disabled`. (Also appears to have `current`, `selected` and `hidden` available). Is this mentioned somewhere in the Docs? perhaps this ticket could transform into a Docs request :)

**Comment by dmtrKovalenko** [comment]
It is mentioned in the docs by reference to the https://next.material-ui-pickers.dev/api/Day. 

@oliviertassinari that's why I am saying that adding only props will confuse developers and force looking through documentation instead of just write the code.

**Comment by oliviertassinari** [comment]
A couple of observations:

- Assuming @haxxxton uses v3 (which is very likely as suggest a 5th argument).
When landing on https://material-ui-pickers.dev/api/DatePicker, the cell contains:

<img width="1066" alt="Capture d’écran 2020-07-15 à 17 49 08" src="https://user-images.githubusercontent.com/3165635/87566614-8e819200-c6c3-11ea-94f0-4c56169109a3.png">

We don't have access to the props `PickersDay` accepts. 

- Now, let's assume @haxxxton uses v4.
When loading on https://next.material-ui-pickers.dev/api/DatePicker, the cell contains:

<img width="1080" alt="Capture d’écran 2020-07-15 à 17 51 08" src="https://user-images.githubusercontent.com/3165635/87566894-e5876700-c6c3-11ea-80f8-4eaded4c3944.png">

After scrolling (scrolling is probably an issue on its own), there is a link but it's dead. We don't have direct access to the props `PickersDay` accepts.

- We have a hard limit on the arguments of any of the public Material-UI functions to 4.

--- 

> that's why I am saying that adding only props will confuse developers and force looking through documentation instead of just write the code.

@dmtrKovalenko How would you solve this problem (#1996)?

**Comment by dmtrKovalenko** [comment]
Yeah my bad. If it was related to v3 -- my theory is still theory. We could close the issue in favour of v4.

**Comment by haxxxton** [comment]
for clarity (apologies for not adding it to my opening post). The version im using is `3.2.10`
