### ISSUE TITLE
Inputadornment for non keyboard types

### ISSUE THREAD

**Issue by toonvd** [mui-org/material-ui-pickers#1999]
For inline labeling, it would come in handy that a start adornment can be added on keyboard types.

Use case: date range with from-to with height restrictions, having the null value does not work when there is a default selection.
An input adornment would be the cleanest way to achieve this. In the same way kg is added on https://material-ui.com/components/text-fields/#input-adornments.

**Comment by dmtrKovalenko** [comment]
Thanks for rising an issue! But it is not enough information for us to properly reproduce and understand your problem. Can you please provide more details about the issue?

Please provide a reproduction, this [codesandbox template](https://codesandbox.io/s/material-ui-pickers-v4-jfm6g) could be useful.

Thanks ;)

**Comment by toonvd** [comment]
Hi

Thanks for the patience and the nice lib :).
What I was aiming for is to have a startadornment to use as a label in MobileDateTimePicker.
This mostly because in some cases, room for a label is non existent.

https://codesandbox.io/s/fancy-morning-09uq9

**Comment by dmtrKovalenko** [comment]
We are already move all our work to the `v4`. And there we have new `renderInput` API , so you can render and pass any props to the textfield

```jsx
<DatePicker 
  renderInput={props => <TextFiled {....props} InputProps={{ endAdornement: anything }} />}
/>
```

**Comment by toonvd** [comment]
Hi

That's awesome, because v4 is marked alpha, I was using v3.
I suppose it is not an option in the old version?
Will close the issue already since it is not a problem in future versions.

**Comment by toonvd** [comment]
Hi

The TextFieldComponent prop helped me out.
Thanks again for your patience and the great lib!
