### ISSUE TITLE
Automatic switch to month doesn't happen in static date range picker

### ISSUE THREAD

**Issue by mallowigi** [mui-org/material-ui-pickers#2000]
Hi, I've been using the MUI Date Range Picker (alpha 9) and there's one behavior that seems to be missing: when changing the date dynamically, the calendars don't "focus" on the selected dates.

You can even see it here: https://next.material-ui-pickers.dev/demo/daterangepicker#static-mode

I can play with the mobile date picker and select a month that is not into view, yet the desktop date picker is not jumping to the said date like it does with the non-static verions

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The date ranges change but the calendar doesn't "jump" to the selected month/year

## Expected Behavior 🤔

The calendar should "jump" to the selected month/year like in non-static views

## Steps to Reproduce 🕹

https://next.material-ui-pickers.dev/demo/daterangepicker#static-mode

Steps:

1. Change the date in the mobile view of the static picker
2. See that the desktop view doesn't "jump"

## Context 🔦

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v4.0.0-alpha9 |

**Comment by oliviertassinari** [comment]
@mallowigi What does "jump" mean in this context? Are you referring to controlling the state defined as "displayedValue" in #1980?

**Comment by mallowigi** [comment]
By jump I mean the ability to move the calendar to the selected date (month/year)

**Comment by oliviertassinari** [comment]
Ok, thanks for the confirmation.

I see that this behavior is native to the `DatePicker`. If you change the *value*, to one that is outside of the current *displayed value*, it will update the *displayed value* to match the new *value* prop. https://next.material-ui-pickers.dev/demo/datepicker#static-mode.

@dmtrKovalenko What do you think of reproducing the same behavior? It seems to be a sensible default. A new test case for it seems also welcome.

**Comment by MirkoTV** [comment]
+1

**Comment by dmitry-kovalev** [comment]
Hi.
Will this bug be fixed?
Still reproduced on latest @material-ui/pickers: 4.0.0-alpha.12

**Comment by oliviertassinari** [comment]
@dmitry-kovalev please try the component available in @material-ui/lab@v5.
