### ISSUE TITLE
[DatePicker] Support focused input in open state

### ISSUE THREAD

**Issue by amok** [mui-org/material-ui-pickers#2002]
**I'd like to keep input focused/active when desktop calendar is open.**

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

MUI-pickers version: 4.0.0-alpha.9 (see deps below)

I looked through the code, issues, API docs and did not find any proper solution.
As far as I understand `DesktopWrapper` has "hardcoded" `role="dialog"` 

https://github.com/mui-org/material-ui-pickers/blob/6ffb24b2ff995658f06bebe4fda4759276e83d96/lib/src/wrappers/DesktopWrapper.tsx#L37

which makes `TrapFocus` of `PickerPopper` to enforce focused state on a Calendar element

https://github.com/mui-org/material-ui-pickers/blob/6ffb24b2ff995658f06bebe4fda4759276e83d96/lib/src/_shared/PickersPopper.tsx#L120

## Examples 🌈

https://monosnap.com/file/CtU6UsH6Rl49MdJXEFrar06fxHuUbY

![image](https://user-images.githubusercontent.com/1369559/87799285-b6086400-c855-11ea-8597-98a8b1f48b46.png)

## Motivation 🔦

I'm trying to achieve the following behaviour:
When input is clicked -  open calendar but keep the input focused and active.
DateRangePicker already supports this behaviour, see attached video and check https://next.material-ui-pickers.dev/demo/daterangepicker#basic-usage

```
    "@material-ui/core": "^4.9.13",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@material-ui/pickers": "^4.0.0-alpha.9",
```

**Comment by lamhungypl** [comment]
[#1817](https://github.com/mui-org/material-ui-pickers/issues/1877) [#1998](https://github.com/mui-org/material-ui-pickers/issues/1998).I am also waiting for this behavior.

**Comment by Serzh470** [comment]
I support this too, this behavior will be aligned with material design templates:
[Desktop pickers](https://material.io/components/date-pickers#desktop-pickers)
