### ISSUE TITLE
Version 4.0.0-alpha.10 not working correctly with DateTimePicker. The selection of same day not working!

### ISSUE THREAD

**Issue by italoiz** [mui-org/material-ui-pickers#2012]
In the version `4.0.0-alpha.10` with `<DateTimePicker />` component, when the initial date is provided on the `date` property, not is possible to select the same day of the initially provided date, check the bellow gif. But, in the version `4.0.0-alpha.9` the behavior is another. See the bellow gif.

| *4.0.0-alpha.9* | *4.0.0-alpha.10* |
|--------------|----------------|
| <img src="https://user-images.githubusercontent.com/8454560/87867607-2651db00-c965-11ea-9c52-4d725e565da3.gif" width="200" /> | <img src="https://user-images.githubusercontent.com/8454560/87867627-63b66880-c965-11ea-890d-d6268444334a.gif" width="200" /> |

- [ ] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

In the version `4.0.0-alpha.10` with `<DateTimePicker />` component, when the initial date is provided on the `date` property, not is possible to select the same day of the initially provided date, check the bellow gif.

The StackBlitz live example: https://stackblitz.com/edit/react-ts-prwww3?file=DatePicker.tsx

## Expected Behavior 🤔

The expected behavior it should be possible to select the same day of initially provided date on the `date` property.

The StackBlitz live example: https://stackblitz.com/edit/react-ts-yhzzxy?file=DatePicker.tsx

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v4.0.0-alpha.10  |
| React       |    v16.13.1     |
| Browser     |     Google Chrome 83.0.4103.116    |

**Comment by dmtrKovalenko** [comment]
Ha ha ha @oliviertassinari 😨
We need to allow `sameDaySelction` for `<DateTimePicker />`
