### ISSUE TITLE
[docs] Use permanent banner over temporary notif to drive usage on next

### ISSUE THREAD

**Issue by thanpolas** [mui-org/material-ui-pickers#2015]
Hello, 

thank you for this awesome library and the time you've put into this. I hope you find this feedback useful.

As a new developer trying to install material-ui-pickers I got confused installing the package. In particular with the Peer Library and how to use it.

In the [Installation Page](https://material-ui-pickers.dev/getting-started/installation), we are instructed to install the peer library. The way this is stated is very confusing to me, here are my concerns & questions:

1. It's stated: "Important: For material-ui-pickers v3 use v1.x version of @date-io adapters.". 
    1. The way this is worded, gave me the impression that "material-ui-pickers v3" is a past version, I checked, it is the current version.
    2. Why does the "current" version of material-ui-pickers, need to use a past version of "date-io" and not the current?
2. Why do we need another package (@date-io/...) and can't directly use the library we already have installed on our project?

I trust there are perfectly good answers for all the above. What I am trying to convey is that: 

a. the instructions are confusing to new users.
b. My eyebrow got raised that I have to install a "proxy-peer" library (`@date-io/....`) to "use the date management library of your choice.".

Again, thank you for the great library.

**Comment by oliviertassinari** [comment]
@thanpolas Check the documentation of the next version we work on http://next.material-ui-pickers.dev/, it should already be fixed.

**Comment by thanpolas** [comment]
nice, yea this is much clearer. Maybe link that page from the frontpage?

**Comment by oliviertassinari** [comment]
@dmtrKovalenko What do you think of replacing the snackbar that only shows during the first display with a fixed header? Something similar to https://v0.material-ui.com/#/?

<img width="747" alt="Capture d’écran 2020-07-21 à 15 11 21" src="https://user-images.githubusercontent.com/3165635/88058934-73e86680-cb64-11ea-9b5c-9811e80dfb64.png">

**Comment by oliviertassinari** [comment]
A couple more benchmark of top banners:

<img width="869" alt="Capture d’écran 2020-07-25 à 12 36 00" src="https://user-images.githubusercontent.com/3165635/88455166-72c07d80-ce73-11ea-8430-235ae7487003.png">

https://www.gatsbyjs.org/

<img width="1121" alt="Capture d’écran 2020-07-25 à 12 36 38" src="https://user-images.githubusercontent.com/3165635/88455172-85d34d80-ce73-11ea-8416-045e2042a1f9.png">

https://nextjs.org/

**Comment by oliviertassinari** [comment]
The documentation was moved to https://next.material-ui.com/components/pickers/. I have added a deprecation message on the `next` version: https://www.npmjs.com/package/@material-ui/pickers/v/4.0.0-alpha.12

<img width="1209" alt="Capture d’écran 2020-11-15 à 01 08 35" src="https://user-images.githubusercontent.com/3165635/99159691-1bbf0c80-26df-11eb-81c8-5a898fa58f71.png">

I think that it's good enough. Already 50% of the traffic for the components already happens under http://material-ui.com/. @thanpolas Thanks for the report.
