### ISSUE TITLE
[docs] Explain how to only pick the time of the day

### ISSUE THREAD

**Issue by linonetwo** [mui-org/material-ui-pickers#2018]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I can't get correction time for my `setInterval`

I hope there can be a way to pick "Pure Time" without to be interrupted by year, month, day, and timezone.

## Examples 🌈

I'm prividing `fromUnixTime(syncDebounceInterval / 1000 + new Date().getTimezoneOffset() * 60)`

to TimePicker,

and get it use

```
(getHours(d) * 3600 + getMinutes(d) * 60 + getSeconds(d) - new Date().getTimezoneOffset() * 60) * 1000)
```

trying to prevent timezone and year and month and day.

But the value still can't be correct.

## Motivation 🔦

I only need "Time" for a `setInterval`

**Comment by oliviertassinari** [comment]
Related to #1526?

**Comment by linonetwo** [comment]
I finally get it to work like this:

`syncDebounceInterval` is a unix millsecond time which basically `60 * 60 * 1000`:

```js
                <TimePicker
                  autoOk={false}
                  ampm={false}
                  openTo="hours"
                  views={['hours', 'minutes', 'seconds']}
                  inputFormat="HH:mm:ss"
                  renderInput={timeProps => <TextField {...timeProps} />}
                  value={fromUnixTime(syncDebounceInterval / 1000 + new Date().getTimezoneOffset() * 60)}
                  onChange={date =>
                    requestSetPreference(
                      'syncDebounceInterval',
                      (date.getTime() / 1000 - new Date().getTimezoneOffset() * 60) * 1000,
                    )
                  }
                  onClose={() => {
                    window.preventClosingWindow = false;
                  }}
                  onOpen={() => {
                    window.preventClosingWindow = true;
                  }}
                />
```

I add `new Date().getTimezoneOffset()` to it before edit it, and sub it after edit.

**Comment by oliviertassinari** [comment]
Would it make sense to cover your use case in the documentation?

**Comment by linonetwo** [comment]
Ok, I can add that to doc.

And actually there is an update to my approach:

```js
                  onChange={date => {
                    const timeWithoutDate = setDate(setMonth(setYear(date, 1970), 0), 1);
                    const utcTime = (timeWithoutDate.getTime() / 1000 - new Date().getTimezoneOffset() * 60) * 1000;
                    requestSetPreference('syncDebounceInterval', utcTime);
                    debouncedRequestShowRequireRestartDialog();
                  }}
```

I have to use `setDate(setMonth(setYear(date, 1970), 0), 1)` to remove "Date part" of my time, otherwise this number will be very huge (add `(2020-1970)*365*3600*24` to it ...).

Now it works pretty good.
