### ISSUE TITLE
Property 'lib' is missing in type 'DateFnsUtils' but required in type 'IUtils<unknown>'

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#2021]
The TypeScript error happens after updating from alpha7 to alpha10. I have date-fns 2.15.0 installed.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

> TS2322: Type 'typeof DateFnsUtils' is not assignable to type 'new (...args: any) => MuiPickersAdapter<unknown>'.   Property 'lib' is missing in type 'DateFnsUtils' but required in type 'IUtils<unknown>'.  IUtils.d.ts(70, 3): 'lib' is declared here. LocalizationProvider.d.ts(6, 5): The expected type comes from property 'dateAdapter' which is declared here on type 'IntrinsicAttributes & LocalizationProviderProps & { children?: ReactNode; }'

## Expected Behavior 🤔

No TS error.

## Steps to Reproduce 🕹

https://codesandbox.io/s/mui-datetimepicker-dateadapter-typescript-error-murff

The code that produces the error is below:
```ts
import React, { ReactElement } from 'react';
import { TextField } from '@material-ui/core';
import { DateTimePicker, LocalizationProvider } from '@material-ui/pickers';
import DateFnsUtils from '@material-ui/pickers/adapter/date-fns';

export default function Foo(): ReactElement {
  return (
    <LocalizationProvider dateAdapter={DateFnsUtils}>
      <DateTimePicker
        renderInput={props =>
          <TextField/>
        }
        onChange={() => null}
        value=""
      />
    </LocalizationProvider>
  );
}
```

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v4.0.0-alpha10  |
| React       |  16.13.1     |
| TypeScript  |  3.9.5     |

**tsconfig**:
```
{
  "compilerOptions": {
    "target": "es2019",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": false,
    "sourceMap": true
    "resolveJsonModule": true,
    "lib": ["DOM"],
    "jsx": "react",
    "noEmit": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "types": ["cypress"]
  }
}

```

**Comment by dmtrKovalenko** [comment]
Please try to remove `node_modules` and make `yarn install` or `npm install`.

**Comment by dandv** [comment]
Thanks @dmtrKovalenko, that fixed the issue.

Now I'm running into a different one in my React Hooks Form integration: the calendar popup gets rendered at (0, 0) and the console shows this error message:

> index.js:2177 Warning: Failed prop type: Material-UI: The `anchorEl` prop provided to the component is invalid.
It should be an HTML element instance or a referenceObject

It's caused by passing the inputRef to the TextField, and it did not happen in alpha7.

I'll work on creating a minimal CodeSanbox, but hoped maybe you knew of a similar quick fix.

```ts
const inputRef = useRef<HTMLInputElement>();
<LocalizationProvider dateAdapter={DateFnsUtils}>
  <Controller {...{ name, control }}
    defaultValue={null}
    as={
      <DateTimePicker
        disablePast
        renderInput={props =>
          <TextField {...props} {...{ label, inputRef }} />
        }
        onChange={() => null}
        value=""  // RHF controls controls it
     />
   }
 />
</LocalizationProvider>
```

**Comment by dmtrKovalenko** [comment]
I am not sure please provide reproduction

**Comment by dandv** [comment]
Thanks, I've filed #2022.
