### ISSUE TITLE
Calendar renders in top-left corner with React Hook Form inputRef

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#2022]
I think I'm running into a regression or new incompatibility with React Hook Form. [This sample](https://codesandbox.io/s/mui-datetimepicker-calendar-popup-shows-at-0-0-with-rhf-00u8g?file=/index.tsx) worked fine with MUI Pickers 4.0.0-alpha7 and MUI 4.9.14, but with MUI 4.11.0 and Pickers alpha 10, the picker is positioned at (0,0) and clicking the calendar icon triggers this error message:

> Warning: Failed prop type: Material-UI: The `anchorEl` prop provided to the component is invalid.
It should be an HTML element instance or a referenceObject 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

![image](https://user-images.githubusercontent.com/33569/88160038-facc2c00-cbc2-11ea-9cdb-a2e3c2941456.png)

## Expected Behavior 🤔

The calendar should render under the `Text` input, which does happen if the `inputRef` prop is not passed to the `<Text>`.

## Steps to Reproduce 🕹

Click the calendar icon in the [Code sandbox](https://codesandbox.io/s/mui-datetimepicker-calendar-popup-shows-at-0-0-with-rhf-00u8g?file=/index.tsx).

**Comment by oliviertassinari** [comment]
Tip: merge the `inputRef` prop correctly. This also makes me think of #1768.

**Comment by oliviertassinari** [comment]
👋 Thanks for using Material-UI!

We use GitHub issues exclusively as a bug and feature requests tracker, however,
this issue appears to be a support request.

For support, please check out https://material-ui.com/getting-started/support/. Thanks!

If you have a question on StackOverflow, you are welcome to link to it here, it might help others.
If your issue is subsequently confirmed as a bug,  and the report follows the issue template, it can be reopened.

**Comment by dandv** [comment]
> Tip: merge the `inputRef` prop correctly.

Thanks, not sure if I understood the tip right, but I used `renderInput={props => <TextField {...props} ref={inputRef} />}` instead of `renderInput={props => <TextField {...props} inputRef={inputRef} />}` and the calendar is placed correctly.

The reason I filed this as a bug is that the `inputRef={inputRef}` syntax worked with alpha7 and no longer works with alpha10, so I thought it was a regression.

**Comment by oliviertassinari** [comment]
@dandv The `props` contains two refs, one for the input and a second one for the container, you should fork them if you intend to override them.

@dmtrKovalenko Why do we need two refs? I fail to understand how this work, the variable gets renamed along the way, I lose track of where it's used. It seems that we can simplify the logic to a single ref.

**Comment by dmtrKovalenko** [comment]
We use only input ref. But there I suppose that in this example input is rendering with some delay.

**Comment by oliviertassinari** [comment]
> We use only input ref.

@dmtrKovalenko I'm confused by these lines:

https://github.com/mui-org/material-ui-pickers/blob/d7d90f2a677090b6a9597eefe8739313e597c20a/lib/src/_shared/KeyboardDateInput.tsx#L31-L33

What's the `containerRef` for? If it's to implement that forwardRef logic, what about we simply drop it? Considering developers can already apply a ref on the TextField (which is available in userland and the root component).
