### ISSUE TITLE
docs: @example appears raw

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#2026]
At https://dev.material-ui-pickers.dev/api/DateTimePicker, search for "@example"

![image](https://user-images.githubusercontent.com/33569/88220128-7061e780-cc17-11ea-88a7-4f7e1b609669.png)

**Comment by dmtrKovalenko** [comment]
This example is mostly for the IDE inteellisince. Yes we need more clever props generator – but it is not a priority because we are moving to the core repository where I hope it works better :)
