### ISSUE TITLE
DateRangePicker -> Custom input component demo slightly broken

### ISSUE THREAD

**Issue by Chee7ah** [mui-org/material-ui-pickers#2027]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

DateRangePicker closes immediately after the first date has been picked.
Happens in [alpha.9](https://v4-0-0-alpha-9.material-ui-pickers.dev/demo/daterangepicker#custom-input-component) and [alpha.10](https://v4-0-0-alpha-10.material-ui-pickers.dev/demo/daterangepicker#custom-input-component).

![G51d4zo4g4](https://user-images.githubusercontent.com/16325672/88260792-f0b93480-cc79-11ea-8657-bdd170e0353e.gif)

## Expected Behavior 🤔

DateRangePicker stays open till both ends of the range have been picked.
Works as expected in [alpha.8](https://v4-0-0-alpha-8.material-ui-pickers.dev/demo/daterangepicker#custom-input-component).

![uEhDmjuF5S](https://user-images.githubusercontent.com/16325672/88260671-b2237a00-cc79-11ea-94d9-21059d56c91d.gif)

## Steps to Reproduce 🕹

Steps:

1. Go to [https://v4-0-0-alpha-10.material-ui-pickers.dev/demo/daterangepicker#custom-input-component](https://v4-0-0-alpha-10.material-ui-pickers.dev/demo/daterangepicker#custom-input-component)
2. Fill in a date range with the picker
3. Note that picker closes immediately after first date is picked
4. Have to blur and refocus second input field to be able to fill the second date

## Context 🔦

Live example on the demo page

## Your Environment 🌎

The demo page

**Comment by dmtrKovalenko** [comment]
Thanks for raising. There issue is related to usage of `startProps.ref` instead of `startProps.inputRef`. 

Can you check that it works for you? And if you have time -- PR with a fix of example will be appreciated ❤️

**Comment by Chee7ah** [comment]
Checked, it fixes it. Opened PR #2028 with the change.

**Comment by oliviertassinari** [comment]
Thanks for working on it, I think that we can close the issue once we have taken care of https://github.com/mui-org/material-ui-pickers/pull/2028#issuecomment-663123827.
