### ISSUE TITLE
Support adding more than one character on mask

### ISSUE THREAD

**Issue by allysonjp715** [mui-org/material-ui-pickers#2031]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I want to be able to provide a mask of the form YYYY/MM/DD. Currently we can add a mask of the form `____/__/__` or have a single character in the mask such as XXXX/XX/XX. But it is very useful to have YYYY/MM/DD to indicate the order of month and day.

## Motivation 🔦

It is unclear to our users how to type in a date if they don't know what format to enter it in.

**Comment by oliviertassinari** [comment]
@allysonjp715 From what I could gather, you are using [v3.2.10](https://github.com/open-covid-data/healthmap-gdo-temp/blob/ca177c1b9a940dcd0f51166db6c6f13976894dda/verification/curator-service/ui/package-lock.json#L1746). Would it help if the format was displayed as an input placeholder (only visible when empty)?

<img width="234" alt="Capture d’écran 2020-07-24 à 21 57 26" src="https://user-images.githubusercontent.com/3165635/88430441-bd50e400-cdf8-11ea-82ec-902fc37cca42.png">

Would you also display the mask in the helper text (always visible unless there is an error)?

<img width="246" alt="Capture d’écran 2020-07-24 à 21 59 16" src="https://user-images.githubusercontent.com/3165635/88430575-f5f0bd80-cdf8-11ea-86f6-4a3da19dd45d.png">

**Comment by allysonjp715** [comment]
Thanks for quick response! A mask would be better, but both of those are okay options yes. I tried the emptyLabel prop, but the label didn't disappear when clicking on the input, which I didn't find a good UX.

I didn't know about the helperText before since the prop isn't mentioned in the [documentation](https://material-ui-pickers.dev/api/KeyboardDatePicker). I just now saw it used in the [demos](https://material-ui-pickers.dev/demo/datepicker).

**Comment by oliviertassinari** [comment]
@allysonjp715 The seen what we have in the pipeline on the `next` version. For instance #1749 on how to pick between the two options :).

**Comment by tjbulick** [comment]
@oliviertassinari @dmtrKovalenko Hey. Not sure whether it's worth creating a new issue or not, so commenting here.
I'm joining initial issue author's opinion, it would be great to have guided masks that user fills symbol by symbol. Example of such experience shown below in the 'Date' field:
![](https://i1.wp.com/css-tricks.com/wp-content/uploads/2016/11/mask.gif)
So are there any chances to implement that with material-ui/core@4.x and material-ui/pickers@3.2.10? Or maybe with material-ui/core@5.x and material-ui/pickers@4.x?

If we pass 'mask' prop to KeyboardDatePicker with desired mask now, then it completely breaks the input itself. Live demo: https://codesandbox.io/s/material-demo-forked-woqj8?file=/demo.js

When i try to pass a mask with desired symbols according to the format, then input just clears itself whenever you try to enter something.
![image](https://user-images.githubusercontent.com/28315191/96229020-09966500-0f9f-11eb-8a19-dabdd935c352.png)

Also, i noticed one weird thing: on the [KeyboardDatePicker API](https://material-ui-pickers.dev/api/KeyboardDatePicker) page it says that mask must be a string, but on [another page](https://material-ui-pickers.dev/guides/upgrading-to-v3) it shows that mask could be an array of regexps. So, which of these is true?

I can also open a new issue, if needed. Thank you for your work on material-ui.
