### ISSUE TITLE
Missing initialFocusedDate in v4.0.0-alpha.10

### ISSUE THREAD

**Issue by bobsingor** [mui-org/material-ui-pickers#2032]
## Summary 💡

In material-ui v3 the date picker has the ability to set initialFocusedDate what gives an initially highlighted date on opening the picker. I am missing the ability to set this variable in v4. Is there a motivation why this is removed or will this be added again on the stable version?

**Comment by dmtrKovalenko** [comment]
What is your use case for this prop?

**Comment by bobsingor** [comment]
@dmtrKovalenko For a bookkeeping software we have invoices. An invoice has an "invoice date" and a "due date" if the invoice date is set then i will put the initial focus of the due date on the invoice date. Sometimes we are adding invoices from months ago and then it's not a great user experience to click back all the time to that specific month.

**Comment by dmtrKovalenko** [comment]
Why not to set it as default `value`?

**Comment by oliviertassinari** [comment]
+1 for default `value`. Also, I think that for implementing custom logics, it will be simpler to expose the internal states, to make them controllable: #1980, than exposing a long list of props to cover niche use cases.

**Comment by bobsingor** [comment]
@dmtrKovalenko because then the value is being set. I don't want the value to be set yet. I want the user to be aware of having to choosing a due date and if not chosen to give an error. 

For the user it would be the best experience to have some initially highlighted date option.

There are probably a lot of use cases where multiple dates have a relation to each other but that the "range date" element is not the right choice

**Comment by oliviertassinari** [comment]
Closing for #1980
