### ISSUE TITLE
Transition forwardRef logic issue

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-pickers#2035]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Crash

## Expected Behavior 🤔

Shouldn't crash

## Steps to Reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/elegant-black-f6fgv?file=/src/App.jsx.
2. Open the picker

## Context 🔦

I was looking into https://github.com/mui-org/material-ui/pull/21873#issuecomment-662409709.

See https://github.com/mui-org/material-ui/issues/21858 for a prior-art. This originates from a wrong forward ref logic here. We have added a new warning in v5.0.0-alpha.5 to help identify the origin.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v5.0.0-alpha.4  |
| @material-ui/pickers | v4.0.0-alpha.10  |

**Comment by eps1lon** [comment]
Fixed in #2053
