### ISSUE TITLE
Broken link in the docs

### ISSUE THREAD

**Issue by aamirafridi** [mui-org/material-ui-pickers#2046]
https://v4-0-0-alpha-10.material-ui-pickers.dev/api/DateRangePicker

The link provided for the prop `dateAdapter` is broken

broken link for **here**
> Allows to pass configured date-io adapter directly. More info **here**

**Comment by dmtrKovalenko** [comment]
Here is the right link https://v4-0-0-alpha-10.material-ui-pickers.dev/guides/date-adapter-passing

**Comment by dmtrKovalenko** [comment]
If you would like to open PR and fix the issue - it would be awesome :)

**Comment by aamirafridi** [comment]
@dmtrKovalenko  should I replace the absolute links to relative paths in `docs/prop-types.json` ?

e.g. replace:
```
"description": "Allows to pass configured date-io adapter directly. More info [here](https://material-ui-pickers.dev/guides/date-adapter-passing)\n```jsx\ndateAdapter={new DateFnsAdapter({ locale: ruLocale })}\n```",
```

with 
```
"description": "Allows to pass configured date-io adapter directly. More info [here](/guides/date-adapter-passing)\n```jsx\ndateAdapter={new DateFnsAdapter({ locale: ruLocale })}\n```",
```

**Comment by dmtrKovalenko** [comment]
Ha ha ha. It is more deep problem. Originally it was required to set the right link in the inteliisince right in editor. 

For now only add 'next.' prefix

**Comment by aamirafridi** [comment]
https://github.com/mui-org/material-ui-pickers/pull/2048

**Comment by aamirafridi** [comment]
The propose file link is  broken too [here](https://v4-0-0-alpha-10.material-ui-pickers.dev/demo/datepicker)

![image](https://user-images.githubusercontent.com/55896/88954375-34232c80-d292-11ea-9210-e56c496b48e9.png)

**Comment by oliviertassinari** [comment]
@aamirafridi No need to worry about it, we are working on moving the component to the main repository infrastructure, so we don't have to fix bugs like this one twice (we have that type of regression a couple of time on main).

**Comment by aamirafridi** [comment]
ok cool. thanks :)
I think [this issue](https://github.com/mui-org/material-ui-pickers/issues/1948) still needs to resolved and reopened
