### ISSUE TITLE
Change year order from InlineDatePicker

### ISSUE THREAD

**Issue by ronaiza-cardoso** [mui-org/material-ui-pickers#2047]
Hi, 

is there a way of changing the year order?

starting from the oldest year to the current year?

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Examples 🌈
https://codesandbox.io/s/change-year-order-85q3b?file=/src/index.js

## Motivation 🔦
I look through all the documentation and couldn't find a way of changing the year order... kind like make one reverse of the current year list.

**Comment by ronaiza-cardoso** [comment]
sorry, forget it, I found one example of what I'm looking for here https://github.com/mui-org/material-ui-pickers/issues/1112

**Comment by dmtrKovalenko** [comment]
Example here: https://next.material-ui-pickers.dev/guides/date-io-customization#override-date-logic

**Comment by zachsa** [comment]
Is this possible with v3?

**Comment by dmtrKovalenko** [comment]
Yes it is, using exactly same approach. By patching date-io adapter for MuiPickersUtils provider
