### ISSUE TITLE
Docs for v4.0.0-alpha.11 does not work

### ISSUE THREAD

**Issue by stunaz** [mui-org/material-ui-pickers#2064]
![11](https://user-images.githubusercontent.com/1305483/89123426-445b2780-d49d-11ea-9470-3b0ccee9a2af.png)

**Comment by oliviertassinari** [comment]
We will have it live in https://next.material-ui.com/

**Comment by dmtrKovalenko** [comment]
Fixed https://v4-0-0-alpha-11.material-ui-pickers.dev/

**Comment by dmtrKovalenko** [comment]
Ohhh @oliviertassinari looks like rushing to the @alpha version was not a good idea – documentation styling is broken https://v4-0-0-alpha-11.material-ui-pickers.dev/demo/datepicker

**Comment by oliviertassinari** [comment]
@dmtrKovalenko I have just seen that. Not great, but I'm not sure we should care. Won't we drop this documentation infrastructure anyway?

**Comment by dmtrKovalenko** [comment]
If we don't need docs why was release done?

**Comment by oliviertassinari** [comment]
We need to make a release to unlock: 

- https://github.com/mui-org/material-ui/pull/21873
- https://github.com/mui-org/material-ui/pull/22023

**Comment by dmtrKovalenko** [comment]
> but I'm not sure we should care

We **must** – it still our users. We should never create a buggy release just because somebody needs it. I will work on fixing issues created by release

**Comment by oliviertassinari** [comment]
It's unclear what went wrong with the release. The deploy preview of #2053 and of the release commit https://material-ui-pickers-bepk858nk.vercel.app/demo/datepicker look correct.

**Comment by dmtrKovalenko** [comment]
The problem is with 2 version (v4 and v5) in bundle. Fixed in #2065
