### ISSUE TITLE
Why only first character of week is rendered?

### ISSUE THREAD

**Issue by zzzet** [mui-org/material-ui-pickers#2068]
https://github.com/mui-org/material-ui-pickers/blob/137019c0ca703bce44b2a66feebc34efe5e4cd41/lib/src/views/Calendar/Calendar.tsx#L181
Even with extending the utils for LocalizationProvider and writing custom getWeekdays does not help.
May be we need and `renderWeekDays` to override the default render of week day.

Locale = th
![Screen Shot 2563-08-04 at 5 20 00 PM](https://user-images.githubusercontent.com/5461675/89283073-bcc91080-d676-11ea-8fd1-4cbf324e5729.png)

Locale = id
![Screen Shot 2563-08-04 at 5 20 57 PM](https://user-images.githubusercontent.com/5461675/89283159-dec29300-d676-11ea-9e9c-c0da290c5bbb.png)

**Comment by dmtrKovalenko** [comment]
Yes that's definitely an issue. Originally it was done to support existed `getWeekDays` result.

**Comment by tpeek** [comment]
This issue is being more official tracked here: https://github.com/mui-org/material-ui/issues/23677
