### ISSUE TITLE
How do I prevent the clock view from showing when I clicking on date.

### ISSUE THREAD

**Issue by jack2ky** [mui-org/material-ui-pickers#2080]
I'm using `DateTimePicker`. The calendar shows when the component loads via `openTo="date"` basically I want to do a check to see if the day is available and if it is, then go to the clock. I tried to return false in the change handler. Tried to set an error but the error just came when the component loaded. Right now every time I click the day it always goes to the clock. How can I stop it from going to the clock automatically? I also noticed that there is no onDateChange or onDayChange but there is onYearChange.

**Comment by oliviertassinari** [comment]
You should be able to control the state with the `view` and `onViewChange` props.
