### ISSUE TITLE
v4 mask guide support

### ISSUE THREAD

**Issue by gijsbotje** [mui-org/material-ui-pickers#2083]
in v3 the mask would guide the user through the requested format. In v4 this has been turned off and is a feature our customers are highly requesting us to put back in place. As we needed v4 for other reasons, we would love the option to turn it on again. just like https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#guide.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The boolean just toggles if the mask should show all the placeholder characters and characters in the mask or fill it out when the user reaches it. Having this option would give users of v3 less visual changes after upgrading and (imo) is a great feature to have.

## Examples 🌈

https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#guide

## Motivation 🔦
Customers have requested this to be added back after we had to upgrade to v4. They see their users filling out date time fields without the time, as they don't see the mask for those extra 4 numbers. They tend to ignore the placeholder and just type a date. Without the guide our date fields have proven to be error prone as the user doesn't know what to enter as they think they have filled the field out correctly.

**Comment by dmtrKovalenko** [comment]
Thanks for raising this issue. It is super important that this feature is used. 

I will write documentation about mask generation, but a quick answer:
If your format is `mm/dd/yyyy` you need to provide `inputFormat="__/__/____"`. Make sure that format characters that allow to input 1-char or 2-chars values  (e.g. `d`)  are not supported together with mask– it will fall back to the unmasked input.  

I think there are enough masked examples in https://next.material-ui-pickers.dev/localization/date-fns

**Comment by gijsbotje** [comment]
@dmtrKovalenko thanks for your response.
if i use your suggestion  and do:
```
inputFormat="DD/MM/YYYY HH:mm"
mask="__/__/____ __:__"
```
i get the following warning
```
The mask "__/__/____ __:__ _M" you passed is not valid for the format used DD/MM/YYYY HH:mm. Falling down to uncontrolled not-masked input.
```

also i don't think you understand my issue. The formatting works, but while typing the datetime, you lose the reference to what the format should be. With a guide you still see what position are left to fill out.

if that is what your suggestion should do, there is something else going wrong

**Comment by dmtrKovalenko** [comment]
I understand this, and this error definetely needs to be more descriptive. But it means that the we tried to format the date with passed `inputFormat` but appeared that use cannot type all the the date using your mask.
