### ISSUE TITLE
Bootstrap outline style conflict

### ISSUE THREAD

**Issue by Juliangzr** [mui-org/material-ui-pickers#2084]
When i use material-pickers along with bootstrap i see box borders when i click on the calendar

![image](https://user-images.githubusercontent.com/45461158/90251730-a2302d80-de14-11ea-8730-eeb1e178931c.png)
![image](https://user-images.githubusercontent.com/45461158/90251762-b2480d00-de14-11ea-94aa-add43d44380a.png)
https://codesandbox.io/s/musing-taussig-95oyr

**Comment by oliviertassinari** [comment]
Do you have a reproduction we can look at?

**Comment by Juliangzr** [comment]
> Do you have a reproduction we can look at?

Do you mean the code?

**Comment by oliviertassinari** [comment]
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/next/examples/create-react-app?file=/src/App.js) _may_ be a good starting point. Thank you!

**Comment by Juliangzr** [comment]
here i'm uploading the code with the problem
[pickersproblem.zip](https://github.com/mui-org/material-ui-pickers/files/5074740/pickersproblem.zip)

**Comment by Juliangzr** [comment]
> A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/github/mui-org/material-ui/tree/next/examples/create-react-app?file=/src/App.js) _may_ be a good starting point. Thank you!

https://codesandbox.io/s/musing-taussig-95oyr

**Comment by oliviertassinari** [comment]
@Juliangzr Awesome thanks for the reproduction. Once with only the *core* package: https://codesandbox.io/s/material-demo-forked-vrfe1?file=/index.tsx.

I could track the problem down to https://github.com/twbs/bootstrap/issues/18320. At this point, I think that the best course of action is to ignore the problem. Bootstrap is breaking the behavior of the focus ring with this reset, they force it even in cases where it's not relevant. See https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible for a better approach.

A workaround is to override Bootstrap's styles:

```css
.MuiButton-root:focus {
  outline: 0;
}
.MuiIconButton-root:focus {
  outline: 0;
}
```
