### ISSUE TITLE
DatePicker uses text cursor despite opening a popup

### ISSUE THREAD

**Issue by cyberixae** [mui-org/material-ui-pickers#2085]
1. go to https://material-ui-pickers.dev/demo/datepicker
2. hover the first basic example with your mouse
3. note that a text cursor is shown
4. click on the text field with your mouse
5. note that a popup opens and the user never has the opportunity to edit the text

what happens: user gets wrong idea based on the cursor
what should happen: finger pointer cursor should be used instead of text cursor

**Comment by dmtrKovalenko** [comment]
This is resolved in v4. Originally it was not supposed to use dialog picker on desktop.
