### ISSUE TITLE
Question: Will pickers land in @material-ui/core v4 or v5?

### ISSUE THREAD

**Issue by petermikitsh** [mui-org/material-ui-pickers#2086]
Per the latest release notes:

> v4.0.0-alpha.12

> It is the last release of @material-ui/pickers from the https://github.com/mui-org/material-ui-pickers. Starting from this point, we will work on migrating pickers to https://github.com/mui-org/material-ui repo 😋

Will this be on the v4 or v5 release?

**Comment by oliviertassinari** [comment]
in @material-ui/lab@v5-alpha

**Comment by oliviertassinari** [comment]
We gonna take the next couple of months to stabilize the date picker components, we move the components in the lab first, so we can keep them in alpha even if we need to ship a v5 stable.
