### ISSUE TITLE
useDefaultProps doesn't work props are frozen and cannot be overridden

### ISSUE THREAD

**Issue by rajzik** [mui-org/material-ui-pickers#2088]
https://github.com/mui-org/material-ui-pickers/blob/91dcbaffba239f981613801c6d6294bdcee1c6ca/lib/src/_shared/withDefaultProps.tsx#L5

Props should be cloned.

Proposed fix: 
```tsx
export function useDefaultProps<T>(props: T, { name }: { name: string }) {
  const theme = useTheme();
  const localProps = {...props};
  // OR
  const localProps = _.cloneDeep(props);
  return getThemeProps<any, T, string>({
    props: localProps,
    theme,
    name,
  });
}
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`Cannot add property {{ propertyName }}, object is not extensible`

## Expected Behavior 🤔

No error.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-pickers-playground-forked-z68eu?file=/App.js

Steps:

1. extend the theme with props
2. use picker component
3. Type error will occur
`TypeError Cannot add property InputProps, object is not extensible`

## Context 🔦

Trying to set up default props for material-ui/pickers via the theme.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | vnext  |
| @material-ui/pickers | vnext  |
| React       | v16.13.1 |

**Comment by oliviertassinari** [comment]
Do you have a live reproduction?

**Comment by rajzik** [comment]
@oliviertassinari 

Now I have
https://codesandbox.io/s/material-ui-pickers-playground-forked-z68eu?file=/App.js
but I don't know why is it needed. I have proposed a fix that does work.

**Comment by oliviertassinari** [comment]
I don't understand anything from the message you are communicating. Could you follow the issue template? What's the issue? What's the solution?

**Comment by rajzik** [comment]
@oliviertassinari

I am not really sure what was the issue. I have opened issue with the proposed fix right on the line of code where the issue is.

I have opened PR with the fix and failing test, feel free to close is or approve it. I just wanted to help.

**Comment by oliviertassinari** [comment]
@rajzik Awesome, thanks for the pull request, it's a lot clearer now. The `getThemeProps()` helper is not used correctly. The `props` option should be cloned before provided. This is wrong:

https://github.com/mui-org/material-ui-pickers/blob/91dcbaffba239f981613801c6d6294bdcee1c6ca/lib/src/_shared/withDefaultProps.tsx#L8-L9

**Comment by rajzik** [comment]
@oliviertassinari Sure no problem.

**Comment by oliviertassinari** [comment]
Duplicate with https://github.com/mui-org/material-ui/issues/23675
