### ISSUE TITLE
Property 'getDaysInMonth' is missing in type 'DateFnsUtils' but required in type 'IUtils<unknown>

### ISSUE THREAD

**Issue by TrejGun** [mui-org/material-ui-pickers#2094]
The TypeScript error happens with alpha10 & alpha12. I have date-fns 2.15.0 installed. 
The problem exist because author forgot to publish version 2.9.0 of @date-io/date-fns.
#https://github.com/dmtrKovalenko/date-io/issues/446

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

TS2322: Type 'typeof DateFnsUtils' is not assignable to type 'new (...args: any) => MuiPickersAdapter<unknown>'.   Property 'getDaysInMonth' is missing in type 'DateFnsUtils' but required in type 'IUtils<unknown>'.

## Expected Behavior 🤔

No TS error.

## Steps to Reproduce 🕹

https://codesandbox.io/s/mui-datetimepicker-dateadapter-typescript-error-forked-6wqm0?file=/index.tsx

The code that produces the error is below:
...
`<MuiPickersProvider dateAdapter={DateFnsUtils}>
</MuiPickersProvider>`
...
## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v4.0.0-alpha.12  |
| React       |16.13.1|
| TypeScript  |4.0.2|

**Comment by TrejGun** [comment]
while we are still waiting for a fix, here is a fast workaround:

```ts
import DateFnsUtils from "@material-ui/pickers/adapter/date-fns";

declare module "@material-ui/pickers/adapter/date-fns" {
  export default class DateFnsUtils {
    getDaysInMonth(value: Date): number;
  }
}
```

**Comment by AlexArendsen** [comment]
Getting this error as well, with a slightly different message. Including it here in case to get more search hits.

```
ERROR in [at-loader] ./node_modules/@date-io/date-fns/build/date-fns-utils.d.ts:4:22
    TS2420: Class 'DateFnsUtils' incorrectly implements interface 'IUtils<Date>'.
  Property 'getDaysInMonth' is missing in type 'DateFnsUtils' but required in type 'IUtils<Date>'.
```

**Comment by AlexArendsen** [comment]
@TrejGun I found out what was causing this for me-- according to the [official site](https://material-ui-pickers.dev/getting-started/installation) these pickers only work with `v1.x` of `date-io/date-fns`, etc.

After uninstalling date-io (which is now at 2.x) and reinstalling `@date-io/date-fns@1.x` I was good to go.

**Comment by oliviertassinari** [comment]
@AlexArendsen The issue is for v4.0.0-alpha, while your workaround can work with v3, it doesn't solve the issue with the latest version.

**Comment by TrejGun** [comment]
resolved
