### ISSUE TITLE
Allow setting the "variant" property on the TextField of the pickers

### ISSUE THREAD

**Issue by croraf** [mui-org/material-ui-pickers#2095]
- [X ] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

`KeyboardDatePicker` (and I think other pickers also) in v3 swallows the `variant` property that I want to pass to the underlying `TextField` component.

That is `KeyboardDatePicker` defines its own `variant` while the underlying `TextField` also has a `variant` property of its own that is worth customizing.

**Comment by dmtrKovalenko** [comment]
For v3 use `inputFormat`. It is documented. 

For v4 not relevant.

**Comment by croraf** [comment]
@dmtrKovalenko I was checking this https://material-ui-pickers.dev/api/KeyboardDatePicker 
I don't see where is `inputFormat` documented?

**Comment by croraf** [comment]
Oh `inputVariant` now I see.

**Comment by dmtrKovalenko** [comment]
Sorry `inputVariant` -- Pass material-ui text field variant down, bypass internal variant prop
