### ISSUE TITLE
Document Timezone tuning in date and time pickers

### ISSUE THREAD

**Issue by FunMiles** [mui-org/material-ui-pickers#2098]
I've searched the docs and examples over and over again and I have not found any way to specify in which time-zone the pickers are working. There's plenty of examples for localization, but no discussion as to how to change the time-zone.

I am working on an app for people who travel. The time-zone of schedules need to be localized to where events happen. I do know the city and time zone in which each event happens. I store all the times in a database in UTC but need to have the local time of Paris to be displayed if an event is taking place in Paris, even if the user is currently in New York or anywhere else in the world.
How can this be accomplished? Can we have some examples, or better yet, a documentation of Timezone treatment?

**Comment by ericsantanna** [comment]
I have a similar requirement:
![image](https://user-images.githubusercontent.com/2364103/93401363-4f69eb80-f882-11ea-8aca-2f59405f9cf0.png)

See how the field "Date/Time" is showing "+02:00", I needed it to match the timezone selected in "TimeZone" field.
It is obviously using my local timezone (+02:00), and as I am using native Date and date-fns, there is nothing I can do to force the timezone.

I solved this problem by replacing date-fns for luxon, as luxon supports different timezones.
Native date and date-fns does not support different timezones, it is always set to the timezone set in browser.

However it would be nice to have a way to set timezones on the date and time pickers, even when using date-fns.
If this option is available I could not find it on the docs.

**Comment by FunMiles** [comment]
@ericsantanna Thanks for the comment. Do you have an example on how you set for a single Date/Time picker the timezone?

Edit: I figured it. In addition to setting `utils={LuxonUtils}`, passing a Luxon `DateTime` to initialize the time picker's value sets the time zone...

**Comment by ericsantanna** [comment]
@FunMiles In case you want to use timeZones with date-fns, I have just made this work by overriding DateFnsUtils and creating my own MuiPickersUtilsProvider:

yarn add date-fns-tz

**DateFnsTzUtils.js**
```
import { format } from 'date-fns-tz'
import DateFnsUtils from "@date-io/date-fns";

export default class DateFnsTzUtils extends DateFnsUtils {
    constructor(props) {
        super();
        this.timeZone = props.timeZone;
    }
    format(date, formatString) {
        return format(date, formatString, {
            timeZone: this.timeZone,
            locale: this.locale
        });
    }
}
```

**MuiPickersTzUtilsProvider.jsx**
```
import * as React from 'react';
import * as PropTypes from 'prop-types';
import {MuiPickersContext} from "@material-ui/pickers";

export const MuiPickersTzUtilsProvider = (props) => {
    const { children, utils, dateFormats, dateLibInstance, locale, timeZone } = props;
    const utilsContext = React.useMemo(
        () => new utils({ locale, timeZone, formats: dateFormats, instance: dateLibInstance }),
        [utils, locale, timeZone, dateFormats, dateLibInstance]
    );
    return <MuiPickersContext.Provider value={utilsContext} children={children} />;
};

MuiPickersTzUtilsProvider.propTypes = {
    utils: PropTypes.func.isRequired,
    locale: PropTypes.oneOfType([PropTypes.object, PropTypes.string]),
    timeZone: PropTypes.string,
    children: PropTypes.oneOfType([
        PropTypes.element.isRequired,
        PropTypes.arrayOf(PropTypes.element.isRequired),
    ]).isRequired,
};

export default MuiPickersTzUtilsProvider;
```
**Example of usage:**
```
import React from 'react';
import {KeyboardDateTimePicker,} from '@material-ui/pickers';

import PropTypes from "prop-types";
import DateFnsTzUtils from "./DateFnsTzUtils";
import MuiPickersTzUtilsProvider from "./MuiPickersTzUtilsProvider";

function DateTimeField(props) {
    return (
    <MuiPickersTzUtilsProvider utils={DateFnsTzUtils} timeZone={props.timeZone}>
        <KeyboardDateTimePicker
            variant="inline"
            inputVariant="outlined"
            label="Date/Time"
            autoOk
            {...props}
        />
    </MuiPickersTzUtilsProvider>
    );
}

DateTimeField.propTypes = {
    value: PropTypes.instanceOf(Date).isRequired,
    onChange: PropTypes.func.isRequired,
    format: PropTypes.string,
    timeZone: PropTypes.string,
};

export default DateTimeField;
```

**Comment by FunMiles** [comment]
@ericsantanna Thanks again. Right now, I am satisfied with what luxon offers. I've been able to use it without too much difficulty using the simple setting I mentioned. If I run into trouble, I'll come back here and try your code. I think your code may have the advantage that it looks like it works without setting a default time, but in my app, I provide a default time to speed up entry.

**Comment by redgumnfp** [comment]
Hey,

Stumbled upon this post and it helped a lot.

I got it all working with Luxon in the end, via a prop. 

See my workings below - may help someone, somewhere...

It essentially overrides a few existing functions with the timezone bugs ironed out for Luxon.

```
import LuxonUtils from '@date-io/luxon';
import { DateTime } from 'luxon';

class UTCUtils extends LuxonUtils {
  constructor({ locale }) {
    super();
    this.zone = locale;
  }

  format(date, format) {
    return date.setZone(this.zone)
      .toFormat(format);
  }

  parse(value, formatString) {
    if (value === '') {
      return null;
    }

    return DateTime.fromFormat(value, formatString, { zone: this.zone });
  }

  date(value) {
    if (typeof value === 'undefined') {
      return DateTime.local()
        .setZone(this.zone);
    }

    if (value === null) {
      return null;
    }

    if (typeof value === 'string') {
      return DateTime.fromJSDate(new Date(value), { zone: this.zone });
    }

    if (value instanceof DateTime) {
      return value.setZone(this.zone);
    }

    return DateTime.fromJSDate(value, { zone: this.zone });
  }
}

export default UTCUtils;


```

You'd then pass it in as below:

`
<MuiPickersUtilsProvider utils={UTCUtils} locale="utc">
`

Tested it briefly with keyboard entry, year/month/date picker views - appears to work... but the constructor's a fudge using the locale prop.
