### ISSUE TITLE
defaultHighlight was removed

### ISSUE THREAD

**Issue by WesleyKapow** [mui-org/material-ui-pickers#2099]
Looks like `defaultHighlight` was removed in https://github.com/mui-org/material-ui-pickers/commit/b87e67412a1943eea1447222ff0daf645bfb3e15

1. I think I need this prop. I want to open a date picker up and have a certain date in focus and highlighted (similar to today highlighting).
2. At the very least, please update release docs / change logs to reflect this removal (I had to chase down what happened to it).

NOTE: My use case is for an itinerary app. Users setup a single day at a time and I'd like to default highlight the day the user is currently on. So if the trip is from 9/3/2021 to 9/9/2021 and the user is currently working on 9/4, I'd like to set `minDate=9/3`, `maxDate=9/9` and `defaultHighlight=9/4`. The user could select a different day which would move the entry to the other day.

**Comment by oliviertassinari** [comment]
Should be covered by #1980

**Comment by WesleyKapow** [comment]
@oliviertassinari I think docs should still be updated to reflect that `defaultHighlighted` was removed. Right now, scanning changes gives no indication of this.

**Comment by oliviertassinari** [comment]
@wes-r Any idea where it should be documented? In the upgrade guide? To be honest, there are so many changes coming, we will encourage developers to rewrite.

**Comment by WesleyKapow** [comment]
I think it was removed in alpha-8, so is it possible to modify the changelog here: https://github.com/mui-org/material-ui-pickers/releases/tag/v4.0.0-alpha.8 ?

**Comment by dmtrKovalenko** [comment]
It doesn't actually makes a lot of sense. You probably are looking for `defaultCalendarMonth`? I have added it and it should be available in the next release (already after migration)

**Comment by WesleyKapow** [comment]
`defaultCalendarMonth` will definitely help but ideally I'd be able to set which day gets highlighted. I want the current day the user is working on to be highlighted as if it were "today":

<img width="359" alt="Screen Shot 2020-09-04 at 9 10 53 AM" src="https://user-images.githubusercontent.com/1568246/92242948-96bda880-ee8e-11ea-9176-203b98f78ff9.png">

**Comment by dmtrKovalenko** [comment]
I don't understand. Why you cannot just pass the `value`?

**Comment by WesleyKapow** [comment]
`value` is `null`, not yet set. I don't want to have a date value selected, I want a date value highlighted like it does for "today".

Looks like a combo of `defaultCalendarMonth`, `renderDay` and day's `today` property may yield me what I want.
