### ISSUE TITLE
Document how to change Toolbar text

### ISSUE THREAD

**Issue by Floriferous** [mui-org/material-ui-pickers#2100]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I'm really sorry, there's got to be a simple prop that lets you do this, or other people who have asked, but I just can't find how to change the way the Text in the toolbar is displayed. 

Here's a screenshot of what I'd like to modify:

<img width="293" alt="Screenshot 2020-09-04 at 17 48 25" src="https://user-images.githubusercontent.com/10428082/92258503-3c950580-eed7-11ea-8c6c-54487e13fda9.png">

The thing is, in all the demos, it's never customised, so I'm not even sure if it's possible?

## Expected Behavior

Allow passing a format string like `DD/MM, YYYY` to the `DatePicker` to change the formatting of that date. It's not the same as the input value either, so I don't know where it comes from. Or simply pass a function.

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4 |
| @material-ui/pickers | v3  |

**Comment by tobikl-u** [comment]
https://github.com/mui-org/material-ui-pickers/issues/1113#issuecomment-504658115
