### ISSUE TITLE
Different behavior between v3 and v4 on triggering onChange callback

### ISSUE THREAD

**Issue by kelvien** [mui-org/material-ui-pickers#2101]
On version 3.2.10,  the `onChange` callback is not called when we change views (i.e: from year to month). While the `onChange` callback is called on every view change at version 4 alpha.12
This report is based on my observation comparing it with version 4. Since version 4 is not finalized, I am all ears to know what behavior should we expect

## Current Behavior 😯
In v3, onChange callback is not called on changing views

## Expected Behavior 🤔
I would think that the onChange happens for every view changes in v3

## Steps to Reproduce 🕹
Simply log a message on the `onChange` callback and expect the message to be logged on changing views in v4, but not v3

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |

**Comment by oliviertassinari** [comment]
Thanks for reporting this change of behavior. I think that it should depend on the props provided to the component. It's something we need to double check before making a stable release.

**Comment by oliviertassinari** [comment]
Closing for https://github.com/mui-org/material-ui/issues/24178
