### ISSUE TITLE
DatePicker renderInput is called twice

### ISSUE THREAD

**Issue by yutimo** [mui-org/material-ui-pickers#2103]
Hi

Looks like renderInput handler is called twice, but with different props in arguments? Is it expected behavior? It causes some problems in our client code

"@material-ui/pickers": "^4.0.0-alpha.12"

here is demo: https://codesandbox.io/s/sharp-smoke-txxmr

<img src="https://user-images.githubusercontent.com/34317215/92564214-7c663f00-f281-11ea-936f-760d21d1c062.png" width="400"/>

**Comment by oliviertassinari** [comment]
Which problem does it create for you? The double rendering shouldn't be an issue on its own.

**Comment by zzangs33** [comment]
Hello, can I get some explanation for this issue? I can't understand why double rendering shouldn't be an issue.

**Comment by oliviertassinari** [comment]
The double rendering might be coming from the need of the component to resolve the desktop vs mobile mode.
