### ISSUE TITLE
v4.0.0-alpha.12 not working with typescript v4

### ISSUE THREAD

**Issue by ShadabFaiz** [mui-org/material-ui-pickers#2104]
This is my `dateRange` component.
``` typescript
import TextField from "@material-ui/core/TextField";
import { DateRange, DateRangeDelimiter, DateRangePicker } from "@material-ui/pickers";
import React, { useState } from "react";

export interface IDateStart {
	text: string;
	preFilledValue?: Date;
}

export default function BasicDateRangePicker({
	from,
	to,
	onChange,
}: {
	from: IDateStart;
	to: IDateStart;
	onChange: (from: Date | null, to: Date | null) => void;
}) {
	const [selectedDate, handleDateChange] = React.useState<DateRange<Date>>([
		from.preFilledValue || null,
		to.preFilledValue || null,
	]);

	React.useEffect(() => {
		onChange(selectedDate[0], selectedDate[1]);
	}, [selectedDate]);
	const [open, setOpen] = React.useState(false);

	return (
		<DateRangePicker
			onOpen={() => setOpen(true)}
			disableCloseOnSelect={true}
			startText={from.text}
			endText={to.text}
			value={selectedDate as [Date, Date]}
			inputFormat="dd/MM/yyyy"
			onChange={handleDateChange}
			renderInput={(startProps, endProps) => (
				<>
					<TextField {...startProps} />
					<DateRangeDelimiter> to </DateRangeDelimiter>
					<TextField {...endProps} />
				</>
			)}
		/>
	);
}
```
It is working properly with typescript version 3.7.0, but when I upgraded typescript version to v4.0.2, I'm getting this error:
![Error](https://user-images.githubusercontent.com/8160121/92570036-feb12c00-f29e-11ea-8cab-eafa025f7884.png)

## Current Behavior 😯
Bumping typescript to version 4 break the app.

## Expected Behavior 🤔
Bumping typescript version to v4 should work properly.

## NOTE
This project was created using create-react-app.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | ^4.11.0  |
| @material-ui/pickers | ^4.0.0-alpha.12  |
| React       |    ^16.13.1     |
| TypeScript  |    v4.0.2     |

**Comment by oliviertassinari** [comment]
Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/material-ui-date-picker-ppt05) _may_ be a good starting point. Thank you!
