### ISSUE TITLE
Material time picker size issue 

### ISSUE THREAD

**Issue by srikanthvarada8888** [mui-org/material-ui-pickers#2105]
Hi,

Is there any way that we can reduce size of time picker overlay. We tried it by using css theme provider. Couldn't make it up. Any help on this please

**Comment by srikanthvarada8888** [comment]
can someone  please help here ASAP!

**Comment by oliviertassinari** [comment]
Please submit support requests and questions to StackOverflow using the tag [material-ui](http://stackoverflow.com/tags/material-ui). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/callemall/material-ui/blob/master/CONTRIBUTING.md).
