### ISSUE TITLE
DateRangePicker closes on first click when in Popover

### ISSUE THREAD

**Issue by BjoernRave** [mui-org/material-ui-pickers#2106]
When putting the Daterangepicker inside the Popover Component from Material-UI and trying to go back a month, the picker automatically closes on the first click no matter where.

**Comment by oliviertassinari** [comment]
@BjoernRave We should have solved this issue when used with core v5-alpha.

Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/material-ui-date-picker-ppt05) _may_ be a good starting point. Thank you!

**Comment by BjoernRave** [comment]
Hey @oliviertassinari  sure, here is the reproduction: https://codesandbox.io/s/agitated-vaughan-eimc8?file=/src/App.jsx

What do you exactly mean by:

> We should have solved this issue when used with core v5-alpha.

That the fix for this problem will only be usable for v5 ?

**Comment by oliviertassinari** [comment]
@BjoernRave Thanks for the reproduction but it's not a valid combination of dependencies. The fix is only available with v5 alpha.

**Comment by BjoernRave** [comment]
@oliviertassinari what, how is it not a valid combination of dependencies? Because it used `alpha12` of the pickers library? It was already set like that when using your template and it's the same behavior when using `alpha10` which is supposed to work with v4. 

Okay so that's great to hear that it's fixed in v5.

Can you maybe point me to the code where it's fixed so I can fix it with `patch-package` sind v5 will still take some time?

**Comment by oliviertassinari** [comment]
Thanks for mentioning it, the initial template I have linked needs to be updated.

KO
```json
dependencies": {
    "@material-ui/core": "latest",
    "@material-ui/pickers": "next",
```

OK
```json
dependencies": {
    "@material-ui/core": "next",
    "@material-ui/pickers": "next",
```

**Comment by oliviertassinari** [comment]
Codesandbox template updated, it will avoid future confusion like this.

**Comment by oliviertassinari** [comment]
> Can you maybe point me to the code where it's fixed so I can fix it with patch-package sind v5 will still take some time?

Search for click away portal support.

**Comment by BjoernRave** [comment]
@oliviertassinari okay, thanks for the hint :)
