### ISSUE TITLE
hh:mm:ss does not change

### ISSUE THREAD

**Issue by viniciusbitt** [mui-org/material-ui-pickers#2109]
Using the moment utility I cannot change the hours, minutes and seconds.

- [x] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

I try to change the hours, minutes and seconds and it always goes on 00:00:00
https://codesandbox.io/s/rough-rain-nesho?file=/src/index.tsx

Happens in latest alpha version: https://codesandbox.io/s/friendly-knuth-i4jsy?file=/src/App.js

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v3.2.10  |
| React       |   v16.13.1   |

**Comment by eglavin** [comment]
Check your use of format & inputFormat
```
Old: format="DD/MM/yyyy HH:mm:ss"

New: format="DD/MM/YYYY HH:mm:ss"
```
