### ISSUE TITLE
Attempted import error: 'DateRangeDelimiter' is not exported from '@material-ui/pickers'.

### ISSUE THREAD

**Issue by Akzhan1296** [mui-org/material-ui-pickers#2114]
Good morning! I have problem with DateRangeDelimiter. When I have already unstalled  @material-ui/pickers latest version. 
And can not use DateRangeDelimiter. 
Message is Attempted import error: 'DateRangeDelimiter' is not exported from '@material-ui/pickers'.

**Comment by oliviertassinari** [comment]
This is only available in v4 alpha, not v3
