### ISSUE TITLE
When will be available v4 for date pickers ? not a alpha version

### ISSUE THREAD

**Issue by Akzhan1296** [mui-org/material-ui-pickers#2115]
When will be available v4 for date pickers ? not a alpha version

**Comment by oliviertassinari** [comment]
As long as it takes to handle the breaking changes identified. Likely between 6 and 12 months. Autocomplete would have been 16 months in unstable state for instance. It didn't stop it to gain massive adoption.

Also note that the next alpha release will be under v5-alpha
