### ISSUE TITLE
Custom TextField from KeyboardDatePicker loses focus when typing in date

### ISSUE THREAD

**Issue by SecretUnicorn** [mui-org/material-ui-pickers#2116]
- [x] The issue is present in the latest release. (Non future)
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I tried to overwrite the TextField component so I could set the fullWidth prop and a Clear-Button. Here's how I did it

```jsx
TextFieldComponent={props => 
<TextField 
    {...props}
    margin={"none"}
    size="small"
    fullWidth
    InputProps= {{
                        ...props.InputProps,
                        endAdornment: 
                          <InputAdornment position="end">
                            <IconButton onClick={() => setState({...state, dateTime: null})}>
                              <FontAwesomeIcon icon={faTrashAlt}/>
                            </IconButton>
                          </InputAdornment>
                      }}
/>}
```
Clearing works fine but when I try to enter a date via the keyboard the TextField loses focus after every typed number.

## Expected Behavior 🐛

The TextField does not lose focus on typing like it does with the default TextField provieded.

## Steps to Reproduce 🕹

https://codesandbox.io/s/angry-mirzakhani-n0cs0?fontsize=14&hidenavigation=1&theme=dark

Steps:

1. Add the TextFieldComponent Prop
2. Customize the TextField (I checked with and without the Adornments. Didnt effect the bug)
3. Clear the field
4. Try to type something
5. It loses focus

## Context 🔦

Add a clear button and the fullwidth prop to the base InputField

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v3.2.10 |
| React       |  v16   |
| Browser     |   Firefox  |
| TypeScript  |    x    |
| @date.io/date-fns        |    1.3.13     |

**Comment by SecretUnicorn** [comment]
In addition to that the picker moves to the top left when you try to close it.

**Comment by oliviertassinari** [comment]
Could you provide a reproduction with v4.0.0-alpha? We do no longer support v3.

**Comment by SecretUnicorn** [comment]
i tried using the alpha but my cpu usage goes up to 100% when I open the picker. 

The console is spammed with
`Unstable_Trapfocus:77 too much recursion`

anything I can do ?

**Comment by oliviertassinari** [comment]
@SecretUnicorn The component needs @material-ui/core@v5.0.0-alpha.

**Comment by bryansamuel1** [comment]
did anyone get a fix for this? I am encountering the same problem

**Comment by ntbosscher** [comment]
I managed to get this fixed by passing a constant function rather than an inline one. Hope this helps someone :) 

```jsx
// works
const MyTextField = (props) => <TextField {...props} variant="outlined" />;
function Component() {
     return <KeyboardDateTimePicker TextFieldComponent={MyTextField} />;
}

// doesn't
function Component() {
    return <KeyboardDateTimePicker TextFieldComponent={props => <TextField {...props} variant="outlined" />} />
}
```

**Comment by oliviertassinari** [comment]
@ntbosscher Thanks for the update. This is definitely expected. I'm closing as the renderInput API is free from this problem, in v5
