### ISSUE TITLE
KeyboardDatepicker moment locale formatting "L" breaks when typing

### ISSUE THREAD

**Issue by gummybuns** [mui-org/material-ui-pickers#2120]
When using the `KeyboardDatepicker` with `MomentUtils` does not allow a user to type in a date manually when the `format` prop is `"L"`, or any of moment's Locale Formats.

Using the inline picker still works, but typing or deleting leads to an invalid moment object which the input field does not know how to handle.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Typing into a `KeyboardDatepiker` using `moment` + `format="L"` does not allow a user to type in a date using the input.

## Expected Behavior 🤔
The input should allow a user to type in a date using the keyboard.

## Steps to Reproduce 🕹
* [CodeSandbox Link](https://codesandbox.io/s/new-brook-258eg?file=/src/App.tsx)

![Kapture 2020-09-21 at 16 08 40](https://user-images.githubusercontent.com/47437711/93830459-28663d80-fc25-11ea-83cc-a8ff8c8e3039.gif)

## Context 🔦
We are trying to use the `KeyboardDatepicker` to automatically format to the user's locale

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | ^v4.6.0 |
| @material-ui/pickers | ^v3.2.10  |
| moment | ^2.27.0 |

**Comment by lucapollani** [comment]
I think it's the same issue reported here #1410 and it seems it was not really solved. 

Since I had this problem too, my solution has been to retrieve the full corresponding format of "L" accessing localeData as described here: https://momentjs.com/docs/#/i18n/locale-data/

So for example:
```
moment.localeData('en').longDateFormat("L") // returns the full format of abbreviated date-time formats LT, L, LL and so on

// expected result => "MM/DD/YYYY" => use this as input for format prop of the Picker
```

A further problem of this solution is that if the returned format is for example "M/D/YYYY", the picker will accept only 1 char for month and day which is obviously not correct.

Hope it helps

**Comment by knoefel** [comment]
I ran into the same problem using "Long Localized Date" from date-fns -> `format="P"`. Is there any news/update on this issue?

**Comment by gummybuns** [comment]
cant speak for the project status but for our usecase we really only cared about US / International date formatting, so we just hard-coded the format based on the user's locale and it seems to work decent enough:
```javascript
import getUserLocale from 'get-user-locale';

const US_DATE_FORMAT = 'MM/DD/YYYY';
const INTL_DATE_FORMAT = 'DD/MM/YYYY';

const locale = getUserLocale();
const format = /^en(-US)?$/i.test(locale) ? US_DATE_FORMAT : INTL_DATE_FORMAT;

// something similar if a datetime is needed ...
// use this format for the format prop ...

```

**Comment by knoefel** [comment]
Thanks a lot for letting me know! I used a similar approach by choosing the right format (also hard-coded) for the languages used in the app. But unfortunately i haven't found a way to use an output format like "April 2021" and also be able to type the date via a mask like "__/____".

**Comment by dmtrKovalenko** [comment]
This problem is resolved in v4. Update to material-ui/lab@next or use the alpha version of pickers
