### ISSUE TITLE
DateRangePicker does not auto close with Material-UI v5 alpha 7 and later

### ISSUE THREAD

**Issue by Hybrid-Force** [mui-org/material-ui-pickers#2123]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

After selecting a date range, the picker is not closing automatically.

This problem happens in Material-UI v5 alpha 7 and later versions. It works fine with Material-UI v5 alpha 6 and earlier versions.

## Expected Behavior 🤔

After selecting a date range, the popper should close automatically.

## Steps to Reproduce 🕹

DateRangePicker with Material-UI v5 alpha 6:
https://codesandbox.io/s/hopeful-dirac-muhlp

DateRangePicker with Material-UI v5 alpha 7:
https://codesandbox.io/s/little-cherry-ukzvk

Steps:

1. Open date range picker with material-ui v5 alpha 6
2. Select a date range
3. The picker auto closes
4. Open date range picker with material-ui v5 alpha 7
5. Select a date range
6. The picker does not auto close

## Your Environment 🌎
| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | 5.0.0-alpha.7  |
| @material-ui/pickers | 4.0.0-alpha.12  |
| React       | 16.13.1 |
| Browser     | Chrome 85.0.4183.102 |
| TypeScript  | 4.0.3 |

**Comment by ssypi** [comment]
Happened to me too and also got an another and more significant problem: the end date textfield only changes if changed from clicking the start field, not when clicking the end field.

When clicking the start textfield and choosing the dates, it worked ok except no autoclose, BUT when clicking the end textfield and selecting a date, the end date field did not show the new date. The dates were changed to the correct selected ones and the onChange was triggered with them properly, but the end text field had wrong value in the renderInput call. 

After downgrading to Material-UI v5 alpha 6, the problem suddenly disappeared. (I was on alpha 8)
