### ISSUE TITLE
I can't change the underline color through InputProps

### ISSUE THREAD

**Issue by tarekgabarin** [mui-org/material-ui-pickers#2125]
I can't change the underline color of the input element through `InputProps`. Here is what my code looks like

`                    <KeyboardDatePicker
                        {...props}
                        InputProps={{
                                classes: {
                                    underline: {
                                        borderBottomColor: '#A52A2A'
                                    }
                                }
                            }}    
                        inputRef={inputRef}
                    />`

It says in the documentation to pass any prop you want applied to the input component to `InputProps`. I am doing that but it still doesn't work. can you still use `classes` prop on InputProps? Its not clear in the documentation.

**Comment by oliviertassinari** [comment]
The `classes` prop accepts class names, not style.
