### ISSUE TITLE
Unable to remove outline for MobileDateRangePicker dialog styles

### ISSUE THREAD

**Issue by gopikrishnaA** [mui-org/material-ui-pickers#2127]
Unable to update the styles for outline of the dialog

currently overriding below styles, but not works for me
root: {
 '& .MuiBackdrop-root': {
        backgroundColor: 'transparent'
      },
      '& .MuiDialog-scrollPaper': {
        alignItems: 'start',
        justifyContent: 'start',
        height: 'auto',
        outline: 0
      },
      '& .MuiDialog-paper': {
        margin: theme.spacing(0),
        overflowY: 'hidden',
        outline: 0,
        '&:focus': {
          outline: 0
        },
        '& .MuiDialogContent-root': {
          overflowY: 'hidden',
        }
}

![image](https://user-images.githubusercontent.com/6479573/94366392-90b99100-00f5-11eb-91e2-4f5d649973fb.png)

kindly help on the above issue

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v4.0.0-alpha.12  |
| React       |16.13.1|
| Browser     |Chrome  Version 85.0.4183.121       |
| TypeScript  |  yes   |
| etc.        |         |

**Comment by oliviertassinari** [comment]
Solved with https://github.com/mui-org/material-ui/issues/23532
