### ISSUE TITLE
Support for Material Design filled style

### ISSUE THREAD

**Issue by chris-herring** [mui-org/material-ui-pickers#2129]
Material-UI now supports the changes made to Material Design to display fields using a grey background. e.g.

```jsx
<TextField id="filled-basic" label="Filled" variant="filled" />
```

Will this same change be made to these controls?

**Comment by oliviertassinari** [comment]
@chris-herring I don't understand your question. Could you clarify it? What controls are you referring to?

**Comment by gregStevenard** [comment]
Yes that would be a great feature to have, as it is a bit constraining to not have matching UI. 

@oliviertassinari , I believe @chris-herring  is referring to having the option to set the `variant="filled"` on the input, just like from the doc : [https://material-ui.com/components/text-fields/#filled-adornment-password](https://material-ui.com/components/text-fields/#filled-adornment-password) (password icon would be replaced by the calendar icon ...)

**Comment by oliviertassinari** [comment]
@gregStevenard This is supported in `@material-ui/pickers@4.0.0-alpha.12`. We have changed the API to handle this case, matching the `Autocomplete` :

```tsx
import * as React from "react";
import TextField from "@material-ui/core/TextField";
import { DatePicker } from "@material-ui/pickers";

export default function BasicDatePicker() {
  const [value, setValue] = React.useState<Date | null>(new Date());

  return (
    <DatePicker
      label="Basic example"
      value={value}
      onChange={(newValue) => setValue(newValue)}
      renderInput={(params) => <TextField {...params} variant="filled" />}
    />
  );
}
```

**Comment by gregStevenard** [comment]
@oliviertassinari Amazing! Works like a charm. Nice job on cleaning that `@date-io ` deps too. Merci bien :) !
