### ISSUE TITLE
Calendar Component supports array of dates / range 

### ISSUE THREAD

**Issue by tonyfung99** [mui-org/material-ui-pickers#2132]
Seems currently the calendar component date field only supports a single moment object, which makes the calendar component cannot show multiple selected dates.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Suggest that supports an array of moment objects  / moment-range object in the date props. Then the Calendar highlights all the dates when display.

## Examples 🌈

![image](https://user-images.githubusercontent.com/2355642/95168992-bd039a80-07e4-11eb-9aad-7c8c8db38087.png)

## Motivation 🔦

Would like to use a single set of components to display & pick the date. So that the layout has a standardize material layout to show the date related layout.

**Comment by oliviertassinari** [comment]
Does https://next.material-ui-pickers.dev/demo/daterangepicker cover your use case?
