### ISSUE TITLE
[v4][Regression] Within a form a DatePicker popover is rendered is wrong position

### ISSUE THREAD

**Issue by mak-elena** [mui-org/material-ui-pickers#2138]
I found out that placing  the DatePicker component inside of a form causes appearance  of the popover in a wrong position (always - top, left of window)

In case component placed outside of the form - the position of the popover is correct.

I'm using [react-hook-form](https://github.com/react-hook-form/react-hook-form)

The issues is reproducible since the version 4.0.0.-alpha.9
The version  4.0.0.-alpha.8 works correct.

## Envirionment

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | 4.11.0 |
| @material-ui/pickers | 4.0.0-alpha.12  |
| react-hook-form | 6.9.2  |
| React       |    16.13.1    |
| Browser     |     Chrome    |
| TypeScript  |  3.8.3       |

## Steps to Reproduce

The code sample for reproduction:  
[https://codesandbox.io/s/mui-v4-datetimepicker-with-rhf-forked-fztju?file=/index.tsx](https://codesandbox.io/s/mui-v4-datetimepicker-with-rhf-forked-fztju?file=/index.tsx)

1. under dependencies select the @material Ui/pickers v 4.0.0.-alpha.8
2. restart the app
3. open DatePicker
4. result: Popover is rendered under the input field (correct)
5. Select the version  4.0.0.-alpha.9 or newer
6. restart the the app
7. open DatePicker
8. result: Popover is rendered in the top left position (wrong)

**Comment by PavelSrom** [comment]
I am experiencing the exact same issue

**Comment by oliviertassinari** [comment]
Interesting, I have migrated the codesandbox to v5: https://codesandbox.io/s/mui-v4-datetimepicker-with-rhf-forked-hqiur?file=/index.tsx. The `inputRef` is overriding the one the date picker needs for positioning. You need to fork the ref.

Also, mind that the ref used is wrong. It should be wider than the <input> element: https://github.com/mui-org/material-ui/issues/24149.
