### ISSUE TITLE
Cannot disable transition animation

### ISSUE THREAD

**Issue by FinPlorer** [mui-org/material-ui-pickers#2139]
Hi,
It seems like there is no way to disable animation in Calendar component.
Working on a view with multiples Calendar create massive delay.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Can't disable animation when year change

## Expected Behavior 🤔

Have a prop to disable animation.

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v3.2.10  |

**Comment by oliviertassinari** [comment]
@MatthieuCoelho Did you try with @material-ui/pickers@4.0.0-alpha? We do no longer support v3

**Comment by FinPlorer** [comment]
@oliviertassinari Unfortunately I can't use the alpha

However as a workaround I dismount and remount (using new key on date change) the component to remove the transition.
