### ISSUE TITLE
You should use `import { alpha } from '@material-ui/core/styles'`

### ISSUE THREAD

**Issue by cyberde** [mui-org/material-ui-pickers#2142]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
At the moment of opening any type of date picker

<img width="839" alt="image" src="https://user-images.githubusercontent.com/1424252/96465621-d586a280-1231-11eb-958c-bad3e8724097.png">

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v5.0.0-alpha.13  |
| @material-ui/pickers | v4.0.0-alpha.12 |
| React       |         |
| Browser     |         |
| TypeScript  |         |
| etc.        |         |

**Comment by oliviertassinari** [comment]
This was fixed during the migration to the main repository: https://next.material-ui.com/components/date-picker/.
