### ISSUE TITLE
Provide a working example of a standalone usage of the Calendar component

### ISSUE THREAD

**Issue by yanickrochon** [mui-org/material-ui-pickers#2148]
## Summary 💡

At the time of writing this issue, with version `4.0.0-alpha.12`, there is a [`Calendar`](https://v4-0-0-alpha-12.material-ui-pickers.dev/api/Calendar) component present, so there should be at least a few working standalone examples, without a popup menu.

For example, using the calendar to display events, like an agenda.

## Motivation 🔦

All the components are already there, re-recreating them, or adding new modules seems quite redundant.

**Comment by oliviertassinari** [comment]
@yanickrochon Do you have a specific use case for this component?

**Comment by yanickrochon** [comment]
@oliviertassinari  An example would be to have the Calendar component inside a user-defined popup to display events, like for the Gnome calendar widget :
![image](https://user-images.githubusercontent.com/78461/103299958-c22f4a80-49cb-11eb-9d56-477d89d33458.png)

**Comment by oliviertassinari** [comment]
@yanickrochon We expose a `DayPicker` component  https://next.material-ui.com/components/date-picker/#sub-components. Is it granular enough?

**Comment by yanickrochon** [comment]
If this is implemented in the next release, then it seems fine as far as I can tell. We're on 4.11 at the moment. I ended up implementing an entire custom Calendar component, which also allows me to make it large enough to display custom widget within each day cells.

Perhaps I should propose an Agenda component instead, allowing to have a Google-Calendar-like component with events spanning days, and allowing to switch between a Calendar or a TaskList (or something) view, etc.

**Comment by oliviertassinari** [comment]
> Perhaps I should propose an Agenda component instead, allowing to have a Google-Calendar-like component with events spanning days, and allowing to switch between a Calendar or a TaskList (or something) view, etc.

@yanickrochon This is planned under https://github.com/mui-org/material-ui/issues/22473.
