### ISSUE TITLE
Tree shaking after v4.0.0-alpha.6

### ISSUE THREAD

**Issue by eseQ** [mui-org/material-ui-pickers#2149]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
In v4.0.0-alpha.6 `lib/copy.js` had been removed and now `esm` folder doesn\`t exist.

## Expected Behavior 🤔
Like other `@material-ui` packages I want use tree shaking with babel-import.
```javascript
[
  'import',
  {
    libraryName            : '@material-ui/pickers',
    libraryDirectory       : 'esm',
    camel2DashComponentName: false,
  },
   'pickers',
],
```
But now I got `Can't resolve '@material-ui/pickers/esm/DatePicker'` error.

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v4.0.0-alpha.12  |
| React       | v16.13.1 |

**Comment by oliviertassinari** [comment]
@eseQ This issue was solved in v5 by moving the component to the main repository, sharing the same code infrastructure.

**Comment by eseQ** [comment]
@oliviertassinari ok, big thanks.
