### ISSUE TITLE
Documentation website is broken

### ISSUE THREAD

**Issue by vasadhananjay** [mui-org/material-ui-pickers#2154]
When I try to navigate from [https://material-ui.com/getting-started/installation/](https://material-ui.com/getting-started/installation/ ) to the Components page, it doesn't navigate there. It appears that the necessary javascript file is missing. 

![image](https://user-images.githubusercontent.com/10535188/98294161-551bad80-1f64-11eb-8b8a-b393dc5a2678.png)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

**Comment by oliviertassinari** [comment]
Wrong repository
