### ISSUE TITLE
Min/max time restrictions

### ISSUE THREAD

**Issue by this-self** [mui-org/material-ui-pickers#2156]
As I understand, `minDate` and `maxDate` means to disable only some specific dates range, but not a time.
Is there a way to disable exactly some time and make it impossible to select through analog clock selector?

Thanks

**Version:** Material UI Pickers 3.2.9

**Comment by rmkane** [comment]
Amusing enough, the [docs](https://material-ui-pickers.dev/api/TimePicker) (v3.2.9) list `maxDateMessage` and `minDateMessage` as props, but do not have a `minTime` nor `maxTime` prop.

It looks like a min/max prop has been added to the code in `v4.0.0-alpha.6`.

See: https://github.com/mui-org/material-ui-pickers/blob/v4.0.0-alpha.6/lib/src/TimePicker/TimePicker.tsx#L31

**Comment by this-self** [comment]
> Amusing enough, the [docs](https://material-ui-pickers.dev/api/TimePicker) (v3.2.9) list `maxDateMessage` and `minDateMessage` as props, but do not have a `minTime` nor `maxTime` prop.

@oliviertassinari I meant exactly date time range selector.
It has mentioned props. Please refer here: https://material-ui-pickers.dev/api/DateTimePicker

**Comment by rmkane** [comment]
> I meant exactly date time range selector.

Same difference, the props were added in version 4.

See: https://github.com/mui-org/material-ui-pickers/blob/v4.0.0-alpha.6/lib/src/DateTimePicker/DateTimePicker.tsx#L41
