### ISSUE TITLE
The end of @material-ui/pickers 🙈, long live @mui/x-date-pickers

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#2157]
And that's not the time to cry! ✌️❤️ After a long year of work on v4, pickers are finally taking an official place at MUI. It's meant to move under [MUI X](https://mui.com/x/react-date-pickers/). So [mui/material-ui-pickers](https://github.com/mui/material-ui-pickers) is no longer supported. 

We have closed the docs and moved all the work which will include the new era of date & time picking! In MUI X, this project will live as a generic date picker library, with a deep Material UI integration, among others.

### Contributors

Thank you for being here for the 3 years of this project's existence and the giant thanks to our awesome contributors! And also a special shout-out to the collaborators and maintainers of pickers:

- @dmtrKovalenko - author and main maintainer 
- @TrySound - supercharged our build process 
- @cherniavskii - helped a lot on the project start
- @alitaheri - improved our localization and was an author of different calendar systems support!
- @sakulstra - made a lot of contributions 
- @rosskevin - helped to rewrite the project in typescript 
- @LastDreamer - made several great features 

They will be thankful if you will follow their great work on Twitter 🦊. 

### What's next?

Thank you, be safe, and will see you at https://mui.com/x/react-date-pickers/getting-started/. You can follow this migration guide: https://mui.com/material-ui/guides/pickers-migration/ to move from @material-ui/pickers v3.

### Version history

Based on the version of Material UI, find the following corresponding date picker:

| Material UI | git repository                                             | Docs                                                  | npm package | Last release |
|------------------------|------------------------------------------------------|-------------------------------------------------------|---------|----|
| ^0.15.0                | https://github.com/mui/material-ui/tree/v0.x         | https://v0.mui.com/#/components/date-picker           | [material-ui](https://www.npmjs.com/package/material-ui) | v0.20.0 |
| ^3.0.0                 | https://github.com/mui/material-ui-pickers/tree/v2.2.4 | https://material-ui-pickers-v2.dmtr-kovalenko.vercel.app/ | [material-ui-pickers](https://www.npmjs.com/package/material-ui-pickers) | v2.2.4 |
| ^4.0.0                 | https://github.com/mui/material-ui-pickers/tree/v3-x |  | [@material-ui/pickers](https://www.npmjs.com/package/@material-ui/pickers) | v3.3.10 |
| ^5.0.0-alpha.5         | https://github.com/mui/material-ui-pickers/tree/next | https://material-ui-pickers-git-next-mui-org.vercel.app/ | [@material-ui/pickers](https://www.npmjs.com/package/@material-ui/pickers) | v4.0.0-alpha.12 |
| ^5.0.0                 | https://github.com/mui/material-ui/tree/master       | https://v5-0-6.mui.com/components/pickers/            | [@mui/lab](https://www.npmjs.com/package/@mui/lab) | v5.0.0-alpha.1 |
| ^5.4.1                 | https://github.com/mui/mui-x                         | https://v5.mui.com/x/react-date-pickers/getting-started/ | [@mui/x-date-pickers](https://www.npmjs.com/package/@mui/x-date-pickers) | v5.0.20 |
| ^5.4.1 | https://github.com/mui/mui-x | https://v6.mui.com/x/react-date-pickers/ | [@mui/x-date-pickers](https://www.npmjs.com/package/@mui/x-date-pickers) | ^6.0.0 (LTS) |
| ^5.15.14 | https://github.com/mui/mui-x | https://mui.com/x/react-date-pickers/ | [@mui/x-date-pickers](https://www.npmjs.com/package/@mui/x-date-pickers) | ^7.0.0 (active) |

**Comment by simplecommerce** [comment]
@dmtrKovalenko Hi, great work on this library, I had a question, will the v3 and the docs still be available on this repo even if Material-UI v5 is stable and out?

I just want to know in order to prepare if I have to force and make a change in our current project.

Thanks for the great work again on this library!

**Comment by dmtrKovalenko** [comment]
@simplecommerce It will be available under the same domain name. Just I am going to add a persistent banner about the project migration

**Comment by neolivz** [comment]
What happened to `MuiPickersUtilsProvider`?

**Comment by oliviertassinari** [comment]
> What happened to MuiPickersUtilsProvider?

@neolivz https://mui.com/material-ui/guides/pickers-migration/#muipickersutilsprovider

**Comment by j209** [comment]
What about suporting jalaali or hijri calandar system in material-ui v5 ?

**Comment by oliviertassinari** [comment]
@j209 We are using date-io, so it should still be supported. Would you like to add a demo for it?

**Comment by rajzik** [comment]
@dmtrKovalenko Maybe archive this repository as it is no longer active?

**Comment by dmtrKovalenko** [comment]
@rajzik once all the issues will be moved and the core documentation demo for pickers will be fixed  – I will definitely archive this repo :)

**Comment by j209** [comment]
> @j209 We are using date-io, so it should still be supported. Would you like to add a demo for it?

It would be great if there is a demo for hijri and jalali calendar support in material ui v5+.
[material-ui-next date picker demo](https://next.material-ui.com/components/date-picker/)

**Comment by MartinDevillers** [comment]
Great job on getting adopted in MUI V5 and on building this in general. As a frontend developer I've been working/dealing/struggling with date pickers for almost two decades now, so I know how much effort it takes to create a _usable_ date picker. Moreover, even in these modern days I see major players [like Microsoft Windows 10 missing the boat completely](https://www.linkedin.com/posts/devillers_meanwhile-at-the-white-house-secretary-activity-6368104290812338176-TPsj). So kudos on getting this one right.

Looking forward to migrating to V5. Cheers 👏

**Comment by dmtrKovalenko** [comment]
@MartinDevillers thank you for your warm words. Unfortunately I cannot do this for now cause material-ui.com docs site is completely broken and buggy for pickers examples. 

cc @oliviertassinari

**Comment by oliviertassinari** [comment]
@dmtrKovalenko Are you referring to this issue https://github.com/mui/material-ui/issues/23899?

**Comment by dmtrKovalenko** [comment]
Exactly

**Comment by gregorysl** [comment]
Since material-ui v4.11.2 has support for react v17, will this package receive update to support it as well?

**Comment by karlvonbonin** [comment]
Thank you for your support! Just browsed you site again and wondered how Material-Ui is offerding alsmost the same picker.. haha.. now i know.. Clever to do this with their premium account.. Sad fo us devs ;) 

Thanks and stay healthy!

**Comment by magnusmartin85** [comment]
Thank you for your work :) Is there any information when material-ui v5 stable release will be released? Any estimations? Take care!

**Comment by boonya** [comment]
Hello. Is there any information why does https://material-ui-pickers.dev/ not work?

```txt
$ curl -vk https://material-ui-pickers.dev/
*   Trying ...
* Connected to material-ui-pickers.dev (...) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to material-ui-pickers.dev:443
* Closing connection 0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to material-ui-pickers.dev:443
```

**Comment by dmtrKovalenko** [comment]
I think I stopped paying for the domain. Do somebody still using it 😱 ?

**Comment by dmtrKovalenko** [comment]
@oliviertassinari Can you please check if you still have this project's documentation deployment in material-ui vercel account? If yes, could you please share its link here?

**Comment by simplecommerce** [comment]
we still use it also but only until we can upgrade

**Comment by boonya** [comment]
> I think I stopped paying for the domain. Do somebody still using it 😱 ?

We do. It's not that easy to quickly migrate big project with its bureaucracy and so on.
I would suggest to use Github Pages as a hosting for such documentation. If you want I can help. [I have an experiance.](https://github.com/boonya/backendless-apollo-client/blob/main/.github/workflows/storybook-publish.yml#L34)

**Comment by MartinDevillers** [comment]
> I think I stopped paying for the domain. Do somebody still using it 😱 ?

If you want I can take it over from you and keep the site up and running for a while. I've moved my projects over to MUI-X V5 but I understand there's still people on older versions who want/need support.

**Comment by dmtrKovalenko** [comment]
There should be a dedicated vercel deployment with its own url. But the problem that I don’t have access to mui’s vercel anymore. Need to wait for Olivier’ response.

**Comment by oliviertassinari** [comment]
I have tried to redeploy but it's broken. We are under the free plan of Vercel which limits server functions, no team members, Node.12 is no longer supported, and there are more issues. I think that the simplest if for developers to clone the repository locally and to run the dev server.

**Comment by dmtrKovalenko** [comment]
Hmm, but the previous deployment of the project should be up? Or it is down? It was running all these years somehow...

**Comment by oliviertassinari** [comment]
v4 is still running, I have updated [the table](https://github.com/mui/material-ui-pickers/issues/2157#issue-743199856), but v3 crashes https://material-ui-pickers-git-v3-x-mui-org.vercel.app/, redeployment crashes as well. I'm not sure how long it will keep running. It might be the downside of having the pages server side rendered.

**Comment by dmtrKovalenko** [comment]
Thank you! I think that's fine.

**Comment by Bloodyaugust** [comment]
Checking in as another someone who would _really_ like access to the docs (for `@material-ui/pickers@3.3.10`).

**Comment by darkemlord** [comment]
Please upload the documentation again :'(

**Comment by markcorrea** [comment]
Congrats! But did you really have to delete the old documentation? What about the users that still have to upgrade huge systems and can't migrate in just one day?

**Comment by dmtrKovalenko** [comment]
It is not deleted, it is in sources. You should be able to run it locally. But the infrastructure behind it is so old that it is not possible to easily redeploy it.

**Comment by pedroassis** [comment]
@darkemlord @dmtrKovalenko @markcorrea

I have published this under github pages, you can use mine if they don't copy it to theirs.

https://pedroassis.github.io/material-ui-pickers/

I can send a PR if you want.

If anyone responsible for this repo (which has **500k downloads** weekly in the last year even after the docs were haphazardly deleted) wants to copy this and release it:

add this to your branch:
https://github.com/pedroassis/material-ui-pickers/blob/next/docs/package.json#L9
https://github.com/pedroassis/material-ui-pickers/blob/next/docs/next.config.js#L28

Run

```bash
cd docs
yarn build
yarn export
```

export logs a bunch of errors but it seems to have worked.

Now the index file needs to be in the root, I was too lazy and just copied the whole out folder to the root.
You might be able to fix the basePath|assetPrefix to point to /docs/out, I wasn't in the mood to try it.

![image](https://github.com/mui/material-ui-pickers/assets/4248124/b1379abf-1959-4eac-b6ec-71e7203512d7)

**Comment by dmtrKovalenko** [comment]
@pedroassis thank you so much for doing this, probably that should've been me (because it was my project originally) so I'm sorry and thank you. 

We should probably update the repo itself, but I don't think I have the permissions in Mui org anymore. We should ask @oliviertassinari or somebody else

**Comment by oliviertassinari** [comment]
> I have published this under github pages, you can use mine if they don't copy it to theirs. https://pedroassis.github.io/material-ui-pickers/

@pedroassis We already have the docs for v4.0.0-alpha.12: https://material-ui-pickers-git-next-mui-org.vercel.app/. 

Would you happen to have the one for v3.3.10? It's the one we are missing, thanks.

**Comment by pedroassis** [comment]
@oliviertassinari hnm, I didn't see that lol, should be added to the readme/npm package.

I'll take a look at 3.3.10 tomorrow and let you know.

**Comment by pedroassis** [comment]
@oliviertassinari @dmtrKovalenko 

I also haphazardly worked on the docs, I needed v3 too.

I changed my repo to v3.3.11 and it look alright.

GH Pages is funky, I suppose you guys will use something else to serve it.

A good old static http server will do, with some rewriting rules to make the links work properly.

The files you are looking for will be on docs/out, however the paths are setup for my GH Pages.

Let me know if I can help set that up.
