### ISSUE TITLE
The position of the caret is not correct when we try to enter the date from the keyboard and the format includes letters

### ISSUE THREAD

**Issue by JWootton60** [mui-org/material-ui-pickers#2159]
This [issue](https://github.com/mui-org/material-ui-pickers/issues/1337) was first reported by amaia00, Oct 2, 2019.  The issue was closed by dmtrKovalenko and was tagged as incomplete by  oliviertassinari.  This issue is still a problem.

If you use the [sandbox](https://codesandbox.io/s/material-ui-pickers-usage-demo-95bxc) provided by amaia00 you can see the problem.

Please see the issue reported by amaia00 for details

**Comment by oliviertassinari** [comment]
Fixed in v5: https://codesandbox.io/s/material-ui-pickers-usage-demo-forked-ieqmd?file=/src/App.jsx
