### ISSUE TITLE
PickerToolbar > Grid component has incorrect prop `justifyContent` should be `justify`

### ISSUE THREAD

**Issue by densk1** [mui-org/material-ui-pickers#2160]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

This component has an incorrect prop, noticed it as it's showing up as an error in a unit test.

https://github.com/mui-org/material-ui-pickers/blob/fd8b8322c8561b30c3ae6eb81881519ca5a7f0fb/lib/src/_shared/PickerToolbar.tsx#L86-L92

## Expected Behavior 🤔

Prop should be `justify="space-between"` and not ~`justifyContent="space-between"`~, or indeed not set at all.

From docs [here](https://material-ui.com/api/grid/)

**Comment by oliviertassinari** [comment]
@densk1 You are linking documentation for v4 and a source for v5. it's incoherent.

I have closed because we are in the process of archiving the repository. Ongoing development was moved to https://github.com/mui-org/material-ui and https://next.material-ui.com/components/date-picker/.

**Comment by densk1** [comment]
https://next.material-ui.com/api/grid/
Sure. Mui V5, same issue. Will open issue there.

**Comment by oliviertassinari** [comment]
@densk1 I can't find any usage of `justify="` in v5 to replace. It seems that we are good :).

**Comment by densk1** [comment]
👍🏼 just in case, it's  `justifyContent="` that needs to be replaced with `justify="`.
