### ISSUE TITLE
Customize hours and minutes views

### ISSUE THREAD

**Issue by teriyaki-89** [mui-org/material-ui-pickers#2163]
Hi, guys. The pickers are awesome. However, some people from my team want to customize the views of hours and minutes as they do not like the watches interface at all.
I can not see api to override the view, but it would be ideally to change the view component by demand.
Please suggest me if it is possible and I am not wrong.
Thanks.

**Comment by oliviertassinari** [comment]
See https://github.com/mui-org/material-ui/issues/23690
