### ISSUE TITLE
Remove @babel/runtime requirement

### ISSUE THREAD

**Issue by tracker1** [mui-org/material-ui-pickers#2167]
Would be nice if @babel/runtime weren't required, would need to update the rifm reference for 0.12.0 (latest) but this is a pretty big impact this adds to a bundle.

**Comment by oliviertassinari** [comment]
@tracker1 could you re-evaluate the situation with v5.0.0-alpha.20? (the component was moved to the lab).

**Comment by oliviertassinari** [comment]
I'm closing as v5.0.0-alpha.20 depends on rifm 0.12.0 and @babel/runtime is a dependency to save bundle size. We miss more details in this issue.
