### ISSUE TITLE
CSS Styling of KeyboardTimePicker

### ISSUE THREAD

**Issue by skizzo** [mui-org/material-ui-pickers#2169]
Hi,
how can I change the color (blue-ish in screenshot) of my time picker? I can't find anything in the docs.
![Screenshot 2021-02-05 at 17 54 22](https://user-images.githubusercontent.com/2892572/107063933-3d5dfa80-67db-11eb-9e6a-2c3c88eab599.png)
Thanks for some hints! :)

**Comment by oliviertassinari** [comment]
It's a native time picker, it's not related to Material-UI.

**Comment by oliviertassinari** [comment]
Follow https://github.com/mui-org/material-ui/issues/23690

**Comment by skizzo** [comment]
Since the issue you linked has no valuable solution for this neither, your response is not very helpful. But thanks anyway.
