### ISSUE TITLE
maxDate for DatePicker doesn't work

### ISSUE THREAD

**Issue by AndrejGajdos** [mui-org/material-ui-pickers#2171]
maxDate props for DatePicker doesn't work.

## Current Behavior 😯

If I use `maxDate={new Date()}`, I am able to choose date after current date.

## Steps to Reproduce 🕹

https://codesandbox.io/s/mui-date-picker-title-forked-48s8c?file=/src/demo.tsx

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.3  |
| @material-ui/pickers | v4.0.0-alpha.12  |
| React       |         |
| Browser     |         |
| TypeScript  |         |
| etc.        |         |

**Comment by tobzilla90** [comment]
@AndrejGajdos 
I had the same issue.
You cannot use a function for the `maxDate` param. 

if you pass a variable/constant it is working:
```
 const myMaxDate = new Date('2020-01-01');
 return (
         ...
        <DatePicker
          ...
          maxDate={myMaxDate}
        />
        ...
  );

**Comment by AndrejGajdos** [comment]
@tobzilla90 it doesn't make any difference [codesandbox](https://codesandbox.io/s/mui-date-picker-title-forked-ebllc?file=/src/demo.tsx)

**Comment by tobzilla90** [comment]
@AndrejGajdos 
now you applied a `string` as param. But the input type is `Date`.

You can choose a Date after `maxDate` but then the validator will show that the selected date is not within the range (See that the label and the line gets displayed red). The Picker UI is only limited by the year for the `DatePicker`.

If you want to set the date directly here is how to do this:

```
       <DatePicker
          ...
          maxDate={new Date("2020-08-18")}
        />

**Comment by AndrejGajdos** [comment]
The return of `new Date()` is `Date` type with the current date. There is no difference between my original [codesandbox](https://codesandbox.io/s/mui-date-picker-title-forked-48s8c?file=/src/demo.tsx) and `maxDate={new Date("2020-08-18")}`.

Check this [codesandbox](https://codesandbox.io/s/mui-date-picker-title-forked-xxod4?file=/src/demo.tsx) and console log.
