### ISSUE TITLE
DatePicker variant="static" doesn't respect disabled

### ISSUE THREAD

**Issue by scottlamb** [mui-org/material-ui-pickers#2172]
- [x] The issue is present in the latest release. (That is: I tried the latest released version, 3.2.10. I see there are some alphas which I haven't tried.)
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If I create a static `DatePicker` such as this:

```
      <DatePicker
        variant="static"
        disabled={true}
        value={null}
        onChange={...}
      />
```

the `disabled` attribute appears to have no effect. All the dates appear enabled; the current date is selected.

![image](https://user-images.githubusercontent.com/8949524/108426666-ddab1a80-71f0-11eb-9746-f780e11aebe6.png)

and my `onChange` handler runs when a day is clicked.

## Expected Behavior 🤔

I'd prefer that all days appear disabled and no callbacks run. This seems consistent with the docs, which [say](https://material-ui-pickers.dev/api/DatePicker) `disabled` will "Disable picker and text field".

## Steps to Reproduce 🕹

https://codesandbox.io/s/hardcore-moser-qhexe

Steps:

1. just look at the page...

## Context 🔦

[My software](https://github.com/scottlamb/moonfire-nvr)'s UI is oriented to selecting/viewing existing segments of video. It only makes sense to select dates in which there is video available. Sometimes there are no such dates, eg if there are currently no cameras selected to view or if recording is broken. I think a static date picker makes the most sense because which dates are available is information I don't want to hide behind a click. I also don't think it makes sense for the date picker to appear and disappear (and thus other UI elements jump) based on whether any selection is valid; I'd rather it just appear disabled.

In my existing (ancient jQuery UI-based) interface, the date picker looks like this when disabled:

![image](https://user-images.githubusercontent.com/8949524/108426890-311d6880-71f1-11eb-94ea-6a3b22ee08e7.png)

That's roughly what I want to match in my [React/material-ui-based UI rewrite](https://github.com/scottlamb/moonfire-nvr/issues/111).

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.3  |
| @material-ui/pickers | v3.2.10  |
| React       | 17.0.1 |
| Browser     | Chrome 88.0.4324.150 |
| TypeScript  | yes         |
| etc.        |         |

**Comment by scottlamb** [comment]
I just noticed the README banner: "This project is not longer supported. See #2157 for more details." I will move this over to https://github.com/mui-org/material-ui with a demo using that version...

(although if anyone who happens to read this has an easy workaround on this version, I'd be grateful)

**Comment by oliviertassinari** [comment]
@scottlamb Did you try to reproduce the issue with the v5?

**Comment by scottlamb** [comment]
Yes, same thing: https://codesandbox.io/s/material-ui-issue-forked-eoh3m?file=/src/Demo.js
