### ISSUE TITLE
Use ui picker localization without external libraries

### ISSUE THREAD

**Issue by GeenCo86** [mui-org/material-ui-pickers#2178]
Hello,

is it anyhow possible to use material-ui-pickers without any external date library? For most cases Intl will do the work.

**Comment by dmtrKovalenko** [comment]
No it won't. E.g. parsing inputs according to localised format. 

Temporal will do, but it is too experimental for now. If you want to try implementing pickers with pure intl - make your own custom date-io adapter and pass it just like provided one.
