### ISSUE TITLE
Global export name for Material UI changed 

### ISSUE THREAD

**Issue by ASnow** [mui-org/material-ui-pickers#2180]
Since https://github.com/mui-org/material-ui/pull/13142 Material UI changed global export name to `MaterialUI` instead `material-ui`

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Material dependencies are failed when library exported into global namespace of window (not import commonjs, amd)

## Expected Behavior 🤔

Imports ok 

## Steps to Reproduce 🕹

Just use direct script imports of material and material-pickers

```
<script src="material.umd.js" />
<script src="material-pickers.umd.js" />
```

## Context 🔦

Externals support

## Your Environment 🌎

Webpack with linked externals

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v3.3.10  |
| React       |         |
| Browser     |         |
| TypeScript  |         |
| etc.        |         |

**Comment by ASnow** [comment]
My solution
Create extra js file between material and pickers
```
window['material-ui']=window['MaterialUI'];
```

**Comment by oliviertassinari** [comment]
umd build are only for prototyping and legacy
