### ISSUE TITLE
Dates in the calendar are duplicated

### ISSUE THREAD

**Issue by Potseluiko** [mui-org/material-ui-pickers#2182]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Days in calendar are duplicated (double March 26).
<img width="349" alt="Screenshot 2021-03-26 at 18 02 36" src="https://user-images.githubusercontent.com/2342136/112651571-92be9b80-8e5d-11eb-88ca-be752dc3829a.png">

## Expected Behavior 🤔

No duplicated days.

## Steps to Reproduce 🕹

Steps:

1. import moment from "moment-timezone"
2. import MomentUtils from "@date-io/moment"
3. Set default time zone in moment like this:
`
moment.tz.setDefault("Asia/Damascus");
`

I found two time zones to reproduce this bug:
"Asia/Damascus"
"Asia/Gaza"

4. Live example is here:
[https://codesandbox.io/s/sleepy-yalow-ht57t?file=/src/App.jsx](https://codesandbox.io/s/sleepy-yalow-ht57t?file=/src/App.jsx)

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.4.3  |
| @material-ui/pickers | v3.3.10  |
| React       |   16.12.0  |
| Browser     |   Chrome  Version 88.0.4324.192 (Official Build) (x86_64) |
| TypeScript  |    No     |
| @date-io/moment  | v1.3.11  |
| moment-timezone  | v0.5.33  |

**Comment by oliviertassinari** [comment]
@Potseluiko The component was moved to the main repository under the lab, in v5. https://next.material-ui.com/components/date-picker/. If you have a reproduction with this version, please open a new issue in https://github.com/mui-org/material-ui.
