### ISSUE TITLE
Material customization on dialog

### ISSUE THREAD

**Issue by ezeyuske** [mui-org/material-ui-pickers#2183]
https://github.com/mui-org/material-ui-pickers/blob/e875729b3492a4aedebec9f14589accc83475241/lib/src/_shared/PickersModalDialog.tsx#L113

Here you need send classes data to `useStyles`:
```
const classes = useStyles({ classes: MuiDialogClasses });
```

**Comment by oliviertassinari** [comment]
Active development has moved to v5, in the main repository.
