### ISSUE TITLE
DataRangePicker is not closing the Picker on clicking back or forward when used with Dialogue

### ISSUE THREAD

**Issue by sachin-agarwal-by** [mui-org/material-ui-pickers#2184]
DataRangePicker is not closing the Picker on clicking back or forward when used with Dialogue

## Current Behavior 😯

When I am using DateRangePicker with dialogue  then on clicking on back or forward for changing the dates picker immediately closes.

## Expected Behavior 🤔

Picker shoud keep it open on moving back forward while selecting dates.

## Steps to Reproduce 🕹

Added Below code sample ..

import { Dialog, DialogContent, DialogTitle, TextField, Typography } from "@material-ui/core";
import { DateRangeDelimiter, DateRangePicker } from "material-ui-pickers";
import React, { ReactElement } from "react";
import { useGlobalStyle } from "styles/global-styles";

const Test = (): ReactElement<any> => {
  const globalClasses = useGlobalStyle();

  return (
    <Typography className={globalClasses.title} variant="h1">
      <Dialog maxWidth="lg" disableEnforceFocus={false} disableBackdropClick={true} onClose={() => { }} open={true}>
        <DialogTitle id="customized-dialog-title">
        </DialogTitle>
        <DialogContent dividers>
          <DateRangePicker
            disabled={false}
            startText={"start"}
            endText={"end"}
            onChange={() => { }}
            value={[null, null]}
            renderInput={(startProps, endProps) => (
              <>
                <TextField {...startProps} />
                <DateRangeDelimiter> to </DateRangeDelimiter>
                <TextField {...endProps} />
              </>
            )}
          />
        </DialogContent>
      </Dialog>

    </Typography>
  );
};
export default Test;

**Comment by oliviertassinari** [comment]
Active development has moved to v5, in the main repo

**Comment by sachin-agarwal-by** [comment]
@oliviertassinari where can I find active version and how we can use this component going forward ?
