### ISSUE TITLE
Does maxDateTime exist in DateTimePicker?

### ISSUE THREAD

**Issue by danpacurarandrei** [mui-org/material-ui-pickers#2185]
I am trying to limit picking a date and a time after the current date and time, but I cannot see in Documentation any feature that helps me.
is there an issue with maxTime and maxDateTime or they aren't available?

**Comment by timonla** [comment]
I think what you want was already discussed in https://github.com/mui-org/material-ui-pickers/issues/2156

You can already use this parameter in the Mui-5.0 alpha release https://next.material-ui.com/components/date-time-picker/#date-and-time-validation
