### ISSUE TITLE
Cannot import DateRangeDay in 4.0.0-alpha.12

### ISSUE THREAD

**Issue by tondi** [mui-org/material-ui-pickers#2188]
## Current Behavior 😯
Im trying to use `MobileDateRangePicker` with `renderDay` in 4.0.0-alpha.12

```
import { DateRangeDay } from '@material-ui/pickers/DateRangePicker/DateRangePickerDay';

<MobileDateRangePicker
  renderDay={(date, DateRangeDayProps) => <DateRangeDay {...DateRangeDayProps} />}
   {/* ...otherProps /*}
/>

```
Getting `Module not found: Can't resolve '@material-ui/pickers/DateRangePicker/DateRangePickerDay'`

1. The `DateRangeDay` component is neither exported from `@material-ui/pickers`
2. Documentation for `renderDay` in https://v4-0-0-alpha-12.material-ui-pickers.dev/api/DateRangePicker shows `@example (date, DateRangeDayProps) => <DateRangePickerDay {...DateRangeDayProps} />` mentioning `DateRangePickerDay` which is also not exported

Why is this component not available publicly?

**Comment by oliviertassinari** [comment]
Closing as it's available in v5 https://next.material-ui.com/api/date-range-picker-day/
