### ISSUE TITLE
Lose global styles when wrapped by StylesProvider

### ISSUE THREAD

**Issue by cjnoname** [mui-org/material-ui-pickers#2189]
The calendar will lose all the theme styles wrapped by StylesProvider with either {seed: "data"} or {disableGlobal: true} settings on.

Any one can help?

Thanks

**Comment by oliviertassinari** [comment]
I'm closing as it seems a support request to ask on StackOverflow. 

As for resolving the issue on your own, you would probably want to start by isolating the issue down to a minimal reproduction. What you are describing is weird, it could be coming from a bundling issue for instance.

Note that this git repository is archived, ongoing work has moved to the lab.
