### ISSUE TITLE
Calender control switching disabled in mac safari

### ISSUE THREAD

**Issue by NareshAtnPLUS** [mui-org/material-ui-pickers#2190]
# Calender control switching is disabled in safari

- [ ] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

![image](https://user-images.githubusercontent.com/46529560/120639238-c4bc3180-c48e-11eb-8928-7432b8a86e5b.png)

## Expected Behavior 🤔
![image](https://user-images.githubusercontent.com/46529560/120639179-b3732500-c48e-11eb-90c0-a443bf52ce27.png)

Expected to show the calender switching arrows to functions in safari. This is working fine in chrome.

## Context 🔦
  Im trying to use the calender control functionality to let users to select date as a dimension.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.9.1  |
| @material-ui/pickers | v3.3.1 |
| React       |      16.12.   |
| Browser     |   Safari v14.0.3     |

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version (v5). This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!
