### ISSUE TITLE
Fix deprecation warnings from MUI > 4.12.X

### ISSUE THREAD

**Issue by MoritzHorch** [mui-org/material-ui-pickers#2200]
In [Material-UI 4.12.X](url) several styling deprecations errors were introduced. Especially the `fade` color utility which is used many times in this project. Now I know that active development has been moved to Material-UI V5, but I think we should at least have fixes for such console-spamming errors as long as Material-UI V5 is still not a stable release and especially when the new pickers are only a part of the lab.

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using and opening DatePicker in combination with the `MuiPickersUtilsProvider` the following error will be logged to the console: 

`Material-UI: The `fade` color utility was renamed to `alpha` to better describe its functionality.

You should use `import { alpha } from '@material-ui/core/styles'
  at ...
  at MuiPickersUtilsProvider
  at ...`

Or: `Warning: Failed prop type: The prop `justify` of `ForwardRef(Grid)` is deprecated. Use `justifyContent` instead, the prop was renamed.`

## Expected Behavior 🤔

No deprecation error should be logged and the suggested utilitly / property should be used.

## Steps to Reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/eager-drake-6wqck
2. Open the pickers one by one
3. See several deprecation logs arise

## Context 🔦

This issue heavily disturbs working with the current stable release and right now we do not feel like that using the beta- and lab channels is the right way to go in production apps.

## Your Environment 🌎

"@material-ui/core": "4.12.1",
"@material-ui/pickers": "3.3.10",
"moment": "2.29.1",
"@date-io/moment": "1.x",
"react": "latest",
"react-dom": "latest",
"react-scripts": "latest"

**Comment by MonstraG** [comment]
Same thing here, updated to MUI v4.12.X to simplify migration when v5 finally comes out, hit this.

**Comment by shawndibble** [comment]
Is there a reason why this is flagged as `wontfix`? Is there a workaround or another solution we should be using instead?

**Comment by oliviertassinari** [comment]
We have archived this repository, more details in #2157.
