### ISSUE TITLE
input OnChange

### ISSUE THREAD

**Issue by maitepv87** [mui-org/material-ui-pickers#2202]
- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.?.?  |
| @material-ui/pickers | v4.?.?  |
| React       |         |
| Browser     |         |
| TypeScript  |         |
| etc.        |         |

**Comment by maitepv87** [comment]
I'm using the KeyboardDatePicker component and I was wondering if there was a way to capture and handle the inputOnChange. Thank you

**Comment by maitepv87** [comment]
OliverTassinari seems to be very obvious to you the answer to the question I asked, because you closed without any comment. not all of us are as advantageous as you. thank you.

**Comment by oliviertassinari** [comment]
See https://github.com/mui-org/material-ui-pickers/issues/2157
