### ISSUE TITLE
How to navigate a static calendar with custom UI 

### ISSUE THREAD

**Issue by monaye** [mui-org/material-ui-pickers#2203]
https://codesandbox.io/s/keen-leftpad-8olrm?file=/src/App.js

I am trying to build the custom navigation and can't find the props for me to pass so can display specific years/month to the calender. 

Currently, if I pass `value={ new Date([2021, 7]) }` this will move the calendar to provided date but it also selects the first day of the month. 

Is there a way to navigate calendar without selecting a date? 

```
export default function App() {
  const [value, setValue] = useState(new Date(2021, 6));

  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>

      <LocalizationProvider dateAdapter={DateFnsUtils}>
        <StaticDatePicker
          // orientation="portrait"
          value={value}
          onChange={(newValue) => setValue(newValue)}
        />
      </LocalizationProvider>

      <button onClick={() => setValue(new Date(2021, 7))}>Go to Aug</button> // this will select date as Aug 1st. 
    </div>
  );
}
```

**Comment by oliviertassinari** [comment]
@monaye Please check the API and component on v5.
