### ISSUE TITLE
ToolbarComponent for DateRangePicker is still not working

### ISSUE THREAD

**Issue by BaruchLu** [mui-org/material-ui-pickers#2207]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.?.?  |
| @material-ui/pickers | v4.?.?  |
| React       |         |
| Browser     |         |
| TypeScript  |         |
| etc.        |         |

**Comment by mnajdova** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://material-ui.com/r/issue-template-next), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by oliviertassinari** [comment]
I'm closing as don't handle any support request on https://github.com/mui-org/material-ui-pickers. I'm archiving it.
