### ISSUE TITLE
KeyboardDateTimePicker - variant="inline" - Cancel button is MUST

### ISSUE THREAD

**Issue by manoharreddyporeddy** [mui-org/material-ui-pickers#2208]
Is your feature request related to a problem? Please describe.
There are no Cancel button in KeyboardDateTimePicker when it is variant="inline"

Describe the solution you'd like
Add Cancel button

Describe alternatives you've considered
Nothing is possible to revert
The date & time changed is changed FOREVER

Additional context
Implementation is made based on a wrongly understood material guideline

**Comment by LukasTy** [comment]
Thank you for opening the issue, but we are no longer actively supporting this project.
You can learn about it more here:
- https://github.com/mui/material-ui-pickers/issues/2157 
- https://www.npmjs.com/package/@material-ui/pickers

Please consider upgrading (trying out) [@mui/x-date-pickers library](https://mui.com/x/react-date-pickers/getting-started/) and seeing if it would cover your use case. 😉 
If it still has the same issue—please consider submitting an issue to the [relevant repository](https://github.com/mui/mui-x).
