### ISSUE TITLE
Cannot change the min-width when using datepicker

### ISSUE THREAD

**Issue by thanhlong510** [mui-org/material-ui-pickers#2210]
![image](https://user-images.githubusercontent.com/125276839/233833731-66c8e1dc-baf6-4a47-b0b6-efb3937918fa.png)

I can not change this min-Width value when using datepicker.

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷. A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by oliviertassinari** [comment]
Closing per https://github.com/mui/material-ui-pickers/issues/2157
