### ISSUE TITLE
Issue in onFocus while copy pasting a normal text in date picker 

### ISSUE THREAD

**Issue by Nithinmon-D** [mui-org/material-ui-pickers#2214]
Steps:

1. Select a valid date from the date picker or enter it manually in the field.
2. Copy some text.
3. Use the mouse to select the date in the date picker field.
4. Paste the copied text into the date picker field and observe that the value becomes null, but upon focusing on the picker, the previously selected date is visible.

Expected: In this scenario, when focusing on the field, it should be empty since the value has become null.

**Comment by LukasTy** [comment]
Hello @Nithinmon-D. This package has long been out of maintenance.
Please find the important information [here](https://github.com/mui/material-ui-pickers/issues/2157).
We highly encourage you to start using `@mui/x-date-pickers`.
You can start [here](https://mui.com/material-ui/migration/pickers-migration/), then migrate to `@mui/x-date-pickers@v5` using [this guide](https://mui.com/x/migration/migration-pickers-lab/) and consider spending time to bump your usage to [at least v6](https://mui.com/x/introduction/support/#supported-versions) (current LTS) with [this guide](https://mui.com/x/migration/migration-pickers-v5/).
