### ISSUE TITLE
Did it support individual use of MonthPicker or YearPicker?

### ISSUE THREAD

**Issue by taoxueweilong** [mui-org/material-ui-pickers#339]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |         |
| material-ui         |         |
| React               |         |
| Browser             |         |
| Platform            |         |

## Steps to reproduce
1.
2.
3.

**Comment by dmtrKovalenko** [comment]
Yes) But actually cant understand what you mean under "month picker"

**Comment by alancasagrande** [comment]
Not sure why this is a duplicate of #330? That issue is talking about the ability to embed pickers (eliminate the the text field).

This issue is asking for a month/year picker (where you don't have to select a specific date).

**Comment by veeru1087** [comment]
I have been searching all over. There are lot of people asking for just year and month picker, not the date. Please reply if this supports just year/month picker.

**Comment by dmtrKovalenko** [comment]
Actually no. You can just reuse the control, that using for selecting year.

**Comment by veeru1087** [comment]
@alancasagrande Thank you so much! :)

**Comment by veeru1087** [comment]
@alancasagrande By any chance, do you have an online demo of this?

**Comment by veeru1087** [comment]
@alancasagrande I was able to run the demo. This is exactly what we wanted. Thank you for all your work! 
However I am not sure how I could include this in our project. Your Repo was forked on v0.x branch, which is not being maintained now. Did you create any pull request? If we directly have the DatePicker component from source, there were so many old dependencies, and many deprecated code warnings. Sorry for being a pain to you. I am new to working with forked repos. Could you please give me some direction here?

**Comment by alancasagrande** [comment]
@veeru1087 yes v0.x is no longer maintained so they refused by PR. We had to create another repo for the build. What we do is:

1) Run build for https://github.com/OnFrontiers/material-ui
2) Copy to https://github.com/OnFrontiers/material-ui-build 
3) `npm install OnFrontiers/material-ui-build`

I don't recommend relying on `OnFrontiers/material-ui-build` though, you should create a fork of your own. Hopefully you should be able to tree shake `material-ui` if you only need the DatePicker.
