### ISSUE TITLE
UMD 

### ISSUE THREAD

**Issue by ryoshi1986** [mui-org/material-ui-pickers#503]
Hey Guys,

would you be so kind to provide us with an UMD-version? I want to introduce these great pickers to my team and this would really help me alot :) Is this possible? I´d really appreciate it. 

Greetings
Dave

**Comment by TrySound** [comment]
@dmtrKovalenko This can be closed.

**Comment by mszynka** [comment]
This should never be closed. Your "umd" version does not use UMD dist of @material-ui hence imports like '@material-ui/core/Button' will not work if using UMD version of @material-ui!

**Comment by dmtrKovalenko** [comment]
I think it should be fine? We changed the rollup umd build

**Comment by lyvyu** [comment]
Hey guys, any update on this ?! Trying to use umd version of pickers with the latest React Material version and it's not working !!!
