### ISSUE TITLE
Add scroll support for timepicker

### ISSUE THREAD

**Issue by flyingangel** [mui-org/material-ui-pickers#592]
Could you add scroll support for timepicker? On mouse scroll up or down, increment/decrement hour by 1, minute by 10. No one bother to write time like this 15:01 or 15.02
10 should be by default and configurable.

**Comment by takobayashi** [comment]
rc.11 can scroll.
It seems bug since rc.12.

**Comment by dmtrKovalenko** [comment]
@takobayashi there were no such feature never

**Comment by takobayashi** [comment]
@dmtrKovalenko I'm sorry. I miss understood.
I open new issue #594

**Comment by oliviertassinari** [comment]
Closing as "won't fix". The component should leave the scroll event untouched. For instance, this causes accessibility issues with `<input type="number" />`: https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/.
