### ISSUE TITLE
Why we need "ampm" property if moment (and other) already has this setting in locale config?

### ISSUE THREAD

**Issue by vanyakosmos** [mui-org/material-ui-pickers#723]
So if we have 24 hour format set in moment locale configuration then we still need to specify `ampm={false}` on every picker.

**Comment by vanyakosmos** [comment]
Well, libs configuration is not as simple as `ampm` boolean flag

### moment:
- configure (change specific locale or just switch to another locale): 
```
moment.updateLocale('en', {
  longDateFormat: {
    LT: 'HH:mm',   // 24
    LT: 'h:mm A',  // 12
  },
});
```
- usage: `dt.format('LT')`

### [luxon:](https://moment.github.io/luxon/docs/class/src/datetime.js~DateTime.html#static-get-TIME_SIMPLE)
- [manual](https://moment.github.io/luxon/docs/manual/intl.html)
- settings default: `Settings.defaultLocale = 'fr';`
- usage: `dt.toLocaleString(DateTime.TIME_SIMPLE)`

### date-fns
- set locale: `window.__localeId__ = 'fr'`  ([ref](https://date-fns.org/v2.0.0-alpha.24/docs/I18n))
- usage: `dt.format('p')` ([ref](https://date-fns.org/v2.0.0-alpha.24/docs/format))

**Comment by dmtrKovalenko** [comment]
Locale does not contain information about am pm. 
But you are right we can lift up the am pm settings globally. Passing props to Provider. 

That should be done 👍

**Comment by dmtrKovalenko** [comment]
Finally got to the point that it will be a bad way. Closing this
