### ISSUE TITLE
Using with Formik's field.onBlur and form.touched is resetting formik errors

### ISSUE THREAD

**Issue by benneq** [mui-org/material-ui-pickers#825]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.0.5        |
| material-ui         | 3.7.1        |
| React               | 16.7.0        |
| Browser             | Chrome 71.0        |
| Peer library        | moment 2.23.0 and @date-io/moment 0.0.2        | 

## Steps to reproduce
1. Use Formik's `Field` component in combination with your `DatePicker` component
2. Pass Formik's `onBlur` to the `DatePicker`
3. Change the date to an invalid value and see **no** error

## Expected behavior

See an error

## Actual behavior

No error

## Live example

https://codesandbox.io/s/xv73w1vvrw

In this code there are 2 components:
1. `MyDateFormField` This one has **no** `onBlur`
2. `MyOtherDateFormField` This one uses `onBlur` and `form.touched`

When you now make the date invalid (for example: just insert a letter). Then you can see, that the first `DatePicker` shows an error, but the second one doesn't. Even worse: The second one also removes all errors from the first one.

I've also added a `console.log` inside both components. There you can see, that for the second (the broken one) it makes **3** outputs for every change to the field. And even more weird it outputs `false, true, false` for `showError` (and accordingly `undefined, Invalid Date Format, undefined` for the `fieldError` variable.

I'm not sure what's going on there. Or am I just "using it wrong"?

**Comment by dmtrKovalenko** [comment]
Fixed in v3
