### ISSUE TITLE
Seconds part does not change by keyboard input

### ISSUE THREAD

**Issue by vinaydate** [mui-org/material-ui-pickers#899]
**First and foremost: thanks for this great lib.**

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  2.1.1  |
| material-ui         |    3.8.2     |
| React               |     16.7.0-alpha.2    |
| Browser             |    Chrome     |
| Peer library        |    date-fns 2.0.0-alpha.21     | 

## Steps to reproduce
1. Use `TimePicker` with `keyboard` and `seconds`
2. Set seconds in picker to say '24'
3. Input time by keyboard.

## Expected behavior
Seconds typed by Keyboard should be reflected in the display text and value.

## Actual behavior
The seconds part remains to be 24 (on display and associated state) regardless of whatever seconds are keyed in by keyboard.

## Live example
https://codesandbox.io/s/988823vwx4

**Comment by sziebertAu** [comment]
Same problem for me. Tried with version 2.1.2, 2.1.1, 2.1.0, and 2.0.5.

**Comment by dmtrKovalenko** [comment]
Working on v3 https://4joml796nx.codesandbox.io/
