### ISSUE TITLE
Feature request: Quick month selection

### ISSUE THREAD

**Issue by Anwardo** [mui-org/material-ui-pickers#938]
Thanks for the great component, I like it a lot. 🙌

**Is your feature request related to a problem? Please describe.**
One small gripe I have is that there isn't a way to quickly select a specific month by clicking on the month. It feels like the only UX feature missing from the component but I think it's pretty important for a calendar.

-- Just noticed that it is possible to have a month selection but it's not really transparent how to get there. In my opinion click on the month name in the header and on the month in between the arrows should open the month selection.

**Describe the solution you'd like**
I'd like a month list similar to the year list when you click on the year where you can quickly select a specific month instead of having to click on the arrows multiple times to get to the desired month. Should be easy enough to implement using the same component used for the year list.

**Describe alternatives you've considered**

**Additional context**

**Comment by dmtrKovalenko** [comment]
I have created a benchmark with comparison of all date managment libs and [here](https://github.com/dmtrKovalenko/date-io/tree/master/packages/benchmark) you can see results.  
As you can see there luxon is 175 times slower than moment in case of formatting dates. Seems like you just need to [accept](https://github.com/moment/luxon/issues/321) this... 😞

**Comment by dmtrKovalenko** [comment]
We must use `Intl` to compute strings. If you have any idea how to  improve please, rize them in the @date-io library

**Comment by dmtrKovalenko** [comment]
Oh god! I missed the issues :))))

**Comment by stormmuller** [comment]
Looking at the [`DatePickerRoot.tsx`](https://github.com/dmtrKovalenko/material-ui-pickers/blob/next/lib/src/DatePicker/DatePickerRoot.tsx) component. It looks like this should be the case. The `onClick` event calls `setOpenView('month')`. It makes sense because even when you hover over the month the cursor is set to a pointer. Can confirm that clicking on the month doesn't open the month view. So this is probably a bug rather than a feature.

**Comment by stormmuller** [comment]
If @dmtrKovalenko can confirm this to be a bug. I can take a look at the issue and create a PR?

**Comment by dmtrKovalenko** [comment]
Actually that line is displaying only if “date” not provided to the views. I suppose we need to change overall logic of displaying toolbar

**Comment by stormmuller** [comment]
"date" view? I assume you meant the "day" view? Anyway, you're right. If the `views` prop only has the "year" and "month", then clicking on the month does bring  up the month selector. If the "day" view is also included then clicking on the month will take you to the day selector. So I guess it is a feature request. That being said, if we want the user to be able to open the month selector from the day selector, what would be the expected/intuitive UX?

**Comment by edilsalvador** [comment]
First thing that comes to my mind when I see the date and knowing it is clickable is that it will open the month picker since clicking the year will open up the year picker. So it's safe to say that we should add an event when clicking the date it will open up the month picker.

In this case, clicking `Thu, May 9` should open the month picker.
![image](https://user-images.githubusercontent.com/17653666/57433485-2e938e00-726b-11e9-9d1e-87c45bd11ff5.png)

**Comment by edilsalvador** [comment]
In our app what I did was add another Toolbar button for the month view, I'll keep it this way until `mui-pickers` support the month view :sweat_smile: 

![image](https://user-images.githubusercontent.com/17653666/57596728-cf8d8c00-757e-11e9-9301-277ea3452dd7.png)

**Comment by tjaskula** [comment]
I'm interested by that feature as well. It seems that currently I can set the month selection but than I need to select a day. Would be nice just to have a list of months and when selecting one the popup closes.

**Comment by jameelappsintegra** [comment]
![image](https://user-images.githubusercontent.com/47351791/64505159-ee5d1e80-d2e3-11e9-9a54-9a20bf0ed5e3.png)



	MuiPickersMonth: {
			root: {
				color: '#333333',
				fontSize: '2rem',
				'&:focus': {
					color: '#ad582d',
				}
			},
			'&$selected': {
				color: '#ad582d',
				background: '#ae582d'
			}
		},
This code is not working anyone knows the solution for this.
Selected month is not highlighted, even i give usig selector

**Comment by dmtrKovalenko** [comment]
This will be released as a part of v4 #1293

**Comment by DharmedraKumar** [comment]
@edilsalvador The image you have posted above. Do you have any example code so that I can use it?
