### ISSUE TITLE
Clear field value with keyboard

### ISSUE THREAD

**Issue by guilhermeoholz** [mui-org/material-ui-pickers#947]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.2.4      |
| material-ui         |   3.9.2     |
| React               |  16.8.4     |
| Browser             |  Chrome 72.0.3626.121     |
| Peer library        |    moment, 2.24.0     | 

## Steps to reproduce
1. Set some date
2. Erase with backspace

## Expected behavior

When the date is erased in the inline mode, it should send `null` as when we use the `clearable` props.

## Actual behavior

When the date is erased in the inline mode, nothing happens, the field value stays the same... if I set the `clearable` props, it works as expected but then the *showTodayButton* prop is ignored.

## Live example

https://codesandbox.io/s/or724vmpq

**Comment by dmtrKovalenko** [comment]
Fixed in beta.1
