### ISSUE TITLE
minDate and maxDate range on the DateTimePicker

### ISSUE THREAD

**Issue by cescoferraro** [mui-org/material-ui-pickers#953]
![DepbmEA](https://user-images.githubusercontent.com/6259987/54611578-fecbc500-4a35-11e9-80e9-77f2a12cf0e6.gif)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.2.4      |
| material-ui         |     3.9.2    |
| React               |      16.8.4   |
| Browser             |  chrome       |
| Peer library        |  moment       | 

## Expected behavior
minDate and maxDate should invalidate if a date is one second apart on the DateTimePicker

## Actual behavior
minDate and maxDate do not work as exepected on the DateTimePicker.
It only invalidates if the current date is a day after the maxDate or the current date is a day before the minDate.

## Live example

   [LIVE EXAMPLE]( https://codesandbox.io/s/8ly830zw5j?fontsize=14)

**Comment by dmtrKovalenko** [comment]
So the issue is the component doesn't rerender if the minDate or maxDate changed - am I right?

**Comment by cescoferraro** [comment]
![bugggg](https://user-images.githubusercontent.com/6259987/54653334-08d2df80-4a99-11e9-99f9-8991054ce934.png)

**Comment by yufanw** [comment]
From my perspective, the behavior for minDate should match that of maxDate, the minDate should verify that the selected date is at least 1 second AFTER the minDate, and for 1 second before for maxDate

**Comment by doronkilzi** [comment]
I agree with @yufanw (except it should be `ms` and not `s`)
