### ISSUE TITLE
Ability to have extra info panel in the picker

### ISSUE THREAD

**Issue by exiadb** [mui-org/material-ui-pickers#983]
**Is your feature request related to a problem? Please describe.**
Ability to add [info panel](http://airbnb.io/react-dates/?selectedKind=DRP%20-%20Calendar%20Props&selectedStory=with%20info%20panel%20default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) or more add inputs to support the following (Don't worry about the range for now, more of for something like timezone.)
![image](https://user-images.githubusercontent.com/17136588/55958006-08e68980-5cab-11e9-8404-d1be3cc4e07c.png)

**Describe the solution you'd like**
Could be a similar approach to [react-dates](https://github.com/airbnb/react-dates/blob/cffd9195b2e52067d86c65b6dbbf78ce10d62d3a/src/components/DayPicker.jsx#L991) to accept a function prop and a few other props 

**Describe alternatives you've considered**
Could export wrappers with extra props / children so that it is easier for custom build of the pickers.
Or BYO with ref and static picker similar to examples provided.

**Comment by dmtrKovalenko** [comment]
I am actually not aware of that but never seen such approach in material design datepickers. 
From my perspective there is no really such required information for the user, that needs to be shown directly in datepicker. 

Can you add some examples, except timezones?
